[[gravitee-dev-guide-plugins]]
== Plugins

Gravitee Plugins are additional components that can be _plugged into_ the Gravitee ecosystem. Thus, Plugins help you to specify behaviors that meet your strategic needs.

=== Common structure

Each Plugin follows the following common structure:

[source]
-----------------
.
├── pom.xml
├── README.md
└── src
    ├── assembly
    │   └── <plugin>-assembly.xml
    ├── main
    │   ├── java
    │   │   └── <main java files>
    │   └── resources
    │       └── plugin.properties
    └── test
        └── java
            └── <test java files>
-----------------

Hereafter a description about the different key files:

|===
| File                                                               | Description

| <<gravitee-dev-guide-plugins-pom, `pom.xml`>>                      | The main Maven POM file
| <<gravitee-dev-guide-plugins-readme, `README.md`>>                 | The main entry point for the Plugin documentation
| <<gravitee-dev-guide-plugins-assembly, `<plugin>-assembly.xml`>>   | The common Maven assembly descriptor
| <<gravitee-dev-guide-plugins-descriptor, `plugin.properties`>>     | The Plugin descriptor file
|===

[discrete]
[[gravitee-dev-guide-plugins-pom]]
==== pom.xml

Any Plugins (and more generally any Gravitee projects) are https://maven.apache.org/[Maven] managed. Thus, a Plugin project is described by using the Maven https://maven.apache.org/pom.html[Project Object Model] file.

[discrete]
[[gravitee-dev-guide-plugins-readme]]
==== README.md

Each Plugin should have a dedicated `README.md` file to document it. The `README.md` file should contain everything related to the use of your Plugin: _What is its functionality? How can use it? How can configure it?_

[discrete]
[[gravitee-dev-guide-plugins-assembly]]
==== <plugin>-assembly.xml

In order to be _plugged into_ the Gravitee ecosystem, a Plugin need to be deployed following a given file structure. Thus, the `<plugin>-assembly.xml` file is the http://maven.apache.org/plugins/maven-assembly-plugin/[Maven Assembly] descriptor using to build the distribution file.

Commonly, a Plugin distribution file is organized as follow:

[source]
-----------------
.
├── <main Jar file>.jar
└── lib
-----------------

Hereafter a description about the different files:

|===
| File                 | Description

| <main Jar File>.jar  | The Plugin's main Jar file
| lib/                 | A directory containing external libraries to correctly execute the <main Jar File>.jar
|===

[discrete]
===== <main Jar File>.jar

Each Plugin has its main Jar file containing the business behavior *plus* the <<gravitee-dev-guide-plugins-descriptor, Plugin descriptor file>>.

[discrete]
===== lib/

This directory contains all the Plugin's external dependencies (non provided-scope Maven dependencies).

[discrete]
[[gravitee-dev-guide-plugins-descriptor]]
==== plugin.properties

The plugin.properties file is the descriptor of the Plugin. It acts as the _ID Card_ of the Plugin and will be read by Gateway during the Plugin loading process.

Hereafter parameters included into the descriptor:

|===
| Parameter	    | Description

| id	        | The Plugin identifier
| name	        | The Plugin name
| version	    | The Plugin version
| description	| The Plugin description
| class	        | The main Plugin class
| type	        | The type of Plugin (Policy, Reporter)
|===

NOTE: Naturally, the Plugin identifier has to be unique to be correctly loaded by the Gravitee Gateway.

=== Deployment

Each Plugin can be loaded by the Gravitee Gateway by using the two types of Plugin distribution file which are:

- a directory
- a ZIP file (containing the directory)

In order to be loaded, distribution file has to be put inside the associated `plugins` directory that comes from the Gravitee binary file.