[[gravitee-installation-repositories-jdbc]]
= JDBC
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_repositories_jdbc.html
:page-folder: apim/installation-guide/repositories
:page-description: Gravitee.io API Management - Repositories - JDBC
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api, jdbc
:page-layout: apim3x

== Overview

The JDBC plugin is part of the default distribution of APIM. However, you need to install the correct driver for the database you are using. 

== Supported databases

|===
|Database | Version tested | JDBC Driver

|PostgreSQL
|9 / 10 / 11 / 12 / 13
|https://jdbc.postgresql.org/download/[Download page]

|MySQL
|5.6 / 5.7 / 8.0
|https://dev.mysql.com/downloads/connector/j/[Download page]

|MariaDB
|10.1 / 10.2 / 10.3 / 10.4
|https://downloads.mariadb.org/connector-java/[Download page]

|Microsoft SQL Server
|2017-CU12
|https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-2017[Download page]
|===

== Install the JDBC driver

Repeat these steps on each component (APIM Gateway and APIM API) where the SQL database is used.

 1. Download the JDBC driver corresponding to your database version.
 2. Place the driver in `$GRAVITEE_HOME/plugins/ext/repository-jdbc`.
 3. Configure your `gravitee.yml` files, as described in the next section.

[TIP]
====
If you are using Docker to install and run APIM, you should place the driver in the `plugins-ext` folder and configure it by using the Docker compose file or command-line arguments. For more information, see link:{{'/apim/3.x/apim_installation_guide_docker_customize.html' | relative_url}}[Further Customization] of a Docker installation.
====

== Configuration

=== Mandatory configuration

[source,yaml]
----
management:
  type: jdbc             # repository type
  jdbc:                  # jdbc repository
    url:                 # jdbc url
----

=== Optional configuration

The example above shows the minimum configuration needed to get started with a JDBC database. You can configure the following additional properties to fine-tune your JDBC connection and control the behavior of your JDBC database.

[source,yaml]
----
management:
  type: jdbc                    # repository type
  jdbc:                         # jdbc repository
    prefix:                     # tables prefix
    url:                        # jdbc url
    username:                   # jdbc username
    password:                   # jdbc password
    pool:
        autoCommit:             # jdbc auto commit (default true)
        connectionTimeout:      # jdbc connection timeout (default 10000)
        idleTimeout:            # jdbc idle timeout (default 600000)
        maxLifetime:            # jdbc max lifetime (default 1800000)
        minIdle:                # jdbc min idle (default 10)
        maxPoolSize:            # jdbc max pool size (default 10)
----

[[use_a_custom_prefix]]
== Use a custom prefix

From APIM 3.7, you can use a custom prefix for your table names. This is useful if you want to use the same databases for APIM and AM, for example.

The following steps explain how to rename your tables with a custom prefix, using the prefix `prefix_` as an example.

=== On a new installation

If you are installing APIM for the first time, you need to update the following two values in the APIM Gateway and APIM API `gravitee.yml` files:

* `management.jdbc.prefix`
* `ratelimit.jdbc.prefix`

By default, these values are empty.

=== Migrating an existing installation

NOTE: Before running any scripts, you need to create a dump of your existing database. You need to repeat these steps on both APIM Gateway and APIM API.

. Update values `management.jdbc.prefix` and `ratelimit.jdbc.prefix` in your `gravitee.yml` configuration file.
. Run the application on a new database to generate `prefix_databasechangelog`.
. Replace the content of the `databasechangelog` table with the content you generated from `prefix_databasechangelog`.
. Rename your tables using format `prefix_tablename`.
. Rename your indexes using format `idx_prefix_indexname`.
. Rename your primary keys using format `pk_prefix_pkname`.

[[database-enforcing-use-of-primary-key-on-all-tables]]
== Database enforcing use of primary key on all tables

Some databases have an option to enforce the use of a primary key on all tables, for instance, this is the case for MySQL 8.0.13+ with `sql_require_primary_key`.

If you are using a database with such option activated, during the *installation of APIM* or *for an upgrade* , you will need to:

 - disable this option
 - start APIM Management API, to allow the database migration tool, Liquibase, to create the APIM tables and add the primary keys
 - re-enable this option

*Why APIM isn't setting the primary keys when creating the tables?*

Because, as of today, Liquibase is creating 2 tables
for its own use and both don't have a primary key by default, more about it https://forum.liquibase.org/t/why-does-databasechangelog-not-have-a-primary-key/3270[here].
To avoid any compatibility issue with Liquibase, we decided to not override the creation of these tables.