[[gravitee-introduction]]
= Overview of Gravitee.io

[partintro]
--
A popular trend in enterprise software development these days is to design applications to be very decoupled and use API’s to connect them. This approach provides an excellent way to reuse functionality across various applications and business units. Another great benefit of API usage in enterprises is the ability to create those API’s using a variety of disparate technologies.

However, this approach also introduces its own pitfalls and disadvantages. Some of those disadvantages include things like:

* Difficulty discovering or sharing existing API’s
* Difficulty sharing common functionality across API implementations
* Tracking of API usage/consumption
API Management is a technology that addresses these and other issues by providing an API Manager to track APIs and configure governance policies, as well as an API Gateway that sits between the API and the client. This API Gateway is responsible for applying the policies configured during management.

Therefore an API management system tends to provide the following features:

* Centralized governance policy configuration
* Tracking of API’s and consumers of those API’s
* Easy sharing and discovery of API’s
* Leveraging common policy configuration across different API’s
--

[[why-gravitee-io]]
== Why Gravitee.io ?
At the beginning, we were searching for an open-source solution to do API Management. Unfortunately, we've never found
the tool which fit exactly our needs and by choosing one of them we know that we have to pull other components and, for some of them,
a dedicated support (and so, money, money and money...).

That's the main reason why we launch Gravitee.io : our goal is to provide you with an highly integrable solution which
is able to fit perfectly with your infrastructure and our business needs.

Also, Gravitee.io has been developed and designed to be fully extensible using its internal plugin system. You must be
able to do whatever you want : defining your own policy, developing your own reporting system, and so on...

Finally, all components provided by Gravitee.io (including gateway and the management-api) are really lightweight. We
took an aggressive approach to memory management. This makes things really easier for you in terms of high-availability
and our components can be started in a "blazing-fast" mode (generally speaking, it takes less than 3 seconds for the gateway
to be accessible to consumers).

You see no constraint using Gravitee.io at all ? Sounds good ! So let's go further with Gravitee.io right now !

== Fundamentals
Before going further with Gravitee.io, you have to read this section to get a better understanding of the concepts you need
to know to go ahead quickly.

=== API
An API is the main entity used by Gravitee.io. You can see it as a starting point to expose an API through the gateway.

=== Policy
Policy is an other important entity to apply some rules in requests / responses emitted by a consumer and the gateway.
Policies can be chained using a logical order.

Good examples for a policy are:

* Authorization using an API key (see the api-key policy)
* Applying CORS filters
* Applying rate limiting or quota to avoid API flooding.

=== Reporter

== Components
Gravitee.io is not only a product, you can see on it a global solution for API Management. By this, the community provides
components linked between each other and run well together.

=== Gateway
The Gateway is the core component of Gravitee.io.

=== Management API
=== Repository

=== Plugins
The Gateway is developed as a core component around which a set of Plugins.

Plugins are additional components that can be _plugged into_ the Gateway. Hence, Plugins can specialized the Gateway behavior to exactly fit as your needs.
Plugins follow a given directory structure convention. Look at the Developer Guide *TODO: Create the link* to have more information about it.

Currently, there are two kind of Plugins which are:
* Policies
* Reporters

Hereafter an overview about these two kind of Plugins:

==== Policies
As said, a Policy is a kind of Gravitee Plugin acting as a step in the Request/Response Gateway Proxy chain. Then, a Policy can be treated as a _proxy controller_ by guaranteeing if a given business rule is fulfilled during the Request/Response processing.

Want to know how create, use, and deploy a Policy? Check out the Developer Guide! *TODO: Create the link*

==== Reporters