= Session management
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_userguide_user_session_management.html
:page-folder: am/user-guide
:page-layout: am

When a user is signing in, AM stores the fact that the user is authenticated for a certain period of time in what we call a *HTTP Session*.

This mechanism avoid for the user to re-authenticate every time he wants to perform some actions. The same principle applies for your application or when you use an external identity provider such as Facebook, Twitter ... .

NOTE: By default the session last 30 minutes, you can change this value via the gravitee.yml of the gateway, see link:{{ '/am/current/am_installguide_gateway_configuration.html' | relative_url }}[configuration section].

== Session layers

There are three-session layers you need to consider specially when you want to sign-out your users :

. *Application session* : this layer lies in your application after your users have been authenticated from AM.
For traditional web applications this session is stored via HTTP cookies (JSESSIONID, PHPSESSID, ASP.NET_SessionId). For SPA applications this information can be stored in memory or via storage.
It's up to you to clean everything if you want log out your users.

. *Gravitee.io AM session* : a session is created for every authenticated user and this information inside a HTTP cookie.
This cookie acts as Single Sign-on (SSO) cookie and let you remember your users and automatically silently authenticate your users across applications.

NOTE: To automatically authenticate your user across applications (SSO), your applications must share the same identity provider.

[start=3]
. *Identity Provider session* : if you application is configured to use a link:{{ '/am/current/am_userguide_social_identity_providers.html' | relative_url }}[social identity provider] to authenticate a user, the identity provider will create a session in addition of the AM one.
When users attempt to sign in with any of these providers and they are already signed into the provider, they will not be prompted again to sign in.

== Invalidate session

For application session layer, it is up to you to clean everything if you want log out your users.

For the Gravitee.io AM and identity provider sessions, you can read the link:{{ '/am/current/am_userguide_user_session_management_logout.html' | relative_url }}[logout section] to invalidate them.
