= Logging and analytics
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_publisherguide_logging_analytics.html
:page-folder: apim/user-guide/publisher
:page-layout: apim3x

== Overview

You can view API metrics and logs using the API *Analytics* menu option in APIM Console.

=== Metrics

API metrics are presented in one or more _dashboards_. You can select the dashboard with the metrics you want to see from the *Select a dashboard* drop-down menu.
You can then select a time period and view several different types of analytics for your API -- such as requests received and responses sent, the most frequently called applications, response times --
presented in different views and formats.

For more details on creating and configuring API dashboards, see link:/apim/3.x/apim_installguide_dashboard_configuration.html[Configure dashboards^].

=== Logs

You can view the logs for an API by clicking *Analytics* and selecting the *Logs* menu option. This lists all the API requests in date and time order. You can click on an individual entry to view more details.

Log entries include details such as:

- the API endpoint for the request
- the URL of the gateway through which the request was sent

By default, the request header and payload are not logged in APIM, to save space. You can enable this in the logging configuration.

== Configure API logging

NOTE: If you configured a maximum logging duration in the global settings, the maximum duration will be applied to the API logging configuration specified here.
For more details, see link:/apim/3.x/apim_how_to_configuration.html#step-4-update-the-default-apim-settings[Update the default APIM settings^].

WARNING: Logging configuration changes can have a significant impact on performance. Proceed with caution.

. link:/apim/3.x/apim_quickstart_console_login.html[Log in to APIM Console^].
. Click *APIs* and select the API from the list.
. Click *Analytics > Logs*.
. Click the *Configure the logging* link at the top.
. In the *Mode* drop-down, select the type of logging required:
- *Client only* -- to log HTTP request header and payload details between the client and the gateway
- *Proxy only* -- to log HTTP request header and payload details between the gateway and the backend
- *Client and proxy* -- to log HTTP request header and payload details for both
. Select *Logging enabled* to go ahead and enable logging, or *Conditional logging* to specify conditions for logging.
. To specify logging conditions, click *SHOW EDITOR* and select all the conditions which apply. You can restrict logging by:
- application or plan
- request header or query parameter
- HTTP method (GET, POST, etc.)
- request IP address
- duration
- end date
+
You can create rules by combining conditions, for example, you can choose to log only `GET` HTTP methods with a request header called `X-debug` with a value of `true`.
+
Each new condition is added as a line in the *Condition* field.
+
. Click *SAVE*.
+
When you click on the *Back to logs* link, you can see the new information logged in all new log entries.
