= Expression Language
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_publisherguide_expression_language.html
:page-folder: apim/user-guide/publisher
:page-layout: apim3x

== Overview

The APIM Expression Language (EL for short) is one of the key features
that can be used by API publishers to configure various aspects and services of an API.

The EL is a powerful language used for querying and
manipulating an object graph. It is based on the http://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html[SpEL^] (Spring Expression Language).
This means that you can do everything described in the link.

In addition, APIM extends the standard SpEL capabilities by providing extra objects and properties
inside the expression language context.

== Usage
The basic expression language syntax is as follows:

`{#request.id}`

See the sections below for example expression notations.

== API
=== Properties

As an API publisher, you can define properties for your API. These properties are
automatically _injected_ into the expression language context to be used later.

==== Example

* Get the value of the property `my-property` defined in API properties:
`{#properties['my-property']}`

=== Dictionaries

Dictionaries work in a similar way to properties, but you need to specify the dictionary name as well as the property name.

==== Example

* Get the value of the property `my-property` defined in dictionary `my-dictionary`:
`{#dictionaries['my-dictionary']['my-property']}`

=== Endpoints
When you define endpoints for your API, you need to give them a _name_ which
must be a unique identifier across all endpoints of the API. This identifier can be used to get an endpoint reference (i.e. uri).

For example: when you create an API, a _default_ endpoint is created,
corresponding to the value you set for the backend property. This endpoint can
be retrieved with EL by using the following syntax:

`{#endpoints['default']}`

== Request

The properties you can access for API requests are listed below.

|===
.^|Property      |Description            ^.^|Type            |Example

.^|id            |Identifier             ^.^|string          |12345678-90ab-cdef-1234-567890ab
.^|transactionId |Transaction identifier ^.^|string          |cd123456-7890-abcd-ef12-34567890
.^|uri           |URI                    ^.^|string          |/v2/store/MyStore?order=100
.^|path          |Path                   ^.^|string          |/v2/store/MyStore
.^|paths         |Path parts             ^.^|array of string |[,v2,store,MyStore]
.^|pathInfo      |Path info              ^.^|string          |/store/MyStore
.^|pathInfos     |Path info parts        ^.^|array of string |[,store,MyStore]
.^|contextPath   |Context path           ^.^|string          |/v2/
.^|params        |Query parameters       ^.^|array           |#request.params['test'][0]
.^|pathParams    |Path parameters        ^.^|key / value     |storeId -> MyStore (__see Warning for details__)
.^|headers       |Headers                ^.^|key / value     |X-Custom -> myvalue
.^|method        |HTTP method            ^.^|string          |GET
.^|scheme        |HTTP scheme            ^.^|string          |http
.^|version       |HTTP version           ^.^|string          |HTTP_1_1
.^|timestamp     |Timestamp              ^.^|long            |1602781000267
.^|remoteAddress |Remote address         ^.^|string          |0:0:0:0:0:0:0:1
.^|localAddress  |Local address          ^.^|string          |0:0:0:0:0:0:0:1
.^|content       |Body content           ^.^|string          |-
|===

WARNING: `{#request.content}` is only available for policies bound to an `on-request-content` phase.

=== Example

* Get the value of the `Content-Type` header for an incoming HTTP request:
`{#request.headers['content-type']}`

* Get the second part of the request path:
`{#request.paths[1]}`

== Request context

=== Properties

|===
|Property |Description |Type |Always present

.^|attributes
|Request context attributes
^.^|key-value
^.^|X
|===

=== Attributes
When APIM Gateway handles an incoming HTTP request, some attributes are
automatically created. These attributes are:

|===
|Property |Description |Type |Nullable

.^|context-path
|Context-path
^.^|string
^.^|-

.^|resolved-path
|Resolved-path is the path defined in policies
^.^|string
^.^|-

.^|application
|The authenticated application doing incoming HTTP request
^.^|string
^.^|X (for keyless plan)

.^|api
|Called API
^.^|string
^.^|-

.^|user-id
|The user identifier of incoming HTTP request:

* The subscription id for api-key based plan

* Remote IP for keyless based plan

^.^|string
^.^|-

.^|plan
|Plan used to manage incoming HTTP request
^.^|string
^.^|-

.^|api-key
|the api-key used (in case of an api-key based plan)
^.^|string
^.^|X (for no api-key plan)
|===

Additionally, some policies (like the link:/apim/3.x/apim_policies_oauth2.html#attributes[OAuth2 policy])
register other attributes in the context. See the documentation for the policies you are using for more information.

=== Example

* Get the value of the `user-id` attribute for an incoming HTTP request:

`{#context.attributes['user-id']}`

* Get the value of the `plan` attribute for an incoming HTTP request:

`{#context.attributes['plan']}`

* Check that the path starts with a given value:

`{#request.path.startsWith('/my/api')}`

== Response

=== Properties
|===
.^|Property      |Description            ^.^|Type            |Example

.^|content       |Body content           ^.^|string          |-
.^|headers       |Headers                ^.^|key / value     |X-Custom -> myvalue
.^|status        |Status of the HTTP response      ^.^|int    |200
|===

=== Example

* Get the status of an HTTP response:
`{#response.status}`

== Policies
You can use the EL to update some aspects of policy configuration.
The policy specifies if it supports EL or not.

== Mixin

In previous examples, we showed various ways to manipulate objects available
in the EL context. You can also mix property
usage to provide an increasingly dynamic configuration.

For example, we can retrieve the value of an HTTP header where the name
is based on an API property named `my-property`:

`{#request.headers[#properties['my-property']]}`
