= Expression Language
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_publisherguide_expression_language.html
:page-folder: apim/user-guide/publisher
:page-layout: apim3x

The APIM Expression Language (EL for short) is one of the key features
that can be used by API publishers to configure various aspects and services of an API.

This expression language is a powerful language that supports querying and
manipulating an object graph and is based on the http://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html[SpEL] (Spring Expression Language).
This means that you can do everything described in the link.

In addition, APIM extends the standard SpEL capabilities by providing extra objects and properties
inside the expression language context.

== Syntax
The expression language syntax is as follows:

`{#request.id}`

== API
=== Properties

As an API publisher, you can define properties for your API. These properties are
automatically _injected_ into the expression language context to be used later.

=== Example

* Get the value of the property `my-property` defined in API properties:
`{#properties['my-property']}`

=== Endpoints
When defining endpoints for your API, you need to give them a _name_ which
must be a unique identifier across all the endpoints of the API.

Once done, this identifier can be used to get an endpoint reference (ie. uri).

For example: when you're creating an API, a _default_ endpoint is created,
corresponding to the value you set for the backend property. This endpoint can
be retrieved using EL by using the following syntax:

`{#endpoints['default']}`

== Request
=== Properties
|===
.^|Property      |Description            ^.^|Type            |Example

.^|id            |Identifier             ^.^|string          |12345678-90ab-cdef-1234-567890ab
.^|transactionId |Transaction identifier ^.^|string          |cd123456-7890-abcd-ef12-34567890
.^|uri           |URI                    ^.^|string          |/v2/store/MyStore?order=100
.^|path          |Path                   ^.^|string          |/v2/store/MyStore
.^|paths         |Path parts             ^.^|array of string |[,v2,store,MyStore]
.^|pathInfo      |Path info              ^.^|string          |/store/MyStore
.^|pathInfos     |Path info parts        ^.^|array of string |[,store,MyStore]
.^|contextPath   |Context path           ^.^|string          |/v2/
.^|params        |Query parameters       ^.^|key / value     |order -> 100
.^|pathParams    |Path parameters        ^.^|key / value     |storeId -> MyStore (__see Warning for details__)
.^|headers       |Headers                ^.^|key / value     |X-Custom -> myvalue
.^|method        |HTTP method            ^.^|string          |GET
.^|scheme        |HTTP scheme            ^.^|string          |http
.^|version       |HTTP version           ^.^|string          |HTTP_1_1
.^|timestamp     |Timestamp              ^.^|long            |1602781000267
.^|remoteAddress |Remote address         ^.^|string          |0:0:0:0:0:0:0:1
.^|localAddress  |Local address          ^.^|string          |0:0:0:0:0:0:0:1
.^|content       |Body content           ^.^|string          |-
|===

[WARNING]
====
* `{#request.content}` is only available when the policy is bound to an `on-request-content` phase.
* `{#request.pathParams}` keys are based on the path defined in policies configuration. For the example above, the defined path is `/store/:storeId`
====
=== Example

* Get the value of the `Content-Type` header for an incoming HTTP request:
`{#request.headers['content-type']}`

* Get the second part of the request path:
`{#request.paths[1]}`

== Request context
=== Properties
|===
|Property |Description |Type |Always present

.^|attributes
|Request context attributes
^.^|key-value
^.^|X
|===

=== Attributes
When APIM Gateway handles an incoming HTTP request, some attributes are
automatically created. These attributes are:

|===
|Property |Description |Type |Nullable

.^|context-path
|Context-path
^.^|string
^.^|-

.^|resolved-path
|Resolved-path is the path defined in policies
^.^|string
^.^|-

.^|application
|The authenticated application doing incoming HTTP request
^.^|string
^.^|X (for keyless plan)

.^|api
|Called API
^.^|string
^.^|-

.^|user-id
|The user identifier of incoming HTTP request:

* The subscription id for api-key based plan

* Remote IP for keyless based plan

^.^|string
^.^|-

.^|plan
|Plan used to manage incoming HTTP request
^.^|string
^.^|-

.^|api-key
|the api-key used (in case of an api-key based plan)
^.^|string
^.^|X (for no api-key plan)
|===

Additionally, some policies (like the link:/apim/3.x/apim_policies_oauth2.html#attributes[OAuth2 policy])
register other attributes in the context. See the documentation for the policies you are using for more information.

=== Example

* Get the value of the `user-id` attribute for an incoming HTTP request:

`{#context.attributes['user-id']}`

* Get the value of the `plan` attribute for an incoming HTTP request:

`{#context.attributes['plan']}`

* Check that the path starts with a given value:

`{#request.path.startsWith('/my/api')}`

== Policies
Expression language can be used to configure some aspects of policy configuration.
The policy needs to specify if it supports EL or not.

== Mixin

In previous examples, we showed various ways to manipulate objects available
in the EL context. You can also mix property
usage to provide an increasingly dynamic configuration.

For example, we can retrieve the value of an HTTP header where the name
is based on an API property named `my-property`:

`{#request.headers[#properties['my-property']]}`
