---
redirect_from:
  - /apim/3.x/apim_kubernetes_admission_hook.html
---
= Admission WebHooks
:page-liquid:

The three custom resources provided with the Kubernetes plugin can be referenced by each other. Because the Kubernetes plugin is notified once the changes are persisted, consistency issues may appear. For example, removing a plugin currently used by a service will prevent the service from being deployed if the Gateway restarts. To avoid this kind of issue, an https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/[admission WebHook] has been included.

Using this _admission webhook_ some checks are performed before the preservation of the resource. For instance it prevents the following:

* Create or update a Gravitee resource (Plugin, Gateway or Service) using an unknown Kubernetes secret
* Create a Gravitee resource (Gateway or Service) using an unknown reference to a GraviteePlugin resource
* Delete a GraviteePlugin or a GraviteeGateway if they are referenced in a GraviteeService

== Configuration

The WebHook endpoint is exposed by APIM Gateway. To enable the admission WebHook, you need to:

* enable the endpoint using TLS on the deployed Gateway
* create a ClusterIP service
* create the `ValidatingWebhookConfiguration` resource

=== Generate Certificate Authority

If you don't have certificate authority, you can generate it as follows:

[source, bash]
----
# Set your own secret
CA_SECRET=changeit

openssl req -newkey rsa:4096 -keyform PEM -keyout ca.key -x509 -days 3650 -subj "/CN=gateway-admission-ca" -passout pass:${CA_SECRET} -outform PEM -out ca.pem
openssl pkcs12 -export -inkey ca.key -in ca.pem -out ca.p12 -passin pass:${CA_SECRET} -passout pass:${CA_SECRET} -name adminssion-webhook-ca
----

Based on this CA, you can then generate a certificate for the APIM Gateways. The common name must match the full name of the ClusterIP service used to access the WebHook (in this example `gateway-admission-webhook.default.svc`).

[source, bash]
----
# Set your own secrets
CA_SECRET=changeit
SERVER_SECRET=changeit

openssl genrsa -out server.key 4096
openssl req -new -key server.key -out server.csr -sha256 -subj "/CN=gateway-admission-webhook.default.svc"
openssl x509 -req -in server.csr -CA ca.pem -CAkey ca.key -set_serial 100 -extensions server -days 1460 -outform PEM -out server.cer -sha256 -passin pass:${CA_SECRET}
openssl pkcs12 -export -inkey server.key -in server.cer -out server.p12 -passout pass:${SERVER_SECRET} -name gateway-server
----

=== APIM Gateway configuration

Once the **C**ertificate **A**uthority and the server certificate are created, it is possible to configure a APIM Gateway to expose the WebHook endpoint using the service `core/http`.

Create a Kubernetes secret to store the server certificate:

[source, bash]
----
kubectl create secret generic --from-file=server.p12=/path/to/server.p12 --from-literal=keystore-password=${SERVER_SECRET} gateway-server-webhook-cert
----

You then need to complete the chart values for the APIM Gateway with the following elements:

* an environment variable containing the server keystore passord using the secret created
* the service `core` needs to be reachable from outside the container to configure a PKCS12 `keystorecreated`
* a volume mounted using the secret created to expose the `server.p12` file

[source, yaml]
----
gateway:
  env:
  - name: GRAVITEE_SERVICES_CORE_HTTP_SSL_KEYSTORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: gateway-server-webhook-cert
        key: keystore-password
  services:
    core:
      http:
        enabled: true
        port: 18082
        host: "0.0.0.0"
        authentication:
          type: "none"
        secured: true
        ssl:
          keystore:
            type: "PKCS12"
            path: "/p12/keystore"
    kubeController:
      enabled: true
      service-account: "gravitee-gateway-sa"
  additionalPlugins:
  - https://download.gravitee.io/graviteeio-apim/plugins/services/gravitee-kubernetes-controller/gravitee-kubernetes-controller-0.1.0.zip
  extraVolumes: |
    - name: secretp12
      secret:
        secretName: gateway-server-webhook-cert
        items:
        - key: server.p12
          path: keystore
  extraVolumeMounts: |
    - mountPath: /p12
      name: secretp12
----

=== Admission Registration

Before creating the `ValidatingWebhookConfiguration`, a ClusterIP service is required as contact point for APIM Gateway.

NOTE: Remember that the service name must match the one defined during server certificate creation.

[source, yaml]
----
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: gateway
  name: gateway-admission-webhook
spec:
  ports:
    - name: webhook
      port: 18082
      protocol: TCP
      targetPort: 18082
  selector:
    app.kubernetes.io/component: gateway
  type: ClusterIP
----

Finally, the `ValidatingWebhookConfiguration` can be created using the following definition.

NOTE: The ``caBundle`` contains the **C**ertificate **A**uthority in PEM format encoded in Base64. Use this command to obtain the value: ``cat ca.pem | base64 -w 0``

[source, yaml]
----
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "admission-hook.gravitee.io"
webhooks:
  - name: "gateway-admission-webhook.default.svc"
    rules:
      - apiGroups:   ["gravitee.io"]
        apiVersions: ["v1alpha1"]
        operations:  ["CREATE", "UPDATE", "DELETE"]
        resources:   ["*"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: default
        name: gateway-admission-webhook
        port: 18082
        path: "/hooks/kube/admission"
      caBundle: "LS0tLS1CRUdJTi....S0tLQo="
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
----
