= Docker Compose
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_docker_compose.html
:page-folder: am/installation-guide
:docker-image-src: https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/images
:github-repo: https://github.com/gravitee-io/graviteeio-access-management/tree/master/docker
:docker-hub: https://hub.docker.com/r/graviteeio
:page-layout: am

== Overview

This section explains how to run AM images in Docker. It is intended for users who are already familiar with Docker.

NOTE: If you want to change the default configuration for any of the component images , see the relevant component section in the link:{{ 'am/current/am_configurationguide.html' | relative_url }}[AM Configuration Guide^].

== Prerequisites

To run our images, you must start by installing https://docs.docker.com/installation/[Docker^].

== Images

The AM Docker images are https://hub.docker.com/u/graviteeio/[available on Docker Hub^].
You can find all the https://github.com/gravitee-io/graviteeio-access-management/tree/master/docker/[Dockerfiles on GitHub^].

== Run AM

You can run a complete AM environment using our `docker-compose` file. It includes all the AM components and MongoDB.

[source,shell]
....
# Download required Docker Compose files
$ mkdir -p config
$ curl -L -O https://raw.githubusercontent.com/gravitee-io/graviteeio-access-management/master/docker/compose/docker-compose.yml
$ curl -O https://raw.githubusercontent.com/gravitee-io/graviteeio-access-management/master/docker/compose/.env
$ cd config && { curl -O https://raw.githubusercontent.com/gravitee-io/graviteeio-access-management/master/docker/compose/config/nginx.conf ; cd -; }

# (Optional step: pull to ensure that you are running latest images)
$ docker-compose pull

# And run...
$ docker-compose up
....

== EE deployment

To turn on the enterprise edition mode of Access Management, you have to provide a license key to the containers and additional plugins.

You can find below a docker-compose configuration snippet that mount two volumes for both AM Management API and AM Gateway :

* to deploy enterprise plugins in an additional plugin directory
* to deploy the license file

[source,yaml]
----
  management:
    image: graviteeio/am-management-api:3.18.0
    container_name: gio_am_management
    volumes:
      - /path/to/plugins-dir:/opt/graviteeio-am-management-api/plugins-ee
      - /path/to/license-dir/license.key:/opt/graviteeio-am-management-api/license/license.key
    environment:
      - GRAVITEE_PLUGINS_PATH_0=/opt/graviteeio-am-management-api/plugins
      - GRAVITEE_PLUGINS_PATH_1=/opt/graviteeio-am-management-api/plugins-ee

  gateway:
    image: graviteeio/am-gateway:3.18.0
    container_name: gio_am_gateway
    restart: always
    volumes:
      - /path/to/plugins-dir:/opt/graviteeio-am-gateway/plugins-ee
      - /path/to/license/license.key:/opt/graviteeio-am-gateway/license/license.key
    environment:
      - GRAVITEE_PLUGINS_PATH_0=/opt/graviteeio-am-gateway/plugins
      - GRAVITEE_PLUGINS_PATH_1=/opt/graviteeio-am-gateway/plugins-ee
----

NOTE: For versions prior to version 3.18, please use explicitly a version tagged EE like `3.15.0-ee`.

== Check AM is running

When all components are started, you can run a quick test by checking these URLs:

|===
|Image |URL

|{docker-hub}/am-gateway/[graviteeio/am-gateway]
|http://localhost/am/

|{docker-hub}/am-management-api/[graviteeio/am-management-api]
|http://localhost/am/management

|{docker-hub}/am-webui/[graviteeio/am-management-ui]
|http://localhost/am/ui/

|===

== Run AM with a different version or port

If you want to run a different version of AM or change the default port, you can run
`docker-compose` as follows:

[source,shell]
....
$ GIO_AM_VERSION=3 NGINX_PORT=18000 docker-compose up
....

== Run AM with a single command

If you want to get up and running quickly with AM 3.x, you can also run the following command line:

[source,shell]
....
$ curl -L https://bit.ly/docker-am-3x | bash
....

NOTE: You can change default http port (80), by passing `-s <port>` argument to the curl command.

[source,shell]
....
$ curl -L https://bit.ly/docker-am-3x | bash -s 8080
....

The validation steps are the same as in the previous section.
