[[apim-v4-beta-introduction-to-event-native-api-management]]
= Introduction to Event-native API Management (V4 BETA)
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_v4_beta_event_native_api_management_introduction.html
:page-folder: apim/v4-beta
:page-layout: apim3x

[label label-version]#New in version 3.19.0#
[label label-version]#BETA release#

== What is Event-native API Management?

















!!!!!!!
old content - delete:

== New policy execution mode (V4 BETA)

Release 3.19.0 of the Gravitee API Management platform has introduced the first version (BETA) of a new policy execution engine lays the foundation for an evented Gateway to enable event-native API management.

The new V4 policy execution engine enables a new execution flow for Sync APIs and supports the event-driven execution for Async APIs.

It is based on a modern and fully reactive architecture designed to address a number of challenges users have been facing with the existing v3 engine, and to build the foundation of Gravitee's event-native platform by adding features such as native support for Pub/Sub (Publish-Subscribe) design and enabling policies at message level. The new API definition makes it possible for the Gateway to “know” what is necessary in order for it to handle asynchronous API use cases.

The new policy execution engine mode provides the following capabilities:

* The ability to execute policies in the exact order in which they have been placed in Policy Studio. This addreses some issues experienced by users related to the order in which policies are executed by the existing v3 engine where policies interacting with the Head part of the request are always executed first, even when placed in a different order in the Policy Studio during the design phase. With the new execution engine, it is now possible to apply logic on a head policy based on the payload of the request for example, to apply dynamic routing based on the request payload.
* Proper isolation between platform-level policies and API-level policies execution. This ensures that platform-level policies are always executed before any API-level policies during the request stage, and after any API-level policies during the response stage.
* Removal of the need to define a scope for policies (`onRequest`, `onRequestContent`, `onResponse`, `onResponseContent`).
* The introduction of new API types to better differentiate REST APIs from Async APIs (Websocket, SSE, Webhook), as a foundation to fully support the execution of AsyncAPI.

The BETA release does not provide UI support for these capabilities.
