[[event-native-tutorials-mqtt-http]]
= MQTT and HTTP
:page-sidebar: apim_3_x_sidebar
:page-permalink: /apim/3.x/event_native_tutorials_mqtt_http.html
:page-folder: apim/v4-beta
:page-layout: apim3x

== Prerequisites 

Before running this tutorial, you must have the Gravitee API Management Gateway and HiveMQ running in Docker, as specified in link:{{'/apim/3.x/event_native_tutorials_apim.html' | relative_url}}[Installing APIM] and link:{{'/apim/3.x/event_native_tutorials_hivemq.html'| relative_url}}[Installing HiveMQ]

To confirm they are running, go to `http://localhost:8084` and `http://localhost:8086`.

== Setting up Postman

1. Download link:{{'https://raw.githubusercontent.com/gravitee-io-labs/Gravitee.io-API-Management-Tutorials/main/apim-3.20/POST-to-MQTT/POST-to-MQTT.postman-collection.json'|relative_url}}[`postman-collection.json`] and import it into Postman.

The collection `3.20 - POST to MQTT` should now appear in the right sidebar.

_Note to Linus: I expect the URL and other details of the Postman collection will be different in the final version of this document. It may be that "Setting up Postman" is 'promoted' to being a page on its own and is referred to in the prerequisites section._

== Creating the API

1. In the `3.20 - POST to MQTT` collection, navigate to the "Create the API" `POST` request, and send it. You should receive the following response.
+
[code,json]
----
sample
----
+
The first key-pair value in the response specifies the unique ID of the API.
2. Copy the ID, and paste it into the api field in the environment file. 

_Note to Linus: This is a very simple example; future tutorials will have more complex examples here._

== Creating a keyless plan

1. Select the "Create an Open (Keyless) Plan" and send it. You should receive the following response.
+
[code,json]
----
sample
----
+
The first key-pair value in the response specifies the unique ID of the plan.
2. Copy the ID, and paste it into the plan field in the environment file. 

== Starting the API

1. Send the "Start API" POST request.

== Using the API

_Note to Linus: I will be putting various examples in here, such as posting content to MQTT and getting content from it._