[[event-native-tutorials-apim]]
= Installing APIM
:page-sidebar: apim_3_x_sidebar
:page-permalink: /apim/3.x/event_native_tutorials_apim.html
:page-folder: apim/v4-beta
:page-layout: apim3x

This page describes how to install and run APIM in Docker containers on `localhost`.

== Prerequisites

Docker must be installed and running. For more information about installing Docker, see the link:{{'https://www.docker.com/' | relative_url }}[Docker website].

== Installing APIM

1. Download the `docker-compose.yml` file.
+
[code,bash]
----
curl https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml -O  
----

2. Open `docker-compose.yml` in a text editor and add the following line to `/services/gateway/environment` section if it is not already there.
+
[code,yml]
----
- gravitee_api_jupiterMode_enabled=true
----
+
This ensures that the gateway runs with its event-native features enabled.

3. In `docker-compose.yml`, make sure that all the `APIM_VERSION` variables are set to `{APIM_VERSION:-3.20.0}`
+This ensures you are using the correct version of APIM.

4. Run `docker compose` to download and start all of the components.
+
[code,bash]
----
docker compose up -d
----

5. In your browser, go to `http://localhost:8084` to open the APIM UI. You can log in with the Username `admin` and Password `admin`.
+
[TIP]
====
Sometimes it can take a few minutes for APIM to fully start. If you get an error when going to `http://localhost:8084`, wait a few minutes and try again.
====