[[v4-beta-event-native-apim-user-guide]]
= User guide
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/event_native_apim_user_guide.html
:page-folder: apim/v4-beta
:page-layout: apim3x

[label label-version]#New in version 3.20.0#
[label label-version]#BETA release#

[NOTE]
====
This document assumes you are familiar with synchronous APIs, asynchronous APIs, and the OpenAPI specification.
====

[TIP]
====
Before running any of the examples on this page, work through some of the  link:event_native_apim_example_use_cases.html[example use cases] so you know that the event-native engine is running.
====

== Asynchronous APIs

In this release of Gravitee API Management, you can create asynchronous APIs and connect to event brokers and asynchronous data sources. You can configure asynchronous API connections using the RESTful interface to the management API.

The OpenAPI specification for the management API is available at link:/apim/3.x/management-api/3.20/swagger.json[`swagger.json`] (link:/apim/3.x/apim_installguide_rest_apis_documentation.html#apim_console_api_reference[reference documentation]). Examples of how to use the management API to configure asynchronous APIs can be found in the link:https://www.postman.com/gravitee-io/workspace/gravitee-public-workspace/overview[Gravitee Postman Collections], which are described in link:event_native_apim_example_use_cases.html[example use cases].

[NOTE]
====
The management API is in beta and it may change.
====

== Listeners

Gravitee API Management is based mainly on the HTTP protocol, but data can also be consumed by subscription. It has two types of listener: `HTTP` and `SUBSCRIPTION`.

* `HTTP`: this is the most common type of listener. Most synchronous and asynchronous APIs use this listener and consume data over HTTP.
* `SUBSCRIPTION`:  this type of listener is used for specific APIs. It is particularly useful for Webhook which requires the gateway to accept a subscription to start consuming messages from an endpoint and send them to an external Webhook.

== Entrypoints

An _entrypoint_ is how an end user connects to the Gravitee Gateway. The following types of entrypoints are available.

=== HTTP POST

//see link:{{'/apim/3.x/event_native_apim_introduction.html#http_post_and_http_get_entrypoints' | relative_url}}[HTTP POST and HTTP GET entrypoints]

=== HTTP GET

=== Server-sent events (SSE)

(Normal and Advanced)

=== Webhooks

_Brief description of Webhooks, mentioning normal and advanced versions_

_Table or list showing features_

_Simple explanation of use_

_Limitations, if any_


=== Websockets

// link:{{'/apim/3.x/event_native_apim_introduction.html#support_for_websocket_and_sse_entrypoints' | relative_url}}[Support for Websocket and SSE entrypoints]


== Endpoints

An _endpoint_ is how the Gravitee Gateway connects to the source of data. The following types of endpoints are available.

=== Kafka

Kafka is a distributed event-streaming platform used for high-performance data pipelines, streaming analytics, and data integration. There are two connectors, Kafka and Kafka Advanced. Kafka Advanced is only available for the Enterprise Edition of the Gravitee Gateway.

.Kafka Connectors
|===
|Feature | Kafka | Kafka Advanced

| Feature 1 | Yes | Yes
| Feature 2 | No | Yes

|===

// Kafka use cases described on use cases page

=== MQTT 5

MQTT is a lightweight publishing/subscribe transport that is used in the Internet of Things. Gravitee's MQTT connectors currently only support MQTT 5. There are two connectors, MQTT and MQTT Advanced. MQTT Advanced is only available for the Enterprise Edition of the Gravitee Gateway.

.MQTT Connectors
|===
| Feature | MQTT | MQTT Advanced 

| Protocol mediation 
| Yes | Yes 

| link:#quality_of_service[Quality of Service]
| No | Yes

| Advanced security (username and password over TLS)
| No | Yes
|===

The MQTT connector is useful where, for example, only protocol mediation is needed but guaranteed delivery or security.

The MQTT Advanced connector is useful where messages must be delivered reliably (through quality of service) or securely (using advanced security), such as to customers who would pay for such information.

== Additional types of endpoints and entrypoints

You can add additional types of endpoints and entrypoints by adding a type of plugin called a connector.

You can download additional entrypoint connectors from the link:https://download.gravitee.io/#graviteeio-apim/plugins/entrypoints/[Gravitee APIM entrypoint plugins download page]

You can download additional endpoint connectors from the link:https://download.gravitee.io/#graviteeio-apim/plugins/endpoints/[Gravitee APIM endpoints plugins download page] and the link:https://download.gravitee.io/#graviteeio-ee/apim/plugins/entrypoints/[Gravitee APIM Enterprise Edition endpoints plugins download page]. 

They are standard plugins and can be installed as described in link:{{'/apim/3.x/apim_installation_guide_plugins.html' | relative_url}}[Installing and updating Plugins].

[NOTE]
====
Connectors with `advanced` in their filenames can only be used with the Enterprise Edition of the Gravitee Gateway.
====

== How to create a V4 BETA asynchronous API

The link:https://www.postman.com/gravitee-io/workspace/gravitee-public-workspace/overview[Gravitee V4 BETA Postman Collection] contains several examples of how to create and test an asynchronous API using the event-native V4 BETA API definition and link:{{'/apim/3.x/v4_new_policy_execution_engine_introduction.html' | relative_url}}[the new V4 BETA policy execution engine] .

For example, to create an HTTP POST entrypoint that connects to a Kafka endpoint, send a POST request to `{\{management_host}}/management/organizations/DEFAULT/environments/DEFAULT/v4/apis/`, where `{\{management_host}}` is the host for the management API, with the following message body:

[source json]
----
{
    "name": "Data Ingestion to Kafka",
    "apiVersion": "1.0",
    "definitionVersion": "4.0.0",
    "type": "async",
    "description": "Data Ingestion to Kafka",
    "listeners": [
        {
            "type": "http",
            "paths": [
                {
                    "path": "/data/ingestion/kafka"
                }
            ],
            "entrypoints": [
                {
                    "type": "http-post",
                    "configuration": {
                        "requestHeadersToMessage": false
                    }
                }
            ]
        }
    ],
    "endpointGroups": [
        {
            "name": "default",
            "type": "kafka",
            "endpoints": [
                {
                    "name": "default",
                    "type": "kafka",
                    "weight": 1,
                    "inheritConfiguration": false,
                    "configuration": {
                        "bootstrapServers": "kafka:9092",
                        "topics" : ["demo"],
                        "consumer" : {
                            "enabled": false
                        },
                        "producer": {
                            "enabled": true
                        }
                    }
                }
            ]
        }
    ],
    "flows": [
        {
            "name": "",
            "selectors": [],
            "request": [],
            "response": [],
            "subscribe": [],
            "publish": [],
            "enabled": true
        }
    ]
}
----

== Quality of Service

When working with asynchronous APIs, quality of service is important. Quality of service defines the guaranteed level of message delivery. For example, a quality of service of "none" means that a given message might be delivered zero, one, or several times. A quality of service of "at-most-once" means that a given message will be delivered zero or one times, with no duplication.

A higher quality of service could lead to lower system performance depending on the endpoint chosen.

The quality of service is set on the entrypoints (see link:#setting_quality_of_service[Setting quality of service]). A given quality of service may or may not be supported by a given endpoint (see link:#compatibility[Compatibility]). Support also depends on the protocol used for the entrypoint.

For example, when using an HTTP listener with a websocket entrypoint it is not possible to ensure data is received by the client, so no quality of service can be guaranteed.

However, when using Subscription listener, it can be ensured that messages sent are received either by using the HTTP return code (for Webhook) or a transactional publisher (for Kafka). For these entrypoints, the quality of service can be increased.

The quality-of-service levels are described in the following table.

.Table Quality of service levels
[cols="1,4"]
|===
|Level | Description

| None
| A given message might be delivered zero, one, or many times. This level allows high throughput and good performance but without guaranteed delivery. After failure or disconnection, the client will only receive messages sent after reconnection.

| Auto (0 or N)
| A given message might be delivered zero, one, or many times. This level allows a trade-off between performance and delivery guarantee. Delivery is highly dependent on the capabilities supported by the endpoint connector.  In case of failure or disconnection, after reconnection the client will resume, if possible, from a previously saved state, although duplication of messages could potentially exist.

| At-Most-Once (0 or 1)
| A given message might be delivered zero times or once without any duplication. Depending on the capabilities of the entrypoint connector, performance could be degraded.

| At-Least-Once (1 or N)
| A given message is delivered once or many times. This level gives a good balance between guaranteed delivery and performance when compared to At-Most-Once, especially when the entrypoint connector is not able to resume message streams after failure.

|===

=== Setting quality of service

You can set quality of service levels with the `qos` object in the `entrypoints` object, as shown in the following example. See the link:/apim/3.x/management-api/3.20/swagger.json[`swagger.json`] definition of the Management API for a list of possible `qos` values you can specify.

[source json]
----
"entrypoints": [
                {
                    "type": "sse",
                    "qos": "none",
                    "configuration": {
                        "heartbeatIntervalInMs": 5000,
                        "metadataAsComment": false,
                        "headersAsComment": false
                    }
                }
            ]
----

=== Compatibility

Not all levels of quality of service work with every entrypoint / endpoint combination. The following table shows how they can be used.

.Table Quality of service compatibility matrix
|===
| Entrypoint| MQTT5 endpoint | MQTT5 advanced endpoint | Kafka endpoint | Kafka advanced endpoint

| SSE
| At-Least-Once, At-Most-Once
| At-Least-Once, At-Most-Once
| None, Auto
| None, Auto, At-Least-Once, At-Most-Once

| SSE advanced
| At-Least-Once, At-Most-Once
| At-Least-Once, At-Most-Once
| None, Auto
| None, Auto, At-Least-Once, At-Most-Once

| HTTP POST
| None, Auto
| None, Auto
| None, Auto
| None, Auto

| HTTP GET
| Auto
| Auto
| Auto
| Auto, At-Least-Once, At-Most-Once

| Websocket
| None, Auto
| None, Auto
| None, Auto
| None, Auto

| Webhook
| At-Least-Once, At-Most-Once
| At-Least-Once, At-Most-Once
| None, Auto
| None, Auto, At-Least-Once, At-Most-Once

| Webhook advanced
| At-Least-Once, At-Most-Once
| At-Least-Once, At-Most-Once
| None, Auto
| None, Auto, At-Least-Once, At-Most-Once

|===

== Policies

Policies are steps in the gateway execution chain. A policy guarantees that a given business rule will be fulfilled during processing.

Policies can be set on request, response, subscribe, or publish phases. The following example shows how to set a policy on a subscribe phase.

[source json]
----
"subscribe": [
                {
                    "name": "Message filtering",
                    "description": "Apply filter to messages",
                    "enabled": true,
                    "policy": "message-filtering",
                    "configuration": {
                        "filter": "{#message.headers.foo == #subscription.metadata['bar']}"
                    }
                }
            ]
----

For an example, see _04 - Event Consumption - Webhook_ > _Webhook Messaging Filtering_ > _Create API_ in the link:https://www.postman.com/gravitee-io/workspace/gravitee-public-workspace/overview[Gravitee V4 BETA Postman Collection].

== Use cases

The link:https://www.postman.com/gravitee-io/workspace/gravitee-public-workspace/overview[Gravitee V4 BETA Postman Collection] contains several examples of how end users can work with your asynchronous APIs. Some examples are described on link:event_native_apim_example_use_cases.html#event_consumption[Event consumption].
