= Contributing to Gravitee.io

You think Gravitee.io is awesome and want to contribute to the project?
Here are few guidelines that should help you get started.

== Using GitHub issues

We use GitHub issues to track bugs and enhancements. Found a bug in the source code? Want to propose new features or enhancements?
You can help us by submitting an issue in our https://github.com/gravitee-io/issues/issues[repository].
Before submitting your issue, please search the https://github.com/gravitee-io/issues/issues[issues archive] to see if your question has already been answered.

Providing the following information will help us deal quickly with your issue:

* **Overview of the issue** : describe the issue and why this is a bug for you.
* **Gravitee.io version(s)** : possible regression ?
* **Browsers and Operating System** : Linux/Windows/Docker ? Browser version for the UI, etc ...
* **You have stack trace, screenshots, logs ?** add these to the issue's description.

== Git Branch Process

This repository is mainly using 2 branches:

 - `master`: ⚠️⚠️⚠️ Any merge or commit pushed on this branch will be immediately and automatically deployed to the production documentation website: http://docs.gravitee.io/
 - `next`: This branch is used to deploy https://nightly-docs.gravitee.io and should be targeted for any documentation update related to a feature not released yet.

Each time something is merged on `master` the `develop` branch is rebased and force pushed:
[source,shell]
----
git checkout master
git fetch --prune && git pull
git checkout develop
git rebase master
# You may need to fix some conflicts
git push --force
----

== Submitting changes

You've submitted an issue to the project and know how to fix it? You can contribute to the project by https://guides.github.com/activities/forking/[forking the repository] and https://guides.github.com/activities/forking/#making-a-pull-request[submitting your pull requests].

Before you submit your pull request consider the following guidelines:

* Make your changes in a new git branch:

[source,shell]
----
git checkout -b my-branch master
----

* Commit your changes using a descriptive commit message.

[source,shell]
----
 git commit -a
----

* Build the doc locally to **ensure everything is ok** (the CI will do the same):

[source,shell]
----
bundle exec jekyll build
----

* Push your branch to GitHub:

[source,shell]
----
git push origin my-branch
----

* In GitHub, send a pull request to `<gravitee-io/gravitee-docs>`, according to the content of your changes you will
either target `master` (for hotfix) or `next` (for new features not released yet).

⚠️ Before submitting the PR please check it is not oudated and rebase it on `master` or `next` if needed

[source,shell]
----
git rebase master
git push --force
----

== Contributor License Agreement

Please sign our https://download.gravitee.io/cla.pdf[Contributor License Agreement (CLA)] and send it to contact@graviteesource.com. For any code changes to be accepted, the CLA must be signed.

== Further Information

You can find more detailed information about contributing in the https://guides.github.com/activities/contributing-to-open-source/[Github guides].
