[[event-native-apim-documentation]]
= Documentation
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/event_native_apim_documentation.html
:page-folder: apim/event-native-apim
:page-layout: apim3x

[label label-version]#New in version 3.20.0#
[label label-version]#BETA release#

== Overview

_This page is for the draft event-native APIM docmentation that Andrew is writing for 3.20. It is here only for initial draft and review purposes. It will be split into different pages and (probably) moved to a new location later._

== Asynchronous APIs

In this release, you can use the gateway to connect to asynchrous APIs. You can configure asynchronous API connections using the RESTful interface to the management API.

The OpenAPI speccification for the management API is available at link:/apim/3.x/management-api/3.19/swagger.json[`swagger.json`] (link:/apim/3.x/apim_installguide_rest_apis_documentation.html#apim_console_api_reference[reference documentation]). Examples of how to use the management API to configure asynchrous APIs can be found in the link:https://github.com/gravitee-io/postman-collections[Gravitee Postman Collections], which are described in link:event_native_apim_using.html[Using Event-native API Management].

The following entrypoints are available.

* SSE
* Websockets
* HTTP GET
* HTTP POST

The following endpoints are available

* Kafka
* MQQT

== Create a v4 async API 

The link:https://github.com/gravitee-io/postman-collections[Gravitee Postman Collections] contain several examples of how to create an API.

For example, to create an HTTP POST entrypoint that connects to a Kafka endpoint, send a POST request to `{\{management_host}}/management/organizations/DEFAULT/environments/DEFAULT/v4/apis/`, where `{\{management_host}}` is the host for the management API, with the following message body:

[source json]
----
{
    "name": "Data Ingestion to Kafka",
    "apiVersion": "1.0",
    "definitionVersion": "4.0.0",
    "type": "async",
    "description": "Data Ingestion to Kafka",
    "listeners": [
        {
            "type": "http",
            "paths": [
                {
                    "path": "/data/ingestion/kafka"
                }
            ],
            "entrypoints": [
                {
                    "type": "http-post",
                    "configuration": {
                        "requestHeadersToMessage": false
                    }
                }
            ]
        }
    ],
    "endpointGroups": [
        {
            "name": "default",
            "type": "kafka",
            "endpoints": [
                {
                    "name": "default",
                    "type": "kafka",
                    "weight": 1,
                    "inheritConfiguration": false,
                    "configuration": {
                        "bootstrapServers": "kafka:9092",
                        "topics" : ["demo"],
                        "consumer" : {
                            "enabled": false
                        },
                        "producer": {
                            "enabled": true
                        }
                    }
                }
            ]
        }
    ],
    "flows": [
        {
            "name": "",
            "selectors": [],
            "request": [],
            "response": [],
            "subscribe": [],
            "publish": [],
            "enabled": true
        }
    ]
}
----

== Quality of Service 

You can set quality of service with the `qos` object in the `entrypoints` object, as shown in the following example. It can have a value of `none`, `auto`, `at-most-once`, or `at-least-once`.

[source json]
----
"entrypoints": [
                {
                    "type": "sse",
                    "qos": "none",
                    "configuration": {
                        "heartbeatIntervalInMs": 5000,
                        "metadataAsComment": false,
                        "headersAsComment": false
                    }
                }
            ]
----

== Policies

You can set a policy on a subscription by setting the `policy` object in the `subscribe` object, as shown in the following example.

[source json]
----
"subscribe": [
                {
                    "name": "Message filtering",
                    "description": "Apply filter to messages",
                    "enabled": true,
                    "policy": "message-filtering",
                    "configuration": {
                        "filter": "{#message.headers.foo == #subscription.metadata['bar']}"
                    }
                }
            ]
----

For an example, see _04 - Event Consumption - Webhook_ > _Webhook Messaging Filtering_ > _Create API_ in The link:https://github.com/gravitee-io/postman-collections[Gravitee Postman Collections].

== Consume a v4 API

The link:https://github.com/gravitee-io/postman-collections[Gravitee Postman Collections] contain several examples of how to consume an API. Some examples are described on link:event_native_apim_using.html#event_consumption[Event consumption].