[[event-native-apim-documentation]]
= Documentation
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/event_native_apim_documentation.html
:page-folder: apim/event-native-apim
:page-layout: apim3x

[label label-version]#New in version 3.20.0#
[label label-version]#BETA release#

== Overview


== Asynchronous APIs

In this release, you can use the gateway to connect to asynchronous APIs. You can configure asynchronous API connections using the RESTful interface to the management API.

The OpenAPI specification for the management API is available at link:/apim/3.x/management-api/3.19/swagger.json[`swagger.json`] (link:/apim/3.x/apim_installguide_rest_apis_documentation.html#apim_console_api_reference[reference documentation]). Examples of how to use the management API to configure asynchronous APIs can be found in the link:https://github.com/gravitee-io/postman-collections[Gravitee Postman Collections], which are described in link:event_native_apim_using.html[Using Event-native API Management].

[NOTE]
====
The management API is in beta and it may change.
====

== Entrypoints and endpoints

An _entrypoint_ is how an end user connects to the Gravitee gateway. An _endpoint_ is how the Gravitee gateway connects to the upstream API.

The following types of entrypoint are available.

* SSE
* SSE advanced
* Websockets
* HTTP GET
* HTTP POST
* Webhook
* Webhook advanced (EE)

The following types of endpoint are available

* Kafka
* Kafka advanced (EE)
* MQTT
* MQTT advanced (EE)

=== Compatability

.Table Endpoint and entrypoint compatability matrix
|===
| Entrypoint| Request message (publish mode) | Response message (subscribe mode) | Endpoint

.4+| HTTP POST
| Yes
| No
| Mock

| Yes
| No
| Kafka, MQTT5, Kinesis,...

| No
| No
| SSE

| Yes
| No
| Websocket

.4+| HTTP GET
| No
| Yes
| Mock

| No
| Yes
| Kafka, MQTT5, Kinesis,...

| No
| Yes
| SSE

| No
| Yes
| Websocket

.4+| SSE
| No
| Yes
| Mock

| No
| Yes
| Kafka, MQTT5, Kinesis,...

| No
| Yes
| SSE

| No
| Yes
| Websocket

.4+| Websocket
| Yes
| Yes
| Mock

| Yes
| Yes
| Kafka, MQTT5, Kinesis,...

| No
| Yes
| SSE

| Yes
| Yes
| Websocket

.4+| Webhook
| No
| Yes
| Mock

| No
| Yes
| Kafka, MQTT5, Kinesis,...

| No
| Yes
| SSE

| No
| Yes
| Websocket

|===


== Create a v4 async API 

The link:https://github.com/gravitee-io/postman-collections[Gravitee Postman Collections] contain several examples of how to create an API.

For example, to create an HTTP POST entrypoint that connects to a Kafka endpoint, send a POST request to `{\{management_host}}/management/organizations/DEFAULT/environments/DEFAULT/v4/apis/`, where `{\{management_host}}` is the host for the management API, with the following message body:

[source json]
----
{
    "name": "Data Ingestion to Kafka",
    "apiVersion": "1.0",
    "definitionVersion": "4.0.0",
    "type": "async",
    "description": "Data Ingestion to Kafka",
    "listeners": [
        {
            "type": "http",
            "paths": [
                {
                    "path": "/data/ingestion/kafka"
                }
            ],
            "entrypoints": [
                {
                    "type": "http-post",
                    "configuration": {
                        "requestHeadersToMessage": false
                    }
                }
            ]
        }
    ],
    "endpointGroups": [
        {
            "name": "default",
            "type": "kafka",
            "endpoints": [
                {
                    "name": "default",
                    "type": "kafka",
                    "weight": 1,
                    "inheritConfiguration": false,
                    "configuration": {
                        "bootstrapServers": "kafka:9092",
                        "topics" : ["demo"],
                        "consumer" : {
                            "enabled": false
                        },
                        "producer": {
                            "enabled": true
                        }
                    }
                }
            ]
        }
    ],
    "flows": [
        {
            "name": "",
            "selectors": [],
            "request": [],
            "response": [],
            "subscribe": [],
            "publish": [],
            "enabled": true
        }
    ]
}
----

== Quality of Service 

You can set quality of service with the `qos` object in the `entrypoints` object, as shown in the following example. See the link:/apim/3.x/management-api/3.19/swagger.json[`swagger.json`] definition of the Management API For values that `qos` can have.

[source json]
----
"entrypoints": [
                {
                    "type": "sse",
                    "qos": "none",
                    "configuration": {
                        "heartbeatIntervalInMs": 5000,
                        "metadataAsComment": false,
                        "headersAsComment": false
                    }
                }
            ]
----

=== Compatability

Not all qualities of service work with every combination of entrypoint and endpoint. The following table shows how they can be combined.

.Table Quality of service compatability matrix
|===
| Entrypoint| MQTT5 | MQTT5 advanced | Kafka | Kafka advanced

| SSE
| none, auto
| none, auto
| none, auto
| none, auto

| SSE advanced
| none, auto
| none, auto
| none, auto
| none, auto, at least once, at most once

| HTTP POST
| none, auto
| none, auto
| none, auto
| none, auto

| HTTP GET
| auto
| auto
| auto
| auto, at least once, at most once

| Websocket
| none, auto
| none, auto
| none, auto
| none, auto

| SSE advanced
| none, auto
| none, auto, at least once, at most once
| none, auto
| none, auto, at least once, at most once

|===
== Policies

Policies can be set on requests, responses, subscriptions, and messages. The following example shows how to set a policy on a subsccription.

[source json]
----
"subscribe": [
                {
                    "name": "Message filtering",
                    "description": "Apply filter to messages",
                    "enabled": true,
                    "policy": "message-filtering",
                    "configuration": {
                        "filter": "{#message.headers.foo == #subscription.metadata['bar']}"
                    }
                }
            ]
----

For an example, see _04 - Event Consumption - Webhook_ > _Webhook Messaging Filtering_ > _Create API_ in The link:https://github.com/gravitee-io/postman-collections[Gravitee Postman Collections].

== Consume a v4 API

The link:https://github.com/gravitee-io/postman-collections[Gravitee Postman Collections] contain several examples of how to consume an API. Some examples are described on link:event_native_apim_using.html#event_consumption[Event consumption].