= Protocols
:page-sidebar: am_2_x_sidebar
:page-permalink: am/2.x/am_protocols_overview.html
:page-folder: am/protocols

Gravitee.io Access Management relies on different authorization/authentication/identity protocols to define how applications can interact with the Gravitee.io AM to authenticate, retrieve user information and make authorization decisions to access protected resources.

== link:/am/2.x/am_protocols_oauth2_overview.html[OAuth 2.0]

The OAuth 2.0 authorization framework enables a third-party application to obtain limited access to an HTTP service,
either on behalf of a resource owner by orchestrating an approval interaction between the resource owner and the HTTP service,
or by allowing the third-party application to obtain access on its own behalf.

== link:/am/2.x/am_protocols_oidc_overview.html[OpenID Connect]

OpenID Connect 1.0 is a simple identity layer on top of the OAuth 2.0 protocol.
It enables Clients to verify the identity of the End-User based on the authentication performed by an Authorization Server,
as well as to obtain basic profile information about the End-User in an interoperable and REST-like manner.