= Upgrade to 3.18.0


== Breaking changes

=== Environment Audits

Endpoint: `[GET] management/organizations/{orgId}/environments/{envId}/apis/{api}/audit` (link:{{ '/apim/3.x/management-api/' | relative_url | append: current_version | append: '/index.html#operation/getApiAudits' }}[API audits^]).

Before this version, the Management API allowed getting all audits of all environments and organizations with this endpoint.

As of 3.18.0, a GET request will return the audits of the environment specified in the url and no longer return organization audits.
To get organization audits you need to use the following endpoint: `[GET] management/organizations/{orgId}/audit`.

The query params `envLog:boolean` & `orgLog:boolean` are removed. 
Now to get only environment or organization audit you have to use the query params `referenceType:string` with `ENVIRONMENT` or `ORGANIZATION`. You can also filter by environment id with `environment:string` query params.


=== Platform alerts on multi-environments APIM

Before this version, platform alerts were common to all environments.
That led to inconsistencies while handling platform alerts on multi-environments APIM.

From this version, platform alerts are scoped to the environment.
For example, if you create an alert on your `production` environment, it is related only to this environment.

Old platform alerts existing before Gravitee upgrade will be linked to the default environment.
You will see them disappear from your others (non-default) environments, and will have to recreate them manually if relevant.

=== System Roles Edition

To provide more flexibility in the way roles are managed, some system roles have been made editable. From now on, the permissions of the following roles can be edited:

. The Environment Admin Role.
. The API Primary Owner Role
. The Application Primary Owner Role

The Organization Admin Role remains a read-only role. If any accidental loss of access happened to one of the roles listed above, the Organization Admin Role will be the only one able to revert the changes.
