= Upgrade to 3.18.0


== Breaking changes

=== Environment Audits

Endpoint: `[GET] management/organizations/{orgId}/environments/{envId}/apis/{api}/audit` (link:{{ '/apim/3.x/management-api/' | relative_url | append: current_version | append: '/index.html#operation/getApiAudits' }}[API audits^]).

Before this version, the Management API allowed getting all audits of all environments and organizations with this endpoint.

As of 3.18.0, a GET request will return the audits of the environment specified in the url and no longer return organization audits.
To get organization audits you need to use the following endpoint: `[GET] management/organizations/{orgId}/audit`.

The query params `envLog:boolean` & `orgLog:boolean` are removed. 
Now to get only environment or organization audit you have to use the query params `referenceType:string` with `ENVIRONMENT` or `ORGANIZATION`. You can also filter by environment id with `environment:string` query params.


=== Platform alerts on multi-environments APIM

Before this version, platform alerts were common to all environments.
That led to inconsistencies while handling platform alerts on multi-environments APIM.

From this version, platform alerts are scoped to the environment.
For example, if you create an alert on your `production` environment, it is related only to this environment.

Old platform alerts existing before Gravitee upgrade will be linked to the default environment.
You will see them disappear from your others (non-default) environments, and will have to recreate them manually if relevant.

=== System Roles Edition

To provide more flexibility in the way roles are managed, some system roles have been made editable. From now on, the permissions of the following roles can be edited:

. The Environment Admin Role.
. The API Primary Owner Role
. The Application Primary Owner Role

The Organization Admin Role remains a read-only role. If any accidental loss of access happened to one of the roles listed above, the Organization Admin Role will be the only one able to revert the changes.

This mode is deactivated by default, you can toggle it on via `gravitee.yml` :

----
console:
  systemRoleEdition:
    enabled: true
----

WARNING: Updating permissions for system roles should be done carefully to avoid any unexpected behavior.

=== Plugin renaming

From this version, and for the next 3.18.x versions and greater, the name of the Elasticsearch repository component changes. +
As a consequence, the Elasticsearch repository component available on https://download.gravitee.io is now +
`gravitee-*apim*-repository-elasticsearch-x.y.z.zip`

instead of +
`gravitee-repository-elasticsearch-x.y.z.zip`

This plugin has also been moved in another folder: +
https://download.gravitee.io/#graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/.

You can download directly the Elasticsearch repository using this link: +
https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/gravitee-apim-repository-elasticsearch-3.18.0.zip

=== MySQL

In 3.18.0, the MySQL Java driver has been updated to 8.0.29. As a consequence, TLS 1.0 and 1.1 are no longer supported.


== Plans data

Since this version, APIM improves plans data storage, and uses the `plans` database collection as the unique source of plans data.

Before trusting data in `plans` collection, we have to ensure their reliability.

In 3.10, an upgrader was introduced to fix data, but was running in dry-run mode per default.

This upgrader will run once again during APIM 3.18 startup, with dry-run mode disabled : if relevant, it will fix plans data in your database as it's explained in https://docs.gravitee.io/pages/apim/3.x/installation-guide/upgrades/3.10.8/README.html#plans_anomalies_in_database[this documentation]

== MongoDB

Before running any script, please create a dump of your existing database.

link:https://gh.gravitee.io/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.18.0/audit-set-environmentId-organizationId.js[/apim/3.x/mongodb/3.18.0/audit-set-environmentId-organizationId.js]::
This script add 'environmentId' and 'organizationId' columns in 'audits' table so audits can be associated to the right target. Creates also new indices.
link:https://gh.gravitee.io/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.18.0/clientRegistrationProvider-set-environmentId.js[/apim/3.x/mongodb/3.18.0/clientRegistrationProvider-set-environmentId.js]::
This script add 'environmentId' columns in 'client_registration_providers' table they can be associated to the right environment.
