:page-sidebar: ee_sidebar
:page-permalink: ee/ee_introduction.html
:page-folder: ee/overview
:page-toc: false
:page-description: Gravitee Enterprise Edition - Introduction
:page-keywords: Gravitee, API Platform, Enterprise Edition, documentation, manual, guide, reference, api

[[gravitee-enterprise-api-platform]]
= Gravitee.io Enterprise API Platform

== Introduction

Since 2015, the Gravitee.io team is providing the amazing (we hope) Gravitee.io API Platform under the Apache v2 license.
To make the platform even better, we (at GraviteeSource) are looking to provide you with additional modules to:

- Improve your API platform with additional modules (Alert Engine, ...)
- Improve the platform capabilities with additional plugins (SAML support, social connectors, ...)
- Help you to manage your growing organization and your digital vision with APIs

We keep in mind that Gravitee.io would not be there without a great community and a large audience thanks to the OSS philosophy.

That's one of the reason why we choose to not apply any change to the existing platform (APIM vs AM) and those modules will still
be released under the Apache v2 License.

If you're talking with the team on Gitter, you may see and understand that we have more and more questions, more and more business contexts to manage, and more and more features to implement
to provide you with the most amazing API Platform. All those things need time, for sure, but also money.

That's why we choose to create the Gravitee.io Enterprise API Platform. This version has many benefits and we are looking
to provide really exciting features to help you and your company on our initial thinking: unleash the power of your APIs.


And the story begins...