:page-sidebar: ee_sidebar
:page-permalink: ee/ee_introduction.html
:page-folder: ee/overview
:page-toc: false
:page-description: Gravitee Enterprise Edition - Introduction
:page-keywords: Gravitee, API Platform, Enterprise Edition, documentation, manual, guide, reference, api

[[gravitee-enterprise-api-platform]]
= Gravitee.io Enterprise API Platform

== Introduction

The Gravitee.io team has been providing the amazing (in our opinion at least!) Gravitee.io API Platform under the Apache v2 license since 2015.

We have big plans to make the platform even better, so with this in mind we're looking into adding some new features to:

- Improve your API platform with additional modules (Alert Engine)
- Improve the platform capabilities with additional plugins (SAML support, social connectors)
- Help you manage your growing organization and your digital API vision

We are very aware that Gravitee.io would not be here without its great community and users, built up through the years in the spirit of open source software.

For this reason, we've decided not to apply any changes to the existing platform (APIM vs AM) and these modules will still be released under the Apache v2 License.

If you're talking with the team on Gitter, you can probably see that we have increasing numbers of questions to answer, business contexts to manage and features to implement to provide you with the best API Platform possible. All of these things take time and, of course, money.

So we've decided to create the Gravitee.io Enterprise API Platform. This version brings many new benefits and exciting new features to help you and your company unleash the power of your APIs.

We look forward to embarking on this new adventure with you.
