= License
:page-sidebar: ee_sidebar
:page-permalink: ee/ee_license.html
:page-folder: ee/overview
:page-description: Gravitee Enterprise Edition - Installation - License
:page-keywords: Gravitee, API Platform, Enterprise Edition, documentation, manual, guide, reference, api

To run a Gravitee.io Enterprise node, you must have a valid license file.

[[ask-license]]
== Get a license

* Send an email to contact@graviteesource.com requesting a license
* Download a trial version from the Gravitee.io website (coming soon)

== Apply the license
Depending on how you want to run the Gravitee Enterprise nodes, the following options are available to you for pushing the license file to the nodes:

* Manual installation (coming soon)
* link:{{ '/ee/installguide_docker.html#license_support' | relative_url }}[Docker images^]

== My license is ending
Thirty days before the end of the license, a daily `WARN` log is print in the log file of the node to inform you that the license is ending.
To keep the nodes running, you need to provide an updated license file. This file will be reloaded silently by the node.
