---
redirect_from:
  - /apim/3.x/apim_installguide_rest_apis_documentation.html
---
= APIM API reference
:page-description: Gravitee.io API Management - Management API - Documentation
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-liquid:

{% assign version = site.products.apim._3x.version | split: "." %}
{% capture current_version %}{{ version[0] }}.{{ version[1] }}{% endcapture %}

== Overview

APIM API includes endpoints for APIM Console and APIM Portal. The sections below gives links to the documentation for the two sets of services.

== APIM Console API reference

APIM API exposes a complete set of endpoints for developers wanting to script some part of APIM administration.

You can access the online endpoint reference or the OpenAPI specification by version. For the:

* Online reference, see https://docs.gravitee.io/apim/3.x/management-api/{{ current_version }}
* OpenAPI spec, see https://docs.gravitee.io/apim/3.x/management-api/{{ current_version }}/swagger.json

[TIP]
====
To see earlier versions, replace the version number in the URL. For example:

* Online reference for 3.0: https://docs.gravitee.io/apim/3.x/management-api/3.0
* OpenAPI spec for 3.0: https://docs.gravitee.io/apim/3.x/management-api/3.0/swagger.json
====

== APIM Portal API reference

APIM API exposes a complete set of endpoints for developers wanting to script some part of the APIM Portal functionality.

You can access the online endpoint reference or the OpenAPI specification by version. For the:

* Online reference, see https://docs.gravitee.io/apim/3.x/portal-api/{{ current_version }}
* OpenAPI spec, see https://docs.gravitee.io/apim/3.x/portal-api/{{ current_version }}/openapi.yaml

[TIP]
====
To see earlier versions, replace the version number in the URL. For example:

* Online reference for 3.0: https://docs.gravitee.io/apim/3.x/portal-api/3.0
* OpenAPI spec for 3.0: https://docs.gravitee.io/apim/3.x/portal-api/3.0/openapi.yaml
====
