= Upgrade AM
:page-toc: true

NOTE: Files specified in this guide can be found at https://github.com/gravitee-io/graviteeio-access-management/tree/master/docs/upgrades

WARNING: If you plan to skip versions when you upgrade, ensure that you read the version-specific upgrade notes for each intermediate version. You may be required to perform manual actions as part of the upgrade.

WARNING: Be sure to run scripts on the correct database since `gravitee-am` is not always the default database! Check your db name by running `show dbs;`

== Upgrade to 3.12

NOTE: For more information about the breaking changes of this version, see link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.12.html[Breaking changes in 3.12^]

== Upgrade to 3.10.7

NOTE: For more information about the breaking changes of this version, see link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.10.7.html[Breaking changes in 3.10.7^]

WARNING
====
Do not upgrade to 3.10.7. We detected a critical bug introduced by our release process which leads to a corrupted version of AM.
This is fixed in 3.10.8. We apologize for this inconvenience.

GitHub issue: link:https://github.com/gravitee-io/issues/issues/6504[6504]
====

== Upgrade to 3.10.6

NOTE: For more information about the breaking changes of this version, see link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.10.6.html[Breaking changes in 3.10.6]

== Upgrade to 3.10.4

NOTE: For more information about the breaking changes of this version please visit link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.10.4.html[Breaking changes in 3.10.4]

== Upgrade to 3.10.0

NOTE: For more information about the breaking changes of this version please visit link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.10.html[Breaking changes in 3.10]

WARNING
====
For JDBC users only, do not upgrade to 3.10.0. We detected a critical bug in a liquibase script that can lead to data loss.
This was fixed in 3.10.1. We apologize for this inconvenience.

GitHub issue: link:https://github.com/gravitee-io/issues/issues/5957[5957]
====

=== REST API

`Clients` endpoints have been removed since they are deprecated from 3.0.0.

With previous versions the administrator user for the Management API was created on startup using hard coded values for username and password. Starting from 3.10.0 it is possible to define your own values thanks to the link:/am/current/am_installguide_management_api_configuration.html#security[security] section of the `gravitee.yml` file. By default, this configuration section use the same behaviour as AM 3.9 and earlier.

=== Repository

==== Mongodb

Before you run any scripts, create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/graviteeio-access-management/master/docs/upgrades/3.x/3.10.0/mongodb/1-move-organization-users.js[upgrades/3.x/3.10.0/mongodb/1-move-organization-users.js]::

This script will move users linked to an organization to a dedicated collection.

https://raw.githubusercontent.com/gravitee-io/graviteeio-access-management/master/docs/upgrades/3.x/3.10.0/mongodb/2-add-default-scopes.js[upgrades/3.x/3.10.0/mongodb/2-add-default-scopes.js]::

This script will create default scopes for applications.

==== JDBC

Before you run any scripts, create a dump of your existing database.

The liquibase scripts will update data automatically on the REST API startup.

If you disabled the liquibase execution using the `liquibase.enabled` option, please apply changes via the following liquibase descriptors :

- https://github.com/gravitee-io/gravitee-access-management/blob/master/gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_10_0/schema.yml[v3_10_0/schema.yml]
- https://github.com/gravitee-io/gravitee-access-management/blob/master/gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_10_0/users-migration.yml[v3_10_0/users-migration.yml]
- https://github.com/gravitee-io/gravitee-access-management/blob/master/gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_10_0/schema-add-default-scopes.yml[v3_10_0/schema-add-default-scopes.yml]
- https://github.com/gravitee-io/gravitee-access-management/blob/master/gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_10_0/schema-add-self-service-account-settings.yml[v3_10_0/schema-add-self-service-account-settings.yml]


== Upgrade to 3.9.2

NOTE: For users of Gravitee Enterprise Edition with Alert Engine, please check your gravitee configuration to ensure that the alert engine feature is explicitly enabled. Starting from this version, the alert engine connector is disabled by default if the option `alerts.alert-engine-enabled` is missing from the `gravitee.yml` file. (see https://docs.gravitee.io/ae/am_configuration.html)

== Upgrade to 3.9.0

NOTE: For more information about the breaking changes of this version please visit link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.9.html[Breaking changes in 3.9]

=== REST API

If you are using the Management API to list domains, scopes or roles, please note that the output has been changed to return a page of result with default size set to 50 elements.

=== HEAP SIZE

Starting from this new version, the default Xms and Xmx parameters has been fixed to 256m.

== Upgrade to 3.8.6

NOTE: For users of Gravitee Enterprise Edition with Alert Engine, please check your gravitee configuration to ensure that the alert engine feature is explicitly enabled. Starting from this version, the alert engine connector is disabled by default if the option `alerts.alert-engine-enabled` is missing from the `gravitee.yml` file. (see https://docs.gravitee.io/ae/am_configuration.html)

== Upgrade to 3.8.0

NOTE: For more information about the breaking changes of this version please visit link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.8.html[Breaking changes in 3.8]

=== Repository

==== Mongodb

Before you run any scripts, create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/gravitee-access-management/master/docs/upgrades/3.x/3.8.0/mongodb/1-add-domain-hrid.js[upgrades/3.x/3.8.0/mongodb/1-add-domain-hrid.js]::
This script updates the database to reflect the following changes :

* Add hrid field to the security domains

== Upgrade to 3.7.0

=== Repository

==== Mongodb

Before you run any scripts, create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/gravitee-access-management/master/docs/upgrades/3.x/3.7.0/mongodb/1-add-alert-permissions.js[upgrades/3.x/3.7.0/mongodb/1-add-alert-permissions.js]::
This script updates the database to reflect the following changes :

* Enable alerting support

== Upgrade to 3.6.0

NOTE: For more information about the breaking changes of this version please visit link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.6.html[Breaking changes in 3.6]

=== Repository

==== Mongodb

Before you run any scripts, create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/gravitee-access-management/master/docs/upgrades/3.x/3.6.0/mongodb/1-add-environment-permissions.js[upgrades/3.x/3.6.0/mongodb/1-add-environment-permissions.js]::
This script updates the database to reflect the following changes :

* Addition of new permissions related to the multi environments feature
* Update existing users permissions according to their role in order to grant access to the default organization and environment

==== JDBC

Before you start for the first time the AM Management API and AM Gateway in version 3.6.0, create a dump of your existing database.

https://github.com/gravitee-io/graviteeio-access-management/tree/master/gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/cockpit[Liquibase scripts]::
These script are executed automatically on startup of AM gateway and AM management console. This script updates the database to reflect the following changes :

* Addition of new permissions related to the multi environments feature
* Update existing users permissions according to their role in order to grant access to the default organization and environment

== Upgrade to 3.4.0

NOTE: For more information about the breaking changes of this version please visit link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.4.html[Breaking changes in 3.4]

=== Repository

==== Mongodb

Before you run any scripts, create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/gravitee-access-management/master/docs/upgrades/3.x/3.4.0/mongodb/1-form-templates-migration.js[upgrades/3.x/3.4.0/mongodb/1-form-templates-migration]::
This script updates the database to reflect the following changes :

* Update form actions and links to make it work with the new cookie session

== Upgrade to 3.1.0

NOTE: For more information about the breaking changes of this version please visit link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.1.html[Breaking changes in 3.1]

=== Repository

==== Mongodb

Before you run any scripts, create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/graviteeio-access-management/master/docs/upgrades/3.x/3.1.0/mongodb/1-email-templates-migration.js[upgrades/3.x/3.1.0/mongodb/1-email-templates-migration]::
This script updates the database to reflect the following changes :

* New email service

== Upgrade to 3.0.0

NOTE: For more information about the breaking changes of this version please visit link:/Resources/changelogs/am-breaking-changes/breaking-changes-3.0.html[Breaking changes in 3.0]

WARNING: We highly recommend that you run the MongoDB database script before starting the Management API.

=== Repository

==== Mongodb

Before you run any scripts, create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/gravitee-access-management/master/docs/upgrades/3.x/3.0.0/mongodb/1-migration-v3.js[upgrades/3.x/3.0.0/mongodb/1-migration-v3]::
This script updates the database to reflect the following changes :

* Adds new fields that refer the default environment and the default organization.
* Attach data to their environment and organization
* Remove unnecessary data

WARNING: During the migration, AM V2 Gateways will still continue to work without any problem. Just make sure to not stop or restart them until the migration is fully completed.

WARNING: Do not forget to update plugins and re-install your custom plugins.
