= Install AM Console
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_management_ui_install_zip.html
:page-folder: am/installation-guide/zip
:page-layout: am
:page-description: Gravitee.io Access Management - Management UI - Installation with .zip
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

== Prerequisites

Requirements to install the AM Gateway are available on link:{{ '/am/current/am_installguide_zip_prerequisites.html' | relative_url }}[this page].

=== Browsers

AM Console is supported with the two most recent versions of modern internet browsers.

== Download and extract the .zip archive

. Download the binaries https://download.gravitee.io/graviteeio-am/components/gravitee-am-webui/gravitee-am-webui-{{ site.products.am.version }}.zip[here^] or from the https://gravitee.io/downloads/access-management[Gravitee download site^].

[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-am/components/gravitee-am-webui/gravitee-am-webui-{{ site.products.am.version }}.zip -o gravitee-am-webui-{{ site.products.am.version }}.zip

[start=2]
. Unpack the archive and place the folders in the required location.

[source,bash]
[subs="attributes"]
$ unzip gravitee-am-webui-{{ site.products.am.version }}.zip

NOTE: A full .zip distribution with all the components can also be found https://download.gravitee.io/graviteeio-am/distributions/graviteeio-am-full-{{ site.products.am.version }}.zip[here^]

== Deploy or run AM Console

AM Console is a client-side Angular application and can be deployed on any HTTP server, such as https://httpd.apache.org/[Apache^] or http://nginx.org/[Nginx^].

NOTE: AM Console uses HTML5 mode and requires server side rewrites to make it work, such as in the Apache and Nginx examples below.

=== Apache

----
<VirtualHost *:80>
    ServerName my-app

    DocumentRoot /path/to/app

    <Directory /path/to/app>
        RewriteEngine on

        # Don't rewrite files or directories
        RewriteCond %{REQUEST_FILENAME} -f [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [L]

        # Rewrite everything else to index.html to allow html5 state links
        RewriteRule ^ index.html [L]
    </Directory>
</VirtualHost>
----

=== Nginx

----
server {
    server_name my-app;

    index index.html;

    root /path/to/app;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
----
