= APIM Component - Install Gateway
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installation_guide_amazon_gateway.html
:page-folder: apim/installation-guide/amazon
:page-layout: apim3x
:page-description: Gravitee.io API Management - Installation Guide - Amazon - Gateway
:page-keywords: Gravitee.io, API Management, apim, guide, package, amazon, linux, aws, component, gateway
:page-toc: true

// author: Tom Geudens
== Prerequisites
* Machine up and running
* Gravitee YUM repository added
* Java 11 jre installed
* MongoDB installed and running
* Elasticsearch installed and running

== Security group
* open port 8082

== Instructions
. Install Gateway:
+
[source,bash]
----
sudo yum install graviteeio-apim-gateway-3x -y
----

. Enable Gateway on startup:
+
[source,bash]
----
sudo systemctl daemon-reload
sudo systemctl enable graviteeio-apim-gateway
----

. Start Gateway:
+
[source,bash]
----
sudo systemctl start graviteeio-apim-gateway
----

. Verify:
+
[source,bash]
----
sudo journalctl -f
----
+
Follow along with the startup process. If any of the prerequisites is missing, this is were you'll get error messages.
+
**NOTE:** You can also see the same in `/opt/graviteeio/apim/gateway/logs/gravitee.log`

. Verify some more:
+
[source,bash]
----
sudo ss -lntp '( sport = 8082 )'
----
+
You should see that there's a process listening on that port.

. Verify some more still:
+
[source,bash]
----
curl -X GET http://localhost:8082/
----
+
If the installation is successful this returns: **No context-path matches the request URI.**

== Next
Next is link:{{ '/apim/3.x/apim_installation_guide_amazon_rest_api.html' | relative_url }}[installing the Gravitee APIM REST API].
