= Install APIM Gateway
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_amazon_gateway.html
:page-folder: apim/installation-guide/amazon
:page-liquid:
:page-layout: apim3x
:page-description: Gravitee.io API Management - Installation Guide - Amazon - API Gateway
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-toc: false

:gravitee-component-name: APIM Gateway
:gravitee-package-name: graviteeio-apim-gateway-3x
:gravitee-service-name: graviteeio-apim-gateway


== Prerequisites

. *YUM package manager* must be configured (link:/apim/3.x/apim_installguide_amazon_configure_yum.html[click here] for instructions on how to configure yum).
. You must have access to a *t2.medium instance* size in AWS.

=== 1. Configure Your Amazon Instance
In your AWS settings, choose the following:

* *[underline]#For Instance Type/Size#*. Select a **t.2medium** instance.

* *[underline]#For IP Address#*. Choose to **auto-assign a public IP** for this option.

* *[underline]#For Storage#*. Generally, **40GB** is a good amount.

* *[underline]#For Security Groups#*. Open port *8082* so that after you complete the installation, you can check the necessary URLs to ensure that APIM Gateway has been installed properly. 


== 2. Install The {gravitee-component-name} Package

To install the last stable version of {gravitee-component-name}, run the following command:

[source,bash,subs="attributes"]
----
sudo yum install -y {gravitee-package-name}
----

== 3. Run {gravitee-component-name}

These steps assume that you are using the default settings.

To configure {gravitee-component-name} to start automatically when the system boots up, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl daemon-reload
sudo systemctl enable {gravitee-service-name}
----

To start and stop {gravitee-component-name}, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl start {gravitee-service-name}
sudo systemctl stop {gravitee-service-name}
----

NOTE: These commands provide no feedback as to whether {gravitee-component-name} started successfully. This information is written to the log files located in `/opt/graviteeio/apim/gateway/logs/`.

== 3. View The Logs

*You must check the logs to confirm if {gravitee-component-name} has been installed correctly.* When `systemd` logging is enabled, logging information is available using the `journalctl` commands.

To tail the journal, run the following command:

[source,bash,subs="attributes"]
----
sudo journalctl -f
----

To list journal entries for the {gravitee-component-name} service, run the following command:

[source,bash,subs="attributes"]
----
sudo journalctl --unit {gravitee-service-name}
----

To list journal entries for the {gravitee-component-name} service starting from a given time, run the following command:

[source,bash,subs="attributes"]
----
sudo journalctl --unit {gravitee-service-name} --since  "2020-01-30 12:13:14"
----

== Confirm {gravitee-component-name} Was Installed

You can also confirm that {gravitee-component-name} has been installed and has started up properly by checking this URL:

|===
|Component |URL

|APIM Gateway
|http://localhost:8082/
|===
