= Install APIM Gateway
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_amazon_gateway.html
:page-folder: apim/installation-guide/amazon
:page-liquid:
:page-layout: apim3x
:page-description: Gravitee.io API Management - Installation Guide - Amazon - API Gateway
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

:gravitee-component-name: APIM Gateway
:gravitee-package-name: graviteeio-apim-gateway-3x
:gravitee-service-name: graviteeio-apim-gateway
:page-toc: false

== Prerequisites

. *YUM package manager* must be configured (link:/apim/3.x/apim_installguide_amazon_configure_yum.html[click here] for instructions on how to configure yum).

== Install the {gravitee-component-name} Package

To install the last stable version of {gravitee-component-name}, run the following command:

[source,bash,subs="attributes"]
----
sudo yum install -y {gravitee-package-name}
----

== Run {gravitee-component-name}

These steps assume that you are using the default settings.

To configure {gravitee-component-name} to start automatically when the system boots up, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl daemon-reload
sudo systemctl enable {gravitee-service-name}
----

To start and stop {gravitee-component-name}, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl start {gravitee-service-name}
sudo systemctl stop {gravitee-service-name}
----

NOTE: These commands provide no feedback as to whether {gravitee-component-name} started successfully. This information is written to the log files located in `/opt/graviteeio/apim/gateway/logs/`.

== View The Logs

*You must check the logs to confirm if APIM Portal has been installed correctly.* When `systemd` logging is enabled, logging information is available using the `journalctl` commands.

To tail the journal, run the following command:

[source,bash,subs="attributes"]
----
sudo journalctl -f
----

To list journal entries for the {gravitee-component-name} service, run the following command:

[source,bash,subs="attributes"]
----
sudo journalctl --unit {gravitee-service-name}
----

To list journal entries for the {gravitee-component-name} service starting from a given time, run the following command:

[source,bash,subs="attributes"]
----
sudo journalctl --unit {gravitee-service-name} --since  "2020-01-30 12:13:14"
----

== Confirm {gravitee-component-name} Was Installed

To test that {gravitee-component-name} has been installed and has started up properly, check this URL:

|===
|Component |URL

|APIM Gateway
|http://localhost:8082/
|===