= Install Full APIM Stack
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_amazon_stack.html
:page-folder: apim/installation-guide/amazon
:page-liquid:
:page-layout: apim3x
:page-description: Gravitee.io API Management - Installation Guide - Amazon - API Management
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

:gravitee-package-name: graviteeio-apim-3x
== Another Test Overview

This section describes how to install the full APIM stack(including all components), along with optional dependencies (MongoDB, Elasticsearch). 

To install APIM components individually, see the respective documentation for link:/apim/3.x/apim_installguide_hybrid_deployment.html#architecture[APIM Gateway], link:/apim/3.x/apim_installguide_amazon_management_api.html[APIM API], link:/apim/3.x/apim_installguide_amazon_management_ui.html[APIM Console], and link:/apim/3.x/apim_installguide_amazon_portal.html[APIM Portal]. 

== Prerequisites

=== Install Nginx

To install Nginx, run the following commands:

[source,bash,subs="attributes"]
----
sudo amazon-linux-extras install nginx1.12
sudo systemctl start nginx
----

=== Configure Your Package Management System

Make sure that you have configured your package management system. For instructions on how to do so, see <<apim_installguide_amazon_introduction.adoc#configure-the-package-management-system-yum, Configure the package management system (yum)>>.

== Install APIM Package (No Dependencies)

To install the APIM package only, run the following command on your favorite terminal:

[source,bash,subs="attributes"]
----
sudo yum install {gravitee-package-name}
----

== Install APIM Package With Dependencies

=== Configure Dependency Repositories

Before you install the APIM package, you may need to add third-party repositories:

==== MongoDB

NOTE: For guidance on installing and configuring MongoDB, see the link:https://docs.mongodb.com/v3.6/tutorial/install-mongodb-on-amazon/[MongoDB Installation documentation, window=\"_blank\"]

[source,bash]
----
echo "[mongodb-org-3.6]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.6/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-3.6.asc" | sudo tee /etc/yum.repos.d/mongodb-org-3.6.repo > /dev/null

sudo yum install -y mongodb-org
sudo systemctl start mongod
----

==== Elasticsearch 7.x

NOTE: For guidance on installing and configuring Elasticsearch, see the link:https://www.elastic.co/guide/en/elasticsearch/reference/7.6/rpm.html#rpm-repo[Elasticsearch Installation documentation, window=\"_blank\"].

[source,bash]
----
echo "[elasticsearch-7.x]
name=Elasticsearch repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md" | sudo tee /etc/yum.repos.d/elasticsearch.repo > /dev/null
sudo yum install -y elasticsearch
sudo systemctl start elasticsearch
----

=== Install APIM

[source,bash,subs="attributes"]
----
curl -L https://bit.ly/install-apim-3x | bash
----

== Run APIM with `systemd`

To start up the APIM components, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl daemon-reload
sudo systemctl start {gravitee-package-name}-gateway {gravitee-package-name}-management-api
sudo systemctl restart nginx
----

== Check the APIM components are running

To test that all components have started, check these URLs:

|===
|Component |URL

|APIM Gateway
|http://localhost:8082/

|APIM API
|http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis

|APIM Management
|http://localhost:8084/

|APIM Portal
|http://localhost:8085/

|===
