= Install APIM Console
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_amazon_management_ui.html
:page-folder: apim/installation-guide/amazon
:page-liquid:
:page-layout: apim3x
:page-description: Gravitee.io API Management - Installation Guide - Amazon - Management UI
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

:gravitee-component-name: APIM Console
:gravitee-package-name: graviteeio-apim-management-ui-3x
:gravitee-service-name: graviteeio-apim-management-ui

== Prerequisites

Before you install {gravitee-component-name}, you must complete the following configuration. You must also ensure APIM API is installed and running.

=== Install Nginx

To install Nginx, run the following command:

[source,bash,subs="attributes"]
----
sudo amazon-linux-extras install nginx1.12
----

=== Configure your package management system

Ensure you have configured your package management system, as described in <<apim_installguide_amazon_introduction.adoc#configure-the-package-management-system-yum, Configure the package management system (yum)>>.

== Install the {gravitee-component-name} package

To install the last stable version of {gravitee-component-name}, run the following command:

[source,bash,subs="attributes"]
----
sudo yum install -y {gravitee-service-name}
----

== Run {gravitee-component-name}

NOTE: {gravitee-component-name} is based on Nginx.

To configure {gravitee-component-name} to start automatically when the system boots up, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl daemon-reload
sudo systemctl enable nginx
----

To start and stop Nginx, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl start nginx
sudo systemctl stop nginx
----

== View the logs

When `systemd` logging is enabled, the logging information are available using the `journalctl` commands.

To tail the journal, run the following command:

[source,shell]
----
sudo journalctl -f
----

To list journal entries for the Nginx service, run the following command:

[source,shell]
----
sudo journalctl --unit nginx
----

To list journal entries for the Nginx service starting from a given time, run the following command:

[source,shell]
----
sudo journalctl --unit nginx --since  "2020-01-30 12:13:14"
----
