= Introduction
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_overview_introduction.html
:page-folder: apim/overview
:page-description: Gravitee.io API Management - Introduction
:page-toc: false
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

Organizations need API management solutions to publish their APIs to external developers, internal developers, and other
partners. API management can unlock the potential of the organization's data and services, as well as facilitate the transformation to OpenAPI and OpenData, extending the company's digital platform offerings, opening up new communication channels, and finding new customers.

Naturally, a growing customer base brings new challenges, such as:

* How to reduce the time taken to enroll new partners.
* How to identify partners and manage their API consumption.
* How to measure consumption from a consumer and/or producer point of view.
* How to share existing APIs and how to discover them.
* How to manage the API lifecycle, versioning, documentation, and so on.

How can all these challenges be addressed seamlessly, for all APIs, using a centralized tool? Simple – by choosing Gravitee.io API Management.

[[gravitee-overview]]
== Gravitee.io API Management

Gravitee.io API Management (APIM) is a flexible, lightweight, and blazing-fast open source API management solution that gives your organization full control over who accesses your API — when and how. APIM is both simple to use and powerful, acting as a global solution for API management.

[[why-gravitee-API]]
== Why Gravitee.io API Management?

Our goal in launching Gravitee.io APIM is to provide users with a highly flexible and scalable solution that integrates with their infrastructure seamlessly and fits their business needs perfectly.

We’ve designed and developed APIM to be fully extensible using its internal plugin system, so you can define your own policy, develop your own reporting system, and more.

Finally, all APIM components (including <<apim_overview_components.adoc#gravitee-components-gateway, API Gateway>> and <<apim_overview_components.adoc#gravitee-components-rest-api, APIM API>>) are incredibly lightweight. We took a consciously aggressive approach to CPU and memory management with our products.

This strategy makes life much easier when it comes to high availability with our lightning-fast component start-up times. Typically, *_it takes less than 5 seconds_* for the API Gateway to be accessible to consumers (subject to the number of APIs being deployed).

_Are you ready to use Gravitee.io API Management? Let’s do this!_
