= Introduction
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_overview_introduction.html
:page-folder: apim/overview
:page-description: Gravitee.io API Management - Introduction
:page-toc: false
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

Increasingly, organizations are using API management solutions to help them publish their APIs to external and internal developers and other
partners, unlocking the potential of their data and services and moving towards an OpenAPI and OpenData approach. This helps companies to extend their
digital platform offerings, opening up new communication channels and finding new customers.

Of course, a growing customer base brings with it a new set of challenges, such as:

* How to reduce the time to enroll new consumers / partners
* How to identify partners and manage their API consumption
* How to measure consumption from a consumer and/or from a producer point of view
* How to share existing APIs and how to discover them
* How to manage the API lifecycle, versioning, documentation, and so on

All of these challenges need to be addressed seamlessly for all APIs using a centralized tool. This is where API Management comes in.

[[gravitee-overview]]
== Gravitee.io API Management

Gravitee.io API Management (Gravitee.io APIM) is a flexible, lightweight, blazing-fast open source API management solution that gives your organization full control over who accesses your APIs, when and how. Gravitee.io API Management is both simple to use and powerful, acting as a global solution for API management.
