= Introduction
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_overview_introduction.html
:page-folder: apim/overview
:page-description: Gravitee.io API Management - Introduction
:page-toc: false
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

Organizations are increasingly using API management solutions to publish their APIs to external developers, internal developers and other
partners. API management can unlock the potential of their data and services and facilitate their transformation to OpenAPI and OpenData, extending their
digital platform offerings, opening up new communication channels and finding new customers.

Naturally, a growing customer base brings new challenges, such as:

* How to reduce the time taken to enroll new partners
* How to identify partners and manage their API consumption
* How to measure consumption from a consumer and/or producer point of view
* How to share existing APIs and how to discover them
* How to manage the API lifecycle, versioning, documentation, and so on

All of these challenges need to be addressed seamlessly for all APIs using a centralized tool. This is where Gravitee.io API Management comes in.

[[gravitee-overview]]
== Gravitee.io API Management

Gravitee.io API Management (APIM) is a flexible, lightweight, blazing-fast open source API management solution that gives your organization full control over who accesses your APIs, when and how. APIM is both simple to use and powerful, acting as a global solution for API management.
