= Plugins
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_overview_plugins.html
:page-folder: apim/overview
:page-layout: apim3x

_Plugins_ are additional components that can be _plugged into_ the <<apim_overview_components.adoc#gravitee-components-gateway, API Gateway>> and / or the <<apim_overview_components.adoc#gravitee-components-rest-api, Management API>>.
Plugins can customize a component's behavior to exactly fit your needs and technical constraints.

Plugins follow a specific directory structure. For more information, see the link:/apim/3.x/apim_devguide_plugins.html[Plugins Developer Guide].

When you use APIM, you will work with multiple types of plugins. The table below lists the different types of plugin with the component(s) they can be plugged into and some examples:

[width="100%",cols="^3,^3,^10",options="header"]
|===
|Type|Component|Examples
| <<gravitee-plugins-idp, Identity Providers>>|Management API|LDAP, Oauth2, InMemory
| <<gravitee-plugins-fetchers, Fetchers>>|Management API|HTTP, GIT
| <<gravitee-plugins-policies, Policies>>|Management API / Gateway|API Key, Rate-limiting, Cache
| <<gravitee-plugins-reporters, Reporters>>|Gateway|Elasticsearch, Accesslog
| <<gravitee-plugins-repositories, Repositories>>|Management API / Gateway|MongoDB, Redis, Elasticsearch
| <<gravitee-plugins-resources, Resources>>|Management API / Gateway|Oauth2, Cache, LDAP
| <<gravitee-plugins-services, Services>>|Management API / Gateway|Sync, local-registry, health-check, monitor
| <<gravitee-plugins-notifiers, Notifiers>>|Alert Engine|Email
| <<gravitee-plugins-alerts, Alerts>>|Management API / Gateway|Vertx
|===

[[gravitee-plugins-idp]]
== Identity Providers

[[gravitee-plugins-fetchers]]
== Fetchers

[[gravitee-plugins-policies]]
== Policies
A *policy* modifies the behavior of the request and / or response handled by the API Gateway. It can be chained by a request policy chain or a response policy chain using a logical order.
Policies can be treated like a _proxy controller_, by guaranteeing that a given business rule is fulfilled during request / response processing.

Examples of a policy are:

* Authorization using an API key (see the link:/apim/3.x/apim_policies_apikey.html[api-key policy])
* Applying header/query parameter transformations
* Applying rate limiting or quotas to avoid API flooding

NOTE: Want to know how to create, use and deploy a custom policy? Check out the link:/apim/3.x/apim_devguide_policies.html[Policies Developer Guide]!

[[gravitee-plugins-reporters]]
== Reporters

A *reporter* is used by a Gateway instance to report many types of event:

* Request/response metrics -- for example, response-time, content-length, api-key
* Monitoring metrics -- for example, CPU, Heap usage
* Health-check metrics -- for example, status, response code

_Out of the box_ reporters are :

* Elasticsearch Reporter
* File Reporter

NOTE: As with all plugins, you can create, use and deploy custom reporters as described in the
link:/apim/3.x/apim_devguide_plugins.html[Plugins Developer Guide].

[[gravitee-plugins-repositories]]
== Repositories
Pluggable storage component for API configurations, policy configurations, analytics and so on.
You can find more information in the link:/apim/3.x/apim_installguide_repositories.html[Installation Guide Repositories] page.

[[gravitee-plugins-resources]]
== Resources

[[gravitee-plugins-services]]
== Services

[[gravitee-plugins-notifiers]]
== Notifiers

A *notifier* is used to send notifications.
At the moment, the only notifier available is the *email notifier*, but others included *slack* or *portal* are planned soon.

[[gravitee-plugins-alerts]]
== Alerts

An *alert* is used to send triggers or events to the Alert Engine which can be processed to send a notification with the configured plugin notifier.
Configuring the notifier is the responsibility of the trigger.
