= Why Gravitee.io API Management?
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_overview_why.html
:page-folder: apim/overview
:page-toc: false
:page-layout: apim3x

Gravitee.io API Management (APIM) began with our search for an open source API management solution. We were unable to find a tool which fit exactly our needs: we knew that choosing one of the existing tools would still necessitate pulling other components and
using dedicated support.

This is why we launched APIM: our goal was to provide users with a highly flexible and scalable
solution which would integrate seamlessly with their infrastructure and perfectly fit their business needs.

APIM has been developed and designed to be fully extensible using its internal plugin system, so you can: define your own policy, develop your own reporting system, and so on.

Finally, all APIM components (including <<apim_overview_components.adoc#gravitee-components-gateway, API Gateway>> and <<apim_overview_components.adoc#gravitee-components-rest-api, APIM API>>) are really lightweight -- we
took an aggressive approach to CPU and memory management. This makes life much easier for you when it comes to high availability
with our blazing-fast component start-up times (it typically takes less than 5 seconds for the API Gateway
to be accessible to consumers, subject to the number of APIs being deployed).

Are you ready to use Gravitee.io API Management? Sounds good -- let's get stuck in!
