= Why Gravitee.io ?
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_overview_why.html
:page-folder: apim/overview
:page-toc: false
:page-layout: apim3x

APIM began with our search for an open source API management solution. We were unable to find a tool which fit exactly our needs: by choosing one of the existing tools we knew that we would have to pull other components and
use dedicated support.

This is why we launched Gravitee.io: our goal was to provide users with a highly flexible and scalable
solution which would integrate seamlessly with their infrastructure and perfectly fit their business needs.

Gravitee.io has been developed and designed to be fully extensible using its internal plugin system, making it fully adaptable, with the capability to: define your own policy, develop your own reporting system, and so on.

Finally, all components provided by Gravitee.io (including <<apim_overview_components.adoc#gravitee-components-gateway, API Gateway>> and <<apim_overview_components.adoc#gravitee-components-rest-api, Management API>>) are really lightweight. We
took an aggressive approach to CPU and memory management. This makes life much easier for you when it comes to high availability
and our components can be started in a "blazing-fast" mode (generally speaking, it takes less than 5 seconds for the gateway
to be accessible to consumers, depending on the number of APIs being deployed).

Ready to use Gravitee.io API Management? Sounds good -- let's get stuck in!
