[[gravitee-installation-guide]]
= Introduction
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide.html
:page-folder: apim/installation-guide
:page-description: Gravitee.io API Management - Installation
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

As described in the link:/apim/3.x/apim_overview_architecture.html[architecture overview] page, Gravitee.io API Management (APIM) is split into four main components:

* link:/apim/3.x/apim_installguide_gateway_install_zip.html[APIM Gateway]
* link:/apim/3.x/apim_installguide_rest_apis_install_zip.html[APIM API]
* link:/apim/3.x/apim_installguide_management_ui_install_zip.html[APIM Console]
* link:/apim/3.x/apim_installguide_portal_ui_install_zip.html[APIM Portal]

The links below provide information on how you can prepare, install, and configure your APIM environment. You can install APIM in a variety of ways, including: 

<<<<<<< HEAD
* link:/apim/3.x/apim_installguide_amazon_introduction.html[Install on Amazon]
=======
* link:/apim/3.x/apim_installguide_hybrid_deployment.html#architecture[Install on Amazon]
>>>>>>> d39f6fc (updated links)

* link:/apim/3.x/apim_installguide_docker_images.html[Install on Docker]

* link:/apim/3.x/apim_installguide_redhat_introduction.html[Install on Red Hat and CentOS (Linux)]

* link:/apim/3.x/apim_installguide_kubernetes.html[Install on Kubernetes]

* link:/apim/3.x/apim_installguide_gateway_install_zip.html[Install with .ZIP]

* link:/apim/3.x/apim_installguide_hybrid_deployment.html#architecture[Install a Hybrid Deployment]



<<<<<<< HEAD
NOTE: The Gravitee.io installation guide provides information on how to install Gravitee.io components. For prerequisite documentation on third-party products such as link:/https://docs.mongodb.com/[MongoDB], link:/https://www.elastic.co/guide/index.html[Elasticsearch], or others, please visit their respective websites.
=======
NOTE: The Gravitee.io installation guide provides information on how to install Gravitee.io components. For prerequisite documentation on third-party products such as link:/https://docs.mongodb.com/[MongoDB], link:/https://www.elastic.co/guide/index.html[Elasticsearch] and others, please visit their websites.
>>>>>>> d39f6fc (updated links)


