= Upgrade APIM
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_migration.html
:page-folder: apim/installation-guide
:page-toc: true
:page-layout: apim3x

== Upgrade Notes

WARNING: If you plan to skip versions when you upgrade, ensure that you read the version-specific upgrade notes for each intermediate version.
You may be required to perform manual actions as part of the upgrade.

WARNING: Be sure to run scripts on the correct database since `gravitee` is not always the default database!
Check your db name by running `show dbs;`

== Upgrade to 3.19.0
=== Breaking changes
==== Custom policies
For users who developed their own policy using `ApiKeyRepository` or `SubscriptionRepository` to retrieve API keys or subscriptions.

In previous versions, those repositories were overridden with a cached implementation, which was returning active API keys and subscriptions only, in an optimized way.

From this version, `ApiKeyRepository` and `SubscriptionRepository` query the database directly without any cache.
Using them in policies is strongly discouraged.

We recommend to update your dependency settings on `gravitee-gateway-api` to version 1.44.1 and then use those new components to access the active API keys or subscriptions:

* `io.gravitee.gateway.api.service.ApiKeyService` : _getByApiAndKey_
* `io.gravitee.gateway.api.service.SubscriptionService` : _getByApiAndClientId_ and _getById_

==== Docker: Portal nginx configuration
In order to provide a better security, the default nginx configuration of the portal docker image has been updated to add by default a Content-Security-Policies header for framing.
After upgrading, the nginx configuration will be updated with this new line:

[source]
----
add_header Content-Security-Policy "frame-ancestors 'self';" always;
----
But as APIM Portal is embedded in APIM Console for the theme customisation, this new header may block the portal from being displayed in the console.

There are 2 ways to manage this change:

1. *Not recommended*. You can disable this security header by setting the environment variable `FRAME_PROTECTION_ENABLED` to `false` when starting the docker container.
2. You can configure the `frame-ancestors` directive to allow the console to display the portal. To do this set the environment variable `ALLOWED_FRAME_ANCESTOR_URLS` with the list of allowed URLs.
For example:

[source]
----
ALLOWED_FRAME_ANCESTOR_URLS="https://mydomain.com https://mydomain2.com"
ALLOWED_FRAME_ANCESTOR_URLS="https://mydomain.com 'self'"
ALLOWED_FRAME_ANCESTOR_URLS="mydomain.com"
----

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors[here^] for more information about the Content-Security-Policy header.

==== Console with a custom base url
By default, the console and the portal are made to work at the root of a URL, for instance:

- `https://apim.portal.com/...`
- `https://apim.console-ui.com/...`

So the assets (image and js files) are loaded from the root, for instance: `https://apim.portal.com/main.js`

But, for different reasons such as DNS limitations, some users would like to use a single domain and share it for all APIM components. Something like:

- `http://apim/portal`
- `http://apim/console`

In this case, both the portal and console applications need to know the `base_href` which allows them to properly load the different assets (`http://apim/portal/main.js`). This should work with whatever URL is used by the user to load the page: a complex link created during login, a redirection, a reload of a page, or just the base URL.

⚠️ Previously the console application was magically working without custom configuration, it's not the case anymore.
In order to handle these scenarios you have the following options:

===== A - Using a reverse proxy
Please refer to this section from the documentation:  https://docs.gravitee.io/apim/3.x/apim_how_to_configure_reverse_proxy.html#nginx_container

This is working thanks to config which will replace the `base_href` with the right value:

[source,nginx]
----
                sub_filter_once  on;
                sub_filter  '<base href="/' '<base href="/console/';
----

===== B - Using environment variables with Gravitee.io APIM Docker images
_Note_: This option is valid only if you're using the official Gravitee.io APIM Docker images.

The portal and console docker images handle environment variables to configure the `base_href` of the apps:

- `PORTAL_BASE_HREF` for the Portal (it was already there in previous versions)
- `CONSOLE_BASE_HREF` for the Console (🆕 this one is new)

This variable will change the `base_href` of the app using this kind of configuration:

[source,nginx]
----
        sub_filter '<base href="/"' '<base href="{{ getenv "PORTAL_BASE_HREF" "/" }}"';
----

The full configuration is available here: https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-portal-webui/docker/config/templates/default.conf.tmpl


You can find an example of use in a simple Docker Compose setup we have in the repository:
https://github.com/gravitee-io/gravitee-api-management/tree/3.19.x/docker/quick-setup/nginx

The magic is happening because of https://github.com/gravitee-io/gravitee-api-management/blob/b03a8eb705280e5f44d5a58293306d29838e79ee/docker/quick-setup/nginx/docker-compose.yml#L123:

[source]
----
        CONSOLE_BASE_HREF=/console/
----

⚠️ The trailing `/` on the previous snippet is **MANDATORY**

===== B (Bis) - Using environment variables with Helm Chart
If the Helm charts are used in a way that each of the Portal, Console, Management-api and Gateway has its own domain then no specific configuration is needed.

Otherwise, it will be needed to set the correct `PORTAL_BASE_HREF` and `CONSOLE_BASE_HREF` environment variables, as explained in section B.

For instance:

[source,yaml]
----
ui:
  image:
    repository: graviteeio/apim-management-ui
    pullPolicy: IfNotPresent
  ingress:
    tls: false
    hosts:
      - localhost
  baseURL: http://localhost:8081/management/organizations/DEFAULT/environments/DEFAULT/
  env:
    - name: CONSOLE_BASE_HREF
      value: "/console/"
...
portal:
  ...
  env:
    - name: PORTAL_BASE_HREF
      value: "/portal/"
----


== Upgrade to 3.18.10
=== Breaking changes
==== Bridge mode
You must upgrade the APIM Gateway used as a bridge server first before you upgrade any APIM Gateways used as clients.

== Upgrade to 3.18.9
=== Breaking changes
==== Change of return type when calling /apis/{apiId}/subscribers
To improve performance while fetching the subscribers of an API, internal methods have changed and the output has evolved.
As a result, a call to  `/organizations/{orgId}/environments/{envId}/apis/{apiId}/subscribers` now returns a list of `ApplicationListItem` instead of `ApplicationEntity`.

The `ApplicationListItem` class contains all the fields present in the `ApplicationEntity` class.


== Upgrade to 3.18.7
=== Breaking changes
WARNING: As part of a future major APIM release, the breaking change described below will be reverted in a subsequent link:{{ '/apim/3.x/apim_changelog.html' | relative_url }}[3.18.x version^] in order to avoid potential issues on existing plan implementations.

==== API key and JWT plans
The security chain (the internal process that selects the executable plan for the incoming request and applies the related security rules) parses all active plans to select and execute the relevant one.

**Prior to this version:**

- The API key plan was executed if the request contained an API key.
- The JWT plan was executed if the request contained a Bearer token.

**From this version:**

The security chain has been improved to select and execute plans more efficiently. As a result, API keys and JWT plans are now only executed if there is an active subscription related to the provided security token. If there is no relevant subscription, the currently parsed plans are not executed and the security chain moves to parse the next available plans. The process continues until the security chain parses plans related to the provided security token and these plans are executed, or until all available plans are parsed without a match.

Specific examples of this change are provided in the table below:
|===
| API plans | Request | Prior to this version | From this version

|API key plan + Keyless plan
|Request contains an invalid API key
|API key plan is executed = HTTP 401 unauthorized
|Keyless plan is executed

|JWT plan 1 + JWT plan 2
|Request contains a Bearer token valid for JWT plan 2
|JWT plan 1 is executed = HTTP 401 unauthorized
|JWT plan 2 is executed
|===


== Upgrade to 3.18.5
=== Breaking changes
==== Portal API
Endpoint: `[GET] portal/environments/{envId}/applications`.

For performance reasons, calling `/applications?size=-1` will no longer return the number of subscribers and the only information available in the owner of each application will be:

- id
- displayName
- email


== Upgrade to 3.18.0
=== Breaking changes
==== Environment Audits
Endpoint: `[GET] management/organizations/{orgId}/environments/{envId}/apis/{api}/audit` (link:{{ '/apim/3.x/management-api/' | relative_url | append: current_version | append: '/index.html#operation/getApiAudits' }}[API audits^]).

Before this version, the Management API allowed getting all audits of all environments and organizations with this endpoint.

As of 3.18.0, a GET request will return the audits of the environment specified in the url and no longer return organization audits.
To get organization audits you need to use the following endpoint: `[GET] management/organizations/{orgId}/audit`.

The query params `envLog:boolean` & `orgLog:boolean` are removed.
Now to get only environment or organization audit you have to use the query params `referenceType:string` with `ENVIRONMENT` or `ORGANIZATION`. You can also filter by environment id with `environment:string` query params.

==== Platform alerts on multi-environments APIM
Before this version, platform alerts were common to all environments.
That led to inconsistencies while handling platform alerts on multi-environments APIM.

From this version, platform alerts are scoped to the environment.
For example, if you create an alert on your `production` environment, it is related only to this environment.

Old platform alerts existing before Gravitee upgrade will be linked to the default environment.
You will see them disappear from your others (non-default) environments, and will have to recreate them manually if relevant.

==== System Roles Edition
To provide more flexibility in the way roles are managed, some system roles have been made editable. From now on, the permissions of the following roles can be edited:

. The Environment Admin Role.
. The API Primary Owner Role
. The Application Primary Owner Role

The Organization Admin Role remains a read-only role. If any accidental loss of access happened to one of the roles listed above, the Organization Admin Role will be the only one able to revert the changes.

This mode is deactivated by default, you can toggle it on via `gravitee.yml` :

----
console:
  systemRoleEdition:
    enabled: true
----

WARNING: Updating permissions for system roles should be done carefully to avoid any unexpected behavior.

==== Plugin renaming
From this version, and for the next 3.18.x versions and greater, the name of the Elasticsearch repository component changes. +
As a consequence, the Elasticsearch repository component available on https://download.gravitee.io is now +
`gravitee-*apim*-repository-elasticsearch-x.y.z.zip`

instead of +
`gravitee-repository-elasticsearch-x.y.z.zip`

This plugin has also been moved in another folder: +
https://download.gravitee.io/#graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/.

You can download directly the Elasticsearch repository using this link: +
https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/gravitee-apim-repository-elasticsearch-3.18.0.zip

==== MySQL
In 3.18.0, the MySQL Java driver has been updated to 8.0.29. As a consequence, TLS 1.0 and 1.1 are no longer supported.

=== Plans data
Since this version, APIM improves plans data storage, and uses the `plans` database collection as the unique source of plans data.

Before trusting data in `plans` collection, we have to ensure their reliability.

In 3.10, an upgrader was introduced to fix data, but was running in dry-run mode per default.

This upgrader will run once again during APIM 3.18 startup, with dry-run mode disabled : if relevant, it will fix plans data in your database as it's explained in https://docs.gravitee.io/pages/apim/3.x/installation-guide/upgrades/3.10.8/README.html#plans_anomalies_in_database[this documentation]

=== MongoDB
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.18.0/audit-set-environmentId-organizationId.js[/apim/3.x/mongodb/3.18.0/audit-set-environmentId-organizationId.js]::
This script add 'environmentId' and 'organizationId' columns in 'audits' table so audits can be associated to the right target. Creates also new indices.
link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.18.0/clientRegistrationProvider-set-environmentId.js[/apim/3.x/mongodb/3.18.0/clientRegistrationProvider-set-environmentId.js]::
This script add 'environmentId' columns in 'client_registration_providers' table they can be associated to the right environment.


== Upgrade to 3.17.3
=== Breaking changes
From this version, and for the next 3.17.x versions, the name of the Elasticsearch repository component changes. +
As a consequence, the Elasticsearch repository component available on https://download.gravitee.io is now +

`gravitee-*apim*-repository-elasticsearch-x.y.z.zip` +

instead of +

`gravitee-repository-elasticsearch-x.y.z.zip`

This plugin has also been moved in another folder: https://download.gravitee.io/#graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/. +

You can download directly the Elasticsearch repository using this link: +
https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/gravitee-apim-repository-elasticsearch-3.17.3.zip


== Upgrade to 3.17.0
=== Breaking Changes
==== Management API Documentation
From this version, APIM's Management API documentation is now using OpenAPI v3 format, instead of the old Swagger v2 format.

As a consequence, the specification of this API is now accessible from:

* `{host:port}/management/openapi.yaml`
* `{host:port}/management/openapi.json`

To allow a smooth transition, the old URL (`{host:port}/management/swagger.json`) will remain available until 3.18.0.

==== Docker Images - Enterprise Edition
To reduce the number of security vulnerabilities and ensure a better maintenance in the future, the base Docker images used for the Enterprise Edition have changed.

As of 3.17.0, APIM Gateway EE and Management API EE base Docker images are moving from **Ubuntu** to **Alpine** with JDK 17. It means users creating their own Docker images based on the one provided by Gravitee.io might need to update their Dockerfile to make them compatible with the Alpine distribution.

_Notes_: Community Edition users will not be affected as the base images were already **Alpine** ones.

=== Upgrade Order
In order to achieve a 0 downtime upgrade, APIM has to be upgraded before upgrading the gateways.

On hybrid architectures where gateway bridge feature is enabled, gateways have to be upgraded in this order :

. The bridge server gateway
. The bridge client gateway

=== Deprecated Bridge Endpoints
Since bridge client rely on their own internals to fulfil API key requests, the ``/apis/{api.id}/keys/{api.key}`` endpoint
has been deprecated on the bridge server and will be removed in a future version.

The ``/keys/_search`` endpoint has been deprecated and replaced with ``/keys/_findByCriteria`` endpoint. It will be removed in a future version.

More information on the gateway bridge feature can be found link:https://docs.gravitee.io/apim/3.x/apim_installguide_hybrid_deployment.html#apim_gateway_http_bridge_server[here].

=== The mongodb upgrade scripts have been moved
For the sake of improving our documentation management process, we have started decommissioning our link:https://github.com/gravitee-io/release[release] repository (which contained among other things this guide).

As a part of this change, our mongodb upgrade scripts are not hosted inside the release repository anymore and
have been moved to the link:https://github.com/gravitee-io/gravitee-api-management/tree/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts[gravitee-api-management] repository.

==== MongoDB
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.17.0/api-keys-cleanup.js[/apim/3.x/mongodb/3.17.0/api-keys-cleanup.js]::
This script performs some cleanup on the keys collection in order to avoid issues while moving to the new model.


== Upgrade to 3.16.5
=== Breaking changes
From this version, and for the next 3.17.x versions, the name of the Elasticsearch repository component changes. +
As a consequence, the Elasticsearch repository component available on https://download.gravitee.io is now +
`gravitee-*apim*-repository-elasticsearch-x.y.z.zip`

instead of +
`gravitee-repository-elasticsearch-x.y.z.zip`

This plugin has also been moved in another folder: +
https://download.gravitee.io/#graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/.

You can download directly the Elasticsearch repository using this link: +
https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/gravitee-apim-repository-elasticsearch-3.16.5.zip


== Upgrade to 3.16.2
=== Breaking Change
==== Docker Images - Enterprise Edition
To reduce the number of security vulnerabilities and ensure a better maintenance in the future, the base Docker images used for the Enterprise Edition have changed.

As of 3.16.2, APIM Gateway EE and Management API EE base Docker images are moving from **Ubuntu** to **Alpine** with JDK 17. It means users creating their own Docker images based on the one provided by Gravitee.io might need to update their Dockerfile to make them compatible with the Alpine distribution.

_Notes_: Community Edition users will not be affected as the base images were already **Alpine** ones.


== Upgrade to 3.16.0
=== API definition import process changes
Gravitee 3.16.0 introduces a new **crossId** in API definition, which identifies entities across environments.
This improves the API import and promotion processes reliability.

If you are using the _API import from JSON definition_ feature,
we **highly recommend** updating your API definitions by re-exporting your API.

Otherwise, if you import an API definition which doesn't contain **crossId**,
Gravitee will do the best-effort to import your API definition without it.

=== Deprecations
The Rest API endpoints listed below are deprecated since Gravitee v3.0.9, and will be removed in a future version.

|===
|Deprecated Endpoint| Replace With

|POST /apis/{api.id}/import
|POST /apis/import

|POST /apis/{api.id}/import/swagger
|PUT /apis/{api.id}/import/swagger
|===


== Upgrade to 3.15.14
=== Breaking changes
WARNING: As part of a future major APIM release, the breaking change described below will be reverted in a subsequent link:{{ '/apim/3.x/apim_changelog.html' | relative_url }}[3.15.x version^] in order to avoid potential issues on existing plan implementations.

==== API key and JWT plans
The security chain (the internal process that selects the executable plan for the incoming request and applies the related security rules) parses all active plans to select and execute the relevant one.

**Prior to this version:**

- The API key plan was executed if the request contained an API key.
- The JWT plan was executed if the request contained a Bearer token.

**From this version:**

The security chain has been improved to select and execute plans more efficiently. As a result, API keys and JWT plans are now only executed if there is an active subscription related to the provided security token. If there is no relevant subscription, the currently parsed plans are not executed and the security chain moves to parse the next available plans. The process continues until the security chain parses plans related to the provided security token and these plans are executed, or until all available plans are parsed without a match.

Specific examples of this change are provided in the table below:
|===
| API plans | Request | Prior to this version | From this version

|API key plan + Keyless plan
|Request contains an invalid API key
|API key plan is executed = HTTP 401 unauthorized
|Keyless plan is executed

|JWT plan 1 + JWT plan 2
|Request contains a Bearer token valid for JWT plan 2
|JWT plan 1 is executed = HTTP 401 unauthorized
|JWT plan 2 is executed
|===


== Upgrade to 3.15.9
=== Breaking changes
From this version, and for the next 3.15.x versions, the name of the Elasticsearch repository component changes. +
As a consequence, the Elasticsearch repository component available on https://download.gravitee.io is now +
`gravitee-*apim*-repository-elasticsearch-x.y.z.zip`

instead of +
`gravitee-repository-elasticsearch-x.y.z.zip`

This plugin has also been moved in another folder: +
https://download.gravitee.io/#graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/.

You can download directly the Elasticsearch repository using this link: +
https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/gravitee-apim-repository-elasticsearch-3.15.9.zip


== Upgrade to 3.15.6
=== Breaking Change
==== Docker Images - Enterprise Edition
To reduce the number of security vulnerabilities and ensure a better maintenance in the future, the base Docker images used for the Enterprise Edition have changed.

As of 3.15.6, APIM Gateway EE and Management API EE base Docker images are moving from **Ubuntu** to **Alpine** with JDK 17. It means users creating their own Docker images based on the one provided by Gravitee.io might need to update their Dockerfile to make them compatible with the Alpine distribution.

_Notes_: Community Edition users will not be affected as the base images were already **Alpine** ones.


== Upgrade to 3.15.0
=== Breaking Change
==== Management API
Since they were deprecated since version 3.12.0, the Rest API endpoints listed below have been removed.

|===
|Removed Endpoint| Replace With

|PUT /apis/{api.id}/keys/{apiKey.key}
|PUT /apis/{api.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}

|DELETE /apis/{api.id}/keys/{apiKey.key}
|DELETE /apis/{api.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}

|POST /apis/{api.id}/keys/_verify?apiKey={apiKey.key}
|GET /apis/{api.id}/subscriptions/_canCreate?application={application.id}&key={apiKey.key}

|DELETE /apis/{api.id}/subscriptions/{subscription.id}/keys/{apiKey.key}
|DELETE /apis/{api.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}

|GET /apis/{api.id}/subscriptions/{subscription.id}/keys
|GET /apis/{api.id}/subscriptions/{subscription.id}/apikeys

|POST /apis/{api.id}/subscriptions/{subscription.id}
|POST /apis/{api.id}/subscriptions/{subscription.id}/apikeys/_renew

|POST /apis/{api.id}/subscriptions/{subscription.id}/keys/{apiKey.key}/_reactivate
|POST /apis/{api.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}/_reactivate

|GET /applications/{application.id}/subscriptions/{subscription.id}/keys
|GET /applications/{application.id}/subscriptions/{subscription.id}/apikeys

|POST /applications/{application.id}/subscriptions/{subscription.id}
|POST /applications/{application.id}/subscriptions/{subscription.id}/apikeys/_renew

|DELETE /applications/{application.id}/subscriptions/{subscription.id}/keys/{apiKey.key}
|DELETE /applications/{application.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}
|===

==== Deprecation of path-based API creation
The path-based approach to create APIs will be removed in our next LTS and has been deprecated. From now on, this mode is disabled by default
but can still be re-activated from your organization settings.

==== Gateway
===== Custom policy breaking changes
We've made huge improvements on the v3.15.0 in order to considerably decrease the memory and cpu resources required to serve the traffic on the gateway.
For that, we rework some parts of the gateway which have impacts on few policies we maintain and could have impact on your custom policies you may have developed.

To summarize, here is the short list of the possible breaking changes that could impact you:

. Rework the way request and response headers are internally managed
. Policy class loading

NOTE: Details on each breaking changes are given below.

All policies maintained by Gravitee's teams are already ready to work with APIM v3.15.0. You may consider upgrading your custom policies if they match one of the following cases:

* Your policy relies on a static object instance that was previously instantiated per api and will become shared starting from the v3.15.0 of APIM
* Your policy manipulate request or response headers and should move to new way to manage headers.

For each of these cases, please find the appropriate actions below.

====== Http headers
Starting from 3.15.0 we rework the way the request and response headers are manage to make them even performant than ever.

For that reason, if your custom policy relies on headers make sure to upgrade it by replacing `io.gravitee.common.http.HttpHeaders` with the new headers class `io.gravitee.gateway.api.http.HttpHeaders` and migrate the few methods where name changed a bit:

* `new HttpHeaders()` -> `HttpHeaders.create()`
* `headers.containsKey("key")` -> `headers.contains("key")`
* `headers.get("key")` -> `headers.getAll("key")` (previous get returned a list)

====== Policy class loading
We've made huge improvements on the v3.15.0 by reworking the way policies are loaded when deploying an api on the APIM gateway.
While previously, one ClassLoader were instantiated per deployed api, we decided to shift to a single ClassLoader instance to avoid memory pressure, especially when deploying a lot of apis.
Also, policy instances are now reused across all the requests instead of re-instantiate them on each call.

For that, we had to adapt some policies we support in order to make sure they work with the new class loading and policy instantiation mechanisms.
Basically, policy instances are now considered as fully stateless and must get rid of any state which cannot be shared across the whole platform.

All the policies we support were already stateless. However, few changes have been made on some of them to move from static maps to cache instances that can be safely accessed and revoked concurrently.

*For all custom policies* you may have developed, we strongly recommend adopting the same strategy by *avoiding usage of static instances in your policies*.
If you are unable to adapt your policy before the migration to v3.15.0, there is still the possibility to explicitly switch back to the previous class loading behavior by setting the following configuration:

```yaml
classloader:
  legacy:
    enabled: true
```

WARNING: We highly recommend adopting the new class loading strategy as soon as possible as it may not be maintained in the future versions.


== Upgrade to 3.14.0
=== Breaking changes
==== Gateway
From with this version, the name of the APIM Gateway component changes.
As a consequence:

1. The APIM Gateway component available on https://download.gravitee.io is now `gravitee-*apim-gateway*-x.y.z.zip` instead of `gravitee-gateway-x.y.z.zip`

2. The name of the APIM Gateway folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-gateway*-x.y.z` instead of `graviteeio-gateway-x.y.z`

=== Gateway bridge upgrade
On hybrid architectures where gateway bridge feature is enabled, gateways have to be upgraded in this order :

. The bridge server gateway
. The bridge client gateway

More information on the gateway bridge feature can be found link:https://docs.gravitee.io/apim/3.x/apim_installguide_hybrid_deployment.html#apim_gateway_http_bridge_server[here].

=== ElasticSearch reporter plugins configuration
Before Gravitee 3.14 :

- For ES>=7, GeoIp and UserAgent plugins are enabled by default in Gravitee, and can't be disabled
- For ES<7, those plugins are disabled by default and can be enabled in Gravitee configuration.

Since Gravitee 3.14, it behave the same way for all ES versions :
GeoIp and UserAgent plugins are be enabled by default, and can be disabled by overriding default `reporters.elasticsearch.pipeline.plugins.ingest` configuration.

If your Gravitee configuration enables a plugin which is not available on your ES instance, you will get this kind of error message on gateway startup :

`Unable to create ES pipeline 'gravitee_pipeline': status[400] response[{"error":{"root_cause":[{"reason":"No processor type exists with name [geoip]","processor_type":"geoip"}]`

And then, you have to override `reporters.elasticsearch.pipeline.plugins.ingest` default configuration, to remove unrelevant plugin.


== Upgrade to 3.13.2
=== Breaking changes
==== Gateway
From with this version, the name of the APIM Gateway component changes.
As a consequence:

1. The APIM Gateway component available on https://download.gravitee.io is now `gravitee-*apim-gateway*-x.y.z.zip` instead of `gravitee-gateway-x.y.z.zip`

2. The name of the APIM Gateway folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-gateway*-x.y.z` instead of `graviteeio-gateway-x.y.z`


== Upgrade to 3.13.0
=== Breaking changes
==== Gateway
HTTP Bridge Service is now disabled by default starting.

If you are using this feature, **do not forget to update your settings.**

For more information, link:https://docs.gravitee.io/apim/3.x/apim_installguide_hybrid_deployment.html#apim_gateway_http_bridge_server[click here] for documentation.

==== Management Web UI
From with this version, the name of the APIM Console component changes.
As a consequence:

1. The APIM Console component available on https://download.gravitee.io is now `gravitee-*apim-console*-webui-x.y.z.zip` instead of `gravitee-management-webui-x.y.z.zip`

2. The name of the APIM Console folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-console*-ui-x.y.z` instead of `graviteeio-management-ui-x.y.z`

==== Portal Web UI
From with this version, the name of the APIM Portal component changes.
As a consequence:

1. The APIM Portal component available on https://download.gravitee.io is now `gravitee-*apim*-portal-webui-x.y.z.zip` instead of `gravitee-portal-webui-x.y.z.zip`

2. The name of the APIM Portal folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-portal-ui-x.y.z` instead of `graviteeio-portal-ui-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!


== Upgrade to 3.12.5
=== Breaking changes
==== Gateway
From with this version, the name of the APIM Gateway component changes.
As a consequence:

1. The APIM Gateway component available on https://download.gravitee.io is now `gravitee-*apim-gateway*-x.y.z.zip` instead of `gravitee-gateway-x.y.z.zip`

2. The name of the APIM Gateway folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-gateway*-x.y.z` instead of `graviteeio-gateway-x.y.z`


== Upgrade to 3.12.1
=== Breaking changes
==== Management Web UI
From with this version, the name of the APIM Console component changes.
As a consequence:

1. The APIM Console component available on https://download.gravitee.io is now `gravitee-*apim-console*-webui-x.y.z.zip` instead of `gravitee-management-webui-x.y.z.zip`

2. The name of the APIM Console folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-console*-ui-x.y.z` instead of `graviteeio-management-ui-x.y.z`

==== Portal Web UI
From with this version, the name of the APIM Portal component changes.
As a consequence:

1. The APIM Portal component available on https://download.gravitee.io is now `gravitee-*apim*-portal-webui-x.y.z.zip` instead of `gravitee-portal-webui-x.y.z.zip`

2. The name of the APIM Portal folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-portal-ui-x.y.z` instead of `graviteeio-portal-ui-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!


== Upgrade to 3.12.0
=== Breaking Change
*Policy plugin `gravitee-policy-apikey` prior to version 2.3.0 is no longer compatible with APIM 3.12.0.*

Starting in version 3.12.0, you must use `gravitee-policy-apikey` >= 2.3.0.

=== Default Settings Change Announcement
HTTP Bridge Service will be disabled by default starting in version 3.13.

If you are using this feature, **do not forget to update your settings.**

For more information, link:https://docs.gravitee.io/apim/3.x/apim_installguide_hybrid_deployment.html#apim_gateway_http_bridge_server[click here] for documentation.

=== API Keys
==== Model Change
Before this version, API keys contained a *key* attribute, which is both the value of the key and also the database ID.

Starting in version 3.12.0, APIKeys now contain distinct attributes:

- *key*: API key value
- *ID*: API key database unique ID

The 3 Portal API endpoints listed below now expose distinct *IDs* and *keys* in the HTTP response (previously, the key attribute was exposed as '*ID*') :

- GET /subscriptions/{subscription.id}
- POST /subscriptions/{subscription.id}
- POST /subscriptions/{subscription.id}/_renew

==== Deprecated Endpoints
The Rest API endpoints listed below are now deprecated, and will be removed in a future version.

|===
|Deprecated Endpoint| Replace With

|PUT /apis/{api.id}/keys/{apiKey.key}
|PUT /apis/{api.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}

|DELETE /apis/{api.id}/keys/{apiKey.key}
|DELETE /apis/{api.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}

|POST /apis/{api.id}/keys/_verify?apiKey={apiKey.key}
|GET /apis/{api.id}/subscriptions/_canCreate?application={application.id}&key={apiKey.key}

|DELETE /apis/{api.id}/subscriptions/{subscription.id}/keys/{apiKey.key}
|DELETE /apis/{api.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}

|GET /apis/{api.id}/subscriptions/{subscription.id}/keys
|GET /apis/{api.id}/subscriptions/{subscription.id}/apikeys

|POST /apis/{api.id}/subscriptions/{subscription.id}
|POST /apis/{api.id}/subscriptions/{subscription.id}/apikeys/_renew

|POST /apis/{api.id}/subscriptions/{subscription.id}/keys/{apiKey.key}/_reactivate
|POST /apis/{api.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}/_reactivate

|GET /applications/{application.id}/subscriptions/{subscription.id}/keys
|GET /applications/{application.id}/subscriptions/{subscription.id}/apikeys

|POST /applications/{application.id}/subscriptions/{subscription.id}
|POST /applications/{application.id}/subscriptions/{subscription.id}/apikeys/_renew

|DELETE /applications/{application.id}/subscriptions/{subscription.id}/keys/{apiKey.key}
|DELETE /applications/{application.id}/subscriptions/{subscription.id}/apikeys/{apiKey.id}
|===

=== Repository
==== MongoDB
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.12.0/api-keys-migration.js[/apim/3.x/mongodb/3.12.0/api-keys-migration.js]::
This script adds *key* and *api* columns in api keys *keys* table.


== Upgrade to 3.11.2
=== Breaking changes
==== Management Web UI
From with this version, the name of the APIM Console component changes.
As a consequence:

1. The APIM Console component available on https://download.gravitee.io is now `gravitee-*apim-console*-webui-x.y.z.zip` instead of `gravitee-management-webui-x.y.z.zip`

2. The name of the APIM Console folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-console*-ui-x.y.z` instead of `graviteeio-management-ui-x.y.z`

==== Portal Web UI
From with this version, the name of the APIM Portal component changes.
As a consequence:

1. The APIM Portal component available on https://download.gravitee.io is now `gravitee-*apim*-portal-webui-x.y.z.zip` instead of `gravitee-portal-webui-x.y.z.zip`

2. The name of the APIM Portal folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-portal-ui-x.y.z` instead of `graviteeio-portal-ui-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!


== Upgrade to 3.11.1
=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.11.1/1-event-debug-migration.js[/apim/3.x/mongodb/3.11.1/1-event-debug-migration.js]::
This script removes the `API_ID` property for events of type `DEBUG`.


== Upgrade to 3.11.0
=== Breaking changes
From with this version, the name of the APIM Rest APIs component changes.
As a consequence:

1. The APIM Rest API component available on https://download.gravitee.io is now `gravitee-*apim*-rest-api-x.y.z.zip` instead of `gravitee-management-rest-api-x.y.z.zip`

2. The name of the APIM Rest API folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-rest-api-x.y.z` instead of `graviteeio-rest-api-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!

=== Security update
From this version, API properties can be encrypted.

Encryption key is located in gravitee.yml of Rest APIs and gateway.

WARNING: You should not use this default key, and set your own custom 32 bytes length secret.

```yml
# Encrypt API properties using this secret
api:
  properties:
    encryption:
      secret: vvLJ4Q8Khvv9tm2tIPdkGEdmgKUruAL6
```


== Upgrade to 3.10.19
=== Breaking changes
WARNING: As part of a future major APIM release, the breaking change described below will be reverted in a subsequent link:{{ '/apim/3.x/apim_changelog.html' | relative_url }}[3.10.x version^] in order to avoid potential issues on existing plan implementations.

==== API key and JWT plans
The security chain (the internal process that selects the executable plan for the incoming request and applies the related security rules) parses all active plans to select and execute the relevant one.

**Prior to this version:**

- The API key plan was executed if the request contained an API key.
- The JWT plan was executed if the request contained a Bearer token.

**From this version:**

The security chain has been improved to select and execute plans more efficiently. As a result, API keys and JWT plans are now only executed if there is an active subscription related to the provided security token. If there is no relevant subscription, the currently parsed plans are not executed and the security chain moves to parse the next available plans. The process continues until the security chain parses plans related to the provided security token and these plans are executed, or until all available plans are parsed without a match.

Specific examples of this change are provided in the table below:
|===
| API plans | Request | Prior to this version | From this version

|API key plan + Keyless plan
|Request contains an invalid API key
|API key plan is executed = HTTP 401 unauthorized
|Keyless plan is executed

|JWT plan 1 + JWT plan 2
|Request contains a Bearer token valid for JWT plan 2
|JWT plan 1 is executed = HTTP 401 unauthorized
|JWT plan 2 is executed
|===


== Upgrade to 3.10.15
=== Breaking changes
From this version, and for the next 3.10.x versions, the name of the Elasticsearch repository component changes. +
As a consequence, the Elasticsearch repository component available on https://download.gravitee.io is now +
`gravitee-*apim*-repository-elasticsearch-x.y.z.zip`

instead of +
`gravitee-repository-elasticsearch-x.y.z.zip`

This plugin has also been moved in another folder: +
https://download.gravitee.io/#graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/.

You can download directly the Elasticsearch repository using this link: +
https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-elasticsearch/gravitee-apim-repository-elasticsearch-3.10.15.zip


== Upgrade to 3.10.13
=== Breaking Change
==== Docker Images - Enterprise Edition
To reduce the number of security vulnerabilities and ensure a better maintenance in the future, the base Docker images used for the Enterprise Edition have changed.

As of 3.10.13, APIM Gateway EE and Management API EE base Docker images are moving from **Ubuntu** to **Alpine** with JDK 17. It means users creating their own Docker images based on the one provided by Gravitee.io might need to update their Dockerfile to make them compatible with the Alpine distribution.

_Notes_: Community Edition users will not be affected as the base images were already **Alpine** ones.


== Upgrade to 3.10.9
=== ElasticSearch reporter plugins configuration
Before Gravitee 3.10.9 :

- For ES>=7, GeoIp and UserAgent plugins are enabled by default in Gravitee, and can't be disabled
- For ES<7, those plugins are disabled by default and can be enabled in Gravitee configuration.

Since Gravitee 3.10.9, it behave the same way for all ES versions :
GeoIp and UserAgent plugins are be enabled by default, and can be disabled by overriding default `reporters.elasticsearch.pipeline.plugins.ingest` configuration.

If your Gravitee configuration enables a plugin which is not available on your ES instance, you will get this kind of error message on gateway startup :

`Unable to create ES pipeline 'gravitee_pipeline': status[400] response[{"error":{"root_cause":[{"reason":"No processor type exists with name [geoip]","processor_type":"geoip"}]`

And then, you have to override `reporters.elasticsearch.pipeline.plugins.ingest` default configuration, to remove unrelevant plugin.


== Upgrade to 3.10.8
=== Breaking changes
==== Gateway
From with this version, the name of the APIM Gateway component changes.
As a consequence:

1. The APIM Gateway component available on https://download.gravitee.io is now `gravitee-*apim-gateway*-x.y.z.zip` instead of `gravitee-gateway-x.y.z.zip`

2. The name of the APIM Gateway folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-gateway*-x.y.z` instead of `graviteeio-gateway-x.y.z`

=== Plans anomalies in database
==== TL;DR
In Gravitee < 3.10.8, some processes have caused database inconsistencies, regarding plans and flows.

Gravitee 3.10.8, introduces an automated process to detect and fix those anomalies.

By default, this process will run in dry mode and won't do any database modification.
Check the `gravitee-upgraders.log` file to see if any of your API is concerned, and how it will be fixed.

After check, fix those database anomalies by disabling the dry mode.

==== What are those database anomalies ?
In Gravitee < 3.10.8, some processes have caused inconsistencies in database, regarding plans and flows.

Concerned processes are :

* import an API
* promote an API
* duplicate an API
* rollback an API

For concerned APIs, plans and flows displayed in console doesn't reflect the ones runned by gateway.

==== How to fix it ?
Gravitee 3.10.8, introduces an automated process to detect and fix those anomalies.

This process will run on management API startup. By default, it will run in 'dry' mode, to detect and list anomalies without fixing them in database.

After you checked those anomalies have to be fixed, you can disable the 'dry' mode, and restart your API to update your database.

==== My APIs are concerned ?
On management API startup, you will see this trace in the console, or the dedicated `gravitee-upgraders.log` log file.

If no anomaly was detected :

....
14:19:43.171 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - Starting PlansDataFixUpgrader execution with dry-run enabled
14:19:43.352 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - No plan data anomaly found
14:19:43.360 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - Finishing PlansDataFixUpgrader execution
....

If anomalies were detected :
....
14:51:50.890 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - Starting PlansDataFixUpgrader execution with dry-run enabled
14:51:50.979 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader -
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader - ##############################################################
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader - #                           WARNING                          #
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader - ##############################################################
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader -
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader - We detected database anomalies in your plans data.
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader -
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader - THIS IS A DRY RUN. DATABASE WON'T BE UPDATED.
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader - To fix anomalies, disable the dry run mode.
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader - Below, a list of changes that would happen without dry run
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader - See related documentation : https://docs.gravitee.io/apim/3.x/apim_installguide_migration.html#upgrade_to_3_10_8
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader -
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader - ##############################################################
14:51:50.980 [main] WARN  i.g.r.a.s.i.u.PlansDataFixUpgrader -
14:51:50.980 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - Plans anomalies found for API "Movies" (99999999-6595-9999-8a7e-796595985132) :
14:51:50.981 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - - Will create plan "Gold-Recreated" for API "Movies" (99999999-6595-9999-8a7e-796595985132), which is missing in plans table
14:51:50.982 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - - Will create plan "Free-Recreated" for API "Movies" (99999999-6595-9999-8a7e-796595985132), which is missing in plans table
14:51:50.982 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - - Will close plan "Free" (66664545-1234-1234-1234-1234567891425), cause it's absent from api definition
14:51:51.019 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - Plans anomalies found for API "Horses" (0456455556-5465-5465-4894955554) :
14:51:51.019 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - - Will create plan "LimitedUsage-Recreated" for API "Horses" (0456455556-5465-5465-4894955554), which is missing in plans table
14:51:51.025 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - Plans anomalies found for API "Petstore" (121112-1211-1111-121121211) :
14:51:51.025 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - - Will create plan "Silver-Recreated" for API "Petstore" (121112-1211-1111-121121211), which is missing in plans table
14:51:51.058 [main] INFO  i.g.r.a.s.i.u.PlansDataFixUpgrader - Finishing PlansDataFixUpgrader execution
....

==== How anomalies are fixed ?
This process will fix your API plans data.

But it won't change the runtime behavior of your APIs in the gateway, until you redeploy them manually from console.

===== Some plans were considered by gateway, but were not visible in console
They will be recreated in console, and you will see new plans appear:

* with name suffixed by "-Recreated"
* with description "This plan has been recreated during a data fix process. See documentation : ..."

Those plans will be in `deprecated` state, without any subscription.
It will allow you to check those plans and their flows, and close them if relevant.

===== Some plans visible in console were not considered by gateway
Those plans will be closed, as they were not actually used during API runtime.

==== I'm ready. How to disable the dry mode and fix data ?
To fix data in your database, turn off the dry-mode, setting the `services.plans-data-fix-upgrader.dryRun` parameter to false.
Then, restart the management API.

==== Further configuration ?
You can configure this process in gravitee.yml, for example:
....
services:
  plans-data-fix-upgrader:
    enabled: true
    dryRun: true
    notifyApiOwner: false
....

Possible configuration keys are :
|===
|Key|Description|Default value

|enabled
|If set to false, the process won't execute
|true

|dryRun
|If set to true, the process won't make any database change, but only list changes.
|true

|notifyApiOwner
|If set to true, an email notification will be send to the api owner for each fixed API.
|false
|===


== Upgrade to 3.10.4
=== Breaking changes
==== Management Web UI
From with this version, the name of the APIM Console component changes.
As a consequence:

1. The APIM Console component available on https://download.gravitee.io is now `gravitee-*apim-console*-webui-x.y.z.zip` instead of `gravitee-management-webui-x.y.z.zip`

2. The name of the APIM Console folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-console*-ui-x.y.z` instead of `graviteeio-management-ui-x.y.z`

==== Portal Web UI
From with this version, the name of the APIM Portal component changes.
As a consequence:

1. The APIM Portal component available on https://download.gravitee.io is now `gravitee-*apim*-portal-webui-x.y.z.zip` instead of `gravitee-portal-webui-x.y.z.zip`

2. The name of the APIM Portal folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-portal-ui-x.y.z` instead of `graviteeio-portal-ui-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!


== Upgrade to 3.10.1
=== Breaking changes
From this version, the name of the APIM Rest APIs component changes.
As a consequence:

1. The APIM Rest API component available on https://download.gravitee.io is now `gravitee-*apim*-rest-api-x.y.z.zip` instead of `gravitee-management-rest-api-x.y.z.zip`

2. The name of the APIM Rest API folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-rest-api-x.y.z` instead of `graviteeio-rest-api-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!

=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.10.1/1-upgrade-parameters-for-theme-console.js[/apim/3.x/mongodb/3.10.1/1-upgrade-parameters-for-theme-console.js]::
This script upgrade default value of `theme.logo` in parameters


== Upgrade to 3.10.0
=== Breaking changes
From with this version, the name of some components of Gravitee.io APIM changes.
As a consequence, the following plugins are renamed :

[cols="1,1"]
|===
|before 3.10.0|after 3.10.0

|gravitee.repository.mongodb-x.y.z.zip
|gravitee.*apim*.repository.mongodb-x.y.z.zip

|gravitee.repository.jdbc-x.y.z.zip
|gravitee.*apim*.repository.jdbc-x.y.z.zip

|gravitee.repository.redis-x.y.z.zip
|gravitee.*apim*.repository.redis-x.y.z.zip

|gravitee.repository.hazelcast-x.y.z.zip
|gravitee.*apim*.repository.hazelcast-x.y.z.zip

|gravitee.repository.gateway.bridge.http.client-x.y.z.zip
|gravitee.*apim*.repository.gateway.bridge.http.client-x.y.z.zip

|gravitee.repository.gateway.bridge.http.server-x.y.z.zip
|gravitee.*apim*.repository.gateway.bridge.http.server-x.y.z.zip
|===

These plugins have also been moved in another folder on https://download.gravitee.io.
For instance, the MongoDB plugin is now available using this link:

https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-mongodb/gravitee-apim-repository-mongodb-3.10.0.zip

WARNING: In future versions, others plugins will be renamed. Stay tuned!


== Upgrade to 3.9.4
=== Breaking changes
==== Threat protection policies
From this version, configuration form for JSON Threat Protection Policy and XML Threat Protection Policy changes:
`null` is no longer authorized, only `-1` is accepted for a 'no limit' setting.

===== Impacts
- If some fields are set to `null` in your db, and if you want to edit this policy configuration through *APIM Console*, then the form will replace them by the default value. Please, be careful when updating your policy if you do not want the default values to be applied.
- If some fields are set to `null` in your db, and if you want to edit this policy configuration through *REST API*, an error message will appear if you do not set an explicit value for those fields in your request payload.

==== Management Rest API
From with this version, the name of the APIM Rest APIs component changes.
As a consequence:

1. The APIM Rest API component available on https://download.gravitee.io is now `gravitee-*apim*-rest-api-x.y.z.zip` instead of `gravitee-management-rest-api-x.y.z.zip`

2. The name of the APIM Rest API folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-rest-api-x.y.z` instead of `graviteeio-rest-api-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!


== Upgrade to 3.9.3
=== Breaking changes
From with this version, the name of some components of Gravitee.io APIM changes.
As a consequence, the following plugins are renamed :

[cols="1,1"]
|===
|before 3.9.3|after 3.9.3

|gravitee.repository.mongodb-3.9.x.zip
|gravitee.*apim*.repository.mongodb-3.9.x.zip

|gravitee.repository.jdbc-3.9.x.zip
|gravitee.*apim*.repository.jdbc-3.9.x.zip

|gravitee.repository.redis-3.9.x.zip
|gravitee.*apim*.repository.redis-3.9.x.zip

|gravitee.repository.hazelcast-3.9.x.zip
|gravitee.*apim*.repository.hazelcast-3.9.x.zip

|gravitee.repository.gateway.bridge.http.client-3.9.x.zip
|gravitee.*apim*.repository.gateway.bridge.http.client-3.9.x.zip

|gravitee.repository.gateway.bridge.http.server-3.9.x.zip
|gravitee.*apim*.repository.gateway.bridge.http.server-3.9.x.zip
|===

These plugins have also been moved in another folder on https://download.gravitee.io.
For instance, the MongoDB plugin is now available using this link:

https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-mongodb/gravitee-apim-repository-mongodb-3.9.3.zip

WARNING: In future versions, others plugins will be renamed. Stay tuned!


== Upgrade to 3.9.2
=== Important: Alert Engine
NOTE: For users of Gravitee Enterprise Edition with Alert Engine, please check your gravitee configuration to ensure that the alert engine feature is explictly enable. Starting from this version, the alert engine connector is disabled by default if the option `alerts.alert-engine-enabled` is missing from the gravitee.yaml. (see https://docs.gravitee.io/ae/apim_installation.html#configuration)


== Upgrade to 3.9.0
=== Warning
*For JDBC users only*, please don't upgrade to 3.9.0 since we detected a critical bug in a liquibase script that could lead to data loss. +
This will be fixed in 3.9.1. +
We apologize for this inconvenience.

GitHub issue: https://github.com/gravitee-io/issues/issues/5711[5711]

=== Breaking changes
From this version, in order to propose a better swagger descriptor, all enum values *returned* by the APIM API are in uppercase.

NOTE: Lowercase and uppercase values are still accepted in incoming requests.

=== Memory management
Starting from this new version, the default Xms and Xmx parameters has been fixed to 256m.
Previous value was too high and does not reflect real memory usage for both the API Gateway and Management API.

If, for some reasons, you need to increase those default values, you can set the `GIO_MIN_MEM` and `GIO_MAX_MEM` environment variables in your scripts.
Those variables are then "injected" into the JAVA_OPTS during bootstrap.

=== APIM API - Tags and Tenants
This version changes permissions' scope from `ENVIRONMENT` to `ORGANIZATION` for:

* TAG
* TENANT
* ENTRYPOINT

These permissions are now readonly for the scope `ENVIRONMENT`. They will be deleted on version 3.10.
If you are using these permissions, please update them for the scope `ORGANIZATION`.

=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.9.0/1-tags-and-tenants-migration.js[/apim/3.x/mongodb/3.9.0/1-tags-and-tenants-migration.js]::
This script adds referenceId set to 'DEFAULT' and referenceType set to 'ORGANIZATION' to tags, tenants and entrypoint collections.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.9.0/2-events-migration.js[/apim/3.x/mongodb/3.9.0/2-events-migration.js]::
This script modifies events, so an event can be linked to more than one environment.


== Upgrade to 3.8.6
=== Breaking changes
From with this version, the name of some components of Gravitee.io APIM changes.
As a consequence, the following plugins are renamed :

[cols="1,1"]
|===
|before 3.8.6|after 3.8.6

|gravitee.repository.mongodb-3.8.x.zip
|gravitee.*apim*.repository.mongodb-3.8.x.zip

|gravitee.repository.jdbc-3.8.x.zip
|gravitee.*apim*.repository.jdbc-3.8.x.zip

|gravitee.repository.redis-3.8.x.zip
|gravitee.*apim*.repository.redis-3.8.x.zip

|gravitee.repository.hazelcast-3.8.x.zip
|gravitee.*apim*.repository.hazelcast-3.8.x.zip

|gravitee.repository.gateway.bridge.http.client-3.8.x.zip
|gravitee.*apim*.repository.gateway.bridge.http.client-3.8.x.zip

|gravitee.repository.gateway.bridge.http.server-3.8.x.zip
|gravitee.*apim*.repository.gateway.bridge.http.server-3.8.x.zip
|===

These plugins have also been moved in another folder on https://download.gravitee.io.
For instance, the MongoDB plugin is now available using this link:

https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-mongodb/gravitee-apim-repository-mongodb-3.8.6.zip

WARNING: In future versions, others plugins will be renamed. Stay tuned!


== Upgrade to 3.8.0
=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.8.0/1-page-acl-migration.js[/apim/3.x/mongodb/3.8.0/1-page-acl-migration.js]::
This script replaces *excluded_groups* by *visibility*, *excludedAccessControls* and *accessControls* collection.


== Upgrade to 3.7.0
=== Repository
NOTE: Since 3.7, you have the ability to configure a prefix for your tables or collections name.

Rate limit configuration has to be defined in both Gateway and Management `gravitee.yml` files.

With this centralized configuration, you can disable the liquibase phase of the gateway, if you do not want it to modify your dbms.

If you choose to use prefix, follow these instructions.

==== Mongodb
===== New installation
You just have to modify the `gravitee.yml` files of gateway and console to configure `management.mongodb.prefix` and `ratelimit.mongodb.prefix`. Default value is empty.

===== Migrate an existing installation
Before running any script, please create a dump of your existing database.

If you want to prefix your collections, you will have to rename them. You can use the following script.

Check documentation at https://docs.gravitee.io/apim/3.x/apim_installguide_repositories_mongodb.html

This script rename all the collections adding the `prefix` and `rateLimitPrefix`.

For the following steps, we admit you choose this prefix: prefix_

1. Modify `gravitee.yml` to configure `management.mongodb.prefix` and `ratelimit.mongodb.prefix` if needed.
2. Run the following script to rename your collections: link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.7.0/1-rename-collections-with-prefix.js[/apim/3.x/mongodb/3.7.0/1-rename-collections-with-prefix.js]
3. Run your instances!

==== JDBC
===== New installation
You just have to modify the `gravitee.yml` files of gateway and console to configure `management.jdbc.prefix` and `ratelimit.jdbc.prefix`. Default value is empty.

===== Migrate an existing installation
Before running any script, please create a dump of your existing database.

If you want to prefix your tables, you will have to rename them.
Check documentation at https://docs.gravitee.io/apim/3.x/apim_installguide_repositories_jdbc.html

For the following steps, we admit you choose this prefix: prefix_

1. Modify `gravitee.yml` to configure `management.jdbc.prefix` and `ratelimit.jdbc.prefix` if needed.
2. Run the application on a new database to generate `prefix_databasechangelog`
3. Replace the content of `databasechangelog` table by the generated one from `prefix_databasechangelog`
4. Rename your tables following this syntax: prefix_tablename
5. Rename your indexes following this syntax: idx_prefix_indexname
6. Rename your primary keys following this syntax: pk_prefix_pkname
7. Run your instances!


== Upgrade to 3.6.0
=== Elasticsearch
With Elasticsearch version above 7.x, `geoip` and `user_agent` plugins are automatically enabled.

=== APIM API
Two new configuration keys have been added to the `gravitee.yml` file, they should be set with the URLs of the UI console and the management API:
```yml
console:
  ui:
    url: gravitee_apim_ui_url # TO UPDATE WITH YOUR OWN URL
  api:
    url: gravitee_apim_management_api_url # TO UPDATE WITH YOUR OWN URL
```

NB: **For Gravitee Cockpit to work properly these URLs are mandatory**, they will be used by Cockpit to interact with your APIM installation.


== Upgrade to 3.5.25
=== Breaking changes
==== Gateway
From with this version, the name of the APIM Gateway component changes.
As a consequence:

1. The APIM Gateway component available on https://download.gravitee.io is now `gravitee-*apim-gateway*-x.y.z.zip` instead of `gravitee-gateway-x.y.z.zip`
2. The name of the APIM Gateway folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-gateway*-x.y.z` instead of `graviteeio-gateway-x.y.z`


== Upgrade to 3.5.21
=== Breaking changes
==== Management Web UI
From with this version, the name of the APIM Console component changes.
As a consequence:

1. The APIM Console component available on https://download.gravitee.io is now `gravitee-*apim-console*-webui-x.y.z.zip` instead of `gravitee-management-webui-x.y.z.zip`

2. The name of the APIM Console folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-console*-ui-x.y.z` instead of `graviteeio-management-ui-x.y.z`

==== Portal Web UI
From with this version, the name of the APIM Portal component changes.
As a consequence:

1. The APIM Portal component available on https://download.gravitee.io is now `gravitee-*apim*-portal-webui-x.y.z.zip` instead of `gravitee-portal-webui-x.y.z.zip`

2. The name of the APIM Portal folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-portal-ui-x.y.z` instead of `graviteeio-portal-ui-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!


== Upgrade to 3.5.19
=== Breaking changes
==== Threat protection policies
From this version, configuration form for JSON Threat Protection Policy and XML Threat Protection Policy changes:
`null` is no longer authorized, only `-1` is accepted for a 'no limit' setting.

===== Impacts
- If some fields are set to `null` in your db, and if you want to edit this policy configuration through *APIM Console*, then the form will replace them by the default value. Please, be careful when updating your policy if you do not want the default values to be applied.
- If some fields are set to `null` in your db, and if you want to edit this policy configuration through *REST API*, an error message will appear if you do not set an explicit value for those fields in your request payload.

==== Management Rest API
From with this version, the name of the APIM Rest APIs component changes.
As a consequence:

1. The APIM Rest API component available on https://download.gravitee.io is now `gravitee-*apim*-rest-api-x.y.z.zip` instead of `gravitee-management-rest-api-x.y.z.zip`

2. The name of the APIM Rest API folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-rest-api-x.y.z` instead of `graviteeio-rest-api-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!

=== Improvements
Some performance improvements have been made (https://github.com/gravitee-io/issues/issues/6066[#6066]).
As a consequence, the scheduled service used to automatically close expired subscriptions now runs every hour instead of every 5 seconds


== Upgrade to 3.5.18
=== Breaking changes
From with this version, the name of some components of Gravitee.io APIM changes.
As a consequence, the following plugins are renamed :

[cols="1,1"]
|===
|before 3.5.18|after 3.5.18

|gravitee.repository.mongodb-3.5.x.zip
|gravitee.*apim*.repository.mongodb-3.5.x.zip

|gravitee.repository.jdbc-3.5.x.zip
|gravitee.*apim*.repository.jdbc-3.5.x.zip

|gravitee.repository.redis-3.5.x.zip
|gravitee.*apim*.repository.redis-3.5.x.zip

|gravitee.repository.hazelcast-3.5.x.zip
|gravitee.*apim*.repository.hazelcast-3.5.x.zip

|gravitee.repository.gateway.bridge.http.client-3.5.x.zip
|gravitee.*apim*.repository.gateway.bridge.http.client-3.5.x.zip

|gravitee.repository.gateway.bridge.http.server-3.5.x.zip
|gravitee.*apim*.repository.gateway.bridge.http.server-3.5.x.zip
|===

These plugins have also been moved in another folder on https://download.gravitee.io.
For instance, the MongoDB plugin is now available using this link:

https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-apim-repository-mongodb/gravitee-apim-repository-mongodb-3.5.18.zip

WARNING: In future versions, others plugins will be renamed. Stay tuned!


== Upgrade to 3.5.14
=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.5.14/1-fix-cors-env-vars.js[/apim/3.x/mongodb/3.5.14/1-fix-cors-env-vars.js]::
This script migrate CORS environment variables for portal and console. (See below).

=== Breaking Changes
==== Environment variables
Some environment variables have been doubled for the portal and the console, see correspondence table:

[cols="1,1,1"]
|===
|before 3.5.14|after 3.5.14 (for portal)| after 3.5.14 (for console)

|portal.http.cors.allow-origin
|http.api.portal.cors.allow-origin
|X

|console.http.cors.allow-origin
|X
|http.api.management.cors.allow-origin

|portal.http.cors.allow-headers
|http.api.portal.cors.allow-headers
|X

|console.http.cors.allow-headers
|X
|http.api.management.cors.allow-header

|portal.http.cors.allow-methods
|http.api.portal.cors.allow-methods
|X

|console.http.cors.allow-methods
|X
|http.api.management.cors.allow-methods

|portal.http.cors.exposed-headers
|http.api.portal.cors.exposed-headers
|X

|console.http.cors.exposed-headers
|X
|http.api.management.cors.exposed-headers

|portal.http.cors.max-age
|http.api.portal.cors.max-age
|X

|console.http.cors.max-age
|X
|http.api.management.cors.max-age
|===


== Upgrade to 3.5.11
=== Breaking Changes
==== Management API
If you are using the REST API directly, please note that now these requests need authentication:

* GET /management/organization/{orgId}/environments/{envId}/portal
* GET /management/organization/{orgId}/environments/{envId}/portal/pages
* GET /management/organization/{orgId}/environments/{envId}/portal/pages/_pageId_
* GET /management/organization/{orgId}/environments/{envId}/portal/pages/_pageId_/content
* GET /management/organization/{orgId}/environments/{envId}/portal/pages/_pageId_/media
* GET /management/organization/{orgId}/environments/{envId}/portal/media/_hash_
* GET /management/organization/{orgId}/environments/{envId}/portal/identities
* POST /management/organization/{orgId}/environments/{envId}/portal/apis/_search


== Upgrade to 3.5.2
=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.5.2/1-add-DEFAULT-referenceId-in-memberships.js[/apim/3.x/mongodb/3.5.2/1-add-DEFAULT-referenceId-in-memberships.js]::
This script add the "DEFAULT" `referenceId` for memberships with `null` one. This bug impacts users created when using social authentication since version 3.5.0.


== Upgrade to 3.5.0
=== Breaking Changes
==== Environment variables
Some environment variables have been doubled for the portal and the console, see correspondence table:

[cols="1,1,1"]
|===
|before 3.5.0|after 3.5.0 (for portal)| after 3.5.0 (for console)

|authentication.localLogin.enabled
|portal.authentication.localLogin.enabled
|console.authentication.localLogin.enabled

|scheduler.tasks
|portal.scheduler.tasks
|console.scheduler.tasks

|scheduler.notifications
|portal.scheduler.notifications
|console.scheduler.notifications

|reCaptcha.enabled
|portal.reCaptcha.enabled
|console.reCaptcha.enabled

|reCaptcha.siteKey
|portal.reCaptcha.siteKey
|console.reCaptcha.siteKey

|portal.support.enabled
|portal.support.enabled
|console.support.enabled

|portal.userCreation.enabled
|portal.userCreation.enabled
|console.userCreation.enabled

|portal.userCreation.automaticValidation.enabled
|portal.userCreation.automaticValidation.enabled
|console.userCreation.automaticValidation.enabled

|http.cors.allow-origin
|portal.http.cors.allow-origin
|console.http.cors.allow-origin

|http.cors.allow-headers
|portal.http.cors.allow-headers
|console.http.cors.allow-headers

|http.cors.allow-methods
|portal.http.cors.allow-methods
|console.http.cors.allow-methods

|http.cors.exposed-headers
|portal.http.cors.exposed-headers
|console.http.cors.exposed-headers

|http.cors.max-age
|portal.http.cors.max-age
|console.http.cors.max-age
|===

=== Distribution
From this version, Gravitee.IO APIM is distributed with MongoDB and JDBC plugins, as well as Hybrid HTTP plugin (gateway-bridge-http), in the `full` ZIP. +
You no longer have to choose between the "full" or "full-jdbc" ZIP file.

=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.5.0/1-duplicate-some-parameters-for-console.js[/apim/3.x/mongodb/3.5.01-duplicate-some-parameters-for-console.js]::
This script duplicates some parameters for the console to have different behaviors between portal and console. It also modifies the _id of each mongo document to add referenceId and referenceType.



== Upgrade to 3.4.0
=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.4.0/1-update-audit-to-replace-PORTAL-with_ORGANIZATION-and-ENVIRONMENT.js[/apim/3.x/mongodb/3.4.0/1-update-audit-to-replace-PORTAL-with_ORGANIZATION-and-ENVIRONMENT.js]::
This script convert PORTAL audit into ENVIRONMENT audits or ORGANIZATION audits regarding some conditions.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.4.0/2-update-default-role-REVIEWER.js[/apim/3.x/mongodb/3.4.0/2-update-default-role-REVIEWER.js]::
This script add new permissions to the default REVIEWER role.


== Upgrade to 3.3.0
=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.3.0/1-update-users-and-identityProviders.js[/apim/3.x/mongodb/3.3.0/1-update-users-and-identityProviders.js]::
This script replaces *referenceId* and *referenceType* with *organizationId* for `users` and `identity_providers` collections.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.3.0/2-update-json-validation-policy-scopes.js[/apim/3.x/mongodb/3.3.0/2-update-json-validation-policy-scopes.js]::
This script replaces *REQUEST* and *RESPONSE* with *REQUEST_CONTENT* and *RESPONSE_CONTENT* for json-validation policy configuration in `apis` collections.

=== Deprecation
==== Management API
Starting with this version, `User` and `IdentityProvider` are now linked to an organization and not to an environment.
As a consequence, the Management REST API has been updated.
If you are using the REST API directly, please note that you should adapt your URL for these resources as they will no longer be accessible from version 4.x
In the meantime, these resources will be tagged as `Deprecated`.

[options="header"]
|=============
|Deprecated in 3.3.0, deleted in 4.x                                                                         |Since 3.3.0
|/organizations/DEFAULT/environments/DEFAULT/auth/oauth2/{identity}                                          |/organizations/DEFAULT/auth/oauth2/{identity}
|/organizations/DEFAULT/environments/DEFAULT/configuration/identities                                        |/organizations/DEFAULT/configuration/identities
|/organizations/DEFAULT/environments/DEFAULT/configuration/identities/{identityProvider}                     |/organizations/DEFAULT/configuration/identities/{identityProvider}
|/organizations/DEFAULT/environments/DEFAULT/configuration/rolescopes                                        |/organizations/DEFAULT/configuration/rolescopes
|/organizations/DEFAULT/environments/DEFAULT/configuration/rolescopes/{scope}/roles                          |/organizations/DEFAULT/configuration/rolescopes/{scope}/roles
|/organizations/DEFAULT/environments/DEFAULT/configuration/rolescopes/{scope}/roles/{role}                   |/organizations/DEFAULT/configuration/rolescopes/{scope}/roles/{role}
|/organizations/DEFAULT/environments/DEFAULT/configuration/rolescopes/{scope}/roles/{role}/users             |/organizations/DEFAULT/configuration/rolescopes/{scope}/roles/{role}/users
|/organizations/DEFAULT/environments/DEFAULT/configuration/rolescopes/{scope}/roles/{role}/users/{userId}    |/organizations/DEFAULT/configuration/rolescopes/{scope}/roles/{role}/users/{userId
|/organizations/DEFAULT/environments/DEFAULT/search/users                                                    |/organizations/DEFAULT/search/users
|/organizations/DEFAULT/environments/DEFAULT/user                                                            |/organizations/DEFAULT/user
|/organizations/DEFAULT/environments/DEFAULT/user/subscribeNewsletter                                        |/organizations/DEFAULT/user/subscribeNewsletter
|/organizations/DEFAULT/environments/DEFAULT/user/avatar                                                     |/organizations/DEFAULT/user/avatar
|/organizations/DEFAULT/environments/DEFAULT/user/login                                                      |/organizations/DEFAULT/user/login
|/organizations/DEFAULT/environments/DEFAULT/user/logout                                                     |/organizations/DEFAULT/user/logout
|/organizations/DEFAULT/environments/DEFAULT/user/tasks                                                      |/organizations/DEFAULT/user/tasks
|/organizations/DEFAULT/environments/DEFAULT/user/tags                                                       |/organizations/DEFAULT/user/tags
|/organizations/DEFAULT/environments/DEFAULT/user/notifications                                              |/organizations/DEFAULT/user/notifications
|/organizations/DEFAULT/environments/DEFAULT/user/tokens                                                     |/organizations/DEFAULT/user/tokens
|/organizations/DEFAULT/environments/DEFAULT/user/tokens/{token}                                             |/organizations/DEFAULT/user/tokens/{token}
|/organizations/DEFAULT/environments/DEFAULT/users                                                           |/organizations/DEFAULT/users
|/organizations/DEFAULT/environments/DEFAULT/users/{id}                                                      |/organizations/DEFAULT/users/{id}
|/organizations/DEFAULT/environments/DEFAULT/users/{id}/groups                                               |/organizations/DEFAULT/users/{id}/groups
|/organizations/DEFAULT/environments/DEFAULT/users/{id}/memberships                                          |/organizations/DEFAULT/users/{id}/memberships
|/organizations/DEFAULT/environments/DEFAULT/users/{id}/resetPassword                                        |/organizations/DEFAULT/users/{id}/resetPassword
|/organizations/DEFAULT/environments/DEFAULT/users/{id}/avatar                                               |/organizations/DEFAULT/users/{id}/avatar
|/organizations/DEFAULT/environments/DEFAULT/users/{id}/roles                                                |/organizations/DEFAULT/users/{id}/roles
|/organizations/DEFAULT/environments/DEFAULT/users/{id}/_process                                             |/organizations/DEFAULT/users/{id}/_process
|/organizations/DEFAULT/environments/DEFAULT/users/registration                                              |/organizations/DEFAULT/users/registration
|/organizations/DEFAULT/environments/DEFAULT/users/registration/finalize                                     |/organizations/DEFAULT/users/registration/finalize
|=============


== Upgrade to 3.2.0
=== Breaking Changes
==== Portal UI
The variables css of `gv-link` component has been modified to improve the theme's customization.
Now the component uses :

* Active border color `--gv-link-active--bdc` instead of Active border bottom color `--gv-link-active--bdbc`
* Active border style `--gv-link-active--bds` instead of Active border bottom style `--gv-link-active--bdbs`
* Active border width `--gv-link-active--bdw` instead of Active border bottom width `--gv-link-active--bdbw`

For example, if you has set `--gv-link-active--bdbw=3px`, now you should set `--gv-link-active--bdw=0 0 3px 0`


== Upgrade to 3.1.0
=== Docker images
All the UI based docker images (APIM Console, APIM Portal) are now using HTTP port 8080 and HTTPS port 8443 by default to
avoid the need of a root account to use 80/443 to improve the security of our platform.


== Upgrade to 3.0.10
=== Breaking Changes
==== Management API
Starting with this version, `Apis` resources require authentication even for the GET method.

If you are using the REST API directly, please note that you should adapt your application.

`Apis` resources start with the path `/management/organizations/DEFAULT/environments/DEFAULT/apis/`

==== Portal API
Starting with this version, `Apis`, `Pages` and `Categories` resources that were public for GET method require authentication if the users have to sign in to access the portal. (forceLogin = true)

If you are using the REST API directly, please note that you should adapt your application.

* `Apis` resources start with the path `/portal/environments/DEFAULT/apis`
* `Pages` resources start with the path `/portal/environments/DEFAULT/pages`
* `Categories` resources start with the path `/portal/environments/DEFAULT/categories`


== Upgrade to 3.0.7
=== Breaking changes
The `portalURL` parameter in the gravitee.yml file has been removed.
It has become useless with this issue https://github.com/gravitee-io/issues/issues/4144[#4144].

As this `portalURL` stands for the former portal, it will be replaced by the `management.url` parameter in the console settings.
This parameter will be initialized with the former `portalURL` value if it still exists in your gravitee.yml.
Otherwise, the default value of `management.url` is http://localhost:3000

The `portal.url` parameter in the console settings will also have a default value : http://localhost:4100


== Upgrade to 3.0.2
=== 'View' renamed to 'Categories'
In the new portal, 'views' are called 'categories'. But in the management console, they are still called 'views'.
To be consistent, the term 'View' is replaced by 'Category' in the whole platform.

Linked to this issue: https://github.com/gravitee-io/issues/issues/3843[#3843]

==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.0.2/1-rename-view-in-category.js[upgrades/3.x/3.0.2/mongodb/1-rename-view-in-category.js]::
This script renames a field in 'apis' collection, rename 'views' collection, change 3 parameters, replace 'view' by 'category' in 'audits' collection and convert documentation view LINK to ctagory LINK


== Upgrade to 3.0.0
=== Important
If you are using mongoDB, it is *strongly recommended* to run the scripts to upgrade your database *before* starting the new version of the gravitee REST APIs.
Otherwise, you could experience data corruption issues.

IMPORTANT: Mongo version *MUST* be at least *3.6*

=== General
==== Organization & Environment
In this new version Gravitee comes with a new way of managing your environments.
By default, Gravitee is configured with a first Organization:
```
organization {
  id: DEFAULT,
  name: Default organization
}
```
And a first Environment in this Organization:
```
environment {
  id: DEFAULT,
  name: Default environment,
  organization: DEFAULT
}
```

It will allow you to manage more than one environment for each instance of Gravitee.

=== Breaking Changes
==== API-Key policy
In this new version, if api-keys used to call an API is invalid or has expired, the gateway will fail with a *401* (instead of 403 in previous versions of Gravitee).

==== Management API
If you are using the REST API directly, please note that you will have to adapt the URL
from `https://host/management/` to `https://host/management/organizations/DEFAULT/environments/DEFAULT/`

The resource `/views/default` has been deleted since a view does not have a *default* field anymore.

==== Management UI
The actual portal has been replaced by a brand new version, with its own location. As a consequence, the URL of the management UI has been modified to remove the */management* part.

For instance, to access the _Platform Overview_ page, you should use `https://host/\#!/platform` instead of `https://host/#!/management/platform`

==== Memberships, roles and role mappings
One major breaking change in this new version is the replacement of *MANAGEMENT* and *PORTAL* scopes by *ENVIRONNMENT* and *ORGANIZATION* scopes. It's not just a renaming but a dispatch of permissions among these 2 news scopes. As a consequence, all existing memberships, roles, groups and Identity Providers role mappings should be updated.

* Memberhips, roles and groups have to be updated with migration scripts <<mongodb, here>>
* Role Mappings for Identity Providers stored in database will be updated with a specific upgrader. See <<upgrader, Upgrader>>
* Role mappings defined in the *gravitee.yml* file have to be updated with these new scopes.

Here's a correlation table of permissions before and after migration :
[options="header"]
|=============
|Permission Name |Scope Name before migration |Scope name after migration
|INSTANCE                     |MANAGEMENT  |ENVIRONMENT
|GROUP                        |MANAGEMENT  |ENVIRONMENT
|TAG                          |MANAGEMENT  |ENVIRONMENT
|TENANT                       |MANAGEMENT  |ENVIRONMENT
|API                          |MANAGEMENT  |ENVIRONMENT
|ROLE                         |MANAGEMENT  |ORGANIZATION
|APPLICATION                  |MANAGEMENT  |ENVIRONMENT
|PLATFORM                     |MANAGEMENT  |ENVIRONMENT
|AUDIT                        |MANAGEMENT  |ENVIRONMENT
|NOTIFICATION                 |MANAGEMENT  |ENVIRONMENT
|USER                         |MANAGEMENT  |ORGANIZATION
|MESSAGE                      |MANAGEMENT  |ENVIRONMENT
|DICTIONARY                   |MANAGEMENT  |ENVIRONMENT
|ALERT                        |MANAGEMENT  |ENVIRONMENT
|ENTRYPOINT                   |MANAGEMENT  |ENVIRONMENT
|SETTINGS                     |MANAGEMENT  |ENVIRONMENT
|DASHBOARD                    |MANAGEMENT  |ENVIRONMENT
|QUALITY_RULE                 |MANAGEMENT  |ENVIRONMENT
|METADATA                     |PORTAL      |ENVIRONMENT
|DOCUMENTATION                |PORTAL      |ENVIRONMENT
|APPLICATION                  |PORTAL      |ENVIRONMENT
|VIEW                         |PORTAL      |ENVIRONMENT
|TOP_APIS                     |PORTAL      |ENVIRONMENT
|SETTINGS                     |PORTAL      |ENVIRONMENT
|API_HEADER                   |PORTAL      |ENVIRONMENT
|IDENTITY_PROVIDER            |PORTAL      |ENVIRONMENT
|CLIENT_REGISTRATION_PROVIDER |PORTAL      |ENVIRONMENT
|=============

=== Repository
==== Mongodb
Before running any script, please create a dump of your existing database.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.0.0/1-collections-linked-to-environment-or-organization.js[/apim/3.x/mongodb/3.0.0/1-collections-linked-to-environment-or-organization.js]::
This script adds new fields that refer the default environment or the default organization.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.0.0/2-roles-groups-and-memberships-migration.js[/apim/3.x/mongodb/3.0.0/2-roles-groups-and-memberships-migration.js]::
This script migrates permission values in roles since MANAGEMENT roles and PORTAL roles have been merged and dispatched into new ENVIRONMENT and ORGANIZATION roles.
It also updates memberships and groups by adding or removing columns.
All previous indexes for *roles* and *memberships* will be deleted and replaced by new indexes.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.0.0/3-replace-apiArray-by-unique-api.js[/apim/3.x/mongodb/3.0.0/3-replace-apiArray-by-unique-api.js]::
This script adds a new field that refers the api and remove the api array.
All previous indexes for *plans* will be deleted and replaced by new indexes.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.0.0/4-remove-devMode.js[/apim/3.x/mongodb/3.0.0/4-remove-devMode.js]::
This script removes the 'devMode' parameter, since the legacy portal has been replaced.

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.0.0/5-remove-orphan-documentation-pages.js[/apim/3.x/mongodb/3.0.0/5-remove-orphan-documentation-pages.js]::
Due to a bug in a previous version of gravitee when importing APIs, orphan pages may have been created. Orphan pages are all pages with a parentId but no page with such id exists.
In some situation, this can lead to errors when accessing portal or apis documentation.
You may use this script to find and remove orphan pages.

_Note: You can make a 'dry run' by commenting line 6 and uncommenting line 5._

link:https://raw.githubusercontent.com/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.0.0/6-remove-ALL-view-and-defaultView-field.js[/apim/3.x/mongodb/3.0.0/6-remove-ALL-view-and-defaultView-field.js]::
This script removes the 'All' *view*, since the legacy portal has been replaced and the new portal does not need this default view anymore. The script also updates existing views to remove *defaultView* field.

=== Upgrader
==== Identity providers
Because of the evolution of the roles and their scope, role mappings in *Identity Providers* must be updated. To achieve this, a specific service has been created and will be launched at APIM startup. As this is not necessary to launch this service more than once, it can be disabled with some configuration.
[source, yaml]
----
services:
  # v3 upgrader service. Can be disabled after first launch.
  v3-upgrader:
    enabled: true
----

=== Docker
Docker images for Gravitee.io APIM have been renamed to follow the same conventions as the others Gravitee.io modules.

In the case of Gravitee.io APIM, all the images have been prefixed by `-apim`.

For example, for the API gateway `graviteeio/gateway` has been replaced by `graviteeio/apim-gateway`.

Please have a look to the documentation at: https://docs.gravitee.io/apim/3.x/apim_installguide_docker_images.html



