= Session management

When a user signs in, AM stores the fact that the user is authenticated for a certain period of time in what we call an *HTTP Session*.

This mechanism prevents the need for reauthentication every time users want to perform some actions. The same principle applies for your applications or when you use an external identity provider such as Facebook or Twitter.

NOTE: By default the session lasts 30 minutes, you can change this value via the `gravitee.yml` file of your AM Gateway, as described in the link:/Guides/am/current/configuration-guide/introduction.html[Configuration Guide^].

== Session layers

There are three session layers in particular that you need to consider when you want to sign out your users:

1. *Application session*: this layer is in your application after your users have been authenticated in AM.
For traditional web applications, this session is stored with HTTP cookies (JSESSIONID, PHPSESSID, ASP.NET_SessionId). For SPA applications, this information can be stored in memory or in a database.
You need to clean everything up if you want log out your users.

2. *Gravitee.io AM session*: a session is created for every authenticated user, and this information is in an HTTP cookie.
This cookie acts as Single Sign-on (SSO) cookie, helps you remember your users, and automatically silently authenticates your users across applications.
+
NOTE: To automatically authenticate your users across applications (SSO), your applications must share the same identity provider.

3. *Identity Provider session*: if your application is configured to use a link:/Guides/am/current/user-guide/identity-provider/social/introduction.html[social identity provider^] to authenticate a user, the identity provider creates a session in addition to the AM session.
When users attempt to sign in with any of these providers and they are already signed into the provider, they will not be prompted again to sign in.

== Invalidate session

You need to clean up application session layers if you want log out your users.

You can use the information in link:./logout.html[Logout^] to disable AM and identity provider sessions.
