---
redirect_from:
  - /am/current/am_userguide_user_session_management_logout.html
---
= Logout

== Invalidate session

Authenticated users who want to invalidate their session can call the following URL: `https://AM_GATEWAY_HOST/{domain}/logout`

NOTE: By default, access tokens and refresh tokens are not revoked. You can add the `invalidate_tokens=true` query parameter to the request to invalidate current user tokens.

== Redirect users after logout

You can specify the `post_logout_redirect_uri=http://myApp/logoutCallback` or `target_url=http://myApp/logoutCallback` query parameter to redirect the user to your application after logout.

NOTE: You can define list of allowed URLs where the user will be redirected after being sign out. It prevents some vulnerabilities like being redirected to unsafe websites.

== Single sign out

[label label-version]#New in version 3.10#

With single sign out, your end users can sign out of both their AM session and the social identity provider (configured in your application) in one action.

To enable single sign out:

. In AM Console, click *Applications* and select your application.
. Click *Settings > General*.
. Switch on *Single Sign Out* and click *SAVE*.

NOTE: If you call the default logout API endpoint, your users will be logged out in both places.

=== Limitations

Currently only the following identity providers are compatible with the *Single Sign Out* feature:

- Certified OpenID Connect provider
- Azure AD
