---
layout: doc
permalink: gravitee_privacy_policy.html
title: Privacy Policy
---

This is the privacy notice of Gravitee Topco Limited. In this document, "we", "our", or "us" refer to Gravitee Topco Limited

We are company number 13233796 registered in England.

Our registered office is at 71-75 Shelton Street, London, WC2H 9JQ, United Kingdom.

== Introduction
This privacy notice aims to inform you about how we collect and process any information that we collect from you, or that you provide to us. It covers information that could identify you (“personal information”) and information that could not. In the context of the law and this notice, “process” means collect, store, transfer, use or otherwise act on information. It tells you about your privacy rights and how the law protects you.

We are committed to protecting your privacy and the confidentiality of your personal information. Our policy is not just an exercise in complying with the law, but a continuation of our respect for you and your personal information.

We undertake to preserve the confidentiality of all information you provide to us, and hope that you reciprocate.

Our policy complies with the UK Data Protection Act 2018 (Act) accordingly incorporating the EU General Data Protection Regulation (GDPR).

The law requires us to tell you about your rights and our obligations to you in regard to the processing and control of your personal data. We do this now, by requesting that you read the information provided at http://www.knowyourprivacyrights.org.

Except as set out below, we do not share, or sell, or disclose to a third party, any information collected through our website.

=== 1. Data Privacy

If you have any questions about privacy, including any requests to exercise your legal rights, please contact us dataprivacy@graviteesource.com.

=== 2. Data We Process
We may collect, use, store and transfer different kinds of personal data about you. We have collated these into groups as follows:
Your identity includes information such as first name, last name, title, date of birth, and other identifiers that you may have provided at some time.

Your contact information includes information such as billing address, delivery address, email address, telephone numbers and any other information you have given to us for the purpose of communication or meeting.

Your financial data includes information such as your bank account and payment card details.

Transaction data includes details about payments or communications to and from you and information about products and services you have purchased from us.

Technical data includes your internet protocol (IP) address, browser type and version, time zone setting and location, browser plug-in types and versions, operating system and platform and other technology on the devices you use to access this website.

Your profile includes information such as your username and password, purchases or orders made by you, your interests, preferences, feedback and survey responses.

Marketing data includes your preferences in receiving marketing from us; communication preferences; responses and actions in relation to your use of our services.

We may aggregate anonymous data such as statistical or demographic data for any purpose. Anonymous data is data that does not identify you as an individual. Aggregated data may be derived from your personal data but is not considered personal information in law because it does not reveal your identity.

For example, we may aggregate profile data to assess interest in a product or service.
However, if we combine or connect aggregated data with your personal information so that it can identify you in any way, we treat the combined data as personal information and it will be used in accordance with this privacy notice.

=== 3. Special Personal Information
Special personal information is data about your race or ethnicity, religious or philosophical beliefs, sex life, sexual orientation, political opinions, trade union membership, information about your health and genetic and biometric data.

It also includes information about criminal convictions and offences.

We do not collect any special personal information about you.

OR

We may collect special personal information about you if there is a lawful basis on which to do so.

=== 4. If You Do Not Provide Personal Information We Need
Where we need to collect personal data by law, or under the terms of a contract we have with you, and you fail to provide that data when requested, we may not be able to perform that contract. In that case, we may have to stop providing a service to you. If so, we will notify you of this at the time.

== The Bases Upon Which We Process Information About You

The law requires us to determine under which of six defined bases we process different categories of your personal information, and to notify you of the basis for each category.

If a basis on which we process your personal information is no longer relevant then we shall immediately stop processing your data.

If the basis changes then if required by law we shall notify you of the change and of any new basis under which we have determined that we can continue to process your information.


=== 5. Information We Process Because We Have a Contractual Obligation With You
When you create an account on our website, buy a product or service from us, or otherwise agree to our terms and conditions, a contract is formed between you and us.

In order to carry out our obligations under that contract we must process the information you give us. Some of this information may be personal information.

We may use it in order to:

* Verify your identity for security purposes.
* Sell products to you.
* Provide you with our services.
* Provide you with suggestions and advice on products, services and how to obtain the most from using our website.

We process this information on the basis there is a contract between us, or that you have requested we use the information before we enter into a legal contract.

We shall continue to process this information until the contract between us ends or is terminated by either party under the terms of the contract.

=== 6. Information We Process With Your Consent
Through certain actions when otherwise there is no contractual relationship between us, such as when you browse our website or ask us to provide you more information about our business, including [job opportunities and] our products and services, you provide your consent to us to process information that may be personal information.

Wherever possible, we aim to obtain your explicit consent to process this information, for example, by asking you to agree to our use of cookies.

If you have given us explicit permission to do so, we may from time to time pass your name and contact information to selected associates whom we consider may provide services or products you would find useful.

We continue to process your information on this basis until you withdraw your consent or it can be reasonably assumed that your consent no longer exists.

You may withdraw your consent at any time by instructing us dataprivacy@graviteesource.com. However, if you do so, you may not be able to use our website or our services further.

=== 7. Information We Process for the Purposes of Legitimate Interests
We may process information on the basis there is a legitimate interest, either to you or to us, of doing so.

Where we process your information on this basis, we do after having given careful consideration to:

* Whether the same objective could be achieved through other means.
* Whether processing (or not processing) might cause you harm.
* Whether you would expect us to process your data, and whether you would, in the round, consider it reasonable to do so.

For example, we may process your data on this basis for the purposes of:

* Record-keeping for the proper and necessary administration of Gravitee.
* Responding to unsolicited communication from you to which we believe you would expect a response.
* Protecting and asserting the legal rights of any party.
* Insuring against or obtaining professional advice that is required to manage Gravitee's risk.
* Protecting your interests where we believe we have a duty to do so.

=== 8. Information We Process Because We Have a Legal Obligation
Sometimes, we must process your information in order to comply with a statutory obligation.

For example, we may be required to give information to legal authorities if they so request or if they have the proper authorisation such as a search warrant or court order.

This may include your personal information.

== Specific Uses of Information You Provide to Us

=== 9. Information Provided on the Understanding That It Will Be Shared With A Third Party
Our website allows you to post information with a view to that information being read, copied, downloaded, or used by other people. Examples include, but are not limited to:

* Posting a message our forum.
* Tagging an image.
* Clicking on an icon next to another visitor’s message to convey your agreement, disagreement or thanks.

In posting personal information, it is up to you to satisfy yourself about the privacy level of every person who might use it.

We do not specifically use this information except to allow it to be displayed or shared.

We do store it, and we reserve a right to use it in the future in any way we decide.

Once your information enters the public domain, we have no control over what any individual third party may do with it. We accept no responsibility for their actions at any time.

Provided your request is reasonable and there is no legal basis for us to retain it, then at our discretion we may agree to your request to delete personal information that you have posted. You can make a request by contacting us at dataprivacy@graviteesource.com.

=== 10. Complaints Regarding Content on Our Website
We attempt to moderate user generated content, but we are not always able to do so as soon as that content is published.

If you complain about any of the content on our website, we shall investigate your complaint.
If we feel it is justified or if we believe the law requires us to do so, we shall remove the content while we investigate.

Free speech is a fundamental right, so we have to make a judgment as to whose right will be obstructed: yours, or that of the person who posted the content that offends you.

If we think your complaint is vexatious or without any basis, we shall not correspond with you about it.

=== 11. Information Relating to Your Method of Payment

First option:
We store information about your debit or credit card or other means of payment when you first provide it to us.

We store this payment information [at your request] in order to make repeat purchasing of goods and services easier next time you visit our website.

We also store it to help us prevent fraud.

We take the following measures to protect your payment information:

* We keep your payment information encrypted on our servers.

* We do not keep all your payment information so as:

a) to prevent the possibility of our duplicating a transaction without a new instruction from you;
b) to prevent any other third party from carrying out a transaction without your consent

* Access to your payment information is restricted to authorised staff only.

* If we ask you questions about your payment information, we only show [partial detail OR the first four OR the last four digits of the debit or credit card number], so that you can identify the means of payment to which we refer.

We automatically delete your payment information [after X days OR when a credit or debit card expires].

Second Option:
Payment information is never taken by us or transferred to us either through our website or otherwise. Our employees and contractors never have access to it.

At the point of payment, you are transferred to a secure page on the website of [WorldPay / SagePay / PayPal / MoneyBookers / Stripe] or some other reputable payment service provider. That page may be branded to look like a page on our website, but it is not controlled by us.

=== 12. Information About Your Direct Debit
When you agree to set up a direct debit arrangement, the information you give to us is passed to our own bank [name of bank] for processing according to our instructions. We [do / do not] keep a copy.

[We keep this information only for the duration of the direct debit arrangement.]

We are registered under the direct debit guarantee scheme. This provides for the customer's bank to refund disputed payments without question, pending further investigation. Direct debits can only be set up for payments to beneficiaries that are approved originators of direct debits. In order to be approved, these beneficiaries are subjected to careful vetting procedures. Once approved, they are required to give indemnity guarantees through their banks.

=== 13. Job Application & Employment
If you send us information in connection with a job application, we may keep it for up to three years in case we decide to contact you at a later date.

If we employ you, we collect information about you and your work from time to time throughout the period of your employment. This information will be used only for purposes directly relevant to your employment. After your employment has ended, we will keep your file for [six years] before destroying or deleting it.

=== 14. Communicating With Us
When you contact us, whether by telephone, through our website or by email, we collect the data you have given to us in order to reply with the information you need.

We record your request and our reply in order to increase the efficiency of our business.

We do not keep any personally identifiable information associated with your message, such as your name or email address.

OR

We keep personally identifiable information associated with your message, such as your name and email address so as to be able to track our communications with you to provide a high quality service.

=== 15. Complaining
When we receive a complaint, we record all the information you have given to us.

We use that information to resolve your complaint.

If your complaint reasonably requires us to contact some other person, we may decide to give to that other person some of the information contained in your complaint. We do this as infrequently as possible, but it is a matter for our sole discretion as to whether we do give information, and if we do, what that information is.

We may also compile statistics showing information obtained from this source to assess the level of service we provide, but not in a way that could identify you or any other person.

=== 16. Affiliate & Business Partner Information
This is information given to us by you in your capacity as an affiliate of us or as a business partner.

It allows us to recognise visitors that you have referred to us, and to credit to you commission due for such referrals. It also includes information that allows us to transfer commission to you.

The information is not used for any other purpose.

We undertake to preserve the confidentiality of the information and of the terms of our relationship.

We expect any affiliate or partner to agree to reciprocate this policy.

== Use of Information We Collect Through Automated Systems When You Visit Our Website

=== 17. Cookies
Cookies are small text files that are placed on your computer's hard drive by your web browser when you visit any website. They allow information gathered on one web page to be stored until it is needed for use on another, allowing a website to provide you with a personalised experience and the website owner with statistics about how you use the website so that it can be improved.

Some cookies may last for a defined period of time, such as one day or until you close your browser. Others last indefinitely.

Your web browser should allow you to delete any you choose. It also should allow you to prevent or limit their use.

Our website uses cookies. They are placed by software that operates on our servers, and by software operated by third parties whose services we use.

When you first visit our website, we ask you whether you wish us to use cookies. If you choose not to accept them, we shall not use them for your visit except to record that you have not consented to their use for any other purpose.

If you choose not to use cookies or you prevent their use through your browser settings, you will not be able to use all the functionality of our website.

We use cookies in the following ways:

 * To track how you use our website.
* To record whether you have seen specific messages we display on our website.
* To keep you signed in to our website.
* To record your answers to surveys and questionnaires on our site while you complete them.
* To record the conversation thread during a live chat with our support team.
[We provide more information about the cookies we use in our cookie policy].

=== 18. Personal Identifiers From Your Browsing Activity
Requests by your web browser to our servers for web pages and other content on our website are recorded.

We record information such as your geographical location, your Internet service provider and your IP address. We also record information about the software you are using to browse our website, such as the type of computer or device and the screen resolution.

We use this information in aggregate to assess the popularity of the webpages on our website and how we perform in providing content to you.

If combined with other information we know about you from previous visits, the data possibly could be used to identify you personally, even if you are not signed in to our website.

=== 19. Our Use of Re-marketing
Re-marketing involves placing a cookie on your computer when you browse our website in order to be able to serve to you an advert for our products or services when you visit some other website.

We may use a third party to provide us with re-marketing services from time to time. If so, then if you have consented to our use of cookies, you may see advertisements for our products and services on other websites.

== Disclosure & Sharing of Your Information

=== 20. Information We Obtain From Third Parties
Although we do not disclose your personal information to any third party (except as set out in this notice), we sometimes receive data that is indirectly made up from your personal information from third parties whose services we use.

No such information is personally identifiable to you.

=== 21. Third Party Advertising on Our Website
Third parties may advertise on our website. In doing so, those parties, their agents or other companies working for them may use technology that automatically collects information about you when their advertisement is displayed on our website.

They may also use other technology such as cookies or JavaScript to personalise the content of, and to measure the performance of their adverts.

We do not have control over these technologies or the data that these parties obtain. Accordingly, this privacy notice does not cover the information practices of these third parties.

=== 22. Credit Reference
To assist in combating fraud, we share information with credit reference agencies, so far as it relates to clients or customers who instruct their credit card issuer to cancel payment to us without having first provided an acceptable reason to us and given us the opportunity to refund their money.

=== 23. Data May Be Process Outside the European Union
Our websites are hosted in France.

We may also use outsourced services in countries outside the European Union from time to time in other aspects of our business.

Accordingly data obtained within the UK or any other country could be processed outside the European Union.

For example, some of the software our website uses may have been developed in the United States of America or in Australia.

We use the following safeguards with respect to data transferred outside the European Union:

* The processor is within the same corporate group as our business or organisation and abides by the same binding corporate rules regarding data processing.
* The data protection clauses in our contracts with data processors include transfer clauses written by or approved by a supervisory authority in the European Union.
* We comply with a code of conduct approved by a supervisory authority in the European Union.
* We are certified under an approved certification mechanism as provided for in the Act.
* Both our organisation and the processor are public authorities between whom there is either a legally binding agreement or administrative arrangements approved by a supervisory authority in the European Union relating to protection of your information.

== Control Over Your Own Information

=== 24. Your Duty to Inform Us of Changes
It is important that the personal data we hold about you is accurate and current. Please keep us informed if your personal data changes.

=== 25. Access to Your Personal Information
At any time you may review or update personally identifiable information that we hold about you, by signing in to your account on our website.

To obtain a copy of any information that is not provided on our website you should contact us to make that request.

After receiving the request, we will tell you when we expect to provide you with the information, and whether we require any fee for providing it to you.

=== 26. Removal of Your Information
If you wish us to remove personally identifiable information from our website, you should contact us to make your request.

This may limit the service we can provide to you.

=== 27. Verification of Your Information
When we receive any request to access, edit or delete personal identifiable information we shall first take reasonable steps to verify your identity before granting you access or otherwise taking any action. This is important to safeguard your information.

=== 28. Use of Site by Children
We do not sell products or provide services for purchase by children, nor do we market to children.

If you are under 18, you may use our website only with consent from a parent or guardian.

=== 29. How You Can Complain
If you are not happy with our privacy policy or if you have any complaint then you should tell us.

If a dispute is not settled then we hope you will agree to attempt to resolve it by engaging in good faith with us in a process of mediation or arbitration.

If you are in any way dissatisfied about how we process your personal information, you have a right to lodge a complaint with the Information Commissioner's Office (ICO). This can be done at https://ico.org.uk/make-a-complaint/. *We would, however, greatly appreciate the opportunity to talk to you about your concern before you approach the ICO.*

=== 30. Retention Period for Personal Data
Except as otherwise mentioned in this privacy notice, we keep your personal information only for as long as required by us:

* To provide you with the services you have requested;
* To comply with other law, including for the period demanded by our tax authorities;
* To support a claim or defence in court.

=== 32. Compliance With the Law
Our privacy policy has been compiled so as to comply with the law of every country or legal jurisdiction in which we aim to do business. If you think it fails to satisfy the law of your jurisdiction, we should like to hear from you.

However, ultimately it is your choice as to whether you wish to use our website.

=== 33. Review of This Privacy Policy
We may update this privacy notice from time to time as necessary. The terms that apply to you are those posted here on our website on the day you use our website. We advise you to print a copy for your records.

If you have any questions regarding our privacy policy, please contact us.
