= Reporters
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_reporters.html
:page-folder: am/installation-guide
:page-liquid:
:page-layout: am
:page-description: Gravitee.io Access Management - Reporters
:page-keywords: Gravitee.io, API Platform, API Management, Access Gateway, oauth2, openid, documentation, manual, guide, reference, api

== Overview

A *reporter* is used by gateway and management API instances to report many types of event:

* Administration metrics : administrative tasks (CRUD on resources)
* Authentication / Authorization metrics: (Sign-in activity, Sign-up activity)

By default, a default reporter is created using MongoDB or JDBC implementation according to the backend configured into the gravitee.yaml file.

Since AM 3.6, it is possible to create additional reporters. 

== File Reporter
 
This implementation is a "File" based reporter to write events into a dedicated file. It may be useful if you want to ingest event into a thirdparty system.

=== Configuration

File reporters are configurable into the gravitee.yaml file under the `reporter` section with the following properties:

|===
|property | type | required | description 

|directory
|string
|N
|Path to the directory where files will be created, this directory has to exist (default: ${gravitee.home}/audit-logs/)

|output
|string
|N
|Format used to export event. Possible values: JSON, MESSAGE_PACK, ELASTICSEARCH, CSV (default: JSON)
|===

[source,yaml]
----
reporters:
  file:
    #directory:  # directory where the files are created (this directory have to exist): default value = ${gravitee.home}/audit-logs/
    #output: JSON # JSON, ELASTICSEARCH, MESSAGE_PACK, CSV
----

NOTE: Audit logs will be created in a tree of directories that represent the resource hierarchy from the organization to the domain. For example, audit logs of the domain `my-domain` in the environment `dev` and organization `my-company` will be created into the tree of directories : ${reporters.file.directory}/my-company/dev/my-domain/audit-2021_02_11.json

WARNING: There are currently no retention period for the audit logs, so you will have to manage an independent process to remove old logs.

To create a file reporter for a domain, follow this link:/am/current/am_userguide_audit_log_file[documentation]

