= Repositories
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_repositories.html
:page-folder: am/installation-guide
:page-liquid:
:page-layout: am
:page-description: Gravitee.io Access Management - Repositories
:page-keywords: Gravitee.io, API Platform, API Management, Access Gateway, oauth2, openid, documentation, manual, guide, reference, api

== Overview

AM uses repositories to store different types of data (known as _scopes_).

You configure repositories in the `gravitee.yml` configuration file. The configuration can be different for each scope --
for example, you can use MongoDB for management, Redis for rate limiting and Elasticsearch for analytics.

AM supports the following repositories:

- link:am_installguide_repositories_mongodb.html[MongoDB repositories]
- link:am_installguide_repositories_jdbc.html[JDBC repositories] (new in Gravitee.io AM 3.4.x)

For information on how to install and configure the repositories, see the relevant configuration section.

[[gravitee-repositories-scopess]]
== Scopes

Examples of scopes are:

* Management: All the data needed to manage the Access Management platform, including security domains, clients,
identity providers, and so on
* OAuth2: Tokens generated for OAuth2

[[gravitee-repositories-types]]
== Supported storage
The following matrix shows the compatibility between scopes and implementations:

|===
|Scope|MongoDB|JDBC|Redis |Elasticsearch| Cassandra

|Management
|X
|X
|-
|-
|-

|OAuth2
|X
|X
|-
|-
|-

|===
