= Breaking changes in 3.21.6 / 3.20.11 / 3.19.17
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_breaking_changes_3.21.6.html
:page-folder: am/installation-guide
:page-layout: am

NOTE: To take advantage of these new features and incorporate these breaking changes, **use the migration guide available link:{{ '/am/current/am_installguide_migration.html' | relative_url }}[here]**.


=== Rename or Remove users with duplicate user name

We have introduced a unique constraint on the `username` field  in the **users** collection/table in AM version 3.21.6 / 3.20.11 / 3.19.17.
This constraint was necessary to fix the https://github.com/gravitee-io/issues/issues/9117[AM-680] bug to avoid users with the same user name within an identity provider (IDP).
Users with same user name are not active user and it is not possible to log in using these user's details.
As a result you may experience issues while upgrading AM from any previous version to 3.21.6 in case the **users** collection/table already has more than one user with the same user name in the `username` field.
For the relational database there could be a unique constraint error in the management API log and for the MongoDB the application may not start as MongoDB won't be able to apply the unique constraint due to duplicate data.
To start the application you will need to rename or delete the duplicate users from both the **users** collection/table  and the corresponding identity provider collection/table.

These are the steps you will take to delete the duplicate users:

* Run a query to find all the users with the duplicate user name from the **users** collection/table
* Rename or Delete these users from the corresponding identity provider collection/table
* Rename or Delete these users from the users collection/table

=== MongoDB

WARNING: These steps should be tested in a test environment first

A migration script is available https://github.com/gravitee-io/gravitee-access-management/tree/master/docs/upgrades/username_uniqueness/username_uniqueness.js[here] to help you. This script will identify duplicates and rename some of them according to the connection metadata for each profile (the mostly used profile will be considered as the reference and other will be renamed with a "_TO_RENAME_OR_DELETE" sufix).

For safety, this script define at the beginning a boolean *dryRun* set to *true* to only display the script output and see the action that will be applyed in case of duplicate. To effectively process the changes, you will have to define this variable to *false*;

We strongly recommend executing this script in a test environment first.
Backup the database before executing in the production environment.

NOTE: this script will generate a summary in JSON format about actions that has been applied

[source,bash]
----
  $>mongosh mongohostname:27017/gravitee-am /tmp/username_uniqueness.js | tee /tmp/script.out
----

=== Relational Database

WARNING: These steps should be tested in a test environment first

We strongly recommend executing the query in a test environment first.
Backup the database before executing in the production environment.
Also you need to update the query with the appropriate identity provider name.


Run the following **select** statement to identify data with duplicate user name.

[source,sql]
----
select id, u.username, u.source
from users u,
(select username, source
from (select username, source, count(username) as count
from users
group by source, username) as multiEntries
where multiEntries.count > 1) aa
where u.username = aa.username
and u.source = aa.source
----

Once confirmed, run the following query to delete entries from the IDP tables;

NOTE: IDP collection name start with `idp_users_` followed by a sequence of characters


=== Delete from Identity Provider Table(s)

Replace the IDP table(s) name and run the following query:

[source,sql]
----
delete
from idp_users_YOUR_IDP
where id in (select external_id
from users u
(select username, source
from (select username, source, count(username) as count
from users
group by source, username) as multiEntries
where multiEntries.count > 1) aa
where u.username = aa.username
and u.source = aa.source);
----


=== Delete from Users Table

Now delete data from the **users** table

[source,sql]
----
delete
from users
where id in (select id
from users u, -- remove username and source
(select username, source
from (select username, source, count(username) as count
from users
group by source, username) as multiEntries
where multiEntries.count > 1) aa
where u.username = aa.username
and u.source = aa.source);
----
