= Breaking changes in 3.10
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_breaking_changes_3.10.html
:page-folder: am/installation-guide
:page-layout: am

NOTE: For all these breaking changes, the Migration Guide can be found link:{{ '/am/current/am_installguide_migration.html' | relative_url }}[here].

WARNING: For JDBC users only please upgrade directly to the 3.10.1 minimum. See link:{{ '/am/current/am_installguide_migration.html#upgrade_to_3_10_0' | relative_url }}[here] for more details.

== Clients are removed

Starting from v3.0.0 `Clients` concept has been replaced by `Applications`. In this version, `Clients` endpoints have been removed.

----

  - http(s)://AM_MANAGEMENT_API/management/organization/DEFAULT/environment/DEFAULT/domains/:domainId/clients/**

----

== Users Management

Until now, the users collection/table contained users related both to domains and organizations. Starting from this version there is a dedicated collection/table to store users linked to an organization (ie.: users used to connect to the AM console). If you encounter authentication issue on the console, please make sure that you have followed the link:{{ '/am/current/am_installguide_migration.html' | relative_url }}[migration guide].
