= Breaking changes in 3.6
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_breaking_changes_3.6.html
:page-folder: am/installation-guide
:page-layout: am

NOTE: For all these breaking changes, the Migration Guide can be found link:{{ '/am/current/am_installguide_migration.html' | relative_url }}[here].

== AM Multi Environments introduced

In preparation for the upcoming Cockpit product offering (see link:https://www.gravitee.io/products/roadmap[Roadmap > Cockpit]), we have introduced two concepts:

* link:{{ '/am/current/am_adminguide_organizations_and_environments.html#organization' | relative_url }}[Organization]
* link:{{ '/am/current/am_adminguide_organizations_and_environments.html#environment' | relative_url }}[Environment]

To provide this new feature, new permissions have been created that requires the execution of database migration scripts. (see link:{{ '/am/current/am_installguide_migration.html' | relative_url }}[Migration Guide])

At the UI level, the *global settings* menu is now named *organization settings* and it is accessible at the bottom left corner of the console UI.
