= Breaking changes in 3.9
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_breaking_changes_3.9.html
:page-folder: am/installation-guide
:page-layout: am

NOTE: For all these breaking changes, the Migration Guide can be found link:{{ '/am/current/am_installguide_migration.html' | relative_url }}[here].

== Memory management

Starting from this new version, the default Xms and Xmx parameters has been fixed to 256m.
Previous value was too high and does not reflect real memory usage for both the Gateway and Management API.

If, for some reasons, you need to increase those default values, you can set the `GIO_MIN_MEM` and `GIO_MAX_MEM` environment variables in your scripts.
Those variables are then "injected" into the JAVA_OPTS during bootstrap.

== REST API

Starting from this new version, the response format has changed for the following resources :

* List Domains
* List Scopes
* List Roles

Instead of a simple list of data, a `Page` object is now returned with a list of resources with a default page size of 50 elements. This page object has the following structure :

```
{
	currentPage: 1
	totalCount: 10
	data: [ ... list of resources ... ]
}
```


