= Breaking changes in 3.12
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_breaking_changes_3.12.html
:page-folder: am/installation-guide
:page-layout: am

NOTE: To take advantage of these new features and incorporate these breaking changes, **use the migration guide available link:{{ '/am/current/am_installguide_migration.html' | relative_url }}[here]**.

== Management REST API: Application Scopes

Until now, the application OAuth settings contained multiple collections about scopes, such as:

* scopes: a list with all scopes authorized for the application.
* defaultScopes: a list of scopes added as default if the authorized request doesn't specify a list of scopes.
* scopeApprovals: a map to specify the amount of time (in seconds) that a scope is considered acceptable by the end user.

[source,json]
----
{
  "settings": {
    "oauth": {
      "scopes": [ "scope1", "openid"],
      "defaultScopes": [ "openid"],
      "scopeApprovals": { "opendid" : 3600}
    }
  }
}
----

Because more and more settings related to a scope exist, the OAuth settings for an application have to be refactored to provide a single list — `scopeSettings` — containing objects with scope settings. **This object has the following attribtues**:

* **scope**: the scope name.
* **defautlScope**: boolean to defined this scope as a default one if the authorize request doesn't specify a list of scopes.
* **scopeApproval**: the amount of time (in seconds) that a scope is considered as accepted per the end user.

[source,json]
----
{
  "settings": {
    "oauth": {
      "scopeSettings": [
        {"scope" : "scope1", "defaultScope" :true},
        {"scope" : "openid", "scopeApproval": 3600, "defaultScope" :true}]
    }
  }
}
----


If you are using the Management REST API directly, please make this change and adapt your application or scripts.
