ifdef::env-github[]
:mongodb-scripts-dir: /apim/3.x/mongodb
endif::[]

= Upgrade to 3.7.0

== Repository

NOTE: Since 3.7, you have the ability to configure a prefix for your tables or collections name.

Rate limit configuration has to be defined in both Gateway and Management `gravitee.yml` files.

With this centralized configuration, you can disable the liquibase phase of the gateway, if you do not want it to modify your dbms.

If you choose to use prefix, follow these instructions.

=== Mongodb

==== New installation

You just have to modify the `gravitee.yml` files of gateway and console to configure `management.mongodb.prefix` and `ratelimit.mongodb.prefix`. Default value is empty.

==== Migrate an existing installation

Before running any script, please create a dump of your existing database.

If you want to prefix your collections, you will have to rename them. You can use the following script.

Check documentation at https://docs.gravitee.io/apim/3.x/apim_installguide_repositories_mongodb.html

This script rename all the collections adding the `prefix` and `rateLimitPrefix`.

For the following steps, we admit you choose this prefix: prefix_

1. Modify `gravitee.yml` to configure `management.mongodb.prefix` and `ratelimit.mongodb.prefix` if needed.
2. Run the following script to rename your collections: link:{mongodb-scripts-dir}/3.7.0/1-rename-collections-with-prefix.js[]
3. Run your instances!

=== JDBC

==== New installation

You just have to modify the `gravitee.yml` files of gateway and console to configure `management.jdbc.prefix` and `ratelimit.jdbc.prefix`. Default value is empty.

==== Migrate an existing installation

Before running any script, please create a dump of your existing database.

If you want to prefix your tables, you will have to rename them.
Check documentation at https://docs.gravitee.io/apim/3.x/apim_installguide_repositories_jdbc.html

For the following steps, we admit you choose this prefix: prefix_

1. Modify `gravitee.yml` to configure `management.jdbc.prefix` and `ratelimit.jdbc.prefix` if needed.
2. Run the application on a new database to generate `prefix_databasechangelog`
3. Replace the content of `databasechangelog` table by the generated one from `prefix_databasechangelog`
4. Rename your tables following this syntax: prefix_tablename
5. Rename your indexes following this syntax: idx_prefix_indexname
6. Rename your primary keys following this syntax: pk_prefix_pkname
7. Run your instances!

