= Logout
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_userguide_user_session_management_logout.html
:page-folder: am/user-guide
:page-layout: am

== Invalidate session

Authenticated users who want to invalidate their session can call the following URL: `https://AM_GATEWAY_HOST/{domain}/logout`

NOTE: By default, access tokens and refresh tokens are not revoked. You can add the `invalidate_tokens=true` query parameter to the request to invalidate current user tokens.

== Redirect users after logout

You can specify the `post_logout_redirect_uri=http://myApp/logoutCallback` or `target_url=http://myApp/logoutCallback` query parameter to redirect the user to your application after logout.

NOTE: You can define list of allowed URLs where the user will be redirected after being sign out. It prevents some vulnerabilities like being redirected to unsafe websites.

== Single logout

[label label-version]#New in version 3.10#

Single logout let your end users sign out of both their Gravitee.io AM session and the social identity provider (configured in your application) with a single action.

To enable single logout feature :

. link:{{ '/am/current/am_userguide_authentication.html' | relative_url }}[Log in to AM Console^].
. Select your application and click *Settings > General*.
. Switch on *Single Sign Out* and click *SAVE*.

Call the default logout endpoint and your users will be logout at both places.

=== Limitations

Currently only the following identity providers are compatible with the Single Sign Out feature :

- Certified OpenID Connect provider
- Azure AD

