= Docker Compose
:page-toc: false
:page-sidebar: apim_1_x_sidebar
:page-permalink: apim/1.x/apim_installguide_docker_compose.html
:page-folder: apim/installation-guide/docker
:page-layout: apim
:docker-image-src: https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/images
:github-repo: https://github.com/gravitee-io/gravitee-docker
:docker-hub: https://hub.docker.com/r/graviteeio

IMPORTANT: We assume that you are familiar with Docker. +
To run our official images, you must start by installing https://docs.docker.com/installation/[Docker]

Gravitee.io docker images are https://hub.docker.com/u/graviteeio/[available on Docker Hub].
You could find all https://github.com/gravitee-io/gravitee-docker/[Dockerfiles on GitHub].

== Docker Compose

You can launch a complete demo environment using our ready-to-use docker-compose file. It includes Gravitee.io API Management + MongoDB + Elasticsearch.

WARNING: Before running the commands below, make sure you have the minimum vm.max_map_count property set in order to run Elasticsearch. https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html[Click here] to see how to check the current value and update if necessary.

[source, shell]
....
# Download compose files
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/common.yml -o "common.yml"
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/docker-compose-local.yml -o "docker-compose-local.yml"

# (Optional step: pull to ensure that you are running latest images)
$ docker-compose -f docker-compose-local.yml pull

# And run...
$ docker-compose -f docker-compose-local.yml up
....

When all components are started, you can do a quick test to see if everything is ok by checking these urls:
|===
|Image |Address

|{docker-hub}/gateway/[graviteeio/gateway]
|http://localhost:8000

|{docker-hub}/management-api/[graviteeio/management-api]
|http://localhost:8005/management/

|{docker-hub}/management-ui/[graviteeio/management-ui]
|http://localhost:8002

|===

Once done, you're now ready to play with Gravitee.io API Management, so let's take a look to the <<gravitee-quickstart, Quickstart guide>>.
