= Configure Gravitee.io RPM Repository
:page-sidebar: apim_1_x_sidebar
:page-permalink: apim/1.x/apim_installguide_rpm_repository.html
:page-folder: apim/installation-guide/rpm/repository
:page-liquid:
:page-layout: apim
:page-description: Gravitee.io API Management - RPM - Repository
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

The RPMs for Gravitee.io API Management can be downloaded from our link:#installing_from_the_rpm_repository[RPM repository].
It can be used to install Gravitee.io API Management stack or each component individually on any RPM-based system such as OpenSuSE, SLES, CentOS, Red Hat, and Oracle Enterprise.

NOTE: RPM install is not supported on distributions with old versions of RPM, such as SLES 11 and CentOS 5. Please see link:/apim/1.x/apim_installguide_gateway_install_zip.html[Install Gravitee.io API Management with .zip] instead.

== Set up YUM repository
First, some packages are required to handle GPG signatures of our RPM packages:

[source,bash]
----
sudo yum install pygpgme yum-utils
----

== Create Gravitee.io repository configuration
Create a file called graviteeio.repo in the `/etc/yum.repos.d/` directory for RedHat based distributions, or in the `/etc/zypp/repos.d/` directory for OpenSuSE based distributions, containing:

[source,bash]
----
[graviteeio]
name=graviteeio
baseurl=https://packagecloud.io/graviteeio/rpms/el/7/$basearch
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/graviteeio/rpms/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
----

Before going ahead, you may to refresh your local cache.

[source,bash]
----
sudo yum -q makecache -y --disablerepo='*' --enablerepo='graviteeio'
----

Your repository is now ready for use. You can now choose to install Gravitee.io API Management in a single step, or
install components individually:

* link:/apim/1.x/apim_installguide_stack_install_rpm[Install API Management]
* link:/apim/1.x/apim_installguide_gateway_install_rpm[Install API Gateway]
* link:/apim/1.x/apim_installguide_management_api_install_rpm[Install Management API]
* link:/apim/1.x/apim_installguide_portal_install_rpm[Install Portal]