= Install Management API with RPM
:page-sidebar: apim_1_x_sidebar
:page-permalink: apim/1.x/apim_installguide_management_api_install_rpm.html
:page-folder: apim/installation-guide/rpm/management-api
:page-liquid:
:page-layout: apim
:page-description: Gravitee.io API Management - Management API - Installation with RPM
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

== Installing from the RPM repository

IMPORTANT: We assume that you have configured your RPM repository by following link:/apim/1.x/apim_installguide_rpm_repository.html[this documentation].

You can install Gravitee.io Management API with one of the following commands (depending on your system):

[source,bash]
----
sudo yum install graviteeio-apim-management-api
sudo dnf install graviteeio-apim-management-api
sudo zypper install graviteeio-apim-management-api
----

== Download and install the RPM manually

[source,bash]
----
wget --content-disposition https://packagecloud.io/graviteeio/rpms/packages/el/7/graviteeio-apim-management-api-{{ site.products.apim.version }}-0.noarch.rpm/download.rpm
sudo rpm --install graviteeio-apim-management-api-{{ site.products.apim.version }}-0.noarch.rpm
----

== Running Gravitee.io Management API with `systemd`

To configure Gravitee.io Management API to start automatically when the system boots up, run the following commands:

[source,shell]
----
sudo systemctl daemon-reload
sudo systemctl enable graviteeio-apim-management-api
----

Gravitee.io Management API can be started and stopped as follows:

[source,shell]
----
sudo systemctl start graviteeio-apim-management-api
sudo systemctl stop graviteeio-apim-management-api
----

These commands provide no feedback as to whether Gravitee.io Management API was started successfully or not.
Instead, this information will be written in the log files located in `/opt/graviteeio/apim/management-api/logs/`.

When `systemd` logging is enabled, the logging information are available using the `journalctl` commands:

To tail the journal:

[source,shell]
----
sudo journalctl -f
----

To list journal entries for the Gravitee.io Management API service:

[source,shell]
----
sudo journalctl --unit graviteeio-apim-management-api
----

To list journal entries for the Gravitee.io Management API service starting from a given time:

[source,shell]
----
sudo journalctl --unit graviteeio-apim-management-api --since  "2020-01-30 12:13:14"
----