= Install API Gateway with RPM
:page-sidebar: apim_1_x_sidebar
:page-permalink: apim/1.x/apim_installguide_gateway_install_rpm.html
:page-folder: apim/installation-guide/rpm/gateway
:page-liquid:
:page-layout: apim
:page-description: Gravitee.io API Management - Gateway - Installation with RPM
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

== Installing from the RPM repository

IMPORTANT: We assume that you have configured your RPM repository by following link:/apim/1.x/apim_installguide_rpm_repository.html[this documentation].

You can install Gravitee.io API Gateway with one of the following commands (depending on your system):

[source,bash]
----
sudo yum install graviteeio-apim-gateway
sudo dnf install graviteeio-apim-gateway
sudo zypper install graviteeio-apim-gateway
----

== Download and install the RPM manually

[source,bash]
----
wget --content-disposition https://packagecloud.io/graviteeio/rpms/packages/el/7/graviteeio-apim-gateway-{{ site.products.apim.version }}-0.noarch.rpm/download.rpm
sudo rpm --install graviteeio-apim-gateway-{{ site.products.apim.version }}-0.noarch.rpm
----

== Running Gravitee.io API Gateway with `systemd`

To configure Gravitee.io API Gateway to start automatically when the system boots up, run the following commands:

[source,shell]
----
sudo systemctl daemon-reload
sudo systemctl enable graviteeio-apim-gateway
----

Gravitee.io API Gateway can be started and stopped as follows:

[source,shell]
----
sudo systemctl start graviteeio-apim-gateway
sudo systemctl stop graviteeio-apim-gateway
----

These commands provide no feedback as to whether Gravitee.io API Gateway was started successfully or not.
Instead, this information will be written in the log files located in `/opt/graviteeio/apim/gateway/logs/`.

When `systemd` logging is enabled, the logging information are available using the `journalctl` commands:

To tail the journal:

[source,shell]
----
sudo journalctl -f
----

To list journal entries for the Gravitee.io API Gateway service:

[source,shell]
----
sudo journalctl --unit graviteeio-apim-gateway
----

To list journal entries for the Gravitee.io API Gateway service starting from a given time:

[source,shell]
----
sudo journalctl --unit graviteeio-apim-gateway --since  "2020-01-30 12:13:14"
----