= Silent re-authentication
:page-toc: false

[label label-version]#New in version 3.10#

To reduce authentication problems from third parties that can't maintain sessions with AM, you can use the OpenID Connect ID Token to request new tokens silently.

To trigger silent re-authentication, your application must call the link:/Guides/AM/current/developer-guide/protocols/oauth2/introduction.html#authorization_code[authorization endpoint^] with the following parameters:

- *id_token_hint*: ID Token previously issued by the Authorization Server passed as a hint about the end user's current or past authenticated session with the application.
- *prompt*: the value must be `none` to disable interactive login flow.

If the ID token is valid, the end user is (re)connected and AM responds with an authorization code, otherwise a `login_required` error is sent to your application.

To enable silent re-authentication:

. In AM Console, click *Applications* and select your application.
. Click *Settings > General*.
. Enable *Silent re-authentication* and click *SAVE*.
