= Bootstrap your dev environment
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_devguide_bootstrap.html
:page-folder: am/dev-guide/bootstrap
:page-toc: false

== Overview

This page explains how to set up your environment to start contributing to AM.

== Prerequisites

You will need the following tools on your computer:

* Java (JDK >= 11)
* Maven
* Docker
* NPM (preferably NVM)

== Download the AM image

Download the latest AM full distribution available: https://download.gravitee.io/graviteeio-am/distributions/graviteeio-am-full-{{ site.products.am.version }}.zip.
Unzip it into the directory of your choice. You will need these files later on to copy plugins into your local repository.

== Projects to clone

Clone the following repositories in your workspace

* https://github.com/gravitee-io/graviteeio-access-management

If you are using IntelliJ, create a new project from existing sources and select your `graviteeio-access-management` folder.

== Prepare for launch

We will run AM Gateway standalone using a *Run configuration* in IntelliJ.

You first need to copy all the plugins in the distribution you downloaded earlier to the `/resources` directory of the standalone project.

For instance if your download is in the `Downloads` folder and your project is in `~/dev/gravitee-am-gateway`, run:

```
cp ~/Downloads/graviteeio-am-full-{{ site.products.am.version }}/graviteeio-am-gateway-{{ site.products.am.version }}/plugins/* ~/dev/gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/plugins
```

Repeat the previous step for `gravitee-am-management-rest-api`:
```
cp ~/Downloads/graviteeio-am-full-{{ site.products.am.version }}/graviteeio-am-management-api-{{ site.products.am.version }}/plugins/* ~/dev/gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/plugins
```

=== Run prerequisites

Before starting the AM Gateway, you need to start Mongo.

* Mongo:

```
docker run -p 27017:27017 --name local-mongo -d mongo:3
```

=== Run configuration

==== AM Gateway

Create a new Run configuration in IntelliJ:

. Click *Run -> Edit configurations -> + -> Application*.
. Name it as required.
. Choose *Use classpath of module*: `gravitee-am-gateway-standalone-container`.
. Select *Main class*: `io.gravitee.am.gateway.container.GatewayContainer`.
. In the VM options, add the following (change the path to point to your project):
```
-Dgravitee.home=/home/user/dev/gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources
```

==== AM API

Repeat the steps above for `gravitee-management-rest-api`.

==== AM Console

Run `npm install` from the `gravitee-am-ui` directory.

Then run `npm run start` to start AM Console.
