[[gravitee-admin-guide-orgs-and-envs]]
= Organizations and environments
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_adminguide_organizations_and_environments.html
:page-folder: apim/user-guide/admin
:page-description: Gravitee.io API Management - Admin Guide - Organizations and Environments
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

== Overview
In preparation for the upcoming Cockpit product offering (see link:https://www.gravitee.io/products/roadmap[Roadmap > Cockpit]), we have introduced two concepts:

== Environment
An _environment_ is roughly equivalent to what you can find in APIM Portal. In an environment, users can manage their APIs, applications and subscriptions. +
An environment handles its own categories, groups, documentation pages and quality rules. +

Some examples of environments you can define are:

* technical environments, such as DEV / TEST / PRODUCTION
* functional environments, such as PRIVATE APIS / PUBLIC APIS / PARTNERSHIP

An environment belongs to one organization.

=== Updating environment settings

You can update a Gateway's environment settings in APIM Console by clicking **Settings** in the left-hand navigation.

== Organization
An _organization_ allows users to customize APIM to their own internal organization. It can manage multiple environments by sharing configurations like:

* Users
* Roles
* Identity providers
* Notification templates

It also allows operations across managed environments (like API import/export).

=== Updating organization settings

You can update a Gateway's organization settings in APIM Console by clicking **Organization settings** in the left-hand navigation.

WARNING: The descriptions above may change slightly in future versions. Stay informed by subscribing to our link:https://gravitee.io/[newsletter].

NOTE: By default, the OSS version of APIM comes with a default organization and a default environment. For a multi-environment setup, you need APIM link:/ee/ee_introduction.html[Enterprise Edition].
