= Monitor with Prometheus
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_monitoring_prometheus.html
:page-folder: am/installation-guide/monitoring
:page-toc: true
:page-layout: am

== Prometheus

Prometheus is an open-source systems monitoring and alerting toolkit.
Prometheus collects and stores its metrics as time series data, i.e. metrics information is stored with the timestamp at which it was recorded, alongside optional key-value pairs called labels.

NOTE: For more elaborate overviews of Prometheus and how to install it please visit the https://prometheus.io/[official website,role=external,window=_blank].

=== Enable the metrics service

You can enable the metrics service in the `gravitee.yml` configuration file.
Prometheus support is activated and exposed using the internal API of the link:{{ '/am/current/am_installguide_gateway_technical_api.html' | relative_url }}[Gateway] and link:{{ '/am/current/am_installguide_management_api_technical_api.html' | relative_url }}[Management] components.

[source,yaml]
----
services:
  metrics:
    enabled: true
    prometheus:
      enabled: true
----

WARNING: By default, the internal API is bound to `localhost` only, so it must not be invoked outside `localhost`.
If you need to expose the API more widely, you may need to set the `services.core.http.host` property to the correct network interface.
If you are running the application in a Docker container, set the IP to the IP address of the container.
Each change requires a restart.

=== Configure labels
Labels are used to provide dimensionality to a metric. For instance, metrics related to a http request have a `http_path` label, which allows then to query timeseries for a specific path, or any other operation on timeseries.

You can specify which labels you want in the configuration file:
[source,yaml]
----
services:
  metrics:
    enabled: true
    labels:
      - local
      - remote
      - http_method
      - http_code
      - http_path
    prometheus:
      enabled: true
----

The list of available labels can be found here: https://vertx.io/docs/apidocs/io/vertx/micrometer/Label.html[Label]

WARNING: Enabling labels may result in a high cardinality in values, which can cause issues on the metrics backend (i.e. the gateway) and affect performance.
So it must be used with care. In general, it is fine to enable labels when the set of possible values are bounded.

Default values are `local`, `http_method` and `http_code`.

NOTE: Starting from the version 3.10.0, Gravitee AM uses Vert.x 4 and the metrics labels have been renamed.
We have introduced a new field in prometheus configuration that you can configure to use old Vert.x 3 label names.
Set it to 3.10, to use old labels.

[source,yaml]
----
services:
  metrics:
    prometheus:
      naming:
        version: 3.10
----

=== Prometheus configuration

The following example use the metrics provided by the link:{{ '/am/current/am_installguide_gateway_technical_api.html' | relative_url }}[AM Gateway internal API] and the link:{{ '/am/current/am_installguide_management_api_technical_api.html' | relative_url }}[AM Management internal API].

NOTE: Find the complete available metrics list in the next section.

The default port is :

* 18092 for the AM Gateway
* 18093 for the AM Management API

.Scrape Management API metrics
[source,yaml]
----
scrape_configs:
  - job_name: 'gio-am-mngt'
    basic_auth:
      username: admin
      password: adminadmin
    metrics_path: /_node/metrics/prometheus
    static_configs:
      - targets: ['localhost:18093']
----

.Scrape Gateway metrics
[source,yaml]
----
scrape_configs:
  - job_name: 'gio-am-gw'
    basic_auth:
      username: admin
      password: adminadmin
    metrics_path: /_node/metrics/prometheus
    static_configs:
      - targets: ['localhost:18092']
----

== Available metrics

[label label-version]#New in version 3.18#

This section lists and describes available metrics specific to Access Management.

There are three types of metrics:

* **Counter**: reports a count over a specified property of an application
* **Gauge**: only reports data when observed
* **Timer**: measure latencies or frequency of events in the system

=== Access Management

This section describes metrics that are provided by the Management API and the Gateway.

.Access Management metrics
|===
|Metrics|Type|Description

|gio_events_sync
|Gauge
|Number of events to process by the synchronization servide.

|gio_apps
|Gauge
|Number of applications managed by the gateway

|gio_app_evt_total
|Counter
|Number of events (Create, Update, Delete) regarding applications received by the gateway

|gio_domains
|Gauge
|Number of domains managed by the gateway

|gio_domain_evt_total
|Counter
|Number of events (Create, Update, Delete) regarding domains received by the gateway

|gio_idps
|Gauge
|Number of identity providers managed by the gateway

|gio_idp_evt_total
|Counter
|Number of events (Create, Update, Delete) regarding identity providers received by the gateway

|gio_auth_evt_total
|Counter
|Global number of events (Create, Update, Delete) received by the gateway

|===

.HTTP Server Metrics
|===
|Metrics|Type|Description

|http_server_active_connections
|Gauge
|Number of opened connections to the HTTP Server.

|http_server_request_bytes_max
|Gauge
|Size of requests in bytes

|http_server_request_bytes_sum
|Counter
|Total sum of observations for http_server_request_bytes_max

|http_server_request_bytes_count
|Counter
|Number of observations for http_server_request_bytes_max

|http_server_requests_total
|Counter
|Number of processed requests

|http_server_active_requests
|Gauge
|Number of requests being processed

|http_server_response_bytes_max
|Gauge
|Size of responses in bytes

|http_server_response_bytes_sum
|Counter
|Total sum of observations for http_server_response_bytes_max

|http_server_response_bytes_count
|Counter
|Number of observations for http_server_response_bytes_max

|http_server_response_time_seconds_max
|Gauge
|Response processing time

|http_server_response_time_seconds_sum
|Counter
|Total sum of observations for http_server_response_time_seconds_max

|http_server_response_time_seconds_count
|Counter
|Number of observations for http_server_response_time_seconds_max

|===

NOTE: In addition of these metrics, JVM metrics about GC, Heap and Threads are available and prefixed by `jvm_`.

=== Backend

AM can rely on MongoDB or a RDBMS (Postgres, MySQL, MariaDB or SQLServer) to persist data.
AM will provide metrics about connection pool for this system.

==== MongoDB

.MongoDB connection pool metrics
|===
|Metrics|Type|Description

|mongodb_driver_pool_checkedout
|Gauge
|Number of connections that are currently in use

|mongodb_driver_pool_size
|Gauge
|Current size of the Connections Pool

|mongodb_driver_pool_waitingqueuesize
|Gauge
|Size of the wait queue for a connection

|===

==== RDBMS

.R2DBC connection pool metrics
|===
|Metrics|Type|Description

|r2dbc_pool_acquiredSize
|Gauge
|Number of connections that are currently in use

|r2dbc_pool_allocatedSize
|Gauge
|Current size of the Connections Pool

|r2dbc_pool_pendingAcquireSize
|Gauge
|Size of the wait queue for a connection

|r2dbc_pool_idleSize
|Gauge
|Number of connections that are currently idle

|r2dbc_pool_maxAllocatedSize
|Gauge
|Maximum number of allocated connections

|===
