[[gravitee-cockpit-installation-idp-github]]
= Configure a Github identity provider
:page-sidebar: cockpit_sidebar
:page-permalink: cockpit/3.x/cockpit_installguide_idp_github.html
:page-folder: cockpit/installation-guide/idp
:page-description: Gravitee.io Cockpit - Identity Provider - Github
:page-keywords: Gravitee.io, API Platform, API Management, Cockpit, documentation, manual, guide, reference, api, idp, github

== Overview

This page explains how to configure Cockpit for https://github.com/[GitHub^] account login.

== Create a GitHub OAuth application

Before you can connect to Cockpit using a GitHub account, you need to create a GitHub application to link to Cockpit.

=== Create a new GitHub application

. Go to https://github.com/settings/developers.
. Click *OAuth Apps*.
. Click *New OAuth App*.
. Enter the application details. Authorization URL should follow this pattern: http://localhost:8063/auth/login/callback?provider=github
+
WARNING: The `Authorization callback URL` must exactly match the domain hosting Cockpit.
. Click *Register application*.
. Save client ID and Secret.

== Configure Cockpit

In `gravitee.yml` file, uncomment the following lines

[source,yaml]
----
auth:
  github:
    userAutorizationUri: https://github.com/login/oauth/authorize
    accessTokenUri: https://github.com/login/oauth/access_token
    userProfileUri: https://api.github.com/user
    codeParameter: code
    responseType: code
    clientId: <your client ID goes here>
    clientSecret: <your client secret goes here>
    redirectUri: http://localhost:8063/auth/login/callback?provider=github
    scopes:
    http:
      connectionTimeout: 10000
      maxTotalConnection: 10
----

WARNING: The `redirectUri` must exactly match the domain hosting Cockpit.

=== Disable the Github identity provider plugin

To disable the plugin you can add the following environment variable in your configuration.

[source,properties]
----
gravitee_identity_provider_cockpit-idp-github_enabled=false
----
