= Install Rest APIs
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_rest_apis_install_zip.html
:page-folder: apim/installation-guide/with-zip
:page-liquid:
:page-description: Gravitee.io API Management - Management API - Installation with .zip
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

This page explains how to install the two APIM REST APIs:

* Management API
* Portal API

NOTE: You must install each REST API first before you can use its corresponding UI.

== Prerequisites

Your environment must meet the requirements listed below before you install the REST APIs.

=== JDK

The REST APIs require at least Java 11. Before you install them, check your Java version as follows:

[source,bash]
----
java -version
echo $JAVA_HOME
----

NOTE: You can download the latest OpenJDK from https://jdk.java.net/archive/[OpenJDK Download Site].

=== MongoDB and Elasticsearch

The default REST API distribution requires link:/apim/3.x/apim_installguide_repositories_mongodb.html[MongoDB] to store mandatory data and link:/apim/3.x/apim_installguide_repositories_elasticsearch.html[Elasticsearch] to store reporting data.

NOTE: You can download MongoDB from the https://www.mongodb.org/downloads#production[MongoDB download site]
and Elasticsearch from the https://www.elastic.co/downloads/elasticsearch[Elasticsearch download site]

== Download and extract the `.zip` archive

Note that the archive includes the binaries for all the APIM components, so if you previously downloaded it to install another component, you do not need to download it again.

. Download the binaries https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip[here] or from the https://gravitee.io/downloads/api-management[Gravitee downloads page].

[source,bash]
----
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip -o gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

[start=2]
. Extract the `graviteeio-rest-api-xxx` directory from the archive and place it in the required location.

[source,bash]
----
$ unzip gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

== Run the Rest APIs from the command line

Management API and Portal API can be started together from the command line as follows:

[source,bash]
----
$ cd graviteeio-rest-api-{{ site.products.apim._3x.version }}
$ ./bin/gravitee
----

By default, Management API and Portal API run in the foreground, print their logs to standard output (stdout), and can be stopped
by pressing **Ctrl-C**.

NOTE: Both APIs are launched with this command. You can configure which APIs are to be launched. See link:/apim/3.x/apim_installguide_rest_apis_configuration.html[Rest APIs > Configuration] for more information.

Once the APIs are running, you will see this log:

[source,bash]
[subs="attributes"]
...
11:01:53.162 [main] INFO  i.g.r.a.s.node.GraviteeApisNode - Gravitee.io - Rest APIs id[2e05c0fa-8e48-4ddc-85c0-fa8e48bddc11] version[{{ site.products.apim._3x.version }}] pid[24930] build[175] jvm[AdoptOpenJDK/OpenJDK 64-Bit Server VM/12.0.1+12] started in 8042 ms.
...

== Check Management API is running

You can test that your Management API node is running by sending an HTTP request to port `8083` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis
----

You will receive a response something like this:

[source,json]
----
[]
----

== Check Portal API is running

You can test that your Portal API node is running by sending an HTTP request to port `8083` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8083/portal/environments/DEFAULT/apis
----

You will receive a response something like this:

[source,json]
----
{
  "data" : [ ],
  "metadata" : {
    "data" : {
      "total" : 0
    }
  }
}
----

== Run the REST APIs as a daemon

To run the Rest APIs as a daemon, specify `-d` on the command line and record the process ID in a file using option `-p`:

[source,bash]
----
$ ./bin/gravitee -d -p=/var/run/gio.pid
----

You can find log messages in the `$GRAVITEE_HOME/logs/` directory.

To shut down the REST APIs, kill the process ID recorded in the `pid` file:

[source,bash]
----
$ kill `cat /var/run/gio.pid`
----

== REST API directory structure

The `.zip` and (`.tar.gz`) package is entirely self-contained. All files and directories are, by default, contained within
`$GRAVITEE_HOME`, the directory created when extracting the archive.

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Location  |Description
|bin       |Binary scripts including `gravitee` to start a node
|config    |Configuration files including `gravitee.yml`
|lib       |Libraries (Gravitee.io libraries and third party libraries)
|logs      |Log file location
|plugins   |Plugin file location
|data      |Search engine metadata
|templates |API templates
|======================
