= Install Management UI with `.zip`
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_management_ui_install_zip.html
:page-folder: apim/installation-guide/with-zip
:page-liquid:
:page-description: Gravitee.io API Management - Management UI - Installation with .zip
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

== System Requirements

=== Browsers

Management UI has been tested with the latest versions of Google Chrome, Firefox and Internet Explorer >= 10

== Installing from the ZIP archive

The binaries are available from https://gravitee.io/downloads/api-management[Downloads page, window=\"_blank\"] or via https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip[Download, window=\"_blank\"].

[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip -o gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip

Once file has been downloaded, you just have to unpack it in the right place

[source,bash]
[subs="attributes"]
$ unzip gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip

=== Deploy

The Management UI is a client-side only AngularJS application and can be deployed on any HTTP server like https://httpd.apache.org/[Apache, window=\"_blank\"] or http://nginx.org/[Nginx, window=\"_blank\"].

=== or Run it

With Python::

[source,bash]
[subs="attributes"]
$ cd graviteeio-management-ui-{{ site.products.apim._3x.version }}
$ python3 -m http.server
$ Serving HTTP on 0.0.0.0 port 8000 ...

With Node::

[source,bash]
[subs="attributes"]
$ npm install http-server -g
$ cd graviteeio-management-ui-{{ site.products.apim._3x.version }}
$ http-server