= Install Rest APIs with `.zip`
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_rest_apis_install_zip.html
:page-folder: apim/installation-guide/with-zip
:page-liquid:
:page-description: Gravitee.io API Management - Management API - Installation with .zip
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

== System Requirements

=== JDK

Rest APIs require at least Java 11. Before you install them, please check your Java version :

[source,bash]
----
java -version
echo $JAVA_HOME
----

NOTE: You can download the latest OpenJDK from https://jdk.java.net/archive/[OpenJDK Download Site].

=== Datastore

Default Gravitee.io Rest APIs distribution requires MongoDB to store mandatory data and ElasticSearch to store reporting data.

NOTE: You can download MongoDB from https://www.mongodb.org/downloads#production[MongoDB Download Site]
and download Elasticsearch from https://www.elastic.co/downloads/elasticsearch[Elastic Download Site]

== Download and install the +.zip+ package

The binaries are available from https://gravitee.io/downloads/api-management[Downloads page] or via https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip[Download].

[source,bash]
----
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip -o gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

Once file has been downloaded, you just have to unpack it in the right place

[source,bash]
----
$ unzip gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

== Running Rest APIs from the command line

Management API and Portal API can be started together from the command line as follows:

[source,bash]
----
$ cd graviteeio-rest-api-{{ site.products.apim._3x.version }}
$ ./bin/gravitee
----

By default, Management API and Portal API run in the foreground, prints their logs to the standard output (stdout), and can be stopped
by pressing Ctrl-C.

NOTE: Both APIs are launched with this command. You can configure which APIs has to be launched link:/apim/3.x/apim_installguide_rest_apis_configuration.html[Rest APIs > Configuration] .

If everything goes well, you should see this log:

[source,bash]
[subs="attributes"]
...
11:01:53.162 [main] INFO  i.g.r.a.s.node.GraviteeApisNode - Gravitee.io - Rest APIs id[2e05c0fa-8e48-4ddc-85c0-fa8e48bddc11] version[{{ site.products.apim._3x.version }}] pid[24930] build[175] jvm[AdoptOpenJDK/OpenJDK 64-Bit Server VM/12.0.1+12] started in 8042 ms.
...

== Checking that Management API is running

You can test that your Management API node is running by sending an HTTP request to port `8083` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis
----

which should give you a response something like this:

[source,json]
----
[]
----

== Checking that Portal API is running

You can test that your Portal API node is running by sending an HTTP request to port `8083` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8083/portal/environments/DEFAULT/apis
----

which should give you a response something like this:

[source,json]
----
[]
----

== Running as a daemon

To run Rest APIs as a daemon, specify -d on the command line, and record the process ID in a file using the -p option:

[source,bash]
----
$ ./bin/gravitee -d -p=/var/run/gio.pid
----

Log messages can be found in the `$GRAVITEE_HOME/logs/` directory.

To shut down Rest APIs, kill the process ID recorded in the pid file:

[source,bash]
----
$ kill `cat /var/run/gio.pid`
----

== Directory layout of .zip archive

The .zip and .tar.gz packages are entirely self-contained. All files and directories are, by default, contained within
$GRAVITEE_HOME — the directory created when unpacking the archive.

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Location  |Description
|bin       |Binary scripts including `gravitee` to start a node
|config    |Configuration files including `gravitee.yml`
|lib       |Libraries (gravitee.io libraries and third parties library)
|logs      |Log files location.
|plugins   |Plugin files location.
|data      |Search engine metadata.
|======================

