= Install API Gateway with `.zip`
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_gateway_install_zip.html
:page-folder: apim/installation-guide/with-zip
:page-liquid:
:page-layout: apim3x
:page-description: Gravitee.io API Management - Gateway - Installation with .zip
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

This page explains how to install API Gateway from a `.zip` archive downloaded from the Gravitee download site. You can find details of the archive directory structure at the bottom of the page.

== System requirements

=== JDK

API Gateway requires at least Java 11. Before you install it, check your Java version as follows:

[source,bash]
----
$ java -version
$ echo $JAVA_HOME
----

NOTE: You can download the latest OpenJDK from the https://jdk.java.net/archive/[OpenJDK Download Site, window=\"_blank\"].

=== MongoDB and Elasticsearch

Default API Gateway distribution requires link:/apim/3.x/apim_installguide_repositories_mongodb.html[MongoDB, window=\"_blank\"] to poll environment configuration and link:/apim/3.x/apim_installguide_repositories_elasticsearch.html[Elasticsearch, window=\"_blank\"] for
reporting / analytics. Refer to the respective documentation page for supported versions.

NOTE: You can download MongoDB from https://www.mongodb.org/downloads#production[MongoDB Download Site, window=\"_blank\"]
and Elasticsearch from https://www.elastic.co/downloads/elasticsearch[Elastic Download Site, window=\"_blank\"]

== Download and extract the `.zip` archive

You can download the binaries https://gravitee.io/downloads/api-management[here, window=\"_blank\"] or from the https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip[Gravitee Downloads page, window=\"_blank\"].

[source,bash]
----
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip -o gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

Once you have downloaded the archive, extract the `graviteeio-gateway-xxx` directory and place it in the required location.

[source,bash]
----
$ unzip gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

== Check the installation
=== Run API Gateway from the command line

API Gateway can be started from the command line as follows:

[source,bash]
----
$ cd graviteeio-gateway-{{ site.products.apim._3x.version }}
$ ./bin/gravitee
----

By default, API Gateway runs in the foreground, prints its logs to standard output (stdout), and can be stopped
by pressing **Ctrl-C**.

If all goes well, you will see this log:

[source,bash]
[subs="attributes"]
...
11:01:53.162 [gravitee] [] INFO  i.g.g.standalone.node.GatewayNode - Gravitee.io - Gateway id[2e05c0fa-8e48-4ddc-85c0-fa8e48bddc11] version[{{ site.products.apim._3x.version }}] pid[24930] build[175] jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.121-b13] started in 15837 ms.
...

=== Check API Gateway is running

You can test that your API Gateway node is running by sending an HTTP request to port `8082` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8082/
----

which will give you a response something like this:

[source,bash]
----
No context-path matches the request URI.
----

== Run API Gateway as a daemon

To run API Gateway as a daemon, specify `-d` on the command line and record the process ID in a file using option `-p`:

[source,bash]
----
$ ./bin/gravitee -d -p=/var/run/gio.pid
----

You can find log messages in the `$GRAVITEE_HOME/logs/` directory.

To shut down API Gateway, kill the process ID recorded in the `pid` file:

[source,bash]
----
$ kill `cat /var/run/gio.pid`
----

== API Gateway directory structure

The `.zip` (and `.tar.gz`) package is entirely self-contained. All files and directories are, by default, contained within
`$GRAVITEE_HOME`, the directory created when extracting the archive.

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Location    |Description
|bin       |Binary scripts including `gravitee` to start a node
|config    |Configuration files including `gravitee.yml`
|lib       |Libraries (Gravitee.io libraries and third party libraries)
|logs      |Log files
|plugins   |Plugin files
|======================
