= Install APIM Gateway
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_gateway_install_zip.html
:page-folder: apim/installation-guide/with-zip
:page-liquid:
:page-layout: apim3x
:page-description: Gravitee.io API Management - Gateway - Installation with .zip
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

== Prerequisites

Your environment must meet the requirements listed below before you install APIM Gateway.

=== JDK

APIM Gateway requires at least Java 11. You can check your Java version as follows:

[source,bash]
----
$ java -version
$ echo $JAVA_HOME
----

NOTE: You can download the latest OpenJDK from the https://jdk.java.net/archive/[OpenJDK Download Site, window=\"_blank\"].

=== MongoDB and Elasticsearch

The default APIM Gateway distribution requires link:/apim/3.x/apim_installguide_repositories_mongodb.html[MongoDB, window=\"_blank\"] to poll environment configuration and link:/apim/3.x/apim_installguide_repositories_elasticsearch.html[Elasticsearch, window=\"_blank\"] for
reporting and analytics. See the vendor documentation for supported versions.

NOTE: You can download MongoDB from https://www.mongodb.org/downloads#production[MongoDB Download Site, window=\"_blank\"]
and Elasticsearch from https://www.elastic.co/downloads/elasticsearch[Elastic Download Site, window=\"_blank\"]

== Download and extract the `.zip` archive

Note that the archive includes the binaries for all the APIM components, so if you previously downloaded it to install another component, you do not need to download it again.

. Download the binaries https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip[here, window=\"_blank\"] or from the https://gravitee.io/downloads/api-management[Gravitee downloads page, window=\"_blank\"].

[source,bash]
----
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip -o gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

[start=2]
. Extract the `graviteeio-gateway-xxx` directory from the archive and place it in the required location.

[source,bash]
----
$ unzip gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

== Check the installation
=== Run APIM Gateway from the command line

By default, APIM Gateway runs in the foreground, prints its logs to standard output (stdout), and can be stopped
by pressing **Ctrl-C**.

Run APIM Gateway from the command line as follows:

[source,bash]
----
$ cd graviteeio-gateway-{{ site.products.apim._3x.version }}
$ ./bin/gravitee
----

Once APIM Gateway is running, you will see this log:

[source,bash]
[subs="attributes"]
...
11:01:53.162 [gravitee] [] INFO  i.g.g.standalone.node.GatewayNode - Gravitee.io - Gateway id[2e05c0fa-8e48-4ddc-85c0-fa8e48bddc11] version[{{ site.products.apim._3x.version }}] pid[24930] build[175] jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.121-b13] started in 15837 ms.
...

=== Check APIM Gateway is running

You can test that APIM Gateway is running by sending an HTTP request to port `8082` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8082/
----

You will receive a response something like this:

[source,bash]
----
No context-path matches the request URI.
----

== Run APIM Gateway as a daemon

To run APIM Gateway as a daemon, specify `-d` on the command line and record the process ID in a file using option `-p`:

[source,bash]
----
$ ./bin/gravitee -d -p=/var/run/gio.pid
----

You can find log messages in the `$GRAVITEE_HOME/logs/` directory.

To shut down APIM Gateway, kill the process ID recorded in the `pid` file:

[source,bash]
----
$ kill `cat /var/run/gio.pid`
----

== APIM Gateway directory structure

The `.zip` (and `.tar.gz`) package is entirely self-contained. All files and directories are, by default, contained within
`$GRAVITEE_HOME`, the directory created when extracting the archive.

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Location    |Description
|bin       |Binary scripts including `gravitee` to start a node
|config    |Configuration files including `gravitee.yml`
|lib       |Libraries (Gravitee.io libraries and third party libraries)
|logs      |Log files
|plugins   |Plugin files
|======================
