= Docker Compose
:page-toc: false
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_docker_compose.html
:page-folder: apim/installation-guide/docker
:page-layout: apim3x
:docker-image-src: https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/images
:github-repo: https://github.com/gravitee-io/gravitee-docker
:docker-hub: https://hub.docker.com/r/graviteeio

== Overview

This section explains how to run APIM images in Docker. The procedures are intended for users who are already familiar with Docker.

== Prequisites

To run the official images, you must first install https://docs.docker.com/installation/[Docker, window=\"_blank\"].

== Images

The APIM Docker images are https://hub.docker.com/u/graviteeio/[available on Docker Hub, window=\"_blank\"].
You can find all https://github.com/gravitee-io/gravitee-docker/[Dockerfiles on GitHub, window=\"_blank\"].

== Run APIM API

You can run a complete APIM stack using our docker-compose file.
It includes the four APIM components, MongoDB and Elasticsearch.

[WARNING]
====
Before running the commands below, check the Elasticsearch configuration as follows:

. Ensure sure you have the minimum `vm.max_map_count` property needed set to run Elasticsearch properly. https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html[Click here, window=\"_blank\"] to see how to check the current value and update if necessary.
. Ensure the folder defined as the ES volume in the docker-compose file (e.g. `elasticsearch`) is https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_configuration_files_must_be_readable_by_the_elasticsearch_user[readable by the elasticsearch user, window=\"_blank\"]:
+
`sudo chmod g+rwx elasticsearch/ && sudo chgrp 0 elasticsearch/`
====

[source,shell]
....
# Download docker-compose file
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml -o "docker-compose.yml"

# (Optional step: pull to ensure that you are running latest images)
$ docker-compose pull

# And run...
$ docker-compose up
....

== Check the APIM components are running

When all components are started, you can run a quick test by checking these URLs:

|===
|Component |URL| Expected response

|APIM Gateway
|http://localhost:8082/
|404 status code, with a `No context-path matches the request URI` payload.

|APIM API
|http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis
|200 status code, with a `[]` payload.

|APIM Management
|http://localhost:8084/
|200 status code, showing the UI

|APIM Portal
|http://localhost:8085/
|200 status code, showing the UI

|===
