= Upgrade to 3.13.0

== Breaking changes

=== Gateway
HTTP Bridge Service is now disabled by default starting.

If you are using this feature, **do not forget to update your settings.**

For more information, link:https://docs.gravitee.io/apim/3.x/apim_installguide_hybrid_deployment.html#apim_gateway_http_bridge_server[click here] for documentation.

=== Management Web UI
From with this version, the name of the APIM Console component changes.
As a consequence:

1. The APIM Console component available on https://download.gravitee.io is now `gravitee-*apim-console*-webui-x.y.z.zip` instead of `gravitee-management-webui-x.y.z.zip`

2. The name of the APIM Console folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-console*-ui-x.y.z` instead of `graviteeio-management-ui-x.y.z`

=== Portal Web UI
From with this version, the name of the APIM Portal component changes.
As a consequence:

1. The APIM Portal component available on https://download.gravitee.io is now `gravitee-*apim*-portal-webui-x.y.z.zip` instead of `gravitee-portal-webui-x.y.z.zip`

2. The name of the APIM Portal folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim*-portal-ui-x.y.z` instead of `graviteeio-portal-ui-x.y.z`

WARNING: In future versions, others plugins & components might be renamed. Stay tuned!
