= Run in Docker
:page-sidebar: ae_sidebar
:page-permalink: ae/installguide_docker.html
:page-folder: ae/installation-guide
:page-description: Gravitee Alert Engine - Docker
:page-keywords: Gravitee, API Platform, Alert, Alert Engine, documentation, manual, guide, reference, api
:docker-image-src: https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/images
:docker-hub: https://hub.docker.com/r/graviteeio
:page-layout: ae

== Overview
This section explains how to run AE images in Docker. These procedures are intended for users who are already familiar with Docker.

== Prerequisites
To run our official images, you must first install https://docs.docker.com/installation/[Docker^].

== Images
You can find the complete set of AE images https://hub.docker.com/u/graviteeio/[on Docker Hub^].

|===
|Image name |Version |Base

|{docker-hub}/ae-engine/[graviteeio/ae-engine^]
|latest
|https://hub.docker.com/_/openjdk/[openjdk:11-jre-slim-buster^]

|===

=== graviteeio/ae-engine

The AE image provides a set of environment variables you can use tune your container.

==== Run the image
[source,shell]
....
$ docker run  \
        --publish 72:8072  \
        --name alert-engine  \
        --detach  \
        graviteeio/ae-engine:{{site.products.ae.version}}
....

==== Configure the container
If you want to override the default configuration and any properties included in the `gravitee.yml` file,
you need to use environment variables. For more information, see link:{{ '/ae/installguide_configuration.html#environment_variables' | relative_url }}[Configuration^].

The following example changes the Hazelcast configuration file:
[source,shell]
....
$ docker run  \
        --publish 72:8072  \
        --name alert-engine  \
        --env GRAVITEE_CLUSTER_HAZELCAST_CONFIG_PATH=/path/to/hazelcast.xml
        --detach  \
        graviteeio/ae-engine:{{site.products.ae.version}}
....
