= Install with .zip
:page-sidebar: ae_sidebar
:page-permalink: ae/installguide_engine.html
:page-folder: ae/installation-guide
:page-description: Gravitee Alert Engine - Engine
:page-toc: true
:page-keywords: Gravitee, API Platform, Alert, Alert Engine, documentation, manual, guide, reference, api
:page-layout: ae

== Prerequisites

Your environment must meet the requirements listed below before you install AE.

=== JDK

AE requires a Java version from 8 to the most recent Java 11 version. You can check your Java version as follows:

[source,bash]
----
java -version
echo $JAVA_HOME
----

NOTE: You can download the latest OpenJDK from the https://jdk.java.net/archive/[OpenJDK Download Site^].

== Download and extract the `.zip` archive

. Download the binaries from https://download.gravitee.io/graviteeio-ae/components/gravitee-ae-engine-{{site.products.ae.version}}.zip[here^] or using the command line:
+
[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-ae/components/gravitee-ae-engine-{{site.products.ae.version}}.zip -o gravitee-ae-standalone-{{site.products.ae.version}}.zip

. Extract the archive and place it in the required location (`$GRAVITEE_HOME`).
+
[source,bash]
[subs="attributes"]
$ unzip gravitee-ae-standalone-{{site.products.ae.version}}.zip

== Check the installation

=== Run AE from the command line

By default, AE Engine runs in the foreground, prints its logs to the standard output (stdout), and can be stopped
by pressing *Ctrl-C*.

Run AE from the command line as follows:

[source,bash]
----
$ cd gravitee-ae-standalone-{{site.products.ae.version}}
$ ./bin/gravitee
----

Once AE is running, you should see this log:

[source,bash]
[subs="attributes"]
...
11:23:06.835 [main] [] INFO  i.g.ae.standalone.node.AlertEngineNode - Gravitee.io - Alert Engine - Engine id[92c03b26-5f21-4460-803b-265f211460be] version[{{site.products.ae.version}}] pid[4528] build[${env.BUILD_NUMBER}#${env.GIT_COMMIT}] jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.121-b13] started in 1860 ms.
...

=== Check AE is running

You can test that your AE node is running by sending an HTTP request to port `8072` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8072/
----

You should receive an empty 401 response.

== Run AE as a daemon

To run AE as a daemon, specify `-d` at the command line and record the process ID in a file using option `-p`:

[source,bash]
----
$ ./bin/gravitee -d -p=/var/run/gio.pid
----

You can find log messages in the `$GRAVITEE_HOME/logs/` directory.

To shut down AE Engine, kill the process ID recorded in the `pid` file:

[source,bash]
----
$ kill `cat /var/run/gio.pid`
----

== AE directory structure

The `$GRAVITEE_HOME` directory looks like this:

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Folder    |Description
|bin       |Startup/shutdown scripts
|config    |Configuration files
|lib       |Libraries (Gravitee.io libraries and third party libraries)
|license   |License for Enterprise Edition
|logs      |Log files
|plugins   |Plugin files
|======================
