= Upgrade AE
:page-sidebar: ae_sidebar
:page-permalink: ae/installguide_migration.html
:page-folder: ae/installation-guide
:page-description: Gravitee Alert Engine - Configuration
:page-toc: false
:page-keywords: Gravitee, API Platform, Alert, Alert Engine, documentation, manual, guide, reference, api
:page-layout: ae

== Upgrade to 2.0.0

Moving from 1.6.x to 2.0.0 should run smoothly as only internals have changed.

Major changes:

- Rework of internals of Alert Engine for better performances
- Hazelcast upgrade v5 (previously v4). Hazelcast ensures rolling upgrade between Hazelcast IMDG 4.2 and Hazelcast
Platform 5.0. More info link:https://docs.hazelcast.com/hazelcast/5.2/maintain-cluster/rolling-upgrades#hazelcast-members-compatibility-guarantees[here]

== Upgrade to 1.3.0

WARNING: AE v1.3.0 cannot run alongside a v1.2.x version. *Rolling updates are not supported by this version*.

Major changes:

* Upgrade to Hazelcast v4 (previously v3). Hazelcast V4 brings a lot of improvements and better stability when running on Kubernetes cluster.

=== Deployment strategy

Since the upgrade to Hazelcast v4, AE v1.3.0 can no longer communicate with previous versions. Therefore it is not possible to upgrade AE using a rolling update strategy.

For version 1.3.0, we recommend opting for a *Blue/Green deployment* instead of rolling update strategy, so you can switch all the traffic when ready.

Be aware that you may lose some alerts during the upgrade because all counters will be reset. This mostly depends on the duration of aggregated periods configured on the alerts (the longer the period, the more likely the loss of alerts is).
