---
redirect_from:
  - /am/current/am_devguide_protocols_overview.html
---
= Protocols
:page-toc: false

AM relies on different authorization/authentication/identity protocols to define how applications can interact with it to authenticate, retrieve user information and make authorization decisions when accessing protected resources.

- link:./oauth2/introduction.html[OAuth 2.0]: the OAuth 2.0 authorization framework enables a third-party application to obtain limited access to an HTTP service,
either on behalf of a resource owner by brokering an approval interaction between the resource owner and the HTTP service,
or by allowing the third-party application to obtain access on its own behalf.

- link:./oidc.html[OpenID Connect]: OpenID Connect 1.0 is a simple identity layer on top of the OAuth 2.0 protocol.
It enables clients to verify the identity of the end user based on the authentication performed by an authorization server,
as well as to obtain basic profile information about the end user in an interoperable and REST-like manner.

- link:./uma2.html[UMA 2.0]: User-Managed Access (UMA) is an OAuth-based protocol designed to give to an individual a unified control point for authorizing who and what can get access to their digital data, content and services, no matter where all those things live.

- link:./scim.html[SCIM 2.0]: the System for Cross-domain Identity Management (SCIM) specification is designed to make managing user identities in cloud-based applications and services easier.
Its intent is to reduce the cost and complexity of user management operations by providing a common user schema and extension model.

- link:./fapi.html[FAPI 1.0]: The Financial-grade API (FAPI) is a highly secured OAuth profile that aims to provide specific implementation guidelines for security and interoperability.
