[[apim-kubernetes-operator-user-guide-helm-template-crds]]
= Deploying Custom Resources using Helm
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_kubernetes_operator_user_guide_helm_template_crds.html
:page-folder: apim/kubernetes
:page-layout: apim3x

Helm helps you manage Kubernetes applications — Helm Charts help you define, install, and upgrade even the most complex Kubernetes application.

It is easily possible to use Helm to deploy your CRDs into the cluster and leverage all the features that Helm provides such as templating.

Here are the steps to follow using Helm

1. Create an empty project using Helm
2. Add required templates for the Gravitee CRDs
3. Install/Upgrade your helm charts

You can create an empty project using the following command
....
helm create sample-crds
....

And these should give us a project with the following structure

....
sample-crds
├── Chart.yaml
├── charts
├── templates
│   ├── NOTES.txt
│   ├── _helpers.tpl
│   ├── deployment.yaml
│   ├── hpa.yaml
│   ├── ingress.yaml
│   ├── service.yaml
│   ├── serviceaccount.yaml
│   └── tests
│       └── test-connection.yaml
└── values.yaml
....

The next step is to get rid of exiting templates inside the templates folder and replace them with new templates for our CRDs.
For Example this can be something that you can use for `ManagementContext` CRD

[source,yaml]
....
{{ '{{' }} - range $context := .Values.contexts }}
apiVersion: gravitee.io/v1alpha1
kind: ManagementContext
metadata:
  name: {{ '{{' }} $context.name }}
spec:
  baseUrl: {{ '{{' }} $context.baseUrl }}
  environmentId: {{ '{{' }} $context.environmentId }}
  organizationId: {{ '{{' }} $context.organizationId }}
  auth:
    secretRef:
      name: {{ '{{' }} $context.name }}
      namespace: {{ '{{' }} $context.namespace }}
{{ '{{' }}- end }}
....

Which is based on the following values:

[source,yaml]
....
contexts:
  - name: staging
    baseUrl: http://localhost:9000
    environmentId: DEFAULT
    organizationId: DEFAULT
    token: de6b0c76-abe1-440d-ab0c-76abe1740d99
....

if you want to reference an ConfigMap or a Secret inside your templates so that they will be resolved during the deployment by the GKO, you can use the following syntax for the value:

....
[[ secret `YOUR_SECRET_NAME/KEY_NAME` ]]
[[ configmap `YOUR_CONFIGMAP_NAME/KEY_NAME` ]]
....

Once you finished all your templates, you can packages your templates and install/upgrade your helm charts into the cluster, you can use the following command

....
helm package .
helm install sample-crds sample-crds-0.1.0.tgz
....

For more information how to use Helm, you can visit https://helm.sh[their website^]

For a complete example around the topic described in this section, you can checkout the https://github.com/gravitee-io/gravitee-kubernetes-operator/tree/alpha/docs/guides/deploy-crd-with-helm[Operator repository guide^].
