[[apim-kubernetes-operator-definitions]]
= Custom Resource Definitions (CRDs) reference
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_kubernetes_operator_definitions.html
:page-folder: apim/kubernetes
:page-layout: apim3x

[label label-version]#New in version 3.19.0#

== Overview

The Gravitee Kubernetes Operator comes with two Custom Resource Definitions (CRDs) - `ManagementContext` and `ApiDefinition`.

WARNING: Due to a known issue, you should not create an `ApiDefinition` before you define the relevant `ManagementContext` resource. Gravitee engineers are working to fix this issue soon in a future GKO release so that this dependency is removed.


== `ManagementContext`

The `ManagementContext` custom resource represents the configuration for a Management API.

Resources:

  * The `ManagementContext` CRD code is available on link:https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/api/v1alpha1/managementcontext_types.go[GitHub^].
  * The `ManagementContext` CRD API reference is documented link:{{ '/apim/3.x/apim_kubernetes_operator_api_reference.html#managementcontext' | relative_url }}[here].
  * You can learn how to use the `ManagementContext` resource in link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_management_context.html' | relative_url }}[this section].

The `ManagementContext` refers to a remote Management API. You can have as many `ManagementContext` resources as you want, however you need to reference the relevant `ManagementContext` from the API Definition in order to indicate to the GKO where the API should be published.

=== Examples

A basic example of an `ManagementContext` resource is shown below:

....
apiVersion: gravitee.io/v1alpha1
kind: ManagementContext
metadata:
  name: dev-mgmt-ctx
spec:
  baseUrl: http://localhost:8083
  auth:
    credentials:
      username: admin
      password: admin
....


The next example shows the same resource but with a Personal Token:

....
apiVersion: gravitee.io/v1alpha1
kind: ManagementContext
metadata:
  name: dev-mgmt-ctx
spec:
  baseUrl: http://localhost:8083
  auth:
    bearerToken: xxxx-yyyy-zzzz
....

You can then refer to the `ManagementContext` from the API, as shown in the example below:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: basic-api-example
spec:
  name: "K8s Basic Example"
  contextRef:
    name: "dev-mgmt-ctx"
    namespace: "default"
  version: "1.1"
  description: "Basic api managed by Gravitee Kubernetes Operator"
  proxy:
    virtual_hosts:
      - path: "/k8s-basic"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
....

NOTE: Read more about `ManagementContext` link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_management_context.html' | relative_url }}[here].

== `ApiDefinition`

The `APIDefinition` custom resource represents the configuration for a single proxied API and its versions. It is similar to a YAML representation of an API Definition in JSON format.

Resources:

  * The `ApiDefinition` CRD code is available on link:https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/api/v1alpha1/apidefinition_types.go[GitHub^].
  * The `ApiDefinition` CRD API reference is documented link:{{ '/apim/3.x/apim_kubernetes_operator_api_reference.html#apidefinition' | relative_url }}[here].
  * You can learn how to use the `ApiDefinition` resource in link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_api_definition.html' | relative_url }}[this section].

=== Workflow

The following workflow is applied when a new `ApiDefinition` resource is added to the cluster:

  1. The GKO listens for `ApiDefinition` resources.
  2. The GKO performs some required changes, such as computing automatically IDs or CrossIDs (for API or Plan).
  3. The GKO converts the definition to JSON format.
  4. The GKO compares the definition to the existing definition. If something has changed, the GKO pushes the definition to the Management API (if a `ManagementContext` is provided).
  5. The GKO deploys the API to the API Gateway.

=== Examples

A basic example of an `ApiDefinition` resource is shown below:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: basic-api-example
spec:
  name: "K8s Basic Example"
  version: "1.0"
  description: "Basic api managed by Gravitee Kubernetes Operator"
  proxy:
    virtual_hosts:
      - path: "/k8s-basic"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
....

The same API with support for plans is shown in the example below:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: apikey-example
spec:
  name: "K8s OAuth2 Example"
  version: "1.0"
  description: "Api managed by Gravitee Kubernetes Operator with OAuth2 plan"
  resources:
    - name: "am-demo"
      type: oauth2-am-resource
      configuration:
        version: V3_X
        serverURL: "https://am-nightly-gateway.cloud.gravitee.io"
        securityDomain: "test-jh"
        clientId: "localjh"
        clientSecret: "localjh"
  plans:
    - name: "OAuth2"
      description: "Oauth2 plan"
      security: OAUTH2
      securityDefinition: '{"oauthResource":"am-demo"}'
  proxy:
    virtual_hosts:
      - path: "/k8s-oauth2"
    groups:
      - name: default-group
        endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
....


NOTE: Read more about `ApiDefinition` link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_api_definition.html' | relative_url }}[here].

== CRD dependencies

=== Order of CRD creation

Due to a known issue, you should not create an `ApiDefinition` before you define the relevant `ManagementContext` resource. Gravitee engineers are working to fix this issue soon in a future GKO release so that this dependency is removed.

=== Resource deletion

Since an `ApiDefinition` can rely on a `ManagementContext`, resource deletion is restricted until a check is performed first whether there is an API associated with the respective `ManagementContext`. This is achieved through the use of link:https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/[Finalizers^].

== CRD samples

Check out some sample CRDs in the link:https://github.com/gravitee-io/gravitee-kubernetes-operator/tree//config/samples/apim[GKO GitHub repository^].
