[[apim-kubernetes-operator-quick-start]]
= GKO Quick Start Guide
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_kubernetes_operator_quick_start.html
:page-folder: apim/kubernetes
:page-layout: apim3x

[label label-version]#New in version 3.19.0#
[label label-version]#BETA release#

== Overview

The main purpose of the Gravitee Kubernetes Operator (GKO) is to define, deploy, and publish APIs on your API Portal, Gateway, and Console with Custom Resource Definitions (CRDs).

To enable that, you should deploy the GKO on a Kubernetes cluster.

After a successful GKO deployment, you can try out the GKO functionality by creating CRDs and testing your API by calling it from the API Gateway. This process is documented link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_play.html' | relative_url }}[here].

NOTE: The GKO only works with APIM version 3.19.0 (and above).

== Deploying the GKO on your cluster

NOTE: For full details, see the link:{{ '/apim/3.x/apim_kubernetes_operator_installation_cluster.html' | relative_url }}[GKO deployment guide] section.

=== STEP 1: Prepare your cluster

As a prerequisite, you should have an APIM-ready cluster up and running before you deploy the GKO. You should have user access to the cluster you want to deploy to, and it should be the one defined as your current/active Kubernetes context.

=== STEP 2: Deploy the GKO on your cluster

=== Prerequisites

Before you start, you need to have the following software set up and running on your machine:

. https://kubernetes.io/docs/tasks/tools/#kubectl[Kubectl].
. https://helm.sh/docs/intro/install/[Helm v3].

=== Install the Helm Chart repo

Add the Gravitee.io Helm charts repo using the command below:

....
$ helm repo add graviteeio https://helm.gravitee.io
....

=== Install the Helm Chart

Now, install the chart from the Helm repo with associated the release name.

To prevent potential issues in the future, it is best practice to create a separate namespace for your installation in order to prevent the use of the default Kubernetes namespace. The installation command provided immediately below assumes that such best practice is followed, however this is not a mandatory requirement.

To install the Helm Chart using a dedicated namespace (we use `+gko-system+` as an example), run the following command:

[source,bash]
----
helm upgrade --install --create-namespace gko graviteeio/gko -n gko-system
----

As an optional but recommended next step, you should check if the Gravitee CRDs are available on your cluster. To do so, run the following command:

....
kubectl get crd
....

== Trying out the deployed GKO

After GKO deployment, it is time to try out the GKO functionality by creating CRDs and testing your API via and API call from the API Gateway.

NOTE: Before you start, ensure that the `services.sync.kubernetes` property is enabled (set to `true`) in the link:https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L264[`gravitee.yml`^] file. For more information, see link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_play.html#prerequisites' | relative_url }}[How to try out the GKO after deployment].

The process involves the following stages:

1. Create an Api Context custom resource.
2. Create an API Definition custom resource - this creates a new API on the cluster.
3. Test the new API by calling it through the APIM Gateway.

NOTE: For full details, see link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_play.html' | relative_url }}[How to try out the GKO after deployment].

=== STEP 1: Create an Api Context custom resource

The `ApiContext` custom resource represents the configuration for a Management API.

NOTE: Read more about the Api Context custom resource link:{{ '/apim/3.x/apim_kubernetes_operator_definitions.html' | relative_url }}[here] and link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_api_context.html' | relative_url }}[here].

To create an Api Context custom resource, you need a YAML file with the correct Api Context configuration. You can use the following sample YAML file from Gravitee directly, or as a template to base your configuration on:

https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/config/samples/context/dev/api-context-with-credentials.yml

To create the Api Context resource using the ready Gravitee sample file, run the following command:

....
kubectl apply -f https://raw.githubusercontent.com/gravitee-io/gravitee-kubernetes-operator/master/config/samples/context/dev/api-context-with-credentials.yml
....

For full details on creating an Api Context custom resource, see link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_play.html#step_1_create_an_api_context_custom_resource' | relative_url }}[STEP 1: Create an Api Context custom resource] in the User Guide section.


=== STEP 2: Create an API Definition custom resource

The ApiDefinition custom resource represents the configuration for a single proxied API and its versions. It is similar to a YAML representation of an API Definition in JSON format.

NOTE: Read more about the API Definition custom resource link:{{ '/apim/3.x/apim_kubernetes_operator_definitions.html' | relative_url }}[here] and link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_api_definition.html' | relative_url }}[here].


To create an API Definition custom resource, you need a YAML file with the desired API Definition configuration. You can use the following sample YAML file from Gravitee directly, or as a template to base your configuration on:

https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/config/samples/apim/api-with-context.yml

To create the API Definition resource using the ready Gravitee sample file, run the following command:

....
kubectl apply -f https://raw.githubusercontent.com/gravitee-io/gravitee-kubernetes-operator/master/config/samples/apim/api-with-context.yml
....

For full details on creating an API Definition custom resource, see link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_play.html#step_2_create_an_api_definition_custom_resource' | relative_url }}[STEP 2: Create an API Definition custom resource] in the User Guide section.


=== STEP 3: Test the new API by calling it through the APIM Gateway

NOTE: For the Gateway to work with the GKO, ensure that the `services.sync.kubernetes` property is enabled (set to `true`) in the link:https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L264[`gravitee.yml`^] file. For more information, see the prerequisites section in link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_play.html#prerequisites' | relative_url }}[How to try out the GKO after deployment].

To test the API, you can call it through the APIM Gateway by running the following command using your APIM Gateway URL:

....
curl -i http://<gateway_host>:<gateway_port>/gateway/k8s-basic-with-ctx
....

Where <gateway_host> and <gateway_port> are the gateway host and port.

For full details on trying out the GKO functionality after deployment, see link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_play.html#step_3_call_the_api_through_the_apim_gateway' | relative_url }}[STEP 3: Call the API through the APIM Gateway] in the User Guide section.
