[[apim-kubernetes-custom-resources]]
= Gravitee Custom Resource Definitions
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_kubernetes_custom_resources.html
:page-folder: apim/kubernetes
:page-layout: apim3x

== Custom Resources

The Kubernetes plugin comes with three Custom Resource Definitions:

* GraviteePlugins
* GraviteeGateway
* GraviteeServices

=== GraviteePlugins

The GraviteePlugins resource defines the policies and the resources that are used with the same configuration by different APIs.

NOTE: The policies and resources you can define in a GraviteePlugin resource are the same as in APIM Console Design Studio. Currently, the API key policy isn't managed by the Kubernetes plugin and the Cache resource is limited to the API scope.

[%header,cols=2*]
|===
|Attribute
|Value

|Group
|gravitee.io

|Name
|gravitee-plugins.gravitee.io

|Kind
|GraviteePlugins

|Version
|v1alpha1

|Plural
|gravitee-plugins

|Singular
|gravitee-plugin

|Short Names
|giop

|Definition
|https://raw.githubusercontent.com/gravitee-io/gravitee-kubernetes/master/crds/apim/gravitee-plugin-crd.yml[gravitee-plugin-crd.yml]
|===

A GraviteePlugin resource contains a map of objects describing either a policy configuration or a resource configuration.

NOTE: When a resource is used by a policy (with an OAuth resource or a Cache resource), the policy needs to reference the resource using its full qualified name: `<resource-name>.<custom-resource-name>.<namespace>`

[source,yaml]
----
apiVersion: "gravitee.io/v1alpha1"
kind: GraviteePlugins
metadata:
  name: plugins-example
spec:
  plugins:
    auth-using-jwt:
      policy: jwt
      configuration:
        signature: "HMAC_HS256"
        publicKeyResolver: "GIVEN_KEY"
        useSystemProxy: false
        extractClaims: false
        propagateAuthHeader: true
        resolverParameter: "be0368e97a7574a05995c0bf535fa395776f2e941715870cf5dfab3be6868364"
    my-cache-policy:
      policy: cache
      configuration:
        cacheName: "store-cache.plugins-example.default"
        timeToLiveSeconds: 60
        scope: "API"
  store-cache:
      resource: cache
      configuration:
        name: "my-cache"
        timeToIdleSeconds: 0
        timeToLiveSeconds: 0
        maxEntriesLocalHeap: 100
----

Policies and resources can reference a Kubernetes secret using the `valueFrom/secretKeyRef` syntax. For example, here is how to define the key used for an HMAC signature with the JWT policy.

[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: jwt-key
  namespace: default
type: Opaque
data:
  HS256: YmUwMzY4ZTk3YTc1NzRhMDU5OTVjMGJmNTM1ZmEzOTU3NzZmMmU5NDE3MTU4NzBjZjVkZmFiM2JlNjg2ODM2NA==
----

[source, yaml]
----
apiVersion: "gravitee.io/v1alpha1"
kind: GraviteePlugins
metadata:
  name: plugins-example
  namespace: default
spec:
  plugins:
    auth-using-jwt:
        policy: jwt
        configuration:
          signature: "HMAC_HS256"
          publicKeyResolver: "GIVEN_KEY"
          useSystemProxy: false
          extractClaims: false
          propagateAuthHeader: true
          resolverParameter:
          # reference the entry HS256 of the secret jwt-key
            valueFrom:
              secretKeyRef:
                name: jwt-key
                key: HS256
----

==== GraviteePlugin Status

The custom resource GraviteePlugin provides a Status sub-resource to notify about the integration state.

[source, bash]
----
$ kubectl get giop
NAME                    STATE     MESSAGE
plugins-example         SUCCESS
plugins-example-error   ERROR     Unable to read key 'key-unknown' in secret 'secret-unknown'
----


=== GraviteeGateway

The GraviteeGateway resource defines the authentication plugin and resources that will be inherited from the GraviteeService.

[%header,cols=2*]
|===
|Attribute
|Value

|Group
|gravitee.io

|Name
|gravitee-gateways.gravitee.io

|Kind
|GraviteeGateway

|Version
|v1alpha1

|Plural
|gravitee-gateways

|Singular
|gravitee-gateway

|Short Names
|giogw

|Definition
|https://raw.githubusercontent.com/gravitee-io/gravitee-kubernetes/master/crds/apim/gravitee-gateway-crd.yml[gravitee-gateway-crd.yml]
|===

GraviteeGateway contains three kinds of configuration elements:

* The authentication policy to be used by the APIs
* A map of resource definitions to be inherited by the APIs
* The default HTTP settings for the backend service to be inherited by the APIs

In the following example:

* Authentication will be done using the JWT policy
* A Cache resource is defined
* Default settings for the HTTP client are provided

NOTE: In the same way as the GraviteePlugin, the configuration elements of a GraviteeGateway can reference a Kubernetes secret using the `valueFrom/secretKeyRef` syntax.

[source, yaml]
----
apiVersion: "gravitee.io/v1alpha1"
kind: GraviteeGateway
metadata:
  name: gateway-example
  namespace: default
spec:
  authentication:
    policy: jwt
    configuration:
      signature: "HMAC_HS256"
      publicKeyResolver: "GIVEN_KEY"
      useSystemProxy: false
      extractClaims: false
      propagateAuthHeader: true
      resolverParameter:
        valueFrom:
          secretKeyRef:
            name: jwt-key
            key: HS256
  resources:
    store-cache:
      resource: cache
      configuration:
        name: "my-cache"
        timeToIdleSeconds: 0
        timeToLiveSeconds: 0
        maxEntriesLocalHeap: 100
  defaultBackendConfigurations:
    httpClient:
      connectTimeout: 5000
      idleTimeout: 60000
      keepAlive: true
      readTimeout: 10000
      pipelining: false
      maxConcurrentConnections: 100
      useCompression: true
      followRedirects: false
      version: HTTP_1_1
----

GraviteeGateway definitions can use policies or resources defined through GraviteePlugins.

NOTE: For authentication, if the `authentication` entry and `authenticationReference` are defined, then the `authentication` entry takes precedence.

[source, yaml]
----
apiVersion: "gravitee.io/v1alpha1"
kind: GraviteeGateway
metadata:
  name: gateway-example
  namespace: default
spec:
  authenticationReference:
	# use the "auth-using-jwt" policy defined into the GraviteePlugin named "plugins-example"
    resource: "plugins-example"
    name: "auth-using-jwt"
  resources:
    store-cache:
      resource: cache
      configuration:
        name: "my-cache"
        timeToIdleSeconds: 0
        timeToLiveSeconds: 0
        maxEntriesLocalHeap: 100
  resourceReferences:
	# use the "oauth2-resource-provider" resource defined into the GraviteePlugin named "another-plugins"
    - resource: "another-plugins"
      name: "oauth2-resource-provider"
  defaultBackendConfigurations:
    httpClient:
      connectTimeout: 5000
      idleTimeout: 60000
      keepAlive: true
      readTimeout: 10000
      pipelining: false
      maxConcurrentConnections: 100
      useCompression: true
      followRedirects: false
      version: HTTP_1_1
----

==== GraviteeGateway Status

The custom resource GraviteeGateway provides a Status sub-resource to notify about the integration state.

[source, bash]
----
$ kubectl get giogw
NAME                    STATE     MESSAGE
gateway-example         SUCCESS
gateway-example-error   ERROR     Reference 'some-plugins' undefined in namespace 'default'
----


=== GraviteeServices

The GraviteeServices resource allows you to define one or multiple services (or APIs).

[%header,cols=2*]
|===
|Attribute
|Value

|Group
|gravitee.io

|Name
|gravitee-services.gravitee.io

|Kind
|GraviteeServices

|Version
|v1alpha1

|Plural
|gravitee-services

|Singular
|gravitee-service

|Short Names
|giosvc

|Definition
|https://raw.githubusercontent.com/gravitee-io/gravitee-kubernetes/master/crds/apim/gravitee-service-crd.yml[gravitee-service-crd.yml]
|===

A GraviteeService resource contains one or multiple API definitions with the following sections:

* `enabled`: a boolean value that provides a way to enable or disable the API
* `authentication` or `authenticationReference`: defines which policy is used as authentication mechanism
* `cors`: allows the definition of CORS settings for the API
* `resources` and/or `resourceReferences`: define which resources are used by the API
* `vhosts`: allows the definition of the API context path
* `paths`: contains the policies applied for a given path
* `endpoints`: define the target endpoints of the API

Below is a simple example of an API named `petstore`. This API uses the Keyless authentication policy and doesn't define `cors` configuration. The context path of this API is set to `/mystore`. A spike-arrest policy is applied to the path `/pet/findByStatus` and a rate-limit policy is applied to the path `/store/inventory`. Finally, the Kubernetes service `petstore-svc` is defined as Backend.

[source, yaml]
----
apiVersion: "gravitee.io/v1alpha1"
kind: GraviteeServices
metadata:
  name: service-example
spec:
  services:
    petstore:
      type: api
      authentication:
        policy: key-less
      cors:
        enabled: false
      vhosts:
        - path: "/mystore"
          enabled: true
      paths:
        - prefix: "/pet/findByStatus"
          rules:
            - methods: ["GET"]
              policy: spike-arrest
              configuration:
                spike:
                  limit: 1
                  periodTime: 1
                  periodTimeUnit: "SECONDS"
        - prefix: "/store/inventory"
          rules:
            - methods: ["GET"]
              policy: rate-limit
              configuration:
                rate:
                  limit: 5
                  periodTime: 10
                  periodTimeUnit: "SECONDS"
      endpoints:
        default-group:
          backendServices:
          - name: petstore-svc
            port: 8080
----

A GraviteeService can reference a GraviteeGateway resource. In this case, the authentication policy defined by the GraviteeGateway will be used by all the API definitions present in the GraviteeService resource except if the service overrides it using the `authentication` or the `authenticationReference` properties.

[source, yaml]
----
apiVersion: "gravitee.io/v1alpha1"
kind: GraviteeServices
metadata:
  name: service-example
spec:
  gateway:
    name: gateway-example
    namespace: default
  services:
    petstore:
      type: api
      cors:
        enabled: false
      ...
----

HTTP client settings can be defined at the EndpointGroup level or inherited from the GraviteeGateway resource:

[source, yaml]
----
      endpoints:
        default-group:
          backendServices:
          - name: petstore-svc
            port: 8080
          configuration:
            httpClient:
              connectTimeout: 5000
              idleTimeout: 60000
              keepAlive: true
              readTimeout: 10000
              pipelining: false
              maxConcurrentConnections: 100
              useCompression: true
              followRedirects: false
              version: HTTP_1_1
            httpProxy:
              enabled: false
            httpSslOptions:
              trustAll: true
----

In a path definition, a policy may be defined using a reference coming from a GraviteePlugin resource.


[source, yaml]
----
...
      paths:
        - prefix: "/pet/findByStatus"
          rules:
            - methods: ["GET"]
              policyReference:
                resource: plugin-example
                name: auth-using-jwt
            - methods: ["GET"]
              policy: spike-arrest
              configuration:
                spike:
                  limit: 1
                  periodTime: 1
                  periodTimeUnit: "SECONDS"
...
----


==== GraviteeService Status

The custom resource GraviteeService provides a Status sub-resource to notify about the integration state and the number of services defined by the resource.

[source, bash]
----
$ kubectl get giosvc
NAME                       STATE     MESSAGE   ENABLED   SERVICES
service-example            SUCCESS             1         1
----
