[[apim-kubernetes-operator-installation-cluster]]
= Deploying GKO on a Kubernetes cluster
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_kubernetes_operator_installation_cluster.html
:page-folder: apim/kubernetes
:page-layout: apim3x

[label label-version]#New in version 3.19.0#
[label label-version]#BETA release#

== Overview

This section provides steps on how to deploy the Gravitee Kubernetes Operator (GKO) on an existing APIM-ready Kubernetes cluster.

NOTE: If your architecture requires the management of multiple Kubernetes clusters with a different set of APIs for each cluster, you should deploy the GKO separately on each cluster. Follow the deployment process described below for each cluster deployment.

== Prerequisites

=== Prerequisites

Before you start, you need to have the following software set up and running on your machine:

. https://kubernetes.io/docs/tasks/tools/#kubectl[Kubectl].
. https://helm.sh/docs/intro/install/[Helm v3].

You also need access to an APIM-ready Kubernetes cluster.

By default, the Kubernetes synchronizer is configured to look for API definitions in the API Gateway namespace. To watch all namespaces you must set the property `services.sync.kubernetes.namespaces` to `all` in the Gateway configuration. You can also provide a specific list of namespaces to watch.

It is also recommended to check the current Kubernetes context to ensure that it is set to the correct cluster. To do this, run the following command:

....
kubectl config current-context
....

NOTE: See the link:https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration[Kubernetes documentation^] for more information on displaying a list of contexts and setting your current context.

== Deploying the GKO on the cluster

=== STEP 1: Run the deployment script

Run the following command in your command-line tool (the working directory does not matter) to deploy the GKO on the cluster of your current Kubernetes context:

....
helm repo add graviteeio https://helm.gravitee.io

# If you already have the repository, update it using the following command.
#  helm repo update graviteeio

helm upgrade --install --create-namespace gko graviteeio/gko -n gko-system

# By default the operator is configured to manage all the custom resources in the cluster.
# To manage only the custom resources in the namespace where the operator is deployed, set the following property to false using the following command.
# helm upgrade --install --create-namespace gko graviteeio/gko -n gko-system --set manager.scope.cluster=false
....

The operation is quick and the successful command-line output should be similar to one in the example below:

....
Thank you for installing The Gravitee Kubernetes Operator Helm Chart!

To learn more about your release, try:

  $ helm status gko
  $ helm get all gko

Please visit our documentation to learn about custom resources managed by the operator:

https://docs.gravitee.io/apim/3.x/apim_kubernetes_operator_overview.html
....

The GKO has now been deployed on your cluster.

=== STEP 2: Check if the Gravitee CRDs are available on your cluster

Run the following command:

....
kubectl get crd
....

The command-line output should include `apidefinitions.gravitee.io` and `managementcontexts.gravitee.io`, as shown in the example below:

....
NAME                              CREATED AT
helmcharts.helm.cattle.io         2022-09-28T10:25:02Z
helmchartconfigs.helm.cattle.io   2022-09-28T10:25:02Z
apidefinitions.gravitee.io        2022-09-28T10:34:38Z
managementcontexts.gravitee.io    2022-09-28T10:34:38Z
....
