[[apim-kubernetes-controller-overview]]
= Kubernetes Controller plugin introduction
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_kubernetes_controller_overview.html
:page-folder: apim/kubernetes
:page-layout: apim3x

[label label-version]#New in version 3.7#

== Overview

APIM 3.7 introduced a Kubernetes Controller plugin for APIM Gateway allowing the deployment of APIs using https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resource Definitions (CRDs)^].

APIs deployed using CRDs are not visible through APIM Console.

WARNING: This plugin is still in Alpha version - the API key policy is not available for APIs deployed using this plugin.

You can find more detailed information about the plugin in the following sections:

* link:{{ '/apim/3.x/apim_kubernetes_controller_quick_start.html' | relative_url }}[Quick Start Guide]
* link:{{ '/apim/3.x/apim_kubernetes_controller_installation.html' | relative_url }}[Installation Guide]
* link:{{ '/apim/3.x/apim_kubernetes_controller_custom_resources.html' | relative_url }}[Custom Resources]
* link:{{ '/apim/3.x/apim_kubernetes_controller_admission_hook.html' | relative_url }}[Admission hook]
