[[apim-kubernetes-operator-installation-cluster]]
= Deploying GKO to a remote cluster
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_kubernetes_operator_installation_cluster.html
:page-folder: apim/kubernetes
:page-layout: apim3x

== Overview

This section provides steps how to deploy the Gravitee Kubernetes Operator (GKO) to an existing remote (cloud) Kubernetes cluster

=== Prerequisites

Before you start the deployment process, ensure that you have access to a remote / cloud-based Kubernetes cluster.

It is also recommended to check the current Kubernetes context to ensure that it is set to the correct cluster:

....
kubectl config current-context
....

NOTE: See the link:https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration[Kubernetes documentation^] for more information on displaying a list of contexts and setting your current context.

=== STEP 1: Deploy the GKO to the cluster

Run the following command in your command-line tool (the working directory does not matter) to deploy the GKO to the cluster of your current Kubernetes context:

....
kubectl apply -f https://github.com/gravitee-io/gravitee-kubernetes-operator/releases/download/0.1.0-alpha.2/bundle.yml
....

The operation is quick and the successful command-line output should similar to the example below:

....
namespace/gko-system created
customresourcedefinition.apiextensions.k8s.io/apidefinitions.gravitee.io created
customresourcedefinition.apiextensions.k8s.io/managementcontexts.gravitee.io created
serviceaccount/gko-controller-manager created
role.rbac.authorization.k8s.io/gko-leader-election-role created
clusterrole.rbac.authorization.k8s.io/gko-manager-role created
clusterrole.rbac.authorization.k8s.io/gko-metrics-reader created
clusterrole.rbac.authorization.k8s.io/gko-proxy-role created
rolebinding.rbac.authorization.k8s.io/gko-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/gko-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/gko-proxy-rolebinding created
configmap/gko-manager-config created
service/gko-controller-manager-metrics-service created
deployment.apps/gko-controller-manager created
....

The GKO is now deployed on your cluster.

=== STEP 2: Create a Management Context custom resource

The next step is to create a Management Context custom resource for your APIM instance.

NOTE: Read more about the Management Context custom resource link:{{ '/apim/3.x/3.x/apim_kubernetes_operator_definitions.html' | relative_url }}[here] and link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_management_context.html' | relative_url }}[here].

To do so, first you need to create a YAML file with the correct Management Context configuration. You can use the following sample YAML file from Gravitee as a template to base your configuration on:

https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/alpha/config/samples/context/k3d/managementcontext_credentials.yaml

The content of this sample file is shown below:

....
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Use this context if you are running APIM and GKO in k3d
apiVersion: gravitee.io/v1alpha1
kind: ManagementContext
metadata:
  name: dev-mgmt-ctx
  namespace: default
spec:
  baseUrl: http://apim-apim3-api.apim-dev.svc:83
  environmentId: DEFAULT
  organizationId: DEFAULT
  auth:
    credentials:
      username: admin
      password: admin
....

In your copy, modify the `spec:` section by providing the actual URL of your APIM instance and the user credentials must match with user configuration.

To create the Management Context resource, run the following command (using the relevant filename):

....
kubectl apply -f your_management_context_credentials_config.yaml
....

If the operation is successful, you should see the following line in the command-line output:

....
managementcontext.gravitee.io/dev-mgmt-ctx created
....


=== STEP 3: Create an API Definition custom resource

The final deployment step is to create an API Definition (`ApiDefinition`) custom resource.

NOTE: Read more about the API Definition custom resource link:{{ '/apim/3.x/3.x/apim_kubernetes_operator_definitions.html' | relative_url }}[here] and link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_api_definition.html' | relative_url }}[here].

To do so, first you need to create a YAML file with the desired API Definition configuration. You can use the following sample YAML file from Gravitee as a template to base your configuration on:

https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/alpha/config/samples/apim/basic-example-with-ctx.yml

The content of this sample file is shown below:

....
#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: basic-api-example
  namespace: default
spec:
  name: "K8s Basic Example With Management Context"
  contextRef:
    name: "dev-mgmt-ctx"
    namespace: "default"
  version: "1.1"
  description: "Basic api managed by Gravitee Kubernetes Operator"
  proxy:
    virtual_hosts:
      - path: "/k8s-basic-with-ctx"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
....

To create the API Definition resource, run the following comand (using the relevant filename):

....
kubectl apply -f your_api_definition_config.yml
....

You now have a new API created in your console. You can check it out in your console URL:

http://<YOUR_CONSOLE_URL>/console/#!/environments/default/

To test the API, you can call it through the APIM Gateway by running the following command using your APIM Gateway URL:

....
curl -i http://<YOUR_GATEWAY_URL>/gateway/k8s-basic-with-ctx
....
