[[apim-kubernetes-operator-definitions]]
= Custom Resource Definitions (CRDs) reference
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_kubernetes_operator_definitions.html
:page-folder: apim/kubernetes
:page-layout: apim3x

[label label-version]#New in version 3.19.0#
[label label-version]#BETA release#

== Overview

The Gravitee Kubernetes Operator comes with three Custom Resource Definitions (CRDs) - `ApiContext`, `ApiDefinition`, and `ApiResource`.


== `ApiContext`

The `ApiContext` custom resource represents the configuration for a Management API.

Resources:

  * The `ApiContext` CRD code is available on link:https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/api/v1alpha1/apicontext_types.go[GitHub^].
  * The `ApiContext` CRD API reference is documented link:{{ '/apim/3.x/apim_kubernetes_operator_api_reference.html#apicontext' | relative_url }}[here].
  * You can learn how to use the `ApiContext` resource in link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_api_context.html' | relative_url }}[this section].

The `ApiContext` refers to a remote Management API. You can have as many `ApiContext` resources as you want, however you need to reference the relevant `ApiContext` from the API Definition in order to indicate to the GKO where the API should be published.

=== Examples

A basic example of an `ApiContext` resource is shown below:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiContext
metadata:
  name: dev-ctx
spec:
  management:
    baseUrl: http://localhost:8083
    auth:
      credentials:
        username: admin
        password: admin
....


The next example shows the same resource but with a Personal Token:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiContext
metadata:
  name: dev-ctx
spec:
  management:
    baseUrl: http://localhost:8083
    auth:
      bearerToken: xxxx-yyyy-zzzz
....

You can then refer to the `ApiContext` from the API, as shown in the example below:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: basic-api-example
spec:
  name: "K8s Basic Example"
  contexts:
  - name: "dev-ctx"
    namespace: "default"
  version: "1.1"
  description: "Basic api managed by Gravitee Kubernetes Operator"
  proxy:
    virtual_hosts:
      - path: "/k8s-basic"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
....

NOTE: Read more about `ApiContext` link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_api_context.html' | relative_url }}[here].

== `ApiDefinition`

The `APIDefinition` custom resource represents the configuration for a single proxied API and its versions. It is similar to a YAML representation of an API Definition in JSON format.

Resources:

  * The `ApiDefinition` CRD code is available on link:https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/api/v1alpha1/apidefinition_types.go[GitHub^].
  * The `ApiDefinition` CRD API reference is documented link:{{ '/apim/3.x/apim_kubernetes_operator_api_reference.html#apidefinition' | relative_url }}[here].
  * You can learn how to use the `ApiDefinition` resource in link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_api_definition.html' | relative_url }}[this section].

=== Workflow

The following workflow is applied when a new `ApiDefinition` resource is added to the cluster:

  1. The GKO listens for `ApiDefinition` resources.
  2. The GKO performs some required changes, such as computing automatically IDs or CrossIDs (for API or Plan).
  3. The GKO converts the definition to JSON format.
  4. The GKO compares the definition to the existing definition. If something has changed, the GKO pushes the definition to the Management API (if an `ApiContext` is provided).
  5. The GKO deploys the API to the API Gateway.

=== Examples

A basic example of an `ApiDefinition` resource is shown below:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: basic-api-example
spec:
  name: "K8s Basic Example"
  version: "1.0"
  description: "Basic api managed by Gravitee Kubernetes Operator"
  proxy:
    virtual_hosts:
      - path: "/k8s-basic"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
....

The same API with support for plans is shown in the example below:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: apikey-example
spec:
  name: "K8s OAuth2 Example"
  version: "1.0"
  description: "Api managed by Gravitee Kubernetes Operator with OAuth2 plan"
  resources:
    - name: "am-demo"
      type: oauth2-am-resource
      configuration:
        version: V3_X
        serverURL: "https://am-nightly-gateway.cloud.gravitee.io"
        securityDomain: "test-jh"
        clientId: "localjh"
        clientSecret: "localjh"
  plans:
    - name: "OAuth2"
      description: "Oauth2 plan"
      security: OAUTH2
      securityDefinition: '{"oauthResource":"am-demo"}'
  proxy:
    virtual_hosts:
      - path: "/k8s-oauth2"
    groups:
      - name: default-group
        endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
....


NOTE: Read more about `ApiDefinition` link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_api_definition.html' | relative_url }}[here].

== `ApiResource`

The `ApiResource` custom resource allows you to use the GKO to create reusable link:{{ '/apim/3.x/apim_resources_overview.html' | relative_url }}[API resources] by applying the `ApiResource` custom resource definition. This enables you to define resources such as cache or authentication providers once only and maintain them in a single place, and then reuse them in multiple APIs - any further updates to such a resource will be automatically propagated to all APIs containing a reference to that resource.

NOTE: Read more about `ApiResource` link:{{ '/apim/3.x/apim_kubernetes_operator_user_guide_reusable_resources.html' | relative_url }}[here].


=== Examples

Here is an example of an `ApiResource` cache resource:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiResource
metadata:
  name: reusable-resource-cache
  namespace: default
spec:
  name: "cache-resource"
  type: "cache"
  enabled: true
  configuration:
      timeToIdleSeconds: 0
      timeToLiveSeconds: 0
      maxEntriesLocalHeap: 1000
....

This reusable resource can then be later referenced in any `ApiDefinition` resource using a reference to its namespaced name in the `resources` field:

....
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: resource-ref-example
  namespace: default
spec:
  name: "Resource reference example"
  version: "1.0"
  description: "An API with a reference to a reusable resource"
  resources:
    - ref:
        name: reusable-resource-cache
        namespace: default
  proxy:
    virtual_hosts:
      - path: "/resource-ref-sample"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
....

== CRD dependencies

=== Resource deletion

Since an `ApiDefinition` can rely on a `ApiContext`, resource deletion is restricted until a check is performed first whether there is an API associated with the respective `ApiContext`. This is achieved through the use of link:https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/[Finalizers^].

== CRD samples

Check out some sample CRDs in the link:https://github.com/gravitee-io/gravitee-kubernetes-operator/tree//config/samples/apim[GKO GitHub repository^].
