[[apim-kubernetes-tools]]
= Gravitee Kubernetes Tools
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_kubernetes_tools.html
:page-folder: apim/kubernetes
:page-layout: apim3x

== Overview

Gravitee provides two Kubernetes tools:

  * The Gravitee Kubernetes Operator (GKO)
  * The Gravitee Kubernetes Controller (plugin)

== Gravitee Kubernetes Operator

[label label-version]#New in version 3.19.0#

APIM 3.19.0 has introduced the Gravitee Kubernetes Operator (GKO) - a new technical component designed to be deployed on an existing APIM-ready Kubernetes Cluster. It can also be deployed on a local cluster for testing purposes.

You can use the GKO to define, deploy, and publish APIs to your API Portal and API Gateway and to manage Custom Resource Definitions (CRDs) as part of the process.

In future releases, the GKO will support additional functionality to enable the following:

  * Using the GKO as an Ingress Controller for deploying Ingresses to an API Gateway.
  * Deploying Gravitee products (API Management, Access Management, Alert Engine).
  * Improving automation processes through covering CICD aspects when using Kubernetes with APIM.
  * Managing most API Management resources without directly relying on the Console or on the Management API.

You can find more detailed information about the Gravitee Kubernetes Operator in the link:{{ '/apim/3.x/apim_kubernetes_operator_overview.html' | relative_url }}[Gravitee Kubernetes Operator] section.

NOTE: The GKO only works with APIM version 3.19.0 (and above).

== Gravitee Kubernetes Controller

APIM 3.7 introduced a Kubernetes plugin for APIM Gateway allowing the deployment of APIs using https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resource Definitions (CRDs)^].

You can find more detailed information about the Gravitee Kubernetes Controller plugin in the link:{{ '/apim/3.x/apim_kubernetes_controller_overview.html' | relative_url }}[Gravitee Kubernetes Controller] section.
