= Docker Images Install
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installation_guide_docker_images.html
:page-folder: apim/installation-guide/docker
:page-layout: apim3x
:page-description: Gravitee.io API Management - Installation Guide - Docker - Images
:page-keywords: Gravitee.io, API Management, apim, guide, manual, docker, images, linux
:page-liquid:
:table-caption!:

This page describes how to install and run APIM in Docker containers on `localhost` using the `docker` command and a specified filesystem for persistence and plugins. 

== Prerequisites

Docker must be installed and running. For more information about installing Docker, see the link:{{'https://www.docker.com/' | relative_url }}[Docker website].

== Installing APIM

1. Create the following filesystem.
+
[code,bash]
----
mkdir /gravitee/mongodb
mkdir /gravitee/mongodb/data
mkdir /gravitee/elasticsearch
mkdir /gravitee/elasticsearch/data
mkdir /gravitee/apim-gateway
mkdir /gravitee/apim-gateway/plugins
mkdir /gravitee/apim-gateway/logs
mkdir /gravitee/apim-management-api
mkdir /gravitee/apim-management-api/plugins
mkdir /gravitee/apim-management-api/logs
mkdir /gravitee/apim-management-ui
mkdir /gravitee/apim-management-ui/logs
mkdir /gravitee/apim-portal-ui
mkdir /gravitee/apim-portal-ui/logs
----

2. Create two Docker bridge networks, using the following commands.
+
[source,bash]
----
docker network create graviteestorage
docker network create graviteefrontend
----
+
The `graviteestorage` network is for storage communication, and the `graviteefrontent` network is for frontend communication.

3. Install MongoDB using the following commands.
+
[source,bash]
----
docker pull mongo:3.6
docker run --name gravitee-mongo \
  --net graviteestorage \
  --volume /gravitee/mongodb/data:/data/db \
  --detach mongo:3.6
----
+
Note that MongoDB is on the `graviteestorage` network and uses `/gravitee/mongodb` for persistent storage.

4. Install Elasticsearch using the following commands.
+
[source,bash]
----
docker pull docker.elastic.co/elasticsearch/elasticsearch:7.7.0
docker run --name gravitee-elasticsearch \
  --net graviteestorage \
  --env http.host=0.0.0.0 \
  --env transport.host=0.0.0.0 \
  --env xpack.security.enabled=false \
  --env xpack.monitoring.enabled=false \
  --env cluster.name=gravitee-elasticsearch \
  --env bootstrap.memory_lock=true \
  --env discovery.type=single-node \
  --env "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
  --volume /gravitee/elasticsearch/data:/usr/share/elasticsearch/data \
  --detach docker.elastic.co/elasticsearch/elasticsearch:7.7.0
----
+
Note that Elasticsearch is on the `graviteestorage` network and uses `/gravitee/elasticsearch` for persistent storage.

5. Install the API Management Gateway using the following commands.
+
[source,bash]
----
docker pull graviteeio/apim-gateway:latest
docker run --publish 8082:8082 \
  --volume /gravitee/apim-gateway/plugins:/opt/graviteeio-gateway/plugins-ext \
  --volume /gravitee/apim-gateway/logs:/opt/graviteeio-gateway/logs \
  --env gravitee_management_mongodb_uri="mongodb://gravitee-mongo:27017/gravitee-apim?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000" \
  --env gravitee_ratelimit_mongodb_uri="mongodb://gravitee-mongo:27017/gravitee-apim?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000" \
  --env gravitee_reporters_elasticsearch_endpoints_0="http://gravitee-elasticsearch:9200" \
  --env gravitee_plugins_path_0=/opt/graviteeio-gateway/plugins \
  --env gravitee_plugins_path_1=/opt/graviteeio-gateway/plugins-ext \
  --net graviteestorage \
  --name gravitee-apim-gateway \
  --detach graviteeio/apim-gateway:latest
docker network connect graviteefrontend gravitee-apim-gateway
----
+
Note that the API Management Gateway is on both the `graviteestorage` and `graviteefrontend` networks, and it uses `/gravitee/apim-gateway` for persistent storage. 

6. Install the API Management REST API using the following commands.
+
[source,bash]
----
docker pull graviteeio/apim-management-api:latest
docker run --publish 8083:8083 \
  --volume /gravitee/apim-management-api/plugins:/opt/graviteeio-management-api/plugins-ext \
  --volume /gravitee/apim-management-api/logs:/opt/graviteeio-management-api/logs \
  --env gravitee_management_mongodb_uri="mongodb://gravitee-mongo:27017/gravitee-apim?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000" \
  --env gravitee_analytics_elasticsearch_endpoints_0="http://gravitee-elasticsearch:9200" \
  --env gravitee_plugins_path_0=/opt/graviteeio-management-api/plugins \
  --env gravitee_plugins_path_1=/opt/graviteeio-management-api/plugins-ext \
  --net graviteestorage \
  --name gravitee-apim-management-api \
  --detach graviteeio/apim-management-api:latest
docker network connect graviteefrontend gravitee-apim-management-api
----
+
Note that the API Management REST API is on both the `graviteestorage` and `graviteefrontend` networks, and it uses `/gravitee/apim-api` for persistent storage. 

7. Install the API Management Management UI using the following commands.
+
[source,bash]
----
docker pull graviteeio/apim-management-ui:latest
docker run --publish 8084:8080 \
  --volume /gravitee/apim-management-ui/logs:/var/log/nginx \
  --net graviteefrontend \
  --name gravitee-apim-management-ui \
  --env MGMT_API_URL=http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT \
  --detach graviteeio/apim-management-ui:latest
----
+
Note that the API Management UI is on the `graviteefrontend` network, and it uses `/gravitee/apim-management-ui` for persistent storage. 

8. Install the API Management Portal UI using the following commands.
+
[source,bash]
----
docker pull graviteeio/apim-portal-ui:latest
docker run --publish 8085:8080 \
  --volume /gravitee/apim-portal-ui/logs:/var/log/nginx \
  --net graviteefrontend \
  --name gravitee-apim-portal-ui \
  --env PORTAL_API_URL=http://localhost:8083/portal/environments/DEFAULT \
  --detach graviteeio/apim-portal-ui:latest
----
Note that the API Management Portal UI is on the `graviteefrontend` network, and it uses `/gravitee/apim-portal-ui` for persistent storage.

9. In your browser, go to `http://localhost:8084` to open the APIM UI. You can log in with the Username `admin` and Password `admin`.
