= Quick Install with Docker Compose  (Enterprise Edition)
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installation_guide_docker_compose_quickstart_ee.html
:page-folder: apim/installation-guide/docker
:page-layout: apim3x

This page describes how to install and run APIM Enterprise Edition in Docker containers on `localhost` using the `docker compose` command.

== Prerequisites

Docker must be installed and running. For more information about installing Docker, see the link:{{'https://www.docker.com/' | relative_url }}[Docker website].

You must have a license key for the APIM Enterprise Edition. For more information about getting a license key, visit the link:https://www.gravitee.io/pricing[Gravitee pricing page].

== Installing APIM

1. Download the `docker-compose.yml` file as `docker-compose-apim-ee.yml`.
+
[code,bash]
----
curl https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml -o docker-compose-apim-ee.yml  
----

2. Open `docker-compose-apim-ee.yml` in a text editor, and under `/services/gateway/volumes` add the following line.
+
[code,yml]
----
 - /gravitee/license.key:/opt/graviteeio-gateway/license/license.key
----
+
Where `/gravitee/license.key` is the full path to the license key. This ensures that the gateway can access the license key.

3. Under `/services/management_api/volumes` add the following line.
+
[code,yml]
----
 - /gravitee/license.key:/opt/graviteeio-gateway/license/license.key
----
+
Where `/gravitee/license.key` is the full path to the license key. This ensures that the management API can access the license key.

4. Create a file called `.env` and add the following line to it.
+
[code]
----
APIM_VERSION=3.20.0-ee
----
+
This ensures you are using the correct version of APIM.

5. Run `docker compose` to download and start all of the components.
+
[code,bash]
----
docker compose -f docker-compose-apim-ee.yml up -d
----

6. In your browser, go to `http://localhost:8084` to open the Console. You can log in with the Username `admin` and Password `admin`.
+
[TIP]
====
Sometimes it can take a few minutes for APIM to fully start. If you get an error when going to `http://localhost:8084`, wait a few minutes and try again.
====