= Docker Compose
:page-toc: false
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_docker_compose.html
:page-folder: apim/installation-guide/docker
:page-layout: apim3x
:docker-image-src: https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/images
:github-repo: https://github.com/gravitee-io/gravitee-docker
:docker-hub: https://hub.docker.com/r/graviteeio

IMPORTANT: We assume that you are familiar with Docker. +
To run our official images, you must start by installing https://docs.docker.com/installation/[Docker, window=\"_blank\"]

Gravitee.io docker images are https://hub.docker.com/u/graviteeio/[available on Docker Hub, window=\"_blank\"].
You could find all https://github.com/gravitee-io/gravitee-docker/[Dockerfiles on GitHub, window=\"_blank\"].

== Run Gravitee.io API Management

You can launch a complete Gravitee.io API Management stack using our ready-to-use docker-compose file.

This latest is including Gravitee.io API Management + MongoDB + Elasticsearch.

[WARNING] 
.Elasticsearch configuration
====
Before running the commands below:

. Make sure you have the minimum vm.max_map_count property set in order to run Elasticsearch properly. https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html[Click here, window=\"_blank\"] to see how to check the current value and update if necessary.
. Make sure the folder (e.g. `elasticsearch`) defined as the ES volume, within the docker-compose file, is https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_configuration_files_must_be_readable_by_the_elasticsearch_user[readable by elasticsearch user, window=\"_blank\"]: `sudo chmod g+rwx elasticsearch/ && sudo chgrp 0 elasticsearch/`
====

[source,shell]
....
# Download docker-compose file
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml -o "docker-compose.yml"

# (Optional step: pull to ensure that you are running latest images)
$ docker-compose pull

# And run...
$ docker-compose up
....

== Check your platform

When all components are started, you can do a quick test to see if everything is ok by checking these urls:

|===
|Component |URL| Expected

|API Gateway
|http://localhost:8082/
|Must return 404 status code, with a `No context-path matches the request URI` payload.

|Management API
|http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis
|Must return a 200 status code, with a `[]` payload.

|Management UI
|http://localhost:8084/
|Must return a 200 status code, showing the Management UI

|Portal UI
|http://localhost:8085/
|Must return a 200 status code, showing the Portal

|===

Once done, you're now ready to play with Gravitee.io API Management, so let's take a look to the link:/apim/3.x/apim_quickstart_publish.html[Quickstart guide].
