= Quick Install with Docker Compose
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installation_guide_docker_compose_quickstart.html
:page-folder: apim/installation-guide/docker
:page-layout: apim3x

This page describes how to install and run APIM in Docker containers on `localhost`.

== Prerequisites

Docker must be installed and running. For more information about installing Docker, see the link:{{'https://www.docker.com/' | relative_url }}[Docker website].

== Installing APIM

1. Download the `docker-compose.yml` file as `docker-compose-apim.yml`.
+
[code,bash]
----
curl https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml -o docker-compose-apim.yml  
----

2. Create a file called `.env` and add the following line to it.
+
[code]
----
APIM_VERSION=3.20.0
----
+
This ensures you are using the correct version of APIM.

3. Run `docker compose` to download and start all of the components.
+
[code,bash]
----
docker compose -f docker-compose-apim.yml up -d
----

4. In your browser, go to `http://localhost:8084` to open the APIM UI. You can log in with the Username `admin` and Password `admin`.
+
[TIP]
====
Sometimes it can take a few minutes for APIM to fully start. If you get an error when going to `http://localhost:8084`, wait a few minutes and try again.
====