= Install Cockpit Console
:page-sidebar: cockpit_sidebar
:page-permalink: cockpit/3.x/cockpit_installguide_management_ui_install_zip.html
:page-folder: cockpit/installation-guide
:page-description: Gravitee.io Cockpit - Management UI - Installation with .zip
:page-keywords: Gravitee.io, API Platform, API Management, Cockpit, documentation, manual, guide, reference, api

== Prerequisites

Your environment must meet the requirements listed below before you install Cockpit Console.

NOTE: Before you begin, ensure Cockpit API is installed and running.

=== Browsers

Cockpit Console is compatible with the two most recent versions of modern internet browsers.

== Download and extract the .zip archive

. Download the binaries https://download.gravitee.io/graviteeio-cockpit/components/gravitee-cockpit-webui/gravitee-cockpit-webui-{{ site.products.cockpit.version }}.zip[here^].
+
[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-cockpit/components/gravitee-cockpit-webui/gravitee-cockpit-webui-{{ site.products.cockpit.version }}.zip -o gravitee-cockpit-webui-{{ site.products.cockpit.version }}.zip
+
Unpack the archive and place the folders in the required location.
+
[source,bash]
[subs="attributes"]
$ unzip gravitee-cockpit-webui-{{ site.products.cockpit.version }}.zip

== Deploy or run Cockpit Console

Cockpit Console is a client-side Angular application and can be deployed on any HTTP server, such as https://httpd.apache.org/[Apache^] or http://nginx.org/[Nginx^].

NOTE: Cockpit Console uses HTML5 mode and requires server side rewrites to make it work, such as in the Apache and Nginx examples below.

=== Apache

----
<VirtualHost *:80>
    ServerName my-app

    DocumentRoot /path/to/app

    <Directory /path/to/app>
        RewriteEngine on

        # Don't rewrite files or directories
        RewriteCond %{REQUEST_FILENAME} -f [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [L]

        # Rewrite everything else to index.html to allow html5 state links
        RewriteRule ^ index.html [L]
    </Directory>
</VirtualHost>
----

=== Nginx

----
server {
    server_name my-app;

    index index.html;

    root /path/to/app;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
----
