= Javascript Policy
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_policies_javascript.html
:page-folder: apim/user-guide/publisher/policies
:page-liquid:
:page-layout: apim3x
:page-description: Gravitee.io API Management - Policies - Javascript
:page-keywords: Gravitee.io, API Management, apim, guide, policy, javascript
:page-toc: true

// author: Tom Geudens
// based on but NOT including https://gh.gravitee.io/gravitee-io/gravitee-policy-javascript/master/README.adoc

WARNING: The JavaScript policy is not included by default. To use this policy, you must download and install the plugin.

== Phases
|===
|onRequest|onResponse|onRequestContent|onResponseContent

|X|X|X|X
|===

== Description
You can use this policy to run http://www.javascript.com/[Javascript^] scripts at every stage of gateway processing.

== Phase - onRequest

As an example of what you can do in the **onRequest** phase, this script stops the processing if the request contains a certain header.
[source, javascript]
----
if (request.headers.containsKey('X-Gravitee-Break')) {
    result.state = State.FAILURE;
    result.code = 500
    result.error = 'Stopped processing due to X-Gravitee-Break header'
} else {
    request.headers.set('X-Javascript-Policy', 'ok');
}
----

In the **onRequest** phase you have access to the **request** object and the **context** object.
|===
|Object | Property | Type | Description

|request | id | string | - 
|request | transactionId | string | - 
|request | uri | string | - 
|request | path | string | - 
|request | pathInfo | string | - 
|request | contextPath | string | - 
|request | parameters | multivalue map | - 
|request | pathParameters | multivalue map | - 
|request | headers | iterable map <string, string> | - 
|request | method | enum | - 
|request | version | enum | - 
|request | timestamp | long | - 
|request | remoteAddress | string | - 
|request | localAddress | string | - 
|request | scheme | string | -
|request | sslSession | javax.net.ssl.SSLSession | - 
|request | metrics | <<metricsobject,object>> | - 
|===

The **context** object doesn't have known properties as such, it contains the attributes of the execution environment. And you can add some yourself too. For example, this could be the first line of your **onRequest** script:
[source, javascript]
----
context.setAttribute('custom-policy-start',Date.now());
----
That probably doesn't look all that exciting, but wait until the **onResponse** script and you'll see! The **context** object gives you access to the following methods:
|===
|Object | Method | Description

|context | Object getAttribute(String) | -
|context | void setAttribute(String, Object) | -
|context | void removeAttribute(String) | -
|context | Map<String, Object> getAttributes() | -
|===
 
== Phase - onRequestContent
In the **onRequestContent** phase you have access to the **content** object, also known as the https://dzone.com/articles/rest-api-path-vs-request-body-parameters[request body^]. You can modify this object.

As an example, assuming the following request body:
[source, json]
----
[
    {
        "age": 32,
        "firstname": "John",
        "lastname": "Doe"
    }
]
----

Then you can do the following:
[source, javascript]
----
var content = JSON.parse(request.content);
content[0].firstname = 'Hacked ' + content[0].firstname;
content[0].country = 'US';

JSON.stringify(content);
----

And the request body being passed to the API would be:
[source, json]
----
[
    {
        "age": 32,
        "firstname": "Hacked John",
        "lastname": "Doe",
        "country": "US"
    }
]
----

== Phase - onResponse
In the **onResponse** phase you have access to the **request**, the **response** and the **context** object.
|===
|Object | Property | Type | Description

|response | status | int | -
|response | reason | String | -
|response | headers | iterable map <string, string> | - 
|===

As an example of what you can do in the **onResponse** phase, this script modifies the headers. And it uses the custom **context** attribute you set in the **onRequest** phase too:
[source, javascript]
----
response.headers.remove('Server');
response.headers.set('Server', 'Powered by Gravitee');
response.headers.set('X-Time-Elapsed', String(Date.now() - context.getAttribute('custom-policy-start')));
----

== Phase - onResponseContent
In the **onResponseContent** phase you have access to the **content** object, also known response message. You can modify this object.

As an example, assume that you sent the request body modified in the **onRequestContent** phase to an **echo** API. You can do the following:
[source, javascript]
----
var content = JSON.parse(response.content);
content[0].firstname = content[0].firstname.substring(7);
delete content[0].country;
JSON.stringify(content);
----

And the reponse message would be:
[source, json]
----
[
    {
        "age": 32,
        "firstname": "John",
        "lastname": "Doe"
    }
]
----

== Reference - Metrics [[metricsobject]]
It is highly advisable to use the link:/apim/3.x/apim_policies_metrics_reporter.html[Metrics Reporter] in order to manage the metrics. However, the request object does contain a **metrics** object.

|===
|Object | Property | Type | Description

|metrics | api | String | ID of the API
|metrics | apiResponseTimeMs | long | Response time spend to call the backend upstream
|metrics | application | String | ID of the consuming application
|metrics | endpoint | String | -
|metrics | errorKey | String | Key of the error if the policy chain is failing
|metrics | host | String | Host header value
|metrics | httpMethod | enum | -
|metrics | localAddress | String | -
|metrics | log | object | -
|metrics | mappedPath | String | -
|metrics | message | String | - 
|metrics | path | String | - 
|metrics | plan | String | ID of the plan
|metrics | proxyLatencyMs | long | Latency of the gateway to apply policies
|metrics | proxyResponseTimeMs | long | Global response time to process and respond to the consumer
|metrics | remoteAddress | String | - 
|metrics | requestContentLength | long | -
|metrics | requestId | String | -
|metrics | responseContentLength | long | -
|metrics | securityToken | String | -
|metrics | securityType | enum | -
|metrics | status | int | -
|metrics | subscription | String | ID of the subscription
|metrics | tenant | String | gateway tenant value
|metrics | transactionId | String | -
|metrics | uri | String | -
|metrics | user | String | End-user doing the call (in case of OAuth2 / JWT / Basic Auth)
|metrics | userAgent  | String | Value of the user-agent header
|metrics | zone | String | Gateway zone
|===

WARNING: The metrics object changes in the different processing phases and some properties may not make sense in certain phases!
