= Security

== Brute Force attack

It consists of submitting lots authentication requests based on many passwords expecting one guessing right.
More details on : https://en.wikipedia.org/wiki/Brute-force_attack.
Even with oauth2 activated you can leave login form for in-memory or local users. Some tools can help you to prevent malicious actions by banning IP.

== Fail2Ban

In this part we explain you how to secure APIM UI and REST API against brute force attack.
To install fail2ban follow Official fail2ban website : https://www.fail2ban.org

=== Configuration

Gravitee.io API REST trace all authentication failure into gravitee log file.
Firstly you have to configure fail2ban filter to extract Gravitee authentication failure event.

[source,shell]
----
2019-05-03 16:03:03.304 [gravitee-listener-31] WARN  i.g.m.s.l.AuthenticationFailureListener - Authentication failed event for : admin - IP : 10.50.24.18
----

Add a conf file to declare filter : /etc/fail2ban/filter.d/gravitee.conf

[source,ini]
----
[Definition]
failregex = .*Authentication failed event for.*IP : <HOST>
ignoreregex =
----

Now you have to provide actions to fail2ban in  /etc/fail2ban/action.d/gravitee.conf.
Action are iptables or firewalld commands.

[source,ini]
----
[INCLUDES]

before = iptables-common.conf

[Definition]

# Option:  actionstart
# Notes.:  command executed once at the start of Fail2Ban.
# Values:  CMD
#
actionstart = <iptables> -N f2b-<name>
              <iptables> -A f2b-<name> -j <returntype>
              <iptables> -I <chain> -p <protocol> --dport <port> -j f2b-<name>

# Option:  actionstop
# Notes.:  command executed once at the end of Fail2Ban
# Values:  CMD
#
actionstop = <iptables> -D <chain> -p <protocol> --dport <port> -j f2b-<name>
             <iptables> -F f2b-<name>
             <iptables> -X f2b-<name>

# Option:  actioncheck
# Notes.:  command executed once before each actionban command
# Values:  CMD
#
actioncheck = <iptables> -n -L <chain> | grep -q 'f2b-<name>[ \t]'

# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionban = <iptables> -I f2b-<name> 1 -p tcp -m string --algo bm --string 'X-Forwarded-For: <ip>' -j DROP

# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionunban = <iptables> -D f2b-<name> -p tcp -m string --algo bm --string 'X-Forwarded-For: <ip>' -j DROP

[Init]

----

Finally juste declare the new Gravitee Fail2ban block in the main configuration file.
Up to you to provide right parameters. Each time you modify fail2ban configuration resources you have to restart the service.

[source,ini]
----
[gravitee]
banaction = gravitee
logpath = /opt/gravitee-io-management-api/logs/management_api.log
filter = gravitee
enabled = true
maxretry = 3
----


