= Configuring AM

The following sections explain how to configure AM after installation. For a quick guide to configuring a new environment after installation, see link:/Getstarted/quickstart-am/configuration-quickstart.html[How to configure a production-ready AM environment^]

== Configuring AM Gateway and AM API

There are three different ways to configure these components:

 - Environment variables
 - System properties
 - `gravitee.yml`

The order in which they are listed above corresponds to their order of precedence. In other words, environment variables override the other two configuration types, and system properties override `gravitee.yml`.

== gravitee.yml

The `gravitee.yml` file, found in `GRAVITEE_HOME/config/`, is the default way to configure the components.

WARNING: YAML (`yml`) format is very sensitive to indentation. Ensure you include the correct number of spaces and use spaces instead of tabs.

== Environment variables

You can override the default AM configuration (`gravitee.yml`) and system properties by defining environment variables.

To override this property:

[source,yaml]
----
management:
  mongodb:
    dbname: myDatabase
----

Define one of the following variables:

----
GRAVITEE_MANAGEMENT_MONGODB_DBNAME=myDatabase
GRAVITEE.MANAGEMENT.MONGODB.DBNAME=myDatabase
gravitee_management_mongodb_dbname=myDatabase
gravitee.management.mongodb.dbname=myDatabase
----

WARNING: Some properties are case sensitive and cannot be written in uppercase (for example,
`gravitee_security_providers_0_tokenIntrospectionEndpoint`. We advise you to define environment variables in lowercase and use the correct syntax for each property.

TIP: In some systems, hyphens are not allowed in variable names. For example, you may need to write `gravitee_policy_apikey_header` as `gravitee_policy_api-key_header`.

=== How to manage arrays?

Some properties are arrays. For example:
[source,yaml]
----
analytics:
  elasticsearch:
    endpoints:
      - https://my.first.endpoint.com
      - https://my.second.endpoint.com

security:
  providers:
    - type: ldap
      context-source-username: "cn=Directory Manager"
      context-source-password: "password"
----

Below are some examples of how to write your environment variables. In case of doubt, we recommend you try both.

----
gravitee_analytics_elasticsearch_endpoints_0=https://my.first.endpoint.com
gravitee_analytics_elasticsearch_endpoints_1=https://my.second.endpoint.com

gravitee_security_providers_0_type=ldap
gravitee_security_providers_0_context-source-username=cn=Directory Manager
gravitee_security_providers_0_context-source-password=password
----

or

----
gravitee.analytics.elasticsearch.endpoints[0]=https://my.first.endpoint.com
gravitee.analytics.elasticsearch.endpoints[1]=https://my.second.endpoint.com

gravitee.security.providers[0]type=ldap
gravitee.security.providers[0]context-source-username=cn=Directory Manager
gravitee.security.providers[0]context-source-password=password
gravitee.security.providers[0].users[1].password=password
----

== System properties

You can override the default AM configuration (`gravitee.yml`) by defining system properties.

To override this property:

[source,yaml]
----
management:
  mongodb:
    dbname: myDatabase
----

Add this property to the JVM:

----
-Dmanagement.mongodb.dbname=myDatabase
----
