= Install APIM API
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_rest_apis_install_zip.html
:page-folder: apim/installation-guide/with-zip
:page-liquid:
:page-description: Gravitee.io API Management - Management API - Installation with .zip
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

== Overview

APIM API includes nodes for both of the UI components (APIM Management and APIM Portal). You must install the relevant APIM API node first before you can use the corresponding UI component.

This section describes how to install APIM API and test the nodes are running.

== Prerequisites

Your environment must meet the requirements listed below before you install the APIM API.

=== JDK

The APIM API requires at least Java 11. Before you install it, check your Java version as follows:

[source,bash]
----
java -version
echo $JAVA_HOME
----

NOTE: You can download the latest OpenJDK from https://jdk.java.net/archive/[OpenJDK Download Site, window=\"_blank\"].

=== MongoDB and Elasticsearch

The default APIM API distribution requires link:/apim/3.x/apim_installguide_repositories_mongodb.html[MongoDB] to store mandatory data and link:/apim/3.x/apim_installguide_repositories_elasticsearch.html[Elasticsearch] to store reporting data.

NOTE: You can download MongoDB from the https://www.mongodb.org/downloads#production[MongoDB download site, window=\"_blank\"]
and Elasticsearch from the https://www.elastic.co/downloads/elasticsearch[Elasticsearch download site, window=\"_blank\"].

== Download and extract the `.zip` archive

Note that the archive includes the binaries for all the APIM components, so if you previously downloaded it to install another component, you do not need to download it again.

. Download the binaries https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip[here] or from the https://gravitee.io/downloads/api-management[Gravitee downloads page].

[source,bash]
----
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-{{ site.products.apim._3x.version }}.zip -o gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

[start=2]
. Extract the `graviteeio-rest-api-xxx` directory from the archive and place it in the required location.

[source,bash]
----
$ unzip gravitee-standalone-distribution-{{ site.products.apim._3x.version }}.zip
----

== Run APIM API from the command line

You start APIM API from the command line as follows:

[source,bash]
----
$ cd graviteeio-rest-api-{{ site.products.apim._3x.version }}
$ ./bin/gravitee
----

By default, APIM API runs in the foreground, prints its logs to standard output (stdout), and can be stopped
by pressing **Ctrl-C**.

NOTE: Both APIM API nodes run by default. You can configure APIM to run only one or the other, as described in the link:/apim/3.x/apim_installguide_rest_apis_configuration.html[APIM API configuration] section.

Once APIM API is running, you will see a log such as this one:

[source,bash]
[subs="attributes"]
...
11:01:53.162 [main] INFO  i.g.r.a.s.node.GraviteeApisNode - Gravitee.io - Rest APIs id[2e05c0fa-8e48-4ddc-85c0-fa8e48bddc11] version[{{ site.products.apim._3x.version }}] pid[24930] build[175] jvm[AdoptOpenJDK/OpenJDK 64-Bit Server VM/12.0.1+12] started in 8042 ms.
...

== Check Management API is running

You can test that your Management API node is running by sending an HTTP request to port `8083` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis
----

You will receive a response something like this:

[source,json]
----
[]
----

== Check Portal API is running

You can test that your Portal API node is running by sending an HTTP request to port `8083` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8083/portal/environments/DEFAULT/apis
----

You will receive a response something like this:

[source,json]
----
{
  "data" : [ ],
  "metadata" : {
    "data" : {
      "total" : 0
    }
  }
}
----

== Run APIM API as a daemon

To run APIM API as a daemon, specify `-d` on the command line and record the process ID in a file using option `-p`:

[source,bash]
----
$ ./bin/gravitee -d -p=/var/run/gio.pid
----

You can find log messages in the `$GRAVITEE_HOME/logs/` directory.

To shut down APIM API, kill the process ID recorded in the `pid` file:

[source,bash]
----
$ kill `cat /var/run/gio.pid`
----

== APIM API directory structure

The `.zip` and (`.tar.gz`) package is entirely self-contained. All files and directories are, by default, contained within
`$GRAVITEE_HOME`, the directory created when extracting the archive.

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Location  |Description
|bin       |Binary scripts including `gravitee` to start a node
|config    |Configuration files including `gravitee.yml`
|lib       |Libraries (Gravitee.io libraries and third party libraries)
|logs      |Log file location
|plugins   |Plugin file location
|data      |Search engine metadata
|templates |API templates
|======================
