= Upgrade to 3.0.0

== Important
If you are using mongoDB, it is *strongly recommended* to run the scripts to upgrade your database *before* starting the new version of the gravitee REST APIs.
Otherwise, you could experience data corruption issues.

IMPORTANT: Mongo version *MUST* be at least *3.6*

== General

=== Organization & Environment
In this new version Gravitee comes with a new way of managing your environments.
By default, Gravitee is configured with a first Organization:
```
organization {
  id: DEFAULT,
  name: Default organization
}
```
And a first Environment in this Organization:
```
environment {
  id: DEFAULT,
  name: Default environment,
  organization: DEFAULT
}
```

It will allow you to manage more than one environment for each instance of Gravitee.

== Breaking Changes
=== API-Key policy
In this new version, if api-keys used to call an API is invalid or has expired, the gateway will fail with a *401* (instead of 403 in previous versions of Gravitee).

=== Management API
If you are using the REST API directly, please note that you will have to adapt the URL
from `https://host/management/` to `https://host/management/organizations/DEFAULT/environments/DEFAULT/`

The resource `/views/default` has been deleted since a view does not have a *default* field anymore.

=== Management UI
The actual portal has been replaced by a brand new version, with its own location. As a consequence, the URL of the management UI has been modified to remove the */management* part.

For instance, to access the _Platform Overview_ page, you should use `https://host/\#!/platform` instead of `https://host/#!/management/platform`

=== Memberships, roles and role mappings
One major breaking change in this new version is the replacement of *MANAGEMENT* and *PORTAL* scopes by *ENVIRONNMENT* and *ORGANIZATION* scopes. It's not just a renaming but a dispatch of permissions among these 2 news scopes. As a consequence, all existing memberships, roles, groups and Identity Providers role mappings should be updated.

* Memberhips, roles and groups have to be updated with migration scripts <<mongodb, here>>
* Role Mappings for Identity Providers stored in database will be updated with a specific upgrader. See <<upgrader, Upgrader>>
* Role mappings defined in the *gravitee.yml* file have to be updated with these new scopes.

Here's a correlation table of permissions before and after migration :
[options="header"]
|=============
|Permission Name |Scope Name before migration |Scope name after migration
|INSTANCE                     |MANAGEMENT  |ENVIRONMENT
|GROUP                        |MANAGEMENT  |ENVIRONMENT
|TAG                          |MANAGEMENT  |ENVIRONMENT
|TENANT                       |MANAGEMENT  |ENVIRONMENT
|API                          |MANAGEMENT  |ENVIRONMENT
|ROLE                         |MANAGEMENT  |ORGANIZATION
|APPLICATION                  |MANAGEMENT  |ENVIRONMENT
|PLATFORM                     |MANAGEMENT  |ENVIRONMENT
|AUDIT                        |MANAGEMENT  |ENVIRONMENT
|NOTIFICATION                 |MANAGEMENT  |ENVIRONMENT
|USER                         |MANAGEMENT  |ORGANIZATION
|MESSAGE                      |MANAGEMENT  |ENVIRONMENT
|DICTIONARY                   |MANAGEMENT  |ENVIRONMENT
|ALERT                        |MANAGEMENT  |ENVIRONMENT
|ENTRYPOINT                   |MANAGEMENT  |ENVIRONMENT
|SETTINGS                     |MANAGEMENT  |ENVIRONMENT
|DASHBOARD                    |MANAGEMENT  |ENVIRONMENT
|QUALITY_RULE                 |MANAGEMENT  |ENVIRONMENT
|METADATA                     |PORTAL      |ENVIRONMENT
|DOCUMENTATION                |PORTAL      |ENVIRONMENT
|APPLICATION                  |PORTAL      |ENVIRONMENT
|VIEW                         |PORTAL      |ENVIRONMENT
|TOP_APIS                     |PORTAL      |ENVIRONMENT
|SETTINGS                     |PORTAL      |ENVIRONMENT
|API_HEADER                   |PORTAL      |ENVIRONMENT
|IDENTITY_PROVIDER            |PORTAL      |ENVIRONMENT
|CLIENT_REGISTRATION_PROVIDER |PORTAL      |ENVIRONMENT
|=============

== Repository
=== Mongodb

Before running any script, please create a dump of your existing database.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.x/3.0.0/mongodb/1-collections-linked-to-environment-or-organization.js[upgrades/3.x/3.0.0/mongodb/1-collections-linked-to-environment-or-organization.js]::
This script adds new fields that refer the default environment or the default organization.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.x/3.0.0/mongodb/2-roles-groups-and-memberships-migration.js[upgrades/3.x/3.0.0/mongodb/2-roles-groups-and-memberships-migration.js]::
This script migrates permission values in roles since MANAGEMENT roles and PORTAL roles have been merged and dispatched into new ENVIRONMENT and ORGANIZATION roles.
It also updates memberships and groups by adding or removing columns.
All previous indexes for *roles* and *memberships* will be deleted and replaced by new indexes.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.x/3.0.0/mongodb/3-replace-apiArray-by-unique-api.js[upgrades/3.x/3.0.0/mongodb/3-replace-apiArray-by-unique-api.js]::
This script adds a new field that refers the api and remove the api array.
All previous indexes for *plans* will be deleted and replaced by new indexes.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.x/3.0.0/mongodb/4-remove-devMode.js[upgrades/3.x/3.0.0/mongodb/4-remove-devMode.js]::
This script removes the 'devMode' parameter, since the legacy portal has been replaced.

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.x/3.0.0/mongodb/5-remove-orphan-documentation-pages.js[upgrades/3.x/3.0.0/mongodb/5-remove-orphan-documentation-pages.js]::
Due to a bug in a previous version of gravitee when importing APIs, orphan pages may have been created. Orphan pages are all pages with a parentId but no page with such id exists.
In some situation, this can lead to errors when accessing portal or apis documentation.
You may use this script to find and remove orphan pages.

_Note: You can make a 'dry run' by commenting line 6 and uncommenting line 5._

https://raw.githubusercontent.com/gravitee-io/release/master/upgrades/3.x/3.0.0/mongodb/6-remove-ALL-view-and-defaultView-field.js[upgrades/3.x/3.0.0/mongodb/6-remove-ALL-view-and-defaultView-field.js]::
This script removes the 'All' *view*, since the legacy portal has been replaced and the new portal does not need this default view anymore. The script also updates existing views to remove *defaultView* field.

== Upgrader
=== Identity providers
Because of the evolution of the roles and their scope, role mappings in *Identity Providers* must be updated. To achieve this, a specific service has been created and will be launched at APIM startup. As this is not necessary to launch this service more than once, it can be disabled with some configuration.
[source, yaml]
----
services:
  # v3 upgrader service. Can be disabled after first launch.
  v3-upgrader:
    enabled: true
----

== Docker

Docker images for Gravitee.io APIM have been renamed to follow the same conventions as the others Gravitee.io modules.

In the case of Gravitee.io APIM, all the images have been prefixed by `-apim`.

For example, for the API gateway `graviteeio/gateway` has been replaced by `graviteeio/apim-gateway`.

Please have a look to the documentation at: https://docs.gravitee.io/apim/3.x/apim_installguide_docker_images.html
