---
layout: doc
product: API Management
permalink: apim/current/apim_getstarted_quickinstallation.html
toc: true
sidebar: gettingstarted_sidebar
title: Quick APIM installation
---

[[gravitee-installation-guide-quickstart]]

:page-description: Gravitee.io API Management - Installation - Quickstart
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

= APIM quick installation

This guide assumes you are starting fresh and have no existing API Management data.

== Install with RPMs

[source,shell]
....
$ curl -sSL https://bit.ly/install-apim-3x | bash
....

For more information, see link:/apim/3.x/apim_installguide_redhat_stack.html[Install on RedHat].

== Install with Docker

[source,shell]
....
# Download docker-compose file
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/apim/3.x/docker-compose.yml -o "docker-compose.yml"

# (Optional step: pull to ensure that you are running latest images)
$ docker-compose pull

# And run...
$ docker-compose up
....

For more information, see link:/apim/3.x/apim_installguide_docker_compose.html[Run on Docker].

== Install with Kubernetes

[source,shell]
....
# Add Gravitee.io charts repository
$ helm repo add graviteeio https://helm.gravitee.io

# And install
$ helm install --name graviteeio-apim graviteeio/apim3
....

For more information, see link:/apim/3.x/apim_installguide_kubernetes.html[Kubernetes].
