= Install Access Management on Amazon Linux
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_amazon_stack.html
:page-folder: am/installation-guide/amazon
:page-liquid:
:page-layout: am
:page-description: Gravitee.io Access Management - Installation Guide - Amazon - Access Management
:page-keywords: Gravitee.io, API Platform, Access Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

:gravitee-package-name: graviteeio-am-3x

This section describes how-to install the full Access Management stack, including all the components (Access Gateway, Management API, Management UI)
and, optionally, install dependencies (MongoDB).

If you are looking to install Gravitee.io Access Management individually, please go to their respective documentation:

* link:/am/current/am_installguide_amazon_gateway.html[Install Access Gateway]
* link:/am/current/am_installguide_amazon_management_api.html[Install Management API]
* link:/am/current/am_installguide_amazon_management_ui.html[Install Management UI]

== Install Nginx

Nginx must be installed prior to Gravitee.io Access Management to run the Gravitee.io Management UI:

[source,bash,subs="attributes"]
----
sudo amazon-linux-extras install nginx1.12
sudo systemctl start nginx
----

== Installing Gravitee.io Access Management package

IMPORTANT: We assume that you have configured your package management system by following link:/am/current/am_installguide_amazon_introduction.html[this documentation].

If you are looking to install all the Gravitee.io Access Management components, you can do it with one of the following commands (depending on your system):

[source,bash,subs="attributes"]
----
sudo yum install {gravitee-package-name}
----

== Installing Gravitee.io Access Management package with dependencies

In a very similar way you did in first step, you can install the complete Gravitee.io Access Management with dependencies
thanks to a single command.

=== Configure dependency repositories

Before this, you may potentially have to add third-party repositories:

==== MongoDB

NOTE: Please have a look to the link:https://docs.mongodb.com/v3.6/tutorial/install-mongodb-on-amazon/[MongoDB Installation documentation]

[source,bash]
----
echo "[mongodb-org-3.6]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.6/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-3.6.asc" | sudo tee /etc/yum.repos.d/mongodb-org-3.6.repo > /dev/null

sudo yum install -y mongodb-org
sudo systemctl start mongod
----

=== Install Gravitee.io Access Management components

[source,bash,subs="attributes"]
----
sudo yum install {gravitee-package-name}-with-dependencies
----

== Running Gravitee.io Access Management with `systemd`

To run all Gravitee.io Access Management components, run the following:

[source,bash,subs="attributes"]
----
sudo systemctl daemon-reload
sudo systemctl start {gravitee-package-name}-gateway {gravitee-package-name}-management-api
sudo systemctl restart nginx
----