---
redirect_from:
  - /am/current/am_installguide_quickstart.html
---
= Quick AM installation
:page-description: Gravitee.io Access Management - Installation - Quickstart
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

Use these procedures to quickly install Access Management for the first time. They are not suitable for existing AM environments.

For detailed installation instructions, see the link:/Guides/am/current/installation-guide/introduction.html[Access Management Installation Guide^].

== Install with RPMs

[source,shell]
....
$ curl -sSL https://bit.ly/install-am-3x | bash
....

For more information, see link:/Guides/AM/current/installation-guide/red-hat/stack.html[Install on Red Hat^].

== Install with Docker

[source,shell]
....
$ curl -sSL https://bit.ly/docker-am-3x | bash
....

For more information, see link:/Guides/AM/current/installation-guide/docker/compose.html[Run on Docker^].

== Install with Kubernetes

[source,shell]
....
# Add Gravitee.io charts repository
$ helm repo add graviteeio https://helm.gravitee.io

# And install
$ helm install --name graviteeio-am graviteeio/am
....

For more information, see link:/Guides/AM/current/installation-guide/kubernetes.html[Deploy in Kubernetes^].
