= Configure cache
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_cache.html
:page-folder: apim/installation-guide/cache
:page-description: Gravitee.io API Management - Cache
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x


== Overview

Caches are used to store different types of data in APIM.

They use a https://docs.hazelcast.org/docs/rn/index.html#3-12-12[Hazelcast^] implementation. You can tune the configuration in the `hazelcast.xml` file.

== Default configuration

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-4.1.xsd">

    <network>
        <join>
            <!-- Auto-detection and multicast are disabled by default to avoid latency when starting local / standalone  gateway -->
            <auto-detection enabled="false"/>
            <multicast enabled="false" />
        </join>
    </network>

    <map name="apikeys">
        <!-- Eviction is managed programmatically-->
        <eviction eviction-policy="NONE" size="0"></eviction>
    </map>

    <map name="subscriptions">
        <!-- Eviction is managed programmatically-->
        <eviction eviction-policy="NONE" size="0"></eviction>
    </map>

    <map name="apis">
        <!-- Eviction is managed programmatically-->
        <eviction eviction-policy="NONE" size="0"></eviction>
    </map>
</hazelcast>
----

WARNING: Be careful when modifying the default configuration, it is designed with performance in mind.

By default, the configuration contains 3 maps to cache API keys, subscriptions and APIs.
These caches can be shared between nodes if you configure hazelcast to be able to contact the other nodes.
There are multiple ways to configure hazelcast networking depending on your installation (regular VMs, Kubernetes, AWS, ...).
The simplest way is enabling multicast:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-4.1.xsd">

    <network>
        <join>
            <auto-detection enabled="false"/>
            <!-- Enable multicast to allow hazelcast discovers other nodes -->
            <multicast enabled="true" />
        </join>
    </network>
</hazelcast>
----

NOTE: You can find more information in the https://docs.hazelcast.org/docs[Hazelcast documentation^], also if you need to configure Hazelcast as cluster.

We currently not recommend to enable the distribution mode with Hazelcast unless there are real needs to do so.

We recommend to leave with the default configuration which works in standalone mode.

The distribution mode is not relevant for most of usecases.

== How are cache resources managed in APIM?

API publishers can create cache resources:

- to cache upstream of a response with the link:/apim/3.x/apim_policies_cache.html[Cache policy^].
- to cache access tokens with the link:/apim/3.x/apim_policies_oauth2.html[OAuth2 policy^].

Default distribution comes with link:/apim/3.x/apim_resources_cache.html[Gravitee Resource Cache].
This plugin stores content in memory and is locally managed on each gateway node of the installation.

Configuration of cache resources cannot be managed using the `hazelcast.xml` file. The configuration is directly defined on the cache resource. See link:/apim/3.x/apim_resources_cache.html[Resource Cache^].

=== Need a persistent cache ?

Since 3.10, we provide a new link:/apim/3.x/apim_resources_cache_redis.html[Gravitee Resource Cache Redis] based on https://redis.io/documentation[Redis].
This plugin is not in distribution by default, but you can https://download.gravitee.io/#graviteeio-apim/plugins/resources/gravitee-resource-cache-redis/[download] plugin and follow link:/apim/3.x/apim_installguide_docker_customize.html#install_an_additional_plugin[instructions] to install it.
