[[gravitee-management-api-security]]
= Gravitee.io Management API Security Guide

== Securing the Management API

This guide walks you through the process of configuring the security of Gravitee.io Management API.

=== Security configuration

Gravitee.IO allows you to externalize your configuration via the `gravitee.yml` file. Various properties can be specified inside your configuration file. This section provides the list of security properties used by the Gravitee.io Management API.

NOTE: The parent attribute of `gravitee.yml` for the security part is `security`. 

=== Authentication Type

Gravitee.IO Management API supports both Basic Authentication and OAuth2 Authentication. The authentication-type can be defined using the following property :

[source]
----
security:
  type: # authentication type (default to 'basic-auth', possible values : 'basic-auth', 'oauth2-auth')
----

NOTE: Based on the authentication type you choose, many properties kick in, especially for the Basic Authentication configuration.

=== Authentication Provider

The Gravitee.io management API module supports by default some standard ways to retrieve user information for authentication from Memory, LDAP and Gravitee.io repository (based on the repository type you have chosen). Let's see how to configure it.

[source]
----
security:
  type: basic-auth # authentication type
  authentication-manager: # required authentication-providers parent property
    authentication-providers: # required authentication-provider parent property
      size : # number of authentication-provider to use
----

NOTE: This is the minimum sample file to declare at least one authentication provider

==== InMemory Provider

Basic, in-memory implementation, a simple and convinient way to declare "technical" users such as the administrator users. An example configuration is shown below:

[source]
----
# ===================================================================
# IN MEMORY SECURITY PROPERTIES
#
# This sample file declared one in memory authentication provider with two users
# ===================================================================
security:
  type: basic-auth # authentication type
  authentication-manager: # required authentication-providers parent attribute
    authentication-providers: # required authentication-provider parent attribute
      size : 1 # number of authentication-provider to use (in this sample one)
      authentication-provider-1 : the authentication provider id must be <= size property
      type: memory # authentication provider type (possible values : memory, ldap, gravitee)
        users:
          size: 2 # number of users to create
          user-1: # id user must be <= to users size property
            username: user
            password: password
            roles: USER # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
          user-2: # id user must be <= to users size property
            username: admin
            password: admin
            roles: ADMIN # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
----

NOTE: We've just declared two users, `user` with `ROLE_USER` role and `admin` with `ROLE_ADMIN`

==== LDAP Provider

An AuthenticationProvider implementation that authenticates against an LDAP server. There are many ways in which the LDAP authentication provider can be configure. You should be familiar with LDAP before trying to use it.

[source]
----
# ===================================================================
# LDAP SECURITY PROPERTIES
#
# This sample file declared one ldap authentication provider
# ===================================================================
security:
  type: basic-auth # authentication type
  authentication-manager: # required authentication-providers parent attribute
    authentication-providers: # required authentication-provider parent attribute
      size : 1 # number of authentication-provider to use (in this sample one)
      authentication-provider-1 : # the authentication provider id must be <= size property
      type: ldap # authentication provider type (possible values : memory, ldap, gravitee)
			embedded: true # embedded mode (true to use the embedded ldap server, usefull for test/demo, possible values : true or false)
			# if embedded is false set the following values 
      context-source-username: # context username to connect to your ldap server
      context-source-password: # context password to connect to your ldap server
      context-source-url: # your ldap server url
      role-mapping: true # role mapping mode for ldap user (possible values : true or false)
      # if role-mapping is true set the following role mapper LDAP values (syntax { "user_ldap_role" : "user_new_added_ldap_role"})
      role-mapper: {
                ROLE_DEVELOPERS: ROLE_USER,
                ROLE_MEMBERS: ROLE_USER,
                ROLE_OWNERS: ROLE_ADMIN
               }
      user-dn-patterns: uid={0},ou=people # user dn patterns (default 'uid={0},ou=people')
      group-search-base: ou=groups # groupe search base (default 'ou=groups')
      context-source-base: dc=gravitee,dc=io # the context source base
----

==== Gravitee Repository Provider

An AuthenticationProvider implementation that authenticates against Gravitee data source repository. Users are defined via the Gravitee.io management API.

[source]
----
# ===================================================================
# GRAVITEE SECURITY PROPERTIES
#
# This sample file declared gravitee authentication provider
# ===================================================================
security:
  type: basic-auth # authentication type
  authentication-manager: # required authentication-providers parent attribute
    authentication-providers: # required authentication-provider parent attribute
      size : 1 # number of authentication-provider to use (in this sample one)
      authentication-provider-1: the authentication provider id must be <= size property
      type: gravitee # authentication provider type (possible values : memory, ldap, gravitee)
			password-encoding: # enable password encoding (possible values : true or false)
----

NOTE: If password encoding system is enable the password encoder uses the BCrypt strong hashing function.

==== Combine the providers

You can specify as many providers as you want. They will be checked in same order you declared them inside the authentication-manager attribute. Once a successfull authentication is made, the Gravitee Management API will stop polling the providers.

[source]
----
# ===================================================================
# MULTIPLE PROVIDER SECURITY PROPERTIES
#
# This sample file declared gravitee authentication provider
# ===================================================================
security:
  type: basic-auth # authentication type
  authentication-manager: # required authentication-providers parent attribute
    authentication-providers: # required authentication-provider parent attribute
      size : 3 # number of authentication-provider to use (in this sample three)
      
      # First authentication provider
      authentication-provider-1: the authentication provider id must be <= size property
        type: ldap # authentication provider type (possible values : memory, ldap, gravitee)
			  embedded: true # embedded mode (true to use the embedded ldap server, usefull for test/demo, possible values : true or false)
			  # if embedded is false set the following values 
        context-source-username: # context username to connect to your ldap server
        context-source-password: # context password to connect to your ldap server
        context-source-url: # your ldap server url
        role-mapping: true # role mapping mode for ldap user (possible values : true or false)
        # if role-mapping is true set the following role mapper LDAP values (syntax { "user_ldap_role" : "user_new_added_ldap_role"})
        role-mapper: {
                ROLE_DEVELOPERS: ROLE_USER,
                ROLE_MEMBERS: ROLE_USER,
                ROLE_OWNERS: ROLE_ADMIN
               }
        user-dn-patterns: uid={0},ou=people # user dn patterns (default 'uid={0},ou=people')
        group-search-base: ou=groups # groupe search base (default 'ou=groups')
        context-source-base: dc=gravitee,dc=io # the context source base
     
      # Second authentication provider
      authentication-provider-2: the authentication provider id must be <= size property
        type: memory # authentication provider type (possible values : memory, ldap, gravitee)
        users:
          size: 2 # number of users to create
          user-1: # id user must be <= to users size property
            username: user
            password: password
            roles: USER # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
          user-2: # id user must be <= to users size property
            username: admin
            password: admin
            roles: ADMIN # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)

      # Third authentication provider
      authentication-provider-3: the authentication provider id must be <= size property
        type: gravitee # authentication provider type (possible values : memory, ldap, gravitee)
			  password-encoding: # enable password encoding (possible values : true or false)
----

NOTE: The authentication process will loop through the three providers to attempt user authentication

=== OAuth2 Authentication configuration

Before you get started, make sure you have a fully fonctionnal OAuth2 Authorization Server with OAuth2 Token Validation endpoint that allows a resource server to validate an access token. The OAuth2 Authorization Server must expose the following resource :

[source]
----
Request         POST /oauth/check_token
Request Body    token=<access_token>
Request Headers Authorization: Basic 'Base64.encode(client_id:client_secret)'
                Content-Type: application/x-www-form-encoded
Response Codes  200 OK
Response Body   ::
                {
                    "exp": 1426391913,
                    "user_name": "user",
                    "scope": [
                        "read",
                        "write"
                    ],
                    "authorities": [
                        "ROLE_USER"
                    ],
                    "client_id": "test"
                }
Response Codes  400 KO
Respoce Body    ::
                {
                  Token not recognized/Token expired
                }
----

The Gravitee.io Management supports OAuth2 Authentication via the following configuration :

[source]
----
# ===================================================================
# OAUTH 2 SECURITY PROPERTIES
#
# This sample file declared oauth2 security configuration
# ===================================================================
security:
  type: oauth2-auth # authentication type
  oauth.endpoint.check_token: # OAuth2 token validation endpoint url
  oauth.client.id: # OAuth2 resource server client id
  oauth.client.secret: # OAut2 resource server client secret
----

NOTE: With OAuth2 Authentication type, all requests to Gravitee Management API must contain the following header : Authorization Bearer <your-access-token>

=== Appendix A. Security application properties

NOTE: This sample file is meant as a guide only. Do not copy/paste the entire content; rather pick only the properties that you need.

[source]
----
security:
  type: basic-auth # authentication type
  authentication-manager: # required authentication-providers parent attribute
    authentication-providers: # required authentication-provider parent attribute
      size : 3 # number of authentication-provider to use (in this sample three)
      
      # First authentication provider
      authentication-provider-1: the authentication provider id must be <= size property
        type: ldap # authentication provider type (possible values : memory, ldap, gravitee)
			  embedded: true # embedded mode (true to use the embedded ldap server, usefull for test/demo, possible values : true or false)
			  # if embedded is false set the following values 
        context-source-username: # context username to connect to your ldap server
        context-source-password: # context password to connect to your ldap server
        context-source-url: # your ldap server url
        role-mapping: true # role mapping mode for ldap user (possible values : true or false)
        # if role-mapping is true set the following role mapper LDAP values (syntax { "user_ldap_role" : "user_new_added_ldap_role"})
        role-mapper: {
                ROLE_DEVELOPERS: ROLE_USER,
                ROLE_MEMBERS: ROLE_USER,
                ROLE_OWNERS: ROLE_ADMIN
               }
        user-dn-patterns: uid={0},ou=people # user dn patterns (default 'uid={0},ou=people')
        group-search-base: ou=groups # groupe search base (default 'ou=groups')
        context-source-base: dc=gravitee,dc=io # the context source base
     
      # Second authentication provider
      authentication-provider-2: the authentication provider id must be <= size property
        type: memory # authentication provider type (possible values : memory, ldap, gravitee)
        users:
          size: 2 # number of users to create
          user-1: # id user must be <= to users size property
            username: user
            password: password
            roles: USER # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
          user-2: # id user must be <= to users size property
            username: admin
            password: admin
            roles: ADMIN # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)

      # Third authentication provider
      authentication-provider-3: the authentication provider id must be <= size property
        type: gravitee # authentication provider type (possible values : memory, ldap, gravitee)
        password-encoding: # enable password encoding (possible values : true or false)
----
