---
redirect_from:
  - /am/current/am_userguide_user_management_ssam.html
---
= Self-service account management

[label label-version]#New in version 3.10#
[label label-version]#Early access#

AM self-service account management allows users to manage their accounts with the following capabilities:

- Read and manage their account information.
- List user activities.
- Request to change passwords.
- Manage Multi-factor Authentication (MFA) devices.
- Manage Passwordless credentials.

NOTE: By default these actions are possible only during the login process, but in order to provide a *My Account* space for your end users, AM includes a REST API to perform all these requests.

You can access the online API reference or the OpenAPI specification link:http:/Reference/API/am-rest-api-doc.html[here^].

== Configure self-service account management

NOTE: By default, self-service account management is *disabled* for all security domains.

NOTE: The self-service account API is deployed at `http(s)://AM_GW_HOST/{domain}/account/api/` and secured with the OAuth 2.0 protocol.

To configure the self-service account settings:

. In AM Console, select your security domain.
. Click *Settings > Self-service account*.
. Configure your settings and click *SAVE*.
