= Password policy
:page-sidebar: am_3_x_sidebar


[label label-version]#New in version 3.6#

[quote, OWASP, 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls[Authentication cheat sheet^]']
A key concern when using passwords for authentication is password strength. A "strong" password policy makes it difficult or even improbable for one to guess the password through either manual or automated means.

== Configure a password policy

You can configure the password policy settings for your end users during the *sign up* and *reset password* actions.

. link:/am/current/am_userguide_authentication.html[Log in to AM Console^].
. Select your application and click *Settings > Password policy*.
. Configure your password policy settings and click *SAVE*.

NOTE: You can also configure password policy settings at security domain level, to be applied across all applications.

== Password settings characteristics

You can set the following password characteristics:

- *Minimum length*: length of the passwords should be enforced by the application.
- *Numbers*: must include at least one number.
- *Special characters*: must include at least one special character.
- *Mixed case*: must include lower and upper case letters.

== Custom UI errors

You can access the password policy settings in your *Sign Up* and *Register* link:/am/current/am_userguide_user_management_forms.html[HTML templates^], making it possible to customize the error messages your end users see.

----
<div th:if="${passwordSettings != null}">
  <span>Password policy :</span>
  <p th:if="${passwordSettings.minLength != null}">Contains at least <span th:text="${passwordSettings.minLength}"/> characters</p>
  <p th:if="${passwordSettings.includeNumbers}">Contains a number</p>
  <p th:if="${passwordSettings.includeSpecialCharacters}">Contains a special character</p>
  <p th:if="${passwordSettings.lettersInMixedCase}">Contains letters in mixed case</p>
  <p th:if="${passwordSettings.maxConsecutiveLetters != null}">Max <span th:text="${passwordSettings.maxConsecutiveLetters}"/> consecutive letters or numbers</p>
</div>
----
