= Upgrade to 3.9.0

== Warning
*For JDBC users only*, please don't upgrade to 3.9.0 since we detected a critical bug in a liquibase script that could lead to data loss. +
This will be fixed in 3.9.1. +
We apologize for this inconvenience.

GitHub issue: https://github.com/gravitee-io/issues/issues/5711[5711]

== Breaking changes

From this version, in order to propose a better swagger descriptor, all enum values *returned* by the APIM API are in uppercase.

NOTE: Lowercase and uppercase values are still accepted in incoming requests.

== Memory management

Starting from this new version, the default Xms and Xmx parameters has been fixed to 256m.
Previous value was too high and does not reflect real memory usage for both the API Gateway and Management API.

If, for some reasons, you need to increase those default values, you can set the `GIO_MIN_MEM` and `GIO_MAX_MEM` environment variables in your scripts.
Those variables are then "injected" into the JAVA_OPTS during bootstrap.

== APIM API - Tags and Tenants

This version changes permissions' scope from `ENVIRONMENT` to `ORGANIZATION` for:

    * TAG
    * TENANT
    * ENTRYPOINT

These permissions are now readonly for the scope `ENVIRONMENT`. They will be deleted on version 3.10.
If you are using these permissions, please update them for the scope `ORGANIZATION`.

== Repository

=== Mongodb

Before running any script, please create a dump of your existing database.

link:https://gh.gravitee.io/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.9.0/1-tags-and-tenants-migration.js[/apim/3.x/mongodb/3.9.0/1-tags-and-tenants-migration.js]::
This script adds referenceId set to 'DEFAULT' and referenceType set to 'ORGANIZATION' to tags, tenants and entrypoint collections.

link:https://gh.gravitee.io/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/3.9.0/2-events-migration.js[/apim/3.x/mongodb/3.9.0/2-events-migration.js]::
This script modifies events, so an event can be linked to more than one environment.
