= The Gravitee Developement Reference Guide
:page-sidebar: comm_sidebar
:page-permalink: comm/developers_guidelines_dev_guide.html
:page-folder: comm/developers
:page-toc: true
:page-description: Developers - Guidelines - Reference guide
:page-keywords: Gravitee, API Platform, Alert, Alert Engine, documentation, manual, guide, reference, api, community
:page-layout: comm

This page and all underlying pages are dedicated to the development process of Gravitee.io.

== New Feature / Bug Fix

Before starting, change the issue label to `in progress` and assign it to yourself.

On each repository involved :
* work in a dedicated branch
* once development is finished, squash the commits to a single one
* push and create a PR
* For Java projects, if the pom version changes, update the release.json file into the release repository using the same process.

Once All PR are created, change the issue label to `in review`

You can find more informations on link:/comm/how_to_contribute_github_flow.html[Github flow page]

=== Before commiting

You have to add a licence header to new files.

Please take a look at link:/comm/developers_guidelines_license_header.html[License header]

=== Commit message

Commit messages use the following format : https://gist.github.com/brianclements/841ea7bffdb01346392c=file-commit-formatting-md
Last line of the comment should contains the reference to the gravitee issue using this github format : https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue=linking-a-pull-request-to-an-issue-using-a-keyword

ex:
```
feat(registration): add an optional validation step in user registration process
   
+ remove portalURL config from gravitee.yml (=4144)
    
Closes gravitee-io/issues=4069
```

=== Documentation

When a feature or a bug fix require an update of the link:https://docs.gravitee.io[online documentation], the `pull request` on the `gravitee-docs` repository must be done before passing the github issue in `in review`.

=== Changes in gravitee-repository-jdbc module

If the issue requires an update of the `gravitee-repository-jdbc` module, before creating the PR, run the test-container tests.

`mvn clean test -Dtc=true`

== Web UI

Before creating the PR, check code style with `npm run lint` and fix simple issues with `npm run lint:fix`

or simply run `mvn clean install`


=== Portal WebUI

If you create or delete keys for internationalization, you will need to modify all <local>.json files.

Please take a look at link:/comm/developers_guidelines_license_header.html[i18n]

=== Useful links

Here is a link:/comm/overview_online-resources.html[page] with some gravitee links (nigthly environment, story book...)