= Introduction
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_amazon_introduction.html
:page-folder: am/installation-guide/amazon
:page-layout: am
:page-description: Gravitee.io Access Management - Installation Guide - Amazon - Introduction
:page-keywords: Gravitee.io, API Platform, Access Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

== Overview

This section explains how to install AM on Amazon Linux using the `yum` package manager.

== Configure the package management system (yum)

. Create a file called `graviteeio.repo` in location `/etc/yum.repos.d/` so that you can install AM directly using `yum`:
+
[source,bash]
----
[graviteeio]
name=graviteeio
baseurl=https://packagecloud.io/graviteeio/rpms/el/7/$basearch
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/graviteeio/rpms/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
----
+
. Enable GPG signature handling, which is required by some of our RPM packages:
+
[source,bash]
----
sudo yum install pygpgme yum-utils
----
+
Before continuing, you may to refresh your local cache:
+
[source,bash]
----
sudo yum -q makecache -y --disablerepo='*' --enablerepo='graviteeio'
----
+
Your repository is now ready to use.

== Install the AM components

You can choose to install the full AM stack or install components one by one:

* link:{{ '/am/current/am_installguide_amazon_stack.html' | relative_url }}[Install the full AM stack] (includes all components below)
* link:{{ '/am/current/am_installguide_amazon_gateway.html' | relative_url }}[Install AM Gateway]
* link:{{ '/am/current/am_installguide_amazon_management_api.html' | relative_url }}[Install AM API]
* link:{{ '/am/current/am_installguide_amazon_management_ui.html' | relative_url }}[Install AM Console]
