[[gravitee-admin-guide-orgs-and-envs]]
= Organizations & environments

:page-description: Gravitee.io API Management - Admin Guide - Organizations and Environments
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

In order to prepare the future (see link:https://www.gravitee.io/products/roadmap[Roadmap > Cockpit]), we have introduced two concepts:

== Environment
An *Environment* is roughly equivalent to what you can find in *Gravitee.io Portal*. In an environment, a user can manage his or her APIs, applications and subscriptions. +
An environment handles its own categories, groups, documentation pages and quality rules. +
You can define for instance:

* technical environments: DEV / TEST / PRODUCTION / ...
* functional environments: PRIVATE APIS / PUBLIC APIS / PARTNERSHIP / ...
* ... any other kind of environment

An environment belongs to one organization.

== Organization
An *Organization* allows a user to adapt Gravitee to its own internal organization. It can handle multiple *Environments* by sharing configurations like:

* Users
* Roles
* ...

It will also allow operations across managed environments (like APIs import/export)

WARNING: The descriptions above may change slightly in future versions. Stay informed by subscribing to our link:https://gravitee.io/[newsletter]

NOTE: By default, the OSS version of the platform comes with a 'DEFAULT' organization and a 'DEFAULT' environment. Multi-environments is part of link:/ee/ee_introduction.html[Enterprise Edition]
