---
layout: doc
product: API Management
permalink: apim/3.x/apim_configguide_repos_jdbc.html
sidebar: apim_3_x_sidebar
guide: Configuration Guide
toc: true
title: Configure the JDBC repository plugin
keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api, jdbc
---

This repository plugin is for connecting to SQL databases.

== Supported databases

|===
|Database | Version tested | APIM Plugin | JDBC Driver

|Postgresql
|9 / 10 / 11 / 12 / 13
.4+|https://download.gravitee.io/#graviteeio-apim/plugins/repositories/gravitee-apim-repository-jdbc/[Download the same version as your APIM platform]
|https://jdbc.postgresql.org/download.html[Download page]

|MySQL
|5.6 / 5.7 / 8.0
|https://dev.mysql.com/downloads/connector/j/[Download page]

|MariaDB
|10.1 / 10.2 / 10.3 / 10.4
|https://downloads.mariadb.org/connector-java/[Download page]

|Microsoft SQL Server
|2017-CU12
|https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-2017[Download page]
|===

== Install the JDBC plugin

NOTE: Because the plugin is part of the default distribution from APIM version 3.5, you only need to complete these steps for version 3.4 or earlier.

Repeat these steps on each component (APIM Gateway and APIM API) where the SQL database is used.

 . Download the plugin corresponding to your APIM version (take the latest maintenance release).
 . Place the zip file in the plugin directory for each component (`$GRAVITEE_HOME/plugins`).
 . Download the JDBC driver corresponding to your database version.
 . Place the driver in `$GRAVITEE_HOME/plugins/ext/repository-jdbc`.
 . Configure your `gravitee.yml` files, as described in the next section.


== Configuration

=== Mandatory configuration

[source,yaml]
----
management:
  type: jdbc             # repository type
  jdbc:                  # jdbc repository
    url:                 # jdbc url
----

=== Optional configuration

The example above shows the minimum configuration needed to get started with a JDBC database. You can configure the following additional properties to fine-tune your JDBC connection and control the behavior of your JDBC database.

[source,yaml]
----
management:
  type: jdbc                    # repository type
  jdbc:                         # jdbc repository
    prefix:                     # tables prefix
    url:                        # jdbc url
    username:                   # jdbc username
    password:                   # jdbc password
    pool:
        autoCommit:             # jdbc auto commit (default true)
        connectionTimeout:      # jdbc connection timeout (default 10000)
        idleTimeout:            # jdbc idle timeout (default 600000)
        maxLifetime:            # jdbc max lifetime (default 1800000)
        minIdle:                # jdbc min idle (default 10)
        maxPoolSize:            # jdbc max pool size (default 10)
----

[[use_a_custom_prefix]]
== Use a custom prefix

From APIM 3.7, you can use a custom prefix for your table names. This is useful if you want to use the same databases for APIM and AM, for example.

The following steps explain how to rename your tables with a custom prefix, using the prefix `prefix_` as an example.

=== On a new installation

If you are installing APIM for the first time, you need to update the following two values in the APIM Gateway and APIM API `gravitee.yml` files:

* `management.jdbc.prefix`
* `ratelimit.jdbc.prefix`

By default, these values are empty.

=== Migrating an existing installation

NOTE: Before running any scripts, you need to create a dump of your existing database. You need to repeat these steps on both APIM Gateway and APIM API.

. Update values `management.jdbc.prefix` and `ratelimit.jdbc.prefix` in your `gravitee.yml` configuration file.
. Run the application on a new database to generate `prefix_databasechangelog`.
. Replace the content of the `databasechangelog` table with the content you generated from `prefix_databasechangelog`.
. Rename your tables using format `prefix_tablename`.
. Rename your indexes using format `idx_prefix_indexname`.
. Rename your primary keys using format `pk_prefix_pkname`.
