= How to configure

There are three different ways to configure this component:

 - `gravitee.yml`
 - System Properties
 - Environment variables

In terms of prevalence, `environment variables` override `System properties which are themselves overriding
`gravitee.yml` file.

== gravitee.yml

This is the default way to configure Gravitee.io

WARNING: Yaml (yml) format is very sensitive with indentation. Be careful, and use spaces instead of tabs.


== System Properties

You can override the default configuration (`gravitee.yml`) to configure Gravitee.io by defining system properties.

If you want to override this property:

[source,yaml]
----
management:
  mongodb:
    dbname: myDatabase
----

You have to add this property to the JVM:

----
-Dmanagement.mongodb.dbname=myDatabase
----


== Environment Variables

You can override the default configuration (`gravitee.yml`) to configure Gravitee.io by defining environment variables.

If you want to override this property:

[source,yaml]
----
management:
  mongodb:
    dbname: myDatabase
----

You have to define one of the following variables:

----
GRAVITEE_MANAGEMENT_MONGODB_DBNAME=myDatabase
GRAVITEE.MANAGEMENT.MONGODB.DBNAME=myDatabase
gravitee_management_mongodb_dbname=myDatabase
gravitee.management.mongodb.dbname=myDatabase
----