= Installation Guide
:page-sidebar: cockpit_sidebar
:page-permalink: cockpit/3.x/cockpit_installguide_introduction.html
:page-folder: cockpit/installation-guide

Gravitee.io Cockpit consists of two main components:

* link:/cockpit/3.x/cockpit_installguide_management_api_install_zip.html[Cockpit API]
* link:/cockpit/3.x/cockpit_installguide_management_ui_install_zip.html[Cockpit Console]

The following sections explain how to prepare, install, and configure your Cockpit environment.

NOTE: This Installation Guide provides information about how to install Gravitee.io components. For external components, such as
MongoDB, see the relevant product documentation.

Cockpit generates a certificate that will be used to authenticate installations (APIM/AM) that will connect. To create this certificate, you need to put private/public keys in keystore/truststore file and provide them using the following configuration attributes:

[source,yaml]
----
keystore:
  type: pkcs12
  path: <path to the keystore file>
  password: <password>
truststore:
  type: pkcs12
  path: <path to the truststore file>
  password: <password>
----

You also need a certificate to activate SSL for the WebSocket. Put this certificate in a `server.p12` Keystore and provide it through the following configuration attributes:

[source,yaml]
----
ssl:
  keystore:
    type: pkcs12
    path: <path to the keystore file>
    password: <password>
  truststore:
    type: pkcs12
    path: <path to the truststore file>
    password: <password>
----

WARNING: Cockpit won't start if no keystore/truststore are provided.