= Installation Guide
:page-sidebar: cockpit_sidebar
:page-permalink: cockpit/3.x/cockpit_installguide_introduction.html
:page-folder: cockpit/installation-guide

WARNING: *GOOD NEWS*: In order to provide you with the best experience with Cockpit, we are moving to a SaaS version only moving forward. This will not only improve the offering of new features, but also will deliver a smooth product experience whilst minimising effort required for product updates. We encourage you to sign up for an account to take advantage of these benefits. *Do be aware that Version 3.15 will be the last supported version for on-premise deployment, which will continue to receive maintenance releases to handle bug and security vulnerability fixes.*

Gravitee.io Cockpit consists of two main components:

* link:{{ '/cockpit/3.x/cockpit_installguide_management_api_install_zip.html' | relative_url }}[Cockpit API]
* link:{{ '/cockpit/3.x/cockpit_installguide_management_ui_install_zip.html' | relative_url }}[Cockpit Console]

The following sections explain how to prepare, install, and configure your Cockpit environment.

NOTE: This Installation Guide provides information about how to install Gravitee.io components. For external components, such as
MongoDB, see the relevant product documentation.

Cockpit generates a certificate that will be used to authenticate installations (APIM/AM) when they connect. To create this certificate, you need to put private/public keys in a keystore/truststore file and provide details using the following configuration attributes:

[source,yaml]
----
keystore:
  type: pkcs12
  path: <path to the keystore file>
  password: <password>
truststore:
  type: pkcs12
  path: <path to the truststore file>
  password: <password>
----

You also need a certificate to activate SSL for WebSocket. Put this certificate in a `server.p12` keystore and provide it through the following configuration attributes:

[source,yaml]
----
ssl:
  keystore:
    type: pkcs12
    path: <path to the keystore file>
    password: <password>
  truststore:
    type: pkcs12
    path: <path to the truststore file>
    password: <password>
----

WARNING: Cockpit won't start if no keystore/truststore is provided.

== Generate certificates

If you don't have certificates but still want to install Cockpit for dev purposes, you can generate local certificates.

WARNING: The following commands are only for local development. The certificates they generate are not suitable for production environments.

NOTE: We assume you are in a dedicated folder such as `/path-to-certificates`

[source,bash]
----
# Create certificate authority
openssl req -newkey rsa:4096 -keyform PEM -keyout ca.key -x509 -days 3650 -subj "/emailAddress=contact@company.com/CN=cockpit.company.com/OU=Company/O=Company/L=Lille/ST=France/C=FR" -passout pass:ca-secret -outform PEM -out ca.pem
openssl pkcs12 -export -inkey ca.key -in ca.pem -out ca.p12 -passin pass:ca-secret -passout pass:ca-secret -name cockpit-ca

# Create Java truststore with certificate authority (public, no private key will be exported)
keytool -import -file ca.pem -storetype PKCS12 -keystore ca-truststore.p12 -storepass truststore-secret -noprompt -alias cockpit-ca

# Server key (localhost)
openssl genrsa -out server.key 4096
openssl req -new -key server.key -out server.csr -sha256 -subj "/emailAddress=contact@company.com/CN=localhost/OU=Cockpit/O=Company/L=Lille/ST=France/C=FR"
openssl x509 -req -in server.csr -CA ca.pem -CAkey ca.key -set_serial 100 -extensions server -days 1460 -outform PEM -out server.cer -sha256 -passin pass:ca-secret
openssl pkcs12 -export -inkey server.key -in server.cer -out server.p12 -passout pass:server-secret -name cockpit-server

# Import all into a global keystore
keytool -importkeystore -srcstoretype pkcs12 -srckeystore ca.p12 -srcstorepass ca-secret -deststoretype pkcs12 -destkeystore keystore.p12 -deststorepass keystore-secret
----
