= Third party products
:page-sidebar: ae_sidebar
:page-permalink: ae/3rdparties_installation.html
:page-folder: ae/3rdparties
:page-description: Gravitee Alert Engine - Third Parties - Installation
:page-toc: true
:page-keywords: Gravitee, API Platform, Alert, Alert Engine, documentation, manual, guide, reference, api, third-party
:page-layout: ae

AE works both within and outside the Gravitee.io ecosystem.
You can plug in your own backends and benefit from all the same features.

== Requirements

You must have an Alert Engine available:

* already deployed on you infrastructure
* from our SaaS platform (comming soon)
* by running it with docker:
** `docker run -t -v "${PWD}/licence.key:/opt/graviteeio-alert-engine/license/license.key:ro" -p 8072:8072 graviteeio/ae-engine:latest`
** note that we use a licence.key file that you must have in the current directory (update the cli as you need)

For running the javascript scripts below, we use `node version v18.7.0`.


== Websocket connection

You can send a Triggers through websocket

To test this script:

* boostrap a javascript project with `npm init`
* add `ws` dependency with `npm install --save ws`
* create the `trigger.js` file with the content below.
* run that script with `node trigger.js`

[source,javascript]
----
const WebSocket = require('ws');
const wsTrigger = new WebSocket("ws://localhost:8072/ws/triggers", {
    headers : {
        "Authorization": "Basic base64(username:password)"
    }
});

wsTrigger.onopen = () => {
  console.log("Trigger connection opened");
};

wsTrigger.onmessage = (event) => {
    const response = JSON.parse(event.data.toString());
    if (response.type === 'ALERT_'){

    }
    console.log("Received message:", event.data.toString());
};

wsTrigger.onerror = (error) => {
  console.log("An error has occurred:", error);
};

wsTrigger.onclose = (event) => {
  console.log("Trigger websocket connection closed:", event.code, event.reason);
};

//Later in code
// A trigger example with a webhook notifier
const trigger = {
      "id": "response-time-threshold-id",
      "name" : "Response time Threshold",
      "source" : "my-source", // source of the event to handle
      "enabled" : true,
      "conditions" : [{
        "type" : "THRESHOLD",
        "property" : "response.response_time",
        "operator" : "LT",
        "threshold" : 1500.0
      }],
      "dampening" : {
        "mode" : "STRICT_COUNT",
        "trueEvaluations" : 1
      },
      "notifications": [
          {
              "type" : "webhook-notifier",
              "configuration" : {
                    "url":  "http://localhost:8080/alert/webhook",
                    "method":"POST",
                    "useSystemProxy":false,
                    "body": "${alert.id} - ${alert.name} - ${alert.source} - ${alert.description} - ${alert.severity} - ${notification.message}"
              }
          }
      ]
 };

if (wsTrigger.readyState === WebSocket.OPEN) {
    // You can send a single trigger
    wsTrigger.send(JSON.stringify(trigger));

    // Or an array of triggers
    // ws.send(JSON.stringify([...trigger]));
}

----

Same goes with Events

[source,javascript]
----
const WebSocket = require('ws');

const wsEvent = new WebSocket("ws://localhost:8072/ws/events", {
    headers : {
        "Authorization": "Basic base64(username:password)"
    }
});

wsEvent.onopen = () => {
  console.log("Trigger connection opened");
};

wsEvent.onerror = (error) => {
  console.log("An error has occurred:", error);
};

wsEvent.onclose = (event) => {
  console.log("Trigger websocket connection closed:", event.code, event.reason);
};

// Later in code

const event = {
  "id": "event-id",
  "timestamp": Date.now(),
  "type": "my-source", // Same value as the Trigger `source` property
  "context": { // context of your event, can be re-used in the notifier
      "node.host": "my-host",
      "node.environment": "my-env"
  },
  "properties": { // What will be evaluated by the condition in the trigger
      "response.response_time" : 500
  }
}

if (wsEvent.readyState === WebSocket.OPEN) {
    // You can send a single trigger
    wsEvent.send(JSON.stringify(event));

    // Or an array of events
    // ws.send(JSON.stringify([...event]));
}

A new Alert Engine log line should appear to confirm a new websocket is opened.

And on the `trigger.js` run you should see something like:

----

----
Received message: {"action":"CHANGE","member":"428998e2-fe84-4dfd-82a6-7966d6883073","endpoint":"http://172.20.0.2:8072","id":"8a4a158c-4f31-4a59-8a15-8c4f31aa5902","type":"NODE_DISCOVERY"}
----

== Http Endpoint

You can also submit triggers via HTTP

```bash
$ curl \
    -H "Authorization: Basic base64(username:password)" \
    -XPOST http://localhost:8072/http/triggers -d '{
      "id": "response-time-threshold-id",
      "name" : "Response time Threshold",
      "source" : "my-source",
       "enabled" : true,
      "conditions" : [{
        "type" : "THRESHOLD",
        "property" : "response.response_time",
        "operator" : "LT",
        "threshold" : 1500.0
      }],
      "dampening" : {
        "mode" : "STRICT_COUNT",
        "trueEvaluations" : 1
      },
      "notifications": [
          {
              "type" : "webhook-notifier",
              "configuration" : {
                    "url":  "http://localhost:8080/alert/webhook",
                    "method":"POST",
                    "useSystemProxy":false,
                    "body": "${alert.id} - ${alert.name} - ${alert.source} - ${alert.description} - ${alert.severity} - ${notification.message}"
              }
          }
      ]
 }'
```

Same with events:

```bash
$ curl \
    -H "Authorization: Basic base64(username:password)" \
    -XPOST http://localhost:8072/http/events -d '{
      "id": "event-id",
      "timestamp": 1670343913325,
      "type": "my-source",
      "context": {
          "node.host": "my-host",
          "node.environment": "my-env"
      },
      "properties": {
          "response.response_time" : 500
      }
    }'
```

== OpenAPI specification
Similarly, you can send arrays of triggers and events like with Websockets.
Checkout the OpenAPI specification here:

* 2.0 -- link:{{ '/ae/spec/2.0/index.html' | relative_url }}[online reference] - link:{% link /ae/spec/2.0/alert-engine-spec.yml  %}[OpenAPI spec]
