:page-sidebar: apim_1_x_sidebar
:page-permalink: apim/1.x/apim_overview_introduction.html
:page-folder: apim/overview
:page-description: Gravitee.io API Management - Introduction
:page-toc: false
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim1x

= Introduction

Nowadays, API Management helps organizations to publish their APIs to external developers,
partners and internal developers in order to unlock the potential of their data and services
and to move into an OpenAPI and an OpenData dynamic. By doing so, companies are able to extend their
operations as a digital platform, by creating new "communication" channels and finding new customers.

By providing such facilities, companies are seeing a growing number of consumers and partners
and must face new challenges:

* How to reduce time to enroll new consumers / partners
* How to identify partners and manage their API consumption
* How to measure consumption from a consumer and/or from a producer point of view
* How to share existing APIs and how to discover them
* How to manage API lifecycle, versioning, documentation, ...

It is then a question about how to address these problems in a uniform way for all your APIs using a central tool.

All of these questions are addressed in Gravitee.io API Management

[[gravitee-overview]]
== Gravitee.io API Management

Gravitee.io API Management is a flexible, lightweight and blazing-fast open source API Management solution that helps you and your organizations to control finely who, when and how users access your APIs. Gravitee.io API Management is not only a simple product, it acts as a global solution for API Management.

NOTE: In the rest of the document, we use the short name *Gravitee.io* or *Gravitee.io APIM* to talk about *Gravitee.io API Management*.
