= Upgrade to 1.9.0

== Breaking Changes

=== Expression language

In this new version (and thanks to issue https://github.com/gravitee-io/issues/issues/720[#720]),
HTTP query parameters are now multi-valued in the same way as HTTP headers.

This means that when you're trying to look for query parameter value from an EL, you have to take care
about the position of the query parameter value (this is true only for mixin EL).

For example, for the incoming request `https://gateway/myapi/v1/myresource?my-param=0` or
`https://gateway/myapi/v1/myresource?my-param=0&my-param=1`, the following EL was working in version `< 1.9.x`:

```
{#properties[#request.params['my-param']]}
```

but must be changed to this EL with version `>= 1.9.x`:

```
{#properties[#request.params['my-param'][0]]}
```

On the other side, if you're not using mixin EL to access a single valued query parameter, the following EL is still
valid and is not affected by the change.

```
{#request.params['my-param']}
```

is still valid and is equivalent to:

```
{#request.params['my-param'][0]}
```

== Repository

=== Mongodb

Before running any script, please create a dump of your existing database.

link:https://gh.gravitee.io/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/1.9.0/1-convert-groups.js[/apim/1.x/mongodb/1.9.0/1-convert-groups.js]::
This script convert old group system to the new one.

link:https://gh.gravitee.io/gravitee-io/gravitee-api-management/master/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/resources/scripts/1.9.0/2-remove-old-attributes.js[/apim/1.x/mongodb/1.9.0/2-remove-old-attributes.js]::
This script remove all non requisite attributes.

