= Configure APIM API
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_installguide_rest_apis_configuration.html
:page-folder: apim/installation-guide/rest-apis
:page-description: Gravitee.io API Management - Configuration - Management API
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:page-layout: apim3x

include::../../partial/how-to-configure.adoc[leveloffset=+1]

== `gravitee.yml` configuration

=== Configure HTTP Server

You configure the HTTP Server configuration in the following section of the `gravitee.yml` file:

[source,yaml]
----
jetty:
  port: 8083
  idleTimeout: 30000
  acceptors: -1
  selectors: -1
  pool:
    minThreads: 10
    maxThreads: 200
    idleTimeout: 60000
    queueSize: 6000
  jmx: false
  statistics: false
  accesslog:
    enabled: true
    path: ${gravitee.home}/logs/gravitee_accesslog_yyyy_mm_dd.log
----

==== Enable HTTPS support
First, you need to provide a keystore. If you do not have one, you can generate it :
[source,bash]
----
keytool -genkey \
  -alias test \
  -keyalg RSA \
  -keystore server-keystore.jks \
  -keysize 2048 \
  -validity 360 \
  -dname CN=localhost \
  -keypass secret \
  -storepass secret
----

You then need to enable secure mode in `gravitee.yml` :
[source,yaml]
----
jetty:
  ...
  secured: true
  ssl:
    keystore:
      path: ${gravitee.home}/security/keystore.jks
      password: secret
    truststore:
      path: ${gravitee.home}/security/truststore.jks
      password: secret
----

WARNING: Truststore and keystore defined within the `jetty` section are only used to secure access to APIM API. These are not
used by HTTP client calls for any other purpose (such as Fetch and DCR).

== Configure the Management and Portal APIs
You can configure APIM API to start only the Management or Portal API. You can also change the API endpoints from their default values of `/management` and `/portal`.

[source,yaml]
----
http:
  api:
    # Configure the listening path for the API. Default to /
#    entrypoint: /
    # Configure Management API and Portal API.
#    management:
#      enabled: true
#      entrypoint: ${http.api.entrypoint}management
#    portal:
#      enabled: true
#      entrypoint: ${http.api.entrypoint}portal
----

=== Configure the Plugins repository

You can configure the APIM Gateway <<gravitee-plugins,plugins>> directory.

[source,yaml]
----
plugins:
  path: ${gravitee.home}/plugins
----

=== Configure the Management repository

The Management repository is used to store global configuration such as APIs, applications and apikeys.
The default configuration uses MongoDB (single server). For more information about MongoDB configuration, see:

http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html

[source,yaml]
----
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    username:
#    password:
#    connectionsPerHost: 0
#    connectTimeout: 500
#    maxWaitTime: 120000
#    socketTimeout: 500
#    socketKeepAlive: false
#    maxConnectionLifeTime: 0
#    maxConnectionIdleTime: 0
#    serverSelectionTimeout: 0
#    description: gravitee.io
#    heartbeatFrequency: 10000
#    minHeartbeatFrequency: 500
#    heartbeatConnectTimeout: 1000
#    heartbeatSocketTimeout: 20000
#    localThreshold: 15
#    minConnectionsPerHost: 0
#    sslEnabled: false
#    threadsAllowedToBlockForConnectionMultiplier: 5
#    cursorFinalizerEnabled: true

# Management repository: single MongoDB using URI
# For more information about MongoDB configuration using URI, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
#management:
#  type: mongodb
#  mongodb:
#    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

# Management repository: clustered MongoDB
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
#    dbname: ${ds.mongodb.dbname}
#    connectTimeout: 500
#    socketTimeout: 250
----

=== Configure the Analytics repository

The Analytics repository is used to store all reporting, metrics and health-checks stored by APIM Gateway instances.
The default configuration uses https://www.elastic.co/products/elasticsearch[Elasticsearch].

[source,yaml]
----
  type: elasticsearch
  elasticsearch:
    endpoints:
      - http://localhost:9200
#    index: gravitee
#    security:
#       username:
#       password:
----

[[gravitee-standalone-management-authentication-configuration]]
=== Configure authentication

See the link:/apim/3.x/apim_installguide_authentication.html[dedicated] section.

=== Configure email

==== SMTP

The section below shows the SMTP configuration used for sending email.

[source,yaml]
----
email:
  host: smtp.my.domain
  port: 465
  from: noreply@my.domain
  subject: "[Gravitee.io] %s"
  username: user@my.domain
  password: password
----

===== Configure the Gmail SMTP server

[source,yaml]
----
email:
  enabled: true
  host: smtp.gmail.com
  port: 587
  from: user@gmail.com
  subject: "[Gravitee.io] %s"
  username: user@gmail.com
  password: xxxxxxxx
  properties:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com
----

If you are using 2-Factor Authentication (which is recommended), you need to generate an application password: https://security.google.com/settings/security/apppasswords .

==== Configure email templates

APIM API uses the http://freemarker.org[FreeMarker template engine] to parse and create email templates.

[source,yaml]
----
templates:
  path: ${gravitee.home}/templates
----

The list of email templates is as follows:

[width="100%",cols="20%,60%,20%",frame="topbot",options="header"]
|======================
|Email Template                 |Description                                    |Variables
|groupMember.html               |New API group member notification.             |_username_, *group*, *user*
|apiKeyExpired.html             |API Key expired notification.                  |*owner*, *api*, *plan*, *application*, apiKey, expirationDate
|apiKeyRevoked.html             |API Key revoked notification.                  |*owner*, apiKey
|apiMember.html                 |New API member notification.                   |_username_, *api*, *user*
|applicationMember.html         |New application member notification.           |_username_, *application*, *user*
|subscriptionApproved.html      |API subscription approved notification.        |*owner*, *api*, *plan*, *subscription*
|subscriptionReceived.html      |API subscription received notification.        |*owner*, *api*, *plan*, *application*, *subscription*, subscriptionsUrl
|subscriptionRejected.html      |API subscription rejected notification.        |*owner*, *api*, *plan*, *subscription*
|userRegistration.html          |User registration notification.                |_username_, registrationUrl, *user*
|supportTicket.html             |Support ticket creation.                       |*api*, *application*, *user*, content
|======================

You can access your API data on your API templates with: ${api.name} or ${api.metadata['foo-bar']}

Available attributes:

[width="100%",cols="20%,20%,20%,20%,20%,20%",frame="topbot",options="header"]
|======================
|Api                |Application        |Group              |Plan               |Owner/User    |Subscription
|name               |name               |name               |name               |username      |status
|description        |description        |-                  |description        |firstname     |request
|version            |type               |-                  |order              |lastname      |reason
|role               |status             |-                  |publishedAt (Date) |displayName   |processedAt
|metadata (Map)     |role               |-                  |closedAt (Date)    |email         |startingAt
|deployedAt (Date)  |-                  |-                  |-                  |-             |endingAt
|createdAt (Date)   |createdAt (Date)   |createdAt (Date)   |createdAt (Date)   |-             |closedAt
|updatedAt (Date)   |updatedAt (Date)   |updatedAt (Date)   |updatedAt (Date)   |-             |subscribedAt
|======================

This is an example template:
[source,html]
----
<html>
	<body style="text-align: center;">
		<header>
			<#include "header.html" />
		</header>
		<div style="margin-top: 50px; color: #424e5a;">
			<h3>Hi ${owner.username},</h3>
			<p>The API Key <code>${apiKey}</code> has been expired.
		</p>
	</body>
</html>

----

=== Configure user options

You can configure various user options:

user.login.defaultApplication:: boolean (default: true) -- creates a new application for all new users
user.creation.token.expire-after:: number (default: 86400) -- number of seconds before the user registration token expires
user.reference.secret:: 32 characters (default: s3cR3t4grAv1t33.1Ous3D4R3f3r3nc3) -- secret used to generate a unique anonymous reference to a user; *You must change this value*
user.anonymize-on-delete:enabled:: boolean (default: false) - If true, the user *firstname*, *lastname* and *email* are anonymized when a user is deleted

== Gateway

The field `unknown-expire-after` specifies the duration of visibility (in seconds) of a gateway with the state unknown (default value: 7 days).

[source,yaml]
----
gateway:
  unknown-expire-after: 604800
----

== Default configuration


You can configure various default properties of APIM API in your `gravitee.yml` file.

[source,yaml]
----
include::https://raw.githubusercontent.com/gravitee-io/gravitee-management-rest-api/master/gravitee-rest-api-standalone/gravitee-rest-api-standalone-distribution/src/main/resources/config/gravitee.yml[]
----
