= Secret Management : The Definitive Guide
:page-sidebar: comm_sidebar
:page-permalink: comm/developers_integration_secrets_everywhere.html
:page-folder: comm/developers
:page-toc:
:page-description: Developers - Secrets everywhere
:page-keywords: Gravitee, API Platform, Alert, Alert Engine, documentation, manual, guide, reference, api, community
:page-layout: comm

== Hashicorp Vault

Soon

== Secrethub : The HashiCorp Vault 123 easy

You can consider https://secrethub.io[Secrethub] as a HashiCorp Vault SAAS offer.

The point is that is makes it easy to manage many secrets, for both software and Infrastructure. Whe, using it, you will discover it has so many amazing features.

Ok, so let's dive in now, no blablah.

=== Secrethub everyday CLI

==== Installing the Secrethub CLI

On `GNU/Linux` `Debian`-based distribs::
(on linux debian and probably all debian based linux distrib such as ubuntu, potentially all GNU/Linux distribs)
```bash

# eg : https://github.com/secrethub/secrethub-cli/releases/download/v0.41.0/secrethub-v0.41.0-linux-amd64.tar.gz
export SECRETHUB_CLI_VERSION=0.41.0
export SECRETHUB_OS=linux
export SECRETHUB_CPU_ARCH=amd64

curl -LO https://github.com/secrethub/secrethub-cli/releases/download/v${SECRETHUB_CLI_VERSION}/secrethub-v${SECRETHUB_CLI_VERSION}-${SECRETHUB_OS}-${SECRETHUB_CPU_ARCH}.tar.gz

sudo mkdir -p /usr/local/bin
sudo mkdir -p /usr/local/secrethub/${SECRETHUB_CLI_VERSION}
sudo tar -C /usr/local/secrethub/${SECRETHUB_CLI_VERSION} -xzf secrethub-v${SECRETHUB_CLI_VERSION}-${SECRETHUB_OS}-${SECRETHUB_CPU_ARCH}.tar.gz

sudo ln -s /usr/local/secrethub/${SECRETHUB_CLI_VERSION}/bin/secrethub /usr/local/bin/secrethub
secrethub --version

# note : on debian binary is installed to [/usr/bin/secrethub] by package manager. I prefer local

```

On `GNU/Linux` `Macos` distribs::
```bash

# eg : https://github.com/secrethub/secrethub-cli/releases/download/v0.41.2/secrethub-v0.41.2-darwin-amd64.tar.gz
export SECRETHUB_CLI_VERSION=0.41.0
export SECRETHUB_OS=darwin
export SECRETHUB_CPU_ARCH=amd64


curl -LO https://github.com/secrethub/secrethub-cli/releases/download/v${SECRETHUB_CLI_VERSION}/secrethub-v${SECRETHUB_CLI_VERSION}-${SECRETHUB_OS}-${SECRETHUB_CPU_ARCH}.tar.gz

sudo mkdir -p /usr/local/bin
sudo mkdir -p /usr/local/secrethub/${SECRETHUB_CLI_VERSION}
sudo tar -C /usr/local/secrethub/${SECRETHUB_CLI_VERSION} -xzf secrethub-v${SECRETHUB_CLI_VERSION}-${SECRETHUB_OS}-${SECRETHUB_CPU_ARCH}.tar.gz

sudo ln -s /usr/local/secrethub/${SECRETHUB_CLI_VERSION}/bin/secrethub /usr/local/bin/secrethub

secrethub --version
```


Alright: Now you have the Secrethub CLI installed

Next steps :

The Root Secret (very important)::
** Before you can do anything with the `secrethub` CLI, you will have to create a first secret, the **only** and last secret you will have to be careful about. It's your _root_ secret, because with this one, you will be able to retrieve all other secrets.
** Actually, almost all other secrets : In the `Secrethub` world, There exist other type of _"root"_ secrets, you will be able to create, like  _service account token_, and you will not be able to retrieve them, unless you create a _"non-root"_ secret, to hold their value. We'll discuss those later on, especially "_service accounts_" secrets.

Start reading writing secrets:: Now that we have our root secret, we can start playing wiht secrets. There are two main cases for secret management :
** files : like an SSL certificate)
** strings : a password, for example, or an API Token

* Secrets are not vegan, but they care about `TOFU` : we'll also discuss what that is, after we have played a bit more. T.O.F.U.(_"Trust On First Use"_).


==== The root secret

Secrethub CLI requires authentification to allowyou to run any operation on a secret : this is not a surprise.

Execute this :

```bash

ls -allh ${HOME}/.secrethub

secrethub signup

ls -allh ${HOME}/.secrethub

cat ${HOME}/.secrethub/credential

```

Alright, here is a thing I like about secrethub : It's **really** secret, signing up (and creating your `secrethub` user account)
does not require you to use any browser ! (priceless when talking about security)

Ok, Now run the Following commands, to convince yourself yes, it's just this `${HOME}/.secrethub/credential` which holdsabsolutely everything about you, as a new secrethub.com user :


```bash

secrethub account inspect

```

Okay, you're so in a hurry to start and play with secret now **BUT DO NOT FORGET THE MOST IMPORTANT** :

* The string (a _token_) `${HOME}/.secrethub/credential` is your root secret
* I know you guys at Gravitee.io use `keypass2`, to store your secrets (like email passwordsetc..) : **store your secrethub token in `Keypass2`, once and for all**,
* and then if you ever delete your local `${HOME}/.secrethub/credential`, or if you want to play withg your secrethubuser, on another machine, allyou will have to do is :

```bash
# install/re-install the Secrethub CLI with this guide

mkdir -p ${HOME}/.secrethub/credential
touch ${HOME}/.secrethub/credential

vi ${HOME}/.secrethub/credential
# and then retireve the token from keypass2
```

Right ?

Okay, now that we're secured, let's play with secrets like real devops.

==== Play with secrets

I'll walk you through how to use `secrethub`, first by everyday use cases, so you can taste how valuable, secrethub.io free SAAS offer is

Real life Use cases : Managing many SSH Keys::

Alright, Imagine yourself taking my role as devops leader at Gravitee.io, and one day, what you'll have todo, is to create 10 VMs on AWS,and you will have to never **ever**, loose the SSH keys to ssh into those VMs.

How would you manage that ?

I'll assume all VMs are provisioned with a (*NIX) GNU/Linux distribution OS. Which is the case for 90% of VMs in this world.


First, you'll make a plan, for operations :

* what will I do to provision all those VMS ? (this part we are not interested in,  in the secret management scope,plus you're the devops Team leader now, so yo know how to  do that, no need to lecture you, right? :) )
* How will I create those SSH keys ?
* this part we are not interested in, in the secret management scope,
* the only thing that we are here interested in knowing, is that, depending on the infrastructure provider you will use, to provision your VMs, you will always end up, for each of your 10 VMS, with a linux user name, and for each of those linux users, either :
* with 2 files : the public key, and the private key.
* with just one files: this one and only file, contains both the public and private keys. SSH always is about asymetric cryptography, it's just that different key file formats exists.
* So all in all, I will demonstrate a strategy when we end up with 3 informations, for ech of those 10 VMs : a username, and 2 files (the public, and private key files).
* What strategy will I use, to :
* be absolutely sure, I will never, ever loose any of those SSH Keys ?
* make switching one configuration, to SSH into one VM, to another configuration, to SSH into another VM  , quick and easy ?


_**The Strategy**_

Alright, let's sum up everything, and choose a network hostname for all of those 10 VMs :

* `VM` `1` to `VM` `10` hostnames (the string returned by the `hostname` command on each VM) and public IPs to use to connect over SSH to them :

* `vm1.gio-infra.io`, Public IP `${VM1_PUBLIC_IP}`
* `vm2.gio-infra.io`, Public IP `${VM2_PUBLIC_IP}`
* `vm3.gio-infra.io`, Public IP `${VM3_PUBLIC_IP}`
* `vm4.gio-infra.io`, Public IP `${VM4_PUBLIC_IP}`
* `vm5.gio-infra.io`, Public IP `${VM5_PUBLIC_IP}`
* `vm6.gio-infra.io`, Public IP `${VM6_PUBLIC_IP}`
* `vm7.gio-infra.io`, Public IP `${VM7_PUBLIC_IP}`
* `vm8.gio-infra.io`, Public IP `${VM8_PUBLIC_IP}`
* `vm9.gio-infra.io`, Public IP `${VM9_PUBLIC_IP}`
* `vm10.gio-infra.io`, Public IP `${VM10_PUBLIC_IP}`

* for all VMs :
* linux username : `devopserator` (same username on all VMs)
* on my everyday workstation (or laptop), after I created those 10 VMs, I locally store all 10 SSH key files pairs, so 20 files, like this:
* for the VM `VM${i}`, I store public and private SSH key files at local paths :
* `~/.ssh/vm${i}/id_rsa.pub` (public SSH key, different for each VM),
* `~/.ssh/vm${i}/id_rsa` (private SSH Key different for each VM)
*  So that we arevey clear on where we are now, i exeplicitly end up on my everyday workstation (or laptop) with those 20 local file path :

```bash
# ~/.ssh/vm1/id_rsa.pub
# ~/.ssh/vm1/id_rsa

# ~/.ssh/vm2/id_rsa.pub
# ~/.ssh/vm2/id_rsa

# ~/.ssh/vm3/id_rsa.pub
# ~/.ssh/vm3/id_rsa

# ~/.ssh/vm4/id_rsa.pub
# ~/.ssh/vm4/id_rsa

# ~/.ssh/vm5/id_rsa.pub
# ~/.ssh/vm5/id_rsa

# ~/.ssh/vm6/id_rsa.pub
# ~/.ssh/vm6/id_rsa

# ~/.ssh/vm7/id_rsa.pub
# ~/.ssh/vm7/id_rsa

# ~/.ssh/vm8/id_rsa.pub
# ~/.ssh/vm8/id_rsa

# ~/.ssh/vm9/id_rsa.pub
# ~/.ssh/vm9/id_rsa

# ~/.ssh/vm10/id_rsa.pub
# ~/.ssh/vm10/id_rsa
```

All those key files are different form each other, and I don't want to ever, for any of those 10 VMS loose :
* the Public IP to use to connect to it over ssh
* the linux username to use to connect over SSH to it, `devopserator`
* or the 2 files for the public and private SSH keys.


Now, with that sum up, I see that for each of those 4 VMs, there actually are 4 inforamtions, that I want to not ever loose, and always keep secret, for each of those VMs.

And below here is the strategy I would do that using `secrethub` :

* to secure those secrets for all 10 VMs :

```bash

# ---
# Secrethubsecret manager as the concept of organizations and repos :
# yes, user mgmt works just like for orgs and repos in gtihub, on secrehub, that's why..
#
export NAME_OF_ORG="gravitee-io"
export NAME_OF_REPO_IN_ORG="gravitee-io/infra"

secrethub org init "${NAME_OF_ORG}"
secrethub repo init "${NAME_OF_REPO_IN_ORG}"

# --- #
# In repos, we store secrets into folders... (yes like actual git repos, but it's not...)
# Oh, and yes,(and that's awesome) secrets are versioned in secrethub, like they are
# in HashiCorp Vault, but we'll see that later...
# --- #
# for the Quarter 4 of 2020 CI CD temporary
# migration of the Gravitee CI CD

for MACHINE_NO in 1 2 3 4 5 6 7 8 9 10
do
  secrethub mkdir --parents "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm${MACHINE_NO}/ssh"
done


# --- #
# Example of storing secrets for VM1 :
# note the 'write' command is the one to use to store secrets
export SSH_LX_USERNAME="devopserator"
export SSH_PUBLIC_IP="85.15.46.77"
export LOCAL_SSH_PUBKEY=~/.ssh/vm7/id_rsa.pub
export LOCAL_SSH_PRVIKEY=~/.ssh/vm7/id_rsa


echo "${SSH_LX_USERNAME}" | secrethub write "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm1/ssh/username"
echo "${SSH_PUBLIC_IP}" | secrethub write "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm1/ssh/public_ip"
secrethub write --in-file ${LOCAL_SSH_PUBKEY} "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm1/ssh/pub_key"
secrethub write --in-file ${LOCAL_SSH_PRVIKEY} "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm1/ssh/priv_key"

# etc... for all VMs, securing all SSH key pairs :

for MACHINE_NO in 1 2 3 4 5 6 7 8 9 10
do
  secrethub write --in-file ${LOCAL_SSH_PUBKEY} "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm${MACHINE_NO}/ssh/pub_key"
  secrethub write --in-file ${LOCAL_SSH_PRVIKEY} "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm${MACHINE_NO}/ssh/priv_key"
done



```

* to retrieve, on my everyday workstation (laptop?) those 4 secrets :
* for example, for VM 3:

```bash

export NAME_OF_ORG="gravitee-io"
export NAME_OF_REPO_IN_ORG="gravitee-io/infra"


export PATH_ONMY_MACHINE=~/.ssh/myvm3
rm -fr ${PATH_ONMY_MACHINE}
mkdir -p ${PATH_ONMY_MACHINE}
chmod -R 700 ${PATH_ONMY_MACHINE}

# There you go on how to read secret files
secrethub read --out-file "${PATH_ONMY_MACHINE}/id_rsa" "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm3/ssh/priv_key"
secrethub read --out-file "${PATH_ONMY_MACHINE}/id_rsa.pub" "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm3/ssh/pub_key"
chmod 644 ${PATH_ONMY_MACHINE}/id_rsa.pub
chmod 600 ${PATH_ONMY_MACHINE}/id_rsa

# There you go on how to read secrets stored as strings
secrethub read "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm${MACHINE_NO}/ssh/username"
export PUBL_IP_ADDR=$(secrethub read "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm3/ssh/username")
secrethub read "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm${MACHINE_NO}/ssh/public_ip"
export SSH_USERNAME=$(secrethub read "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm3/ssh/public_ip")


echo "And now you can SSH into VM3 like this :  "
echo ""
echo " ssh -i ${PATH_ONMY_MACHINE}/id_rsa ${SSH_USERNAME}@${PUBL_IP_ADDR}"
echo ""

ssh -Ti ${PATH_ONMY_MACHINE}/id_rsa ${SSH_USERNAME}@${PUBL_IP_ADDR}

# Et voilà !
```

* Now for all of those 10 `VM`s :

```bash

export NAME_OF_ORG="gravitee-io"
export NAME_OF_REPO_IN_ORG="gravitee-io/infra"

# first, if needed, I'll (re-)install Secrethub CLI
# Then, if needed, I'll restore the ~/.secrethub/credential file ,with token value from Keypass2

# And I'll execute this :

# To retrieve all Public IPs to SSH to

touch /etc/hosts

echo "" | tee -a /etc/hosts
echo "# --- # " | tee -a /etc/hosts
echo "# Quarter 4 of 2020 CI CD temporary " | tee -a /etc/hosts
echo "# migration of the Gravitee CI CD Infra " | tee -a /etc/hosts
echo "#  " | tee -a /etc/hosts
echo "" | tee -a /etc/hosts
# note the 'read' command is the one to use to retrieve secrets
for MACHINE_NO in 1 2 3 4 5 6 7 8 9 10
do
  export PUBL_IP_ADDR=$(secrethub read "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm${MACHINE_NO}/ssh/public_ip")
  echo "vm${MACHINE_NO}.gio-infra.io   ${PUBL_IP_ADDR}" | tee -a /etc/hosts
done
echo "# ---" | tee -a /etc/hosts
echo "" | tee -a /etc/hosts

mkdir -p ~/.ssh/
chmod -R 700 ~/.ssh

for MACHINE_NO in 1 2 3 4 5 6 7 8 9 10
do
  mkdir -p ~/.ssh/
  chmod -R 700 ~/.ssh/vm${MACHINE_NO}
  export PATH_ONMY_MACHINE=~/.ssh/vm${MACHINE_NO}/id_rsa
  secrethub read --out-file ${PATH_ONMY_MACHINE} "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm${MACHINE_NO}/ssh/priv_key"
  export PATH_ONMY_MACHINE=~/.ssh/vm${MACHINE_NO}/id_rsa.pub
  secrethub read --out-file ${PATH_ONMY_MACHINE} "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm${MACHINE_NO}/ssh/pub_key"
  chmod 644 ~/.ssh/vm${MACHINE_NO}/id_rsa.pub
  chmod 600 ~/.ssh/vm${MACHINE_NO}/id_rsa
done

echo "# +++---"
echo "#  SSH configurations retireved for all VMs, here is how to SSH in to them:
echo "# +++---"

for MACHINE_NO in 1 2 3 4 5 6 7 8 9 10
do
  export SSH_USERNAME=$(secrethub read "${NAME_OF_REPO_IN_ORG}/migrations/2020/q4/target/vm${MACHINE_NO}/ssh/username")
  echo "# ---"
  echo " TO SSH into VM${MACHINE_NO} : "
  echo "ssh -i ~/.ssh/vm${MACHINE_NO}/id_rsa ${SSH_USERNAME}@vm${MACHINE_NO}.gio-infra.io"
done
echo "# +++---"
echo ""
```

That's pretty much al abvout the basicson howto read/write the 2main types of secrets: files, and strings.

Now next steps :

* service accounts (or the _`credential` for non-human users_ case)
* collaboration and secrets : sharing secrets with other secrethub users, in the same organization (to be continued) :

```bash
secrethub org invite --help
# oh yes, amazing
```

* secrethub SDKs : the secrethub cli actually is just a REST API client. SO you can do the eact same using any programming languages, and there are ready-to -use client libraries in main languages and somany  major industry devops tools inegration : Javascript / Typesript etc... see https://secrethub.io/integrations/

(Amazing, hum?)
