= Check the health of your installations
:page-sidebar: cockpit_sidebar
:page-permalink: cockpit/3.x/cockpit_userguide_installation_health_check.html
:page-folder: cockpit/userguide
:page-description: Gravitee.io Cockpit - Installation health check and monitoring
:page-keywords: Gravitee.io, API Platform, API Management, Cockpit, documentation, manual, guide


== Compatibility notice

NOTE: This feature is only available with APIM & AM 3.8 or higher.

== Overview

Installations that are registered with Cockpit will report valuable information, including configuration of the installation, list of nodes, plugins, and also some regular updates regarding their health status.

=== Nodes

Installations are monitored at node level. The first REST API node connected when you registered the installation acts as the *primary node*.
The role of the primary node is to gather, consolidate, and share the information from the other registered nodes, including:

- status
- name
- version
- sharding tags
- JDK version
- list of plugins
- health checks

If the primary node goes down, another REST API node takes over as primary node. If no REST API nodes are left, after 5 minutes all nodes are considered unhealthy, since Cockpit is no longer able to retrieve health information from the installation.

Nodes can be in a `STARTED` or `STOPPED` state.

You can view all the nodes of an installation which are in a `STARTED` state in the Dashboard, with a color indicating the state of their health.
You can click on a node to access more details about that node, including general details about the node (for example, name and version), the list of plugins.

=== Health checks

Health check data is gathered every 5 seconds. A node is considered unhealthy if its last health check was unhealthy, or if the last health check was more than five minutes ago.
