---
product: API Management
toc: true
title: Install the full APIM stack
guide: Installation Guide
guide-section: RedHat, CentOS, or Oracle Linux
---

:page-liquid:
:page-description: Gravitee.io API Management - Installation Guide - Red Hat or CentOS - API Management
:page-keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
:gravitee-package-name: graviteeio-apim-3x

This section describes how to install the full APIM stack, including all the components and, optionally, dependencies (MongoDB, Elasticsearch).
For instructions on installing the components separately, see the link:./gateway.html[APIM Gateway], link:./rest-api.html[APIM API], link:./console.html[APIM Console], and link:./portal.html[APIM Portal] sections.

== Prerequisites

Before you install the full APIM stack, you must complete the following configuration.

=== Install Nginx

To install Nginx, run the following commands:

[source,bash,subs="attributes"]
----
sudo yum install epel-release
sudo yum install nginx
----

=== Configure your package management system

Ensure you have configured your package management system, as described in link:../amazon-linux/configure-yum.html[Configure YUM].

== Install the APIM package with dependencies

=== 1. Configure dependency repositories

Before you install the APIM package, you may need to add third-party repositories.

==== MongoDB

NOTE: For guidance on installing and configuring MongoDB, see the link:https://docs.mongodb.com/v3.6/tutorial/install-mongodb-on-red-hat/[MongoDB Installation documentation, window=\"_blank\"].

[source,bash]
----
echo "[mongodb-org-3.6]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/3.6/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-3.6.asc" | sudo tee /etc/yum.repos.d/mongodb-org-3.6.repo > /dev/null

sudo yum install -y mongodb-org
sudo systemctl start mongod
----

==== Elasticsearch 7.x

NOTE: For guidance on installing and configuring Elasticsearch, see the link:https://www.elastic.co/guide/en/elasticsearch/reference/7.6/rpm.html#rpm-repo[Elasticsearch Installation documentation, window=\"_blank\"].

[source,bash]
----
echo "[elasticsearch-7.x]
name=Elasticsearch repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md" | sudo tee /etc/yum.repos.d/elasticsearch.repo > /dev/null
sudo yum install -y elasticsearch
sudo systemctl start elasticsearch
----

=== 2. Install APIM

[source,bash,subs="attributes"]
----
curl -L https://bit.ly/install-apim-3x | bash
----

=== 3. Run APIM with `systemd`

To start up the APIM components, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl daemon-reload
sudo systemctl start {gravitee-package-name}-gateway {gravitee-package-name}-management-api
sudo systemctl restart nginx
----

=== 4. Check the APIM components are running

When all components are started, you can run a quick test by checking these URLs:

|===
|Component |URL

|APIM Gateway
|http://localhost:8082/

|APIM API
|http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/apis

|APIM Management
|http://localhost:8084/

|APIM Portal
|http://localhost:8085/

|===

== Install the APIM package (no dependencies)

Already have all required dependencies installed? You can install APIM by running the following command:

[source,bash,subs="attributes"]
----
sudo yum install {gravitee-package-name}
----
