= Configure Cockpit
:page-sidebar: cockpit_sidebar
:page-permalink: cockpit/3.x/cockpit_installguide_configuration.html
:page-folder: cockpit/installation-guide
:page-description: Gravitee Cockpit - Configuration
:page-toc: false
:page-keywords: Gravitee.io, API Platform, API Management, Cockpit, documentation, manual, guide, reference, api

== Overview

There are three different ways to configure Cockpit:

- Environment variables
- System properties
- `gravitee.yml`

The order in which they are listed above corresponds to their order of precedence. In other words, environment variables override the other two configuration types, and system properties override `gravitee.yml`.

=== `gravitee.yml`

The `gravitee.yml` file, found in `GRAVITEE_HOME/config/`, is the default way to configure Cockpit.

WARNING: YAML (`yml`) format is very sensitive to indentation. Ensure you include the correct number of spaces and use spaces instead of tabs.

[source,yaml]
----
############################################################################################################
############################ Gravitee.IO Cockpit Management API - Configuration ############################
############################################################################################################

############################################################################################################
# This file is the general configuration of Gravitee.IO Cockpit Management API:
# - Properties (and respective default values) in comment are provided for information.
# - You can reference other property by using ${property.name} syntax
# - gravitee.home property is automatically set-up by launcher and refers to the installation path. Do not override it !
#
# Please have a look to http://docs.gravitee.io/ for more options and fine-grained granularity
############################################################################################################

# HTTP Server
jetty:
#  IP/hostname to bind to. Default is 0.0.0.0
#  host: 0.0.0.0
  port: 8063
#  idleTimeout: 30000
#  acceptors: -1
#  selectors: -1
#  pool:
#    minThreads: 10
#    maxThreads: 200
#    idleTimeout: 60000
#    queueSize: 6000
#  jmx: false
#  statistics: false
#  accesslog:
#    enabled: true
#    path: ${gravitee.home}/logs/gravitee_accesslog_yyyy_mm_dd.log
#  secured: false
#  ssl:
#    keystore:
#      path: ${gravitee.home}/security/keystore.jks
#      password: secret
#    truststore:
#      path: ${gravitee.home}/security/truststore.jks
#      password: secret

http:
  api:
    # Configure the listening path for the API. Default to /
    #entrypoint: /
  cors:
    # Allows to configure the header Access-Control-Allow-Origin (default value: *)
    # '*' is a valid value but is considered as a security risk as it will be opened to cross origin requests from anywhere.
    #allow-origin: http://developer.mycompany.com
    # Allows to define how long the result of the preflight request should be cached for (default value; 1728000 [20 days])
    #max-age: 864000
    # Which methods to allow (default value: OPTIONS, GET, POST, PUT, DELETE)
    #allow-methods: 'OPTIONS, GET, POST, PUT, DELETE'
    # Which headers to allow (default values: Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With, If-Match)
    #allow-headers: 'X-Requested-With'
  csrf:
    enabled: true
  hsts:
    enabled: true
    include-sub-domains: true
    max-age: 31536000
  connectionTimeout: 10
  pool:
    maxTotalConnection: 10
  client:
    trustAll: true

jwt:
  secret: ybbrZDZmjnzWhstP8xv2SQL28AdHuNah
  issuer: gravitee-cockpit-auth
  expire-after: 604800
  cookie-name: Auth-Graviteeio-Cockpit

reCaptcha:
    enabled: false
    siteKey:
    secretKey:
    minScore:
    serviceUrl:

controller:
  compatible-versions:
    apim: 3.6.3
    am: 3.6.2
    connector: 1.3.0
  #ws:
    #instances: 0
    #port: 8062
    #host: 0.0.0.0
    #alpn: false

ssl:
  keystore:
    type: pkcs12 # Supports jks, pem, pkcs12
    path:
    password:
  truststore:
    type: pkcs12 # Supports jks, pem, pkcs12
    path:
    password:

keystore:
  type: pkcs12 # Supports jks, pem, pkcs12
  path:
  password:

truststore:
  type: pkcs12 # Supports jks, pem, pkcs12
  path:
  password:

# Management repository is used to store global configuration

# Management repository: single MongoDB using URI
# For more information about MongoDB configuration using URI, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
#management:
#  type: mongodb
#  mongodb:
#    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]


# This is the default configuration using MongoDB (single server)
# For more information about MongoDB configuration, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    username:
#    password:
#    connectionsPerHost: 0
#    connectTimeout: 500
#    maxWaitTime: 120000
#    socketTimeout: 500
#    socketKeepAlive: false
#    maxConnectionLifeTime: 0
#    maxConnectionIdleTime: 0
#    serverSelectionTimeout: 0
#    description: gravitee.io
#    heartbeatFrequency: 10000
#    minHeartbeatFrequency: 500
#    heartbeatConnectTimeout: 1000
#    heartbeatSocketTimeout: 20000
#    localThreshold: 15
#    minConnectionsPerHost: 0
#    sslEnabled: false
#    threadsAllowedToBlockForConnectionMultiplier: 5
#    cursorFinalizerEnabled: true
#    writeConcern: 1
#    wtimeout: 0
#    journal: true
#    keystore:
#    keystorePassword:
#    keyPassword
ds:
  mongodb:
    dbname: gravitee-cockpit
    host: localhost
    port: 27017

# Management repository: clustered MongoDB
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
#    dbname: ${ds.mongodb.dbname}
#    connectTimeout: 500
#    socketTimeout: 250

# Management repository: JDBC
#management:
#  type: jdbc
#  jdbc:
#    url:
#    username:
#    password:
#    pool:
#      autoCommit:
#      connectionTimeout:
#      idleTimeout:
#      maxLifetime:
#      minIdle:
#      maxPoolSize:

services:
  core:
    http:
      enabled: true
      port: 18063
      host: localhost
      authentication:
        # authentication type to be used for the core services
        # - none : to disable authentication
        # - basic : to use basic authentication
        # default is "basic"
        type: basic
        users:
          admin: adminadmin

  # metrics service
  metrics:
    enabled: false
    prometheus:
      enabled: true

  dataPurge:
    # Overwrite the next property to change the cron trigger of the job purging the health check reports.
    cron: "0 0 0 */1 * *"
    # The following property is only used to define on premise plan attributes.
    onPremise:
      # On premise we won't delete any health check report by default, that why the default value is -1.
      monitoringDataRetentionDuration: -1

certificates:
  # The default secret to use to protect passwords of generated account keystores (WARN: need to be changed).
  secret: QdjshTRmurH3YtzFCrYATkSG8H65xwah
  # The principal used to generate account certificates.
  principal: 'EMAILADDRESS=contact@graviteesource.com, CN={accountId}, OU=Cockpit, O=GraviteeSource, L=Lille, ST=France, C=FR'
  # Expiration delay in second (default 31536000 == 1 year)
  expire-after: 31536000
  key:
    alg: RSA
    size: 4096
  signature:
    alg: SHA512WithRSA

endpoints:
  ui: "http://localhost:4004"
  ws: "https://localhost:8062"

domainRestrictions:
  apim:
    #account:
    #organization:
    environment: '{environment}.{organization}.{account}.apimgw.gravitee.io'
  am:
    #account:
    #organization:
    environment: '{environment}.{organization}.{account}.amgw.gravitee.io'

email:
  host: localhost
  port: 1025
  subject: "[Gravitee.io Cockpit] %s"
  username:
  password:
  protocol: smtp
  properties:
  templates:
    path: ${gravitee.home}/templates
  # Change this configuration to enable sending email for every new account created
  notifications:
    enabled: false
    recipient: notifications@acme.com

user:
  creation:
    token:
      expire-after: 86400
membership:
  invitation:
    token:
      expire-after: 86400


auth:
  callbackUrl: /auth/login/callback
#  github:
#    userAutorizationUri: https://github.com/login/oauth/authorize
#    accessTokenUri: https://github.com/login/oauth/access_token
#    userProfileUri: https://api.github.com/user
#    codeParameter: code
#    responseType: code
#    clientId:
#    clientSecret:
#    redirectUri: http://localhost:8063/auth/login/callback?provider=github
#    scopes:
#    http:
#      connectionTimeout: 10000
#      maxTotalConnection: 10
#  google:
#    userAutorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#    accessTokenUri: https://oauth2.googleapis.com/token
#    userProfileUri: https://openidconnect.googleapis.com/v1/userinfo
#    codeParameter: code
#    responseType: code
#    clientId:
#    clientSecret:
#    redirectUri: http://localhost:8063/auth/login/callback?provider=google
#    scopes: openid,profile,email
#    http:
#      connectionTimeout: 10000
#      maxTotalConnection: 10
#  oidc:
#    wellKnownUri: https://oidc-server/oidc/.well-known/openid-configuration
#    userAuthorizationUri: https://oidc-server/oauth/authorize
#    accessTokenUri: https://oidc-server/oauth/token
#    userProfileUri: https://oidc-server/oidc/userinfo
#    clientId:
#    clientSecret:
#    redirectUri: http://localhost:8063/auth/login/callback?provider=oidc
#    scopes: openid,profile,email
#    useIdTokenForUserInfo: false
#    publicKeyResolver: JWKS_URL
#    keyResolverParameter: https://oidc-server/oidc/.well-known/jwks.json
#    http:
#      connectionTimeout: 10000
#      maxTotalConnection: 10
----

=== System properties

You can override the default `gravitee.yml` configuration by defining system properties.

To override this property:

[source,yaml]
----
management:
  mongodb:
    dbname: myDatabase
----

Add this property to the JVM:

----
-Dmanagement.mongodb.dbname=myDatabase
----


=== Environment variables

You can override the default `gravitee.yml` configuration and system properties by defining environment variables.

To override this property:

[source,yaml]
----
management:
  mongodb:
    dbname: myDatabase
----

Define one of the following variables:

----
GRAVITEE_MANAGEMENT_MONGODB_DBNAME=myDatabase
GRAVITEE.MANAGEMENT.MONGODB.DBNAME=myDatabase
gravitee_management_mongodb_dbname=myDatabase
gravitee.management.mongodb.dbname=myDatabase
----

WARNING: Some properties are case-sensitive and cannot be written in upper case. We advise you to define environment variables in lower case. Ensure you use the correct syntax for each property.

TIP: Some systems forbid hyphens in variable names. You can replace them with another character such as an underscore (for example, `gravitee_policy_apikey_header` instead of `gravitee_policy_api-key_header`).
