= Password policy
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_userguide_user_management_password_policy.html
:page-folder: am/user-guide
:page-layout: am

[label label-version]#New in version 3.6#

[quote, OWASP, 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls[Authentication cheat sheet^]']
A key concern when using passwords for authentication is password strength. A "strong" password policy makes it difficult or even improbable for one to guess the password through either manual or automated means.

== Configure a password policy

You can configure the password policy settings for your end users during the *sign up* and *reset password* actions.

. link:{{ '/am/current/am_userguide_authentication.html' | relative_url }}[Log in to AM Console^].
. Select your application and click *Settings > Password policy*.
. Configure your password policy settings and click *SAVE*.

NOTE: You can also configure password policy settings at security domain level, to be applied across all applications.

== Password settings characteristics

You can set the following password characteristics:

- *Minimum length*: length of the passwords should be enforced by the application.
- *Numbers*: must include at least one number.
- *Special characters*: must include at least one special character.
- *Mixed case*: must include lower and upper case letters.
- *Exclude common passwords*: will exclude common passwords from a dictionary.
- *Exclude user profile information from passwords*: will user profile information within passwords (case insensitive).

== Password dictionary

By default, the password dictionary includes link:https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10k-most-common.txt[ten thousand common passwords^].

If you wish to use your own password dictionary or add entries to the existing password dictionary, update the `gravitee.yml` file (on both AM Gateway and AM API) as follows:

```yaml
user:
  password:
    policy:
      ...
      ## Password dictionary to exclude most commons passwords
      ## You need to enable the feature in the AM management console

      dictionary:
        filename: /path/to/dictionary.txt
        watch: true # true|false:boolean
```

Where:

- `user.password.policy.dictionary.filename` is the path of the file containing the passwords.
- `user.password.policy.dictionary.watch` if true, will listen for any change on the current `filename` and update the dictionary without restarting the service.

== Custom UI errors

You can access the password policy settings in your *Sign Up* and *Register* link:{{ '/am/current/am_userguide_user_management_forms.html' | relative_url }}[HTML templates^], making it possible to customize the error messages your end users see.

```html
<div th:if="${passwordSettings != null}" id="passwordSettings">
    <span>Password policy :</span>
    <p th:if="${passwordSettings.minLength != null}" id="minLength" class="invalid">Contains at least <span th:text="${passwordSettings.minLength}"/> characters</p>
    <p th:if="${passwordSettings.includeNumbers}" id="includeNumbers" class="invalid">Contains a number</p>
    <p th:if="${passwordSettings.includeSpecialCharacters}" id="includeSpecialChar" class="invalid">Contains a special character</p>
    <p th:if="${passwordSettings.lettersInMixedCase}" id="mixedCase" class="invalid">Contains letters in mixed case</p>
    <p th:if="${passwordSettings.maxConsecutiveLetters != null}" id="maxConsecutiveLetters" class="valid">Max <span th:text="${passwordSettings.maxConsecutiveLetters}"/> consecutive letters or numbers</p>
    <p th:if="${passwordSettings.excludePasswordsInDictionary}" id="excludePasswordsInDictionary" class="advice">Don't use common names or passwords</p>
    <p th:if="${passwordSettings.excludeUserProfileInfoInPassword}" id="excludeUserProfileInfoInPassword" class="invalid">Don't use your profile information in password</p>
</div>
```
