= SCIM 2.0
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_devguide_protocols_scim_overview.html
:page-folder: am/dev-guide/protocols/scim
:page-layout: am

link:http://www.simplecloud.info/[SCIM 2.0^] is a standard for automating the exchange of user identity information between identity domains, or IT systems.

Since it is a standard, SCIM ensures interoperability and user data consistency that can be communicated across similar applications.
SCIM enables to automate the provisioning/deprovisioning process and manage users and groups.

SCIM protocol endpoints exposed by AM API are as follows:

* link:{{ '/am/current/scim/index.html' | relative_url }}[SCIM 2.0 Console^] - link:{% link /am/current/scim/swagger.yml %}[Swagger spec^]

== Protocol

SCIM is a standard that defines schema and protocols for identity management.

It relies on REST APIs with endpoints exposing CRUD (Create, Read, Update, Delete) functionality for users and groups as well as search, discovery and bulk features.
