---
redirect_from:
  - /am/current/am_installguide_redhat_introduction.html
---
= Introduction
:page-liquid:
:page-description: Gravitee.io Access Management - Installation Guide - Red Hat or CentOS - Introduction
:page-keywords: Gravitee.io, API Platform, Access Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

This section explains how to install AM on Red Hat Enterprise Linux, CentOS Linux or Oracle Linux
using the `yum` package manager.

NOTE: RPM installation is not supported on distributions with old versions of RPM, such as SLES 11 and CentOS 5. If you are running one of these versions, you need to link:/Guides/AM/current/installation-guide/zip/gateway.html[Install Access Management with .zip^] instead.

== Configure the package management system (`yum`)

. Create a file called `graviteeio.repo` in location `/etc/yum.repos.d/` so that you can install AM directly using `yum`:
+
[source,properties]
----
[graviteeio]
name=graviteeio
baseurl=https://packagecloud.io/graviteeio/rpms/el/7/$basearch
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/graviteeio/rpms/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
----
+
. Enable GPG signature handling, which is required by some of our RPM packages:
+
[source,bash]
----
sudo yum install pygpgme yum-utils
----
+
. Before continuing, you may need to refresh your local cache:
+
[source,bash]
----
sudo yum -q makecache -y --disablerepo='*' --enablerepo='graviteeio'
----

Your repository is now ready to use.

== Install the AM components

Now, you can link:./stack.html[install all four AM components as a full stack], or install each component individually.
