= Bot Detection
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_userguide_bot_detection.html
:page-folder: am/user-guide
:page-layout: am

== Overview

Bot Detection allows to protect your application by detecting requests coming from bots. Currently this protection applies on three pages: 

* Sign-In
* Sign-Up
* Forgot Password

AM supports various link:{{ '/am/current/am_userguide_bot_detection_plugins.html' | relative_url }}[Bot Detection] mechanisms for protecting user account out of the box.

== Enable Bot Detection

Once you have created a link:{{ '/am/current/am_userguide_bot_detection_plugins.html' | relative_url }}[Plugin], you have to enable the bot detection.

== Bot Detection at Domain level

. link:{{ '/am/current/am_userguide_authentication.html' | relative_url }}[Log in to AM Console^].
. Click *Settings > User Accounts*.
. In the *Bot Detection* section.
. Enable the protection using the toggle button
. Select the plugin to use and click *Save*.

This will apply the protection to all your applications except if one of them overrides the user account settings.

== Bot Detection at Application level

. link:{{ '/am/current/am_userguide_authentication.html' | relative_url }}[Log in to AM Console^].
. Select your application
. Click *Settings > User Accounts*.
. If the application inherit from the domain settings, switch off the toggle button
. In the *Bot Detection* section.
. Enable the protection using the toggle button
. Select the plugin to use and click *Save*.

NOTE: If initially the application inherited from the domain settings remember to apply at the application level all relevant settings regarding the other sections.

