= Silent re-authentication
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_userguide_login_silent_re_auth.html
:page-folder: am/user-guide
:page-layout: am

[label label-version]#New in version 3.10#

To lower authentication friction from third parties which can't maintain session with Gravitee.io AM, the use of the OpenID Connect ID Token let you request for new tokens in a silent manner.

To trigger the silent re-authentication, your application must call the link:{{ '/am/current/am_devguide_protocols_oauth2_overview.html#authorization_code' | relative_url }}[authorization endpoint] with the following parameters :

- *id_token_hint* : ID Token previously issued by the Authorization Server being passed as a hint about the End-User’s current or past authenticated session with the application.
- *prompt* : value must be `none` to disable interactive login flow.

If the ID token is valid, the end user will be (re)connected and AM will respond with an authorization code, otherwise `login_required` error will be sent to your application.

To enable silent re-authentication feature :

. link:{{ '/am/current/am_userguide_authentication.html' | relative_url }}[Log in to AM Console^].
. Select your application and click *Settings > General*.
. Switch on *Silent re-authentication* and click *SAVE*.
