= Login
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_userguide_login.html
:page-folder: am/user-guide
:page-layout: am

Login flow is the key process of Gravitee.io Access Management to prove user identity before providing any access (i.e., tokens).

More than a simple username/password experience, AM gives you the power to design your authentication flows to reflect your authorization business rules.

Out of the box, Gravitee AM comes with several features, such as social login, MFA, passwordless, custom pages, and more to effortlessly tailor your users experience.

To learn more about our login experience, make your way through the guidance below: 

- link:/am/current/am_userguide_identity_providers.html[Link your users to your application].
- link:/am/current/am_userguide_branding.html[Login page branding].
- link:/am/current/am_userguide_mfa.html[Enable MFA].
- link:/am/current/am_userguide_mfa_step_up.html[Step-up authentication].
- link:/am/current/am_userguide_passwordless.html[What about passwordless authentication?]
- link:/am/current/am_userguide_login_silent_re_auth.html[Silent re-authentication].
- link:/am/current/am_userguide_login_identifier_first_login_flow.html[Identifier-first login flow]. 

