= Client-Initiated Backchannel Authentication Flow
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_devguide_protocols_ciba_overview.html
:page-folder: am/dev-guide/protocols/ciba
:page-layout: am

link:https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html[CIBA 1.0]: The Client-Initiated Backchannel Authentication Flow - Core 1.0 (CIBA) is an authentication flow where the Relying Party communicates with OpenID Provider without redirects through the user's browser.

== Protocol

The purpose of the Client-Initiated Backchannel Authentication Flow (link:https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html[CIBA]) is to authenticate a user without relying on the browser redirections. With this flow the Relying Parties (RPs), that can obtain a valid identifier for the user they want to authenticate, will be able to initiate an interaction flow to authenticate their users without having end-user interaction from the consumption device. The flow involves direct communication from the Client to the OpenID Provider (OP) without redirect through the user's browser (consumption device). In order to authenticate the user, the OP will initiate an interaction with an Authentication Device (AD) like a smartphone.

To activate CIBA on your security domain: 

* Click *Settings > CIBA*
* Switch on the *Enable CIBA* toggle
* Adapt the CIBA Settings if necessary
* Save your choice

=== CIBA Settings

There is three parameters for CIBA

* The validity of the *auth_req_id* in second. The *auth_req_id* is generated by the link:https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#auth_backchannel_endpoint[Authentication Backchannel Endpoint] in order to request a token once the user has been authenticated with the Authentication Device.
* The interval in seconds that a client must wait between two calls on the token endpoint to obtain an *access_token* using a given *auth_req_id*.
* The maximum number of characters allowed for the *binding_message* parameter.
* The plugin used to manage the Authentication Device interaction.

=== Authentication Device Interaction Plugins

In order to manage the interactions with the user devices, AM comes with a plugin mechanism to select the implementation that feat your needs. See the list of available link:{{ '/am/current/am_devguide_protocols_ciba_plugins.html' | relative_url }}[plugins] for more details.

== Client Registration

In order to provide a client configuration compatible with CIBA, the client have to register using the link:https://openid.net/specs/openid-connect-registration-1_0.html[Dynamic Client Registration] endpoint.

For more information about the parameters related to CIBA, please see the link:https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#registration[Registration and Discovery Metadata] section of the specification.

Here after an example of payload for a client following CIBA.

[source, json]
----
{ 
        "redirect_uris": ["https://mybank.com/callback"], 
        "client_name": "client1", 
        "application_type" : "web",
        "grant_types": [ "authorization_code","refresh_token"],         
        "response_types" : [ 
                "code", 
                "code id_token token", 
                "code id_token", 
                "code token"
        ],
        "scope":"openid payments", 
        "jwks_uri": "https://mybank.com/.well-known/jwks_uri.json",
        "default_acr_values" : ["urn:mace:incommon:iap:silver"],
        "authorization_signed_response_alg" : "PS256",
        "id_token_signed_response_alg" : "PS256",
        "request_object_signing_alg" : "PS256",
        "token_endpoint_auth_method" : "tls_client_auth",
        "tls_client_auth_subject_dn": "C=FR, ST=France, L=Lille, O=mybank, OU=Client1, CN=mycompamybankgny.com, EMAILADDRESS=contact@mybank.com",
        "tls_client_certificate_bound_access_tokens": true,
        "backchannel_token_delivery_mode": "poll",
        "backchannel_authentication_request_signing_alg": "PS256",
        "backchannel_user_code_parameter": false
      }' 
----

== Hints

The link:https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#auth_request[authentication request] exposes 3 parameters in order to identify the end user: `login_hint`, `login_hint_token` and `id_token_hint`. The `id_token_hint` is the standard ID Token JWT so the `sub` claim will be used to identify the end user. The `login_hint` is a simple string value, AM only consider this parameter as representing the *username* or the user *email address*. Finally the `login_hint_token` is a unspecified JWT that contains information which aim to identify the end-user. In order to manage this parameter, AM accepts the following payload for this JWT where:

* `format` specify the attribute used to identify the end-user (possible values are `username` and `email`)
* According the format the second entry will be either `username` or `email` with the associated value.

[source, json]
----
{
  "sub_id": {
    "format": "email",
    "email": "myuser@acme.com"
  }
}
----
