= Upgrade to 1.25.11

== Change the way query parameters and path are processed

Issue https://github.com/gravitee-io/issues/issues/2557[#2557].

This release fix a behavior that changes how query parameters and paths are processed by the gateway.
The goal is to make the gateway fully transparent.

=== Query parameters
Before this release, query parameters was sent encoded to your backend.
```
in:  ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-.~:/=,+@!$%27%3D
out: ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._%7E%3A%2F%3D%2C%20%40%21%24%27%5B%5D%28%29%3D
```

Now the gateway does not change your parameters.
```
in:  ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-.~:/=,+@!$%27%3D
out: ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-.~:/=,+@!$%27%3D
```

We also have introduced a configuration property for gateway to act like before :
```
legacy:
# Enable this parameter if you want the gateway act like version <1.25.11 .
#  See https://github.com/gravitee-io/issues/issues/2557
  decode-url-params: true #you should not need to activate this.
```

With this parameter the results are :
```
in:  ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-.~:/=,+@!$%27%3D
out: ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._%7E%3A%2F%3D%2C%20%40%21%24%27%5B%5D%28%29%3D
```

==== Dynamic Routing Policy
In case of query parameters used in the target of a dynamic-routing policy, here is the change.
Before :
```
in:  ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/=*,+@!$'%3D
out: ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._%7E%2F%3D*%2C%20%40%21%24%27%5B%5D%28%29%3D
```

After:
```
in:  ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/=*,+@!$'%3D
out: ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/=*,+@!$'[]()%3D
```


After (with legacy config enabled):
```
in:  ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/=*,+@!$'%3D
out: ?foo=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._%7E%3A%2F%3D*%2C%2B%40%21%24%27%5B%5D%28%29%253D
```

[WARNING]
====
The legacy mode is not able to have the exact same behavior than release <1.25.11

You can see some changes :

 - the legacy mode encodes the `+` sign (`%2B`) while old version use `%20`,
 - the legacy mode encodes the `%` sign (`%25`).

So, be careful when upgrading to this release and monitor apis that use "complex" dynamic-routing.
====

=== Path
Before this release, the path used in a dynamic-routing policy was decoded.
```
in:  /ab%20cd%3Def
out: /ab%20cd=ef

in:  /a%2Fb/c
out: /a/b/c
```

After:
```
in:  /ab%20cd%3Def
out: /ab%20cd%3Def

in:  /a%2Fb/c
out: /a%2Fb/c
```
