---
sidebar: ae_sidebar
permalink: ae_overview_introduction.html
folder: ae/overview
description: Gravitee Alert Engine - Introduction
toc: false
keywords: Gravitee, API Platform, Alert, Alert Engine, documentation, manual, guide, reference, api, notifier
---

= Introduction

The Gravitee.io platform is a turnkey solution to manage (APIM) and secure (AM) its APIs.
It provides a lot of features including the ability to monitor its backends APIs through the use of Health Check.
To be complete, this feature needed to be coupled with an alerting component.

And here we are with the Alert Engine (AE) component!

In the APIM context, this component allows to:

- inform API Publisher that the health-check service was able/not able to check an endpoint.

- inform consumer or publisher that he is reaching a percentage of the configured quota.

- inform administrator that one of the gateway instance is consuming more than XX% of heap or XX% of CPU.

- ...and many others uses cases...


== Gravitee Alert Engine

The Alert Engine solution will allow our customers to receive alerts / notifications through different channels (emails, slack ...)
to help monitor the health of their APIs in particular.
The solution does not require any external component as it does not store anything (no database).
AE receives events and is responsible for sending notifications under certain conditions (which have been configured upstream with triggers).

NOTE: It's a part of the support offering for the Gravitee.io Platform, but is completely agnostic and it can be used / consumed by other applications.