= Introduction
:page-sidebar: ae_sidebar
:page-permalink: ae/overview_introduction.html
:page-folder: ae/overview
:page-toc: false
:page-description: Gravitee Alert Engine - Introduction
:page-keywords: Gravitee, API Platform, Alert, Alert Engine, documentation, manual, guide, reference, api
:page-layout: ae

IMPORTANT: Gravitee.io Alert Engine is included as part of link:{{ '/ee/ee_introduction.html' | relative_url }}[Gravitee.io Enterprise]. To use it, you need to <</ee/ee_license.adoc#ask-license, contact Gravitee for a license>>.

Gravitee.io's API Platform is a turnkey solution for managing (APIM) and securing (AM) APIs. As part of its core offering it includes some monitoring capabilities, such as health checking and availability and response time monitoring.

You can extend this core monitoring functionality by coupling your API platform with the Alert Engine (AE) component.

Some of the additional alerting capabilities AE provides are:

- Notifications to API publishers that the health check service was able or unable to check an endpoint.
- Notifications to API consumers or publishers when they reach a given percentage threshold of the quota.
- Notifications to administrators that one of the APIM Gateway instances is consuming more than a percentage threshold of heap or CPU, a new one is available, or a node is down.

== Gravitee.io Alert Engine

Alert Engine (AE) provides APIM and AM users with efficient and flexible API platform monitoring, including advanced alerting configuration and notifications sent through their preferred channels, such as email, Slack and so on.

AE does not require any external components or a database as it does not store anything.
It receives events and sends notifications under the conditions which have been pre-configured upstream with triggers.
