= Enabling bot detection

You can use bot detection to protect your application by detecting requests from bots. Bot detection can be used for three pages:

* Sign-In
* Sign-Up
* Forgot Password

AM supports various bot detection mechanisms for protecting user accounts out of the box.

== Enable bot detection

Once you have created a link:./plugins.html[Plugin^], you need to enable bot detection.

=== Bot detection at domain level

. In AM Console, click *Settings > User Accounts*.
. In the *Bot Detection* section, enable protection using the toggle button.
. Select the plugin to use and click *SAVE*.

This will apply the protection to all your applications, except for any with overrides in the user account settings.

=== Bot detection at application level

. In AM Console, click *Applications* and select your application.
. Click *Settings > User Accounts*.
. If the application inherits from the domain settings, disable the *Inherit configuration* setting.
. In the *Bot Detection* section, enable protection using the toggle button.
. Select the plugin to use and click *SAVE*.

NOTE: If the application was set up to inherit domain settings, remember to reapply the other settings at application level.
