[[gravitee-installation-guide-docker]]

## Docker
:docker-image-src: https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/images
:github-repo: https://github.com/gravitee-io/gravitee-docker
:docker-hub: https://hub.docker.com/r/graviteeio

IMPORTANT: We assume that you are familiar with Docker terms. +
To run our official images, you must start by installing https://docs.docker.com/installation/[Docker]

Gravitee docker images are https://hub.docker.com/u/graviteeio/[available on Docker Hub].
You could find all https://github.com/gravitee-io/gravitee-docker/[Dockerfiles on GitHub].

We provide a complete set of images, based on the official https://hub.docker.com/_/centos/[Centos 6 image]. You could run them individually or follow our <<quickstart-docker-demo, quickstart>> to quickly discover a full Gravitee environment.

### Gravitee.io images
|===
|Image name |Source |Version

|{docker-hub}/gateway/[graviteeio/gateway]
|{github-repo}/tree/master/images/gateway[images/gateway]
|latest

|{docker-hub}/management-api/[graviteeio/management-api]
|{github-repo}/tree/master/images/management-api[images/management-api]
|latest

|{docker-hub}/management-ui/[graviteeio/management-ui]
|{github-repo}/tree/master/images/management-ui[images/management-ui]
|latest

|===


#### graviteeio/gateway

The gateway image provides a set of environment variables which could be used to tune your container. Because mongoDB is our default repository, you could replace default mongoDB address (`MONGO_DEFAULT_HOST:MONGO_DEFAULT_PORT`) by the one you provide (`MONGO_HOST:MONGO_PORT`).
The gateway image also use the elasticsearch reporter. You could replace default ES address (`ES_DEFAULT_HOST`) by the one you provide (`ES_HOST`).

##### Run the image
[source, shell]
....
$ docker run  \
        --publish 80:8082  \
        --env MONGO_HOST=127.0.0.1  \
        --env MONGO_PORT=27017  \
        --env ES_HOST=127.0.0.1  \
        --name gateway
        graviteeio/gateway:latest
....




#### graviteeio/management-api

The management-api image provides a set of environment variables which could be used to tune your container. Because mongoDB is our default repository, you could replace default mongoDB address (`MONGO_DEFAULT_HOST:MONGO_DEFAULT_PORT`) by the one you provide (`MONGO_HOST:MONGO_PORT`).

##### Run the image
[source, shell]
....
$ docker run \
        --publish 80:8082 \
        --env MONGO_HOST=127.0.0.1 \
        --env MONGO_PORT=27017 \
        --name management-api \
        graviteeio/management-api
....



#### graviteeio/management-ui

The management-ui image provides a set of environment variables which could be used to tune your container. The UI need to know where the management-api is. So you have to override `MGMT_API_HOST` and `MGMT_API_PORT` to specify where the management-api is running.

##### Run the image
[source, shell]
....
$ docker run \
        --publish 80:8082 \
        --env MGMT_API_HOST=127.0.0.1 \
        --env MGMT_API_PORT=80 \
        --name management-ui
        graviteeio/management-ui
....


### Base images
|===
|Image name |Source |Version

|{docker-hub}/httpd/[graviteeio/httpd]
|{github-repo}/tree/master/images/base/httpd[images/base/httpd]
|latest

|{docker-hub}/java/[graviteeio/java]
|{github-repo}/tree/master/images/base/java[images/base/java]
|8u45

|===

#### graviteeio/httpd

A CentOS 6 with HTTPd and some tools. 
This is a base image for all apps requiring an HTTP server. 

#### graviteeio/java

A CentOS 6 with a Java Runtime 8u45 and some tools.
This is a base image for all Java apps. 
