[[gravitee-standalone-configuration]]
== Configuration

This guide walks you through the process of configuring both Gravitee.io Standalone Gateway and Management API.

Gravitee.io allows you to externalize your configuration via the `gravitee.yml` file. Various properties can be specified
inside your configuration file.

* How to configure <<gravitee-standalone-gateway-configuration, Standalone Gateway>>
* How to configure <<gravitee-standalone-management-configuration, Standalone Management API>>
* How to configure <<gravitee-repository-mongodb-configuration, MongoDB Repository>>
* How to configure <<gravitee-repository-jdbc-configuration, JDBC Repository>>

NOTE: Below configurations are meant as a guide only. Do not copy/paste the entire content; rather pick only the
properties that you need.

[[gravitee-standalone-gateway-configuration]]
=== Standalone Gateway

[source,yaml]
----
node:
  home: ${gravitee.home}

jetty:
  port: 8082
  idleTimeout: 30000
  acceptors: -1
  selectors: -1
  jmx: false
  statistics: false
  pool:
    minThreads: 10
    maxThreads: 200
    idleTimeout: 60000
    queueSize: 6000

plugins:
  registry:
    path: ${node.home}/plugins

repository:
  type: mongodb
  mongodb:
    dbname: gravitee
    host: localhost
    port: 27017

sync:
  enabled: true
  cron: '*/5 * * * * *'

local:
  enabled: false
  path: ${node.home}/apis
----

NOTE: For Jetty configuration, please refer to its http://www.eclipse.org/jetty/[documentation]. +
Default configuration should be sufficient to start with Gravitee.io

NOTE: For Repository configuration, please refer to the <<gravitee-repository-mongodb-configuration, dedicated section>>.

[grid="none", frame="topbot", cols="25,50,35,*<"]
|===
| Property Path | Description | Default

| *_node.home_* | Home directory of the gateway | ${gravitee.home}
| *_plugins.registry.path_* | Directory where are stored _plugins_ | ${node.home}/plugins
| *_repository.type_* | The type of repository used by the gateway (when sync is enabled) | -
| *_sync.enable_* | Allows the gateway to retrieve API Definitions from the repository | true
| *_sync.cron_* | Cron expression to schedule synchronisation | */5 * * * * * - (each 5 seconds)
| *_local.enabled_* | Flag to load API definitions locally (without repository) | false
| *_local.path_* | Directory where the gateway is looking for API definitions | ${node.home}/apis
|===

[[gravitee-standalone-management-configuration]]
=== Standalone Management API

*TODO*

[[gravitee-repositories-configuration]]
=== Repositories

[[gravitee-repository-mongodb-configuration]]
==== MongoDB

NoSQL store implementation is based on https://www.mongodb.org/[MongoDB], let's see the configuration options:

[source,yaml]
----
# ===================================================================
# MINIMUM MONGO REPOSITORY PROPERTIES
#
# This is a minimal sample file declared connection to MongoDB
# ===================================================================
repository:
  type: mongodb # repository type
  mongodb: # mongodb repository
    dbname: # mongodb name (default gravitee)
    host: # mongodb host (default localhost)
    port: # mongodb port (default 27017)
----

NOTE: This is the minimum sample file to start with a mongo server, number of other properties control the behavior of mongo database, let's jump into it

[source,yaml]
----
# ===================================================================
# MONGO REPOSITORY PROPERTIES
#
# This is a sample file declared all properties for MongoDB Repository
# ===================================================================
repository:
  type: mongodb # repository type
  mongodb: # mongodb repository
    dbname: # mongodb name (default gravitee)
    host: # mongodb host (default localhost)
    port: # mongodb port (default 27017)
    username: # mongodb username (default null)
    password: # mongodb password (default null)
    connectionPerHost: # mongodb connection per host (default 10)
    connectTimeOut: # mongodb connection time out (default 0 -> never)
    maxWaitTime: # mongodb max wait time (default 120000)
    socketTimeout: # mongodb socket time out (default 0 -> never)
    socketKeepAlive: # mongodb socket keep alive (default false)
    maxConnectionLifeTime: # mongodb max connection life time (default null)
    maxConnectionIdleTime: # mongodb max connection idle time (default null)
    minHeartbeatFrequency: # mongodb min heartbeat frequency (default null)
    description: # mongodb description (default null)
    heartbeatConnectTimeout: # mongodb heartbeat connection time out (default null)
    heartbeatFrequency: # mongodb heartbeat frequency (default null)
    heartbeatsocketTimeout: # mongodb heartbeat socket time out (default null)
    localThreshold: # mongodb local threshold (default null)
    minConnectionsPerHost: # mongodb min connections per host (default null)
    sslEnabled: # mongodb ssl mode (default false)
    threadsAllowedToBlockForConnectionMultiplier: # mongodb threads allowed to block for connection multiplier (default null)
    cursorFinalizerEnabled: # mongodb cursor finalizer enabled (default false)
----

NOTE: All theses properties allow you to fine tuned your MongoDB connection

[[gravitee-repository-jdbc-configuration]]
==== JDBC

SQL Store implementation based on Java Persistence API (JPA). SQL DataSource configuration is controlled by the following configuration properties.

[source,yaml]
----
# ===================================================================
# JPA REPOSITORY PROPERTIES
# ===================================================================
repository:
  type: jpa # repository type
  jpa: # jpa repository
    hibernateDialect: org.hibernate.dialect.PostgreSQL9Dialect # hibernate dialect
    driverClassName: org.postgresql.Driver # database driver
    url: jdbc:postgresql://localhost/gravitee # database url
    username: user # database username
    password: password # database password
    showSql: false # show sql mode (default to false)
----

NOTE: We've just declared a connection to a PostgresSQL Database server.

[[gravitee-reporters-configuration]]
=== Reporters

[[gravitee-reporter-elasticsearch-configuration]]
==== Elasticsearch

*TODO*

[[gravitee-reporter-file-configuration]]
==== File (accesslog)

*TODO*