[[gravitee-installation-guide-management-webui]]

== Management UI installation

=== System Requirements

==== Browsers

Gravite.io Management UI has been tested with the latest versions of Google Chrome, Firefox and Internet Explorer >= 10

=== Installing from the ZIP archive

The binaries are available from http://gravitee.io/#downloads or via https://dl.bintray.com/gravitee-io/release/{graviteeio-version}/graviteeio-full-{graviteeio-version}.zip[bintray].

[source,bash]
[subs="attributes"]
$ curl -L https://dl.bintray.com/gravitee-io/release/{graviteeio-version}/graviteeio-full-{graviteeio-version} -o gravitee-standalone-distribution-{graviteeio-version}.zip

Once file has been downloaded, you just have to unpack it in the right place

[source,bash]
[subs="attributes"]
$ unzip gravitee-standalone-distribution-{graviteeio-version}.zip

==== Deploy

The Management UI is a client-side only Angular application and can be deployed on any HTTP server like https://httpd.apache.org/[Apache] or http://nginx.org/[Nginx].

==== or Run it

With Python::

[source,bash]
[subs="attributes"]
$ cd graviteeio-management-ui-{graviteeio-management-ui-version}
$ python3 -m http.server
$ Serving HTTP on 0.0.0.0 port 8000 ...

With Node::

[source,bash]
[subs="attributes"]
$ npm install http-server -g
$ cd graviteeio-management-ui-{graviteeio-management-ui-version}
$ http-server

==== Configuration

The Management UI provides a UI to the Gravitee.io Management API to manage the platform globally. The only one thing to configure is the Gravitee.io Management API URL :

[source,bash]
[subs="attributes"]
$ cd graviteeio-management-ui-{graviteeio-management-ui-version}
$ vi constants.js

[source,javascript]
[subs="attributes"]
'use strict';
angular.module('gvConstants', []).constant('Constants', {
  // if the management REST API is on a different domain, put something like: http://[api-rest-domain]/management/
  "baseURL": '/management/',
  "version": "0.8.2"
});
