[[gravitee-installation-guide-configuration]]
== Configuration

This guide walks you through the process of configuring both Gravitee.io Standalone Gateway and Management API.

Gravitee.io allows you to externalize your configuration via the `gravitee.yml` file. Various properties can be specified
inside your configuration file.

* How to configure <<gravitee-standalone-gateway-configuration, Standalone Gateway>>
* How to configure <<gravitee-standalone-management-configuration, Standalone Management API>>
* How to configure <<gravitee-repository-mongodb-configuration, MongoDB Repository>>
* How to configure <<gravitee-repository-jdbc-configuration, JDBC Repository>>

NOTE: Below configurations are meant as a guide only. Do not copy/paste the entire content; rather pick only the
properties that you need.

[[gravitee-standalone-gateway-configuration]]
=== Standalone Gateway

[source,yaml]
----
node:
  home: ${gravitee.home}

http:
  port: 8082
  secured: false
  compression_supported: false
  idle_timeout: 0
  tcp_keep_alive: true
  ssl:
    client_auth: false
    keystore:
      path: null
      password: null
    trustore:
      path: null
      password: null

plugins:
  registry:
    path: ${node.home}/plugins

management:
  type: mongodb
  mongodb:
    ...

sync:
  enabled: true
  cron: '*/5 * * * * *'

local:
  enabled: false
  path: ${node.home}/apis
----

NOTE: For Jetty configuration, please refer to its http://www.eclipse.org/jetty/[documentation]. +
Default configuration should be sufficient to start with Gravitee.io

NOTE: For Management Repository configuration, please refer to the <<gravitee-repository-mongodb-configuration, dedicated section>>.

[grid="none", frame="topbot", cols="25,50,35,*<"]
|===
| Property Path | Description | Default

| *_node.home_* | Home directory of the gateway | ${gravitee.home}
| *_plugins.registry.path_* | Directory where are stored _plugins_ | ${node.home}/plugins
| *_repository.type_* | The type of repository used by the gateway (when sync is enabled) | -
| *_sync.enable_* | Allows the gateway to retrieve API Definitions from the repository | true
| *_sync.cron_* | Cron expression to schedule synchronisation | */5 * * * * * - (each 5 seconds)
| *_local.enabled_* | Flag to load API definitions locally (without repository) | false
| *_local.path_* | Directory where the gateway is looking for API definitions | ${node.home}/apis
|===

[[gravitee-standalone-management-configuration]]
=== Standalone Management API
Configuration of the Management API is fairly similar to the Standalone Gateway.
You can refer to the above <<gravitee-standalone-gateway-configuration,section>> for more information.


==== Global configuration
[source,yaml]
----
node:
  home: ${gravitee.home}

http:
  port: 8082
  secured: false
  compression_supported: false
  idle_timeout: 0
  tcp_keep_alive: true
  ssl:
    client_auth: false
    keystore:
      path: null
      password: null
    trustore:
      path: null
      password: null

plugins:
  registry:
    path: ${node.home}/plugins

management:
  type: mongodb
  mongodb:
    ...

security:
  type: basic-auth
    ...
----

Finally, the only part which is only relative to the Management API is the security configuration.

[[gravitee-standalone-management-security-configuration]]
==== Security configuration

This guide walks you through the process of configuring the security of the Management API.

NOTE: The parent attribute of `gravitee.yml` for the security part is `security`.

===== Authentication Type

Gravitee.IO Management API supports both Basic Authentication and OAuth2 Authentication. The authentication-type can be defined using the following property :

[source,yaml]
----
security:
  type: # authentication type (default to 'basic', possible values : 'basic', 'oauth2')
----

NOTE: Based on the authentication type you choose, many properties kick in, especially for the Basic Authentication configuration.

===== Authentication Provider

The Gravitee.io management API module supports by default some standard ways to retrieve user information for authentication from Memory, LDAP and Gravitee.io repository (based on the repository type you have chosen). Let's see how to configure it.

[source,yaml]
----
security:
  type: basic                   # authentication type
  providers:                    # required authentication providers
----

NOTE: This is the minimum sample file to declare at least one authentication provider

====== InMemory Provider

Basic in-memory implementation, a simple and convenient way to declare "technical" users such as the administrator users. An example configuration is shown below:

[source,yaml]
----
# ===================================================================
# IN MEMORY SECURITY PROPERTIES
#
# This sample file declared one in memory authentication provider with two users
# ===================================================================
security:
  type: basic                       # authentication type
  providers:                        # required authentication providers
    - type: memory                  # authentication provider type (possible values : memory, ldap, gravitee)
      users:
        - user:
          username: user
          password: password
          roles: USER               # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
        - user:
          username: admin
          password: admin
          roles: ADMIN              # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
----

NOTE: We've just declared two users, `user` with `ROLE_USER` role and `admin` with `ROLE_ADMIN`

====== LDAP Provider

An AuthenticationProvider implementation that authenticates against an LDAP server. There are many ways in which the LDAP authentication provider can be configure. You should be familiar with LDAP before trying to use it.

[source,yaml]
----
# ===================================================================
# LDAP SECURITY PROPERTIES
#
# This sample file declared one ldap authentication provider
# ===================================================================
security:
  type: basic                               # authentication type
  providers:                                # required authentication providers
    - type: ldap
      embedded: true                        # embedded mode (true to use the embedded ldap server, usefull for test/demo, possible values : true or false)
      # if embedded is false set the following values
      context-source-username: test
      context-source-password: test
      context-source-url: ldap://localhost:389/dc=gravitee,dc=io
      role-mapping: true                    # role mapping mode for ldap user (possible values : true or false)
      # if role-mapping is true set the following role mapper LDAP values (syntax { "user_ldap_role" : "user_new_added_ldap_role"})
      role-mapper: {
        ROLE_DEVELOPERS: ROLE_USER,
        ROLE_MEMBERS: ROLE_USER,
        ROLE_OWNERS: ROLE_ADMIN
      }
      user-dn-patterns: uid={0},ou=people   # user dn patterns (default 'uid={0},ou=people')
      group-search-base: ou=groups          # groupe search base (default 'ou=groups')
      context-source-base: dc=gravitee,dc=io # the context source base
----

====== Gravitee Repository Provider

An AuthenticationProvider implementation that authenticates against Gravitee data source repository. Users are defined via the Gravitee.io management API.

[source,yaml]
----
# ===================================================================
# GRAVITEE SECURITY PROPERTIES
#
# This sample file declared gravitee authentication provider
# ===================================================================
security:
  type: basic                       # authentication type
  providers:                        # required authentication providers
    - type: gravitee                # authentication provider type (possible values : memory, ldap, gravitee)
      password-encoding: true       # enable password encoding (possible values : true or false)
----

NOTE: If password encoding system is enable the password encoder uses the BCrypt strong hashing function.

====== Combine the providers

You can specify as many providers as you want. They will be checked in same order you declared them inside the authentication-manager attribute. Once a successfull authentication is made, the Gravitee Management API will stop polling the providers.

[source,yaml]
----
# ===================================================================
# MULTIPLE PROVIDER SECURITY PROPERTIES
#
# This sample file declared gravitee authentication provider
# ===================================================================
security:
  type: basic
  providers:

    # First authentication provider
    - type: ldap
      embedded: true
      role-mapping: true
      # if role-mapping is true set the following role mapper LDAP values
      role-mapper: {
        ROLE_DEVELOPERS: ROLE_USER,
        ROLE_MEMBERS: ROLE_USER,
        ROLE_OWNERS: ROLE_ADMIN
      }
      user-dn-patterns: uid={0},ou=people
      group-search-base: ou=groups
      context-source-base: dc=gravitee,dc=io
      # if embedded is false set the following values
      # context-source-username: test
      # context-source-password: test
      # context-source-url: ldap://localhost:389/dc=gravitee,dc=io

    # Second authentication provider
    - type: memory
      users:
        - user:
          username: user
          password: password
          roles: USER
        - user:
          username: admin
          password: admin
          roles: ADMIN

    # Third authentication provider
    - type: gravitee
      password-encoding: true
----

NOTE: The authentication process will loop through the three providers to attempt user authentication

===== OAuth2 Authentication configuration

Before you get started, make sure you have a fully fonctionnal OAuth2 Authorization Server with OAuth2 Token Validation endpoint that allows a resource server to validate an access token. The OAuth2 Authorization Server must expose the following resource :

[source]
----
Request         POST /oauth/check_token
Request Body    token=<access_token>
Request Headers Authorization: Basic 'Base64.encode(client_id:client_secret)'
                Content-Type: application/x-www-form-encoded
Response Codes  200 OK
Response Body   ::
                {
                    "exp": 1426391913,
                    "user_name": "user",
                    "scope": [
                        "read",
                        "write"
                    ],
                    "authorities": [
                        "ROLE_USER"
                    ],
                    "client_id": "test"
                }
Response Codes  400 KO
Respoce Body    ::
                {
                  Token not recognized/Token expired
                }
----

The Gravitee.io Management supports OAuth2 Authentication via the following configuration :

[source,yaml]
----
# ===================================================================
# OAUTH 2 SECURITY PROPERTIES
#
# This sample file declared oauth2 security configuration
# ===================================================================
security:
  type: oauth2 # authentication type
  oauth.endpoint.check_token: # OAuth2 token validation endpoint url
  oauth.client.id: # OAuth2 resource server client id
  oauth.client.secret: # OAut2 resource server client secret
----

NOTE: With OAuth2 Authentication type, all requests to Gravitee Management API must contain the following header : Authorization Bearer <your-access-token>

[appendix]
===== Security application properties

NOTE: This sample file is meant as a guide only. Do not copy/paste the entire content; rather pick only the properties that you need.

[source,yaml]
----
security:
  type: basic
  providers:

    # First authentication provider
    - type: ldap
      embedded: true
      role-mapping: true
      # if role-mapping is true set the following role mapper LDAP values
      role-mapper: {
        ROLE_DEVELOPERS: ROLE_USER,
        ROLE_MEMBERS: ROLE_USER,
        ROLE_OWNERS: ROLE_ADMIN
      }
      user-dn-patterns: uid={0},ou=people
      group-search-base: ou=groups
      context-source-base: dc=gravitee,dc=io
      # if embedded is false set the following values
      # context-source-username: test
      # context-source-password: test
      # context-source-url: ldap://localhost:389/dc=gravitee,dc=io

    # Second authentication provider
    - type: memory
      users:
        - user:
          username: user
          password: password
          roles: USER
        - user:
          username: admin
          password: admin
          roles: ADMIN

    # Third authentication provider
    - type: gravitee
      password-encoding: true
----


[[gravitee-repositories-configuration]]
=== Repositories

[[gravitee-repositories-types]]
==== Repository types

* management: All the data the manage the Gravitee.io platform, including API definitions, users, teams, ..
* rate limit: Rate limiting data
* analytics: Analytics data

**Compatibility Matrix: **
|===
|Scope|MongoDB |JDBC |Redis |Elasticsearch

|Management
|X
|X
|-
|-

|Rate Limit
|X
|-
|X
|-

|Analytics
|-
|-
|-
|X

|===

[[gravitee-repository-mongodb-configuration]]
==== MongoDB

NoSQL store implementation is based on https://www.mongodb.org/[MongoDB], let's see the configuration options:

[source,yaml]
----
# ===================================================================
# MINIMUM MONGO REPOSITORY PROPERTIES
#
# This is a minimal sample file declared connection to MongoDB
# ===================================================================
management:
  type: mongodb             # repository type
  mongodb:                  # mongodb repository
    dbname:                 # mongodb name (default gravitee)
    host:                   # mongodb host (default localhost)
    port:                   # mongodb port (default 27017)
----

NOTE: This is the minimum sample file to start with a mongo server, number of other properties control the behavior of mongo database, let's jump into it

[source,yaml]
----
# ===================================================================
# MONGO REPOSITORY PROPERTIES
#
# This is a sample file declared all properties for MongoDB Repository
# ===================================================================
management:
  type: mongodb                 # repository type
  mongodb:                      # mongodb repository
    dbname:                     # mongodb name (default gravitee)
    host:                       # mongodb host (default localhost)
    port:                       # mongodb port (default 27017)
    username:                   # mongodb username (default null)
    password:                   # mongodb password (default null)
    connectionPerHost:          # mongodb connection per host (default 10)
    connectTimeOut:             # mongodb connection time out (default 0 -> never)
    maxWaitTime:                # mongodb max wait time (default 120000)
    socketTimeout:              # mongodb socket time out (default 0 -> never)
    socketKeepAlive:            # mongodb socket keep alive (default false)
    maxConnectionLifeTime:      # mongodb max connection life time (default null)
    maxConnectionIdleTime:      # mongodb max connection idle time (default null)
    minHeartbeatFrequency:      # mongodb min heartbeat frequency (default null)
    description:                # mongodb description (default null)
    heartbeatConnectTimeout:    # mongodb heartbeat connection time out (default null)
    heartbeatFrequency:         # mongodb heartbeat frequency (default null)
    heartbeatsocketTimeout:     # mongodb heartbeat socket time out (default null)
    localThreshold:             # mongodb local threshold (default null)
    minConnectionsPerHost:      # mongodb min connections per host (default null)
    sslEnabled:                 # mongodb ssl mode (default false)
    threadsAllowedToBlockForConnectionMultiplier: # mongodb threads allowed to block for connection multiplier (default null)
    cursorFinalizerEnabled:     # mongodb cursor finalizer enabled (default false)
----

NOTE: All theses properties allow you to fine tuned your MongoDB connection

[[gravitee-repository-jdbc-configuration]]
==== JDBC

SQL Store implementation based on Java Persistence API (JPA). SQL DataSource configuration is controlled by the following configuration properties.

[source,yaml]
----
# ===================================================================
# JDBC REPOSITORY PROPERTIES
# ===================================================================
management:
  type: jdbc                    # repository type
  jdbc:                         # jpa repository
    dataSourceClassName:        # JDBC Datasource class name
    jdbcUrl: jdbc:postgresql://localhost/gravitee # database url
    user: user                  # database username
    password: password          # database password
    autoCommit: false           # aut-commit mode (default to true)
    properties:
      specificProperty: property_value
    pool:                       # Pooling configuration
      maxPoolSize: 10
      minIdle: 0
      idleTimeout: 600000       # Idle Timeout in ms (default to 10 minutes)
      connectionTimeout: 30000  # Connection Timeout in ms (default to 30 seconds)
----

NOTE: We've just declared a connection to a PostgresSQL Database server.

[[gravitee-reporters-configuration]]
=== Reporters

[[gravitee-reporter-elasticsearch-configuration]]
==== Elasticsearch

*TODO*

[[gravitee-reporter-file-configuration]]
==== File (accesslog)

*TODO*