[[gravitee-installation-guide-docker]]

## Docker
:docker-image-src: https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/images
:github-repo: https://github.com/gravitee-io/gravitee-docker
:docker-hub: https://hub.docker.com/r/graviteeio

IMPORTANT: We assume that you are familiar with Docker terms. +
To run our official images, you must start by installing https://docs.docker.com/installation/[Docker]

Gravitee.io docker images are https://hub.docker.com/u/graviteeio/[available on Docker Hub].
You could find all https://github.com/gravitee-io/gravitee-docker/[Dockerfiles on GitHub].

We provide a complete set of images.

### Images
|===
|Image name |Source |Version |Base

|{docker-hub}/gateway/[graviteeio/gateway]
|{github-repo}/tree/master/images/gateway[images/gateway]
|latest
|https://hub.docker.com/_/alpine/[alpine:3.3]

|{docker-hub}/management-api/[graviteeio/management-api]
|{github-repo}/tree/master/images/management-api[images/management-api]
|latest
|https://hub.docker.com/_/alpine/[alpine:3.3]

|{docker-hub}/management-ui/[graviteeio/management-ui]
|{github-repo}/tree/master/images/management-ui[images/management-ui]
|latest
|https://hub.docker.com/_/alpine/[nginx:1.10.2-alpine]

|===


#### graviteeio/gateway

The gateway image provides a set of environment variables which could be used to tune your container. 
Because mongoDB is our default repository, you can replace default mongoDB address (`localhost:27017`) by the one you provide (`GRAVITEEIO_MONGODB_HOST:GRAVITEEIO_MONGODB_PORT`).
The gateway image also use the elasticsearch reporter.
You can replace default ES address (`localhost:9300`) by the one you provide (`GRAVITEEIO_ELASTIC_HOST:GRAVITEEIO_ELASTIC_PORT`).

##### Run the image
[source, shell]
....
$ docker run  \
        --publish 82:8082  \
        --env GRAVITEEIO_MONGODB_HOST=172.17.0.1  \
        --env GRAVITEEIO_MONGODB_PORT=27017  \
        --env GRAVITEEIO_ELASTIC_HOST=172.17.0.1  \
        --env GRAVITEEIO_ELASTIC_PORT=9300  \
        --name gateway  \
        --detach  \
        graviteeio/gateway:latest
....




#### graviteeio/management-api

The management-api image provides a set of environment variables which could be used to tune your container. 
Because mongoDB is our default repository, you can replace default mongoDB address (`localhost:27017`) by the one you provide (`GRAVITEEIO_MONGODB_HOST:GRAVITEEIO_MONGODB_PORT`).
The management-api image also use the elasticsearch reporter.
You can replace default ES address (`localhost:9300`) by the one you provide (`GRAVITEEIO_ELASTIC_HOST:GRAVITEEIO_ELASTIC_PORT`).

##### Run the image
[source, shell]
....
$ docker run \
          --publish 81:8083 \
          --env GRAVITEEIO_MONGODB_HOST=172.17.0.1  \
          --env GRAVITEEIO_MONGODB_PORT=27017  \
          --env GRAVITEEIO_ELASTIC_HOST=172.17.0.1  \
          --env GRAVITEEIO_ELASTIC_PORT=9300  \
          --name management-api \
          --detach  \
          graviteeio/management-api:latest
....



#### graviteeio/management-ui

The management-ui image provides a set of environment variables which could be used to tune your container. 
The UI need to know where the management-api is. 
So you have to override `MGMT_API_URL` to specify where the management-api is running.

##### Run the image
[source, shell]
....
$ docker run \
        --publish 80:80 \
        --env MGMT_API_URL=http://localhost:81/management/ \
        --name management-ui \
        --detach  \
        graviteeio/management-ui:latest
....

### Docker Compose

You can launch a complete demo environment using our ready-to-use docker-compose file. It includes Gravitee.io API Management + MongoDB + Elasticsearch.

[source, shell]
....
# Download compose files
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/common.yml -o "common.yml"
$ curl -L https://raw.githubusercontent.com/gravitee-io/gravitee-docker/master/environments/demo/docker-compose-local.yml -o "docker-compose-local.yml"

# And run demo
$ docker-compose -f docker-compose-local.yml up
....

When all components are started, you can do a quick test to see if everything is ok by checking these urls:
|===
|Image |Address

|{docker-hub}/gateway/[graviteeio/gateway]
|http://localhost:8000

|{docker-hub}/management-api/[graviteeio/management-api]
|http://localhost:8005/management/

|{docker-hub}/management-ui/[graviteeio/management-ui]
|http://localhost:8002

|===

Once done, you're now ready to play with Gravitee.io API Management, so let's take a look to the <<gravitee-quickstart, Quickstart guide>>.