= Manual Installation
:page-sidebar: ee_sidebar
:page-permalink: ee/installguide_manual.html
:page-folder: ee/installation-guide
:page-description: Gravitee Enterprise Edition - Installation - Manual
:page-keywords: Gravitee, API Platform, Enterprise Edition, documentation, manual, guide, reference, api











In general there are 2 different ways to provide the license data for a Gravitee EE product.

Using an environmental variable
Using an environmental variable called "license.key" you can directly provide the content of the license file in Base64 format.

Using a file
By default Gravitee is looking for the license file inside the "GRAVITEE_HOME/license/license.key" folder and this can be overwritten by another property "gravitee.license".

Gravitee will first look the "license.key" environmental variable and if it can not find something, then it will look into "gravitee.license" and if it is not set, then fuinaly it will try to retrieve the key from GRAVITEE_HOME folder.

Add license in Kubernetes:
With Kubernetes, it is possible to use both approaches to provide the license information.

Using environmental variable
In this case, first you need to create a new secret from your Gravitee license data and then update your Deployment description and provide a new ENV with the license data from a Kubernetes secret.

spec:
containers:

name: ONE_OF_GRAVITEE_EE_PRODUCTS
image: GRAVITEE_IMAGE
env:

name: license.key
valueFrom:
secretKeyRef:
name: graviteeio-license
key: license.key
optional: false # same as default; "mysecret" must exist

More informartion:
https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/

Using a file
Kubernetes allows you to mount the content of a special secrets inside your pod and we can use this solution to provide the license file to Gravitee.
First you need to create a Secrete containing the license data (please make sure that key is called "license.key") and then mount those content into your pod using Volumes. The mountPath is not unique and it is different for each product.
AM:
Gateway: /opt/graviteeio-am-gateway/license
API: /opt/graviteeio-am-management-api/license

APIM:
Gateway: /opt/graviteeio-gateway/license
API: /opt/graviteeio-management-api/license

AE:
/opt/graviteeio-alert-engine/license

For example:

spec:
containers:
...
volumeMounts:
- name: graviteeio-license
mountPath: "/opt/graviteeio-am-management-api/license"
readOnly: true
volumes:

name: graviteeio-license
secret:
secretName: graviteeio-license
optional: false # default setting; "mysecret" must exist

The solutions above can be used if you want to modify existing resources which are deployed already in the cluster but you can provide these information using helm and when installing r updating existing installations.

This is a very simple example of a values.yaml file that you can use for providing the license data using helm

api:
...
env:
- name: gravitee_services_notifier_enabled
value: "true"
...

extraVolumeMounts: |
- name: graviteeio-license
mountPath: /opt/graviteeio-am-management-api/license
readOnly: true
extraVolumes: |
- name: graviteeio-license
secret:
secretName: graviteeio-license

gateway:
...

env:
- name: GIO_MIN_MEM
value: 256m
.....
extraVolumeMounts: |
- name: graviteeio-license
mountPath: /opt/graviteeio-am-gateway/license
readOnly: true
extraVolumes: |
- name: graviteeio-license
secret:
secretName: graviteeio-license
