= Gateway
:page-sidebar: am_1_x_sidebar
:page-permalink: am/1.x/am_installguide_gateway.html
:page-folder: am/installation-guide

== System Requirements

=== JDK

Gravitee.io AM Gateway requires at least Java 8. Before you install Gravitee.io AM Gateway, please check your Java version :

[source,bash]
----
java -version
echo $JAVA_HOME
----

NOTE: You can download the latest JDK from the http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java SE Download Site].

=== Repository

Default AM Gateway distribution requires MongoDB 3.x to store data.

NOTE: You can download MongoDB 3.x from the https://www.mongodb.org/downloads#production[MongoDB Download Site].

== Installing from the ZIP archive

Binaries are available from https://download.gravitee.io/graviteeio-am/components/gravitee-am-gateway/gravitee-am-gateway-standalone-GRAVITEEIO-AM-VERSION.zip.

[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-am/components/gravitee-am-gateway/gravitee-am-gateway-standalone-GRAVITEEIO-AM-VERSION.zip -o gravitee-am-gateway-standalone-GRAVITEEIO-AM-VERSION.zip

Once file has been downloaded, you just have to unpack it in the right place.

[source,bash]
[subs="attributes"]
$ unzip gravitee-am-gateway-standalone-GRAVITEEIO-AM-VERSION.zip

== Running AM Gateway from the command line

AM Gateway can be started from the command line as follows:

[source,bash]
----
$ cd gravitee-am-gateway-standalone-GRAVITEEIO-VERSION
$ ./bin/gravitee
----

By default, AM Gateway runs in the foreground, prints its logs to the standard output (stdout), and can be stopped
by pressing Ctrl-C.

If everything goes well, you should see this log:

[source,bash]
[subs="attributes"]
...
16:21:01.995 [gravitee] [] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@1e1232cf{HTTP/1.1,[http/1.1]}{0.0.0.0:8092}
16:21:01.996 [gravitee] [] INFO  org.eclipse.jetty.server.Server - Started @19214ms
16:21:01.996 [gravitee] [] INFO  i.g.am.gateway.jetty.JettyHttpServer - HTTP Server is now started and listening on port 8092
...

== Checking that AM Gateway is running

You can test that your AM Gateway node is running by sending an HTTP request to port `8092` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8092/management/apis/
----

== Running as a daemon

To run AM Gateway as a daemon, specify -d on the command line, and record the process ID in a file using the -p option:

[source,bash]
----
$ ./bin/gravitee -d -p=/var/run/gio.pid
----

Log messages can be found in the `$GRAVITEE_HOME/logs/` directory.

To shut down AM Gateway, kill the process ID recorded in the pid file:

[source,bash]
----
$ kill `cat /var/run/gio.pid`
----

== Directory structure

After successfully installed AM Gateway, the `graviteeio-am-gateway` directory looks like this:

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Folder    |Description
|bin       |Startup/shutdown scripts
|config    |App configuration
|lib       |Libraries (gravitee.io AM libraries and third parties library)
|logs      |Gateway log files
|plugins   |Gateway plugins
|======================

