[[event-native-tutorials-apim]]
= Installing APIM
:page-sidebar: apim_3_x_sidebar
:page-permalink: /apim/3.x/event_native_tutorials_apim.html
:page-folder: apim/v4
:page-layout: apim3x

This page describes how to install and run APIM Community Edition or APIM Enterprise Edition with event-native features enabled in Docker containers on `localhost` using the `docker compose` command. If you need granular control over where persistence data is stored, or if you need to add plugins, use the link:{{'/apim/3.x/event_native_tutorials_apim_custom.html' | relative_url }}[Custom APIM Install].

== Prerequisites

Docker must be installed and running. For more information about installing Docker, see the link:{{'https://www.docker.com/' | relative_url }}[Docker website].

If you want to install the Enterprise Edition, you must have a license key. For more information about getting a license key, visit the link:https://www.gravitee.io/pricing[Gravitee pricing page].

== Installing APIM

1. Download the `docker-compose.yml` file as `docker-compose-apim.yml`.
+
[code,bash]
----
curl -L https://bit.ly/docker-apim-3x -o docker-compose-apim.yml  
----

2. Open `docker-compose-apim.yml` in a text editor and add the following line to the `$services.gateway.environment` and `$services.management_api.environment` sections if it is not already there.
+
[code,yml]
----
- gravitee_api_jupiterMode_enabled=true
----
+
This ensures that the gateway runs with its event-native features enabled.

3. If you are installing the Enterprise Edition, add the following line under `$services.gateway.volumes`.
+
[code,yml]
----
 - /gravitee/license.key:/opt/graviteeio-gateway/license/license.key
----
+
Where `/gravitee/license.key` is the full path to the license key. This ensures that the gateway can access the license key.

4. If you are installing the Enterprise Edition, add the following line under `$services.management_api.volumes`.
+
[code,yml]
----
 - /gravitee/license.key:/opt/graviteeio-management-api/license/license.key
----
+
Where `/gravitee/license.key` is the full path to the license key. This ensures that the management API can access the license key.

5. Run `docker compose` to download and start all of the components.
+
[code,bash]
----
docker compose -f docker-compose-apim.yml up -d
----

6. In your browser, go to `http://localhost:8084` to open the Console, and go to `http://localhost:8085` to open the Developer Portal. You can log in to both with the username `admin` and password `admin`.
+
[TIP]
====
Sometimes it can take a few minutes for APIM to fully start. If you get an error when going to `http://localhost:8084` or `http://localhost:8085`, wait a few minutes and try again.
====
