[[event-native-tutorials-mqtt-webhooks]]
= MQTT and Webhooks
:page-sidebar: apim_3_x_sidebar
:page-permalink: /apim/3.x/event_native_tutorials_mqtt_webhooks.html
:page-folder: apim/v4
:page-layout: apim3x

== Prerequisites 

Before running this tutorial, you must have:

* Set up Postman, as described in link:{{'/apim/3.x/event_native_tutorials_postman.html' | relative_url}}[Setting up Postman].
* The Gravitee API Management Gateway running in Docker, as described in link:{{'/apim/3.x/event_native_tutorials_apim.html' | relative_url}}[Installing APIM]. To confirm it is running, go to `http://localhost:8084`.
* HiveMQ running in Docker, as described in link:{{'/apim/3.x/event_native_tutorials_hivemq.html'| relative_url}}[Installing HiveMQ]. To confirm it is running, go to `http://localhost:8086`.

== Creating the API

1. In the Tutorials Postman Collection, open the `MQTT and Webhooks` folder.

2. Open the `Create the API` request and look at the request body. Note that the `definitionVersion` is `4.0.0` and the `type` is `subscription`. This means we are using the Gravitee 4.0.0 OpenAPI specification to create a subscription - that is the gateway accepts a subscription instead of providing a target HTTP path for the request or initial connection. If you look under `entrypoints` you can see that we are creating one entrypoint, a `webhook` entrypoint. Under `endpointGroups` you can see that we are creating one `mqtt5` endpoint, which connects to the host `hivemq` on port `1883`.
+
[TIP]
====
APIM and HiveMQ are both running on the Docker bridge network called `storage`. The host `hivemq` is a host on that network.
====
+
For full details about the structure of the body, see link:{{'/apim/3.x/management-api/3.21/#tag/V4-APIs' | relative_url}}[V4 - APIs] reference documentation.

3. Send the request. You should receive a response that starts like this.
+
[code,json]
----
{
    "id": "48923b1a-3df6-442f-923b-1a3df6d42fbb",
    "name": "Demo of Webhook + MQTT - Subscription Filtering",
    "apiVersion": "1.0.0",
    "definitionVersion": "4.0.0",
    "type": "message",
    "createdAt": 1675090250286,
    "updatedAt": 1675090250286,
----
+
The `id` is the ID of the API we just created. Copy the ID, and paste it into the `CURRENT VALUE` field for the `api` variable in the APIM 3.21 Tutorials Environment. Click Save. 

== Creating a subscription plan

1. Select the `Create an Open (Subscription) Plan` request and look at the request body. It looks like this.
+
[code,json]
----
{
    "name": "Open",
    "description": "Keyless",
    "status": "PUBLISHED",
    "characteristics": [],
    "security": {
        "type": "subscription"
    }
}
----
+
For full details about the structure of the body, see link:{{'/apim/3.x/management-api/3.21/#tag/V4-API-Plans/operation/createApiPlan_1' | relative_url}}[Create a plan] reference documentation.

2. Send the request. You should receive a response that starts like this.
+
[code,json]
----
{
    "id": "bc0fc731-0420-4413-8fc7-310420f41379",
    "name": "Open",
    "description": "Keyless",
    "createdAt": 1675090462705,
    "updatedAt": 1675090462705,
    "publishedAt": 1675090462705,
----
+
The `id` is the ID of the plan we just created.

3. Copy the ID, and paste it into the `CURRENT VALUE` field for the `plan` variable in the APIM 3.21 Tutorials Environment. Click Save. 

== Starting the API

1. Select the `Start the API` request. You will see that it has no request body.

2. Send the request. You should receive a `204` response with no response body.

The API has been created and is ready to be used.

== Using the API

We are now going to create an application and use that application to subscribe to the API.

1. Select the `Create an Application` request. If you look at the body of this request you will see that it is a simple demo application.

2. Send the request. You should receive a response that begins like this.
+
[code,json]
----
{
    "id": "7e15e1b6-80b5-43f3-95e1-b680b5e3f317",
    "name": "application",
    "description": "application",
    "status": "ACTIVE",
    "type": "SIMPLE",
    "created_at": 1675093592934,
    "updated_at": 1675093592934,
----

3. Copy the ID, and paste it into the `CURRENT VALUE` field for the `application` variable in the APIM 3.21 Tutorials Environment. Click Save. 

4. Go to https://webhook.site/ and follow the instructions there to create a callback URL. Do not close the browser window.

5. Copy the callback URL, and paste it into the `CURRENT VALUE` field for the `callback-url` variable in the APIM 3.21 Tutorials.

6. Select the `Subscribe to API` request. If you look at the body of the request, you will see name-value pairs for custom headers, and a `metadata` object. These will become useful later. Send the request. You should see a response that begins like this.
+
[code,json]
----
{
    "id": "7bbbe5d6-0745-4228-bbe5-d60745c2281c",
    "plan": {
        "id": "bc0fc731-0420-4413-8fc7-310420f41379",
        "name": "Open"
    },
    "application": {
        "id": "7e15e1b6-80b5-43f3-95e1-b680b5e3f317",
----

7.  Copy the top-level ID, and paste it into the `CURRENT VALUE` field for the `subscription` variable in the APIM 3.21 Tutorials Environment. Click Save.

8. Go to HiveMQ's client for MQTT at http://www.hivemq.com/demos/websocket-client/. Enter 'localhost' in the Host field, and leave all other fields with their default values. Click "Connect."
+
[NOTE]
====
Although this is a tutorial for webhooks, the HiveMQ client that we are using uses Websockets. This is only used so that we can interact with the MQTT broker.
====

9. Click "Add New Topic Subscription" and enter `demo` in the dialog box. Click "Subscribe"
+ 
You are now subscribed to the `demo` topic.

10. Publish the following message to the `demo` topic.
+
[code,json]
----
{
    "message":"hello"
}
----
+
You will see the message appear in the `webhook.site` window. Note that the custom headers defined when the subscription was created are sent as headers with the message. You will also be able to see the message in the "Messages" pane of the Websockets client window.
+
You can publish as many messages as you want and observe them appearing in real time in the `webhook.site` window.

== Adding a message filter

We are now going to add message filtering.

When we created the subscription to the API, the request body contained the following lines.

[code,json]
----
    "metadata": {
        "feature": "demo-filter"
    }
----

Our filter is going to use this metadata to filter the messages.

1. Select the `Add Flow to API` request. If you look at the body of the request you will see the following line.
+
[code,json]
----
                        "filter": "{#jsonPath(#message.content, '$.feature') == #subscription.metadata.feature}"
----
+
This filter, based on link:{{ '/apim/3.x/apim_publisherguide_expression_language.html' | relative_url }}[APIM Expression Language], blocks all messages, except when the `feature` property of the message matches the value of the subscription's `metadata.feature` property.
+
[TIP]
====
Flows can be added at a number of different specificity levels, including the API, plan, or even organization level, but adding it to the API makes it easy for quick updates and redeployments.
====
+
Send the request. You should see a response that begins like this.
+
[code,json]
----
{
    "id": "48923b1a-3df6-442f-923b-1a3df6d42fbb",
    "name": "Demo of Webhook + MQTT - Subscription Filtering",
    "apiVersion": "1.0.0",
    "definitionVersion": "4.0.0",
    "type": "async",
    "deployedAt": 1675090533628,
    "createdAt": 1675090250286,
    "updatedAt": 1675157012827,
----

2. Once you have modified the API, you have to redeploy it. Select the `Redeploy API` and send it. The message body in the response should be similar to the message body you received in the previous step, but the value of `deployedAt` should have been updated.

3. Go back to the HiveMQ client at http://www.hivemq.com/demos/websocket-client/ and publish the following message to the `demo` topic.
+
[code,json]
----
{
    "message":"hello again"
}
----
+
You will see the message does not appear in the `webhook.site` window, because the filter prevented it from getting through. However, you will be able to see the message in the "Messages" pane of the Websockets client window, confirming that the message was published.

4. Now publish the following message to the `demo` topic.
+
[code,json]
----
{
    "feature": "demo-filter",
    "message-body": "I got through!"
}
----
+
You will see the message does appear in the `webhook.site` window, because the filter allowed it to get through.

== Close the plan and delete the API

After finishing this tutorial, run the `Stop the API`, `Close plan`, and `Delete API` requests in the `Delete API` folder in Postman. This removes the plan and API.

Alternatively, you can delete all Docker containers and volumes.