[[event-native-tutorials-kafka-websockets]]
= Kafka and Websockets
:page-sidebar: apim_3_x_sidebar
:page-permalink: /apim/3.x/event_native_tutorials_kafka_websockets.html
:page-folder: apim/v4
:page-layout: apim3x

== Prerequisites 

Before running this tutorial, you must have:

* Set up Postman, as described in link:{{'/apim/3.x/event_native_tutorials_postman.html' | relative_url}}[Setting up Postman].
* The Gravitee API Management Gateway running in Docker, as described in link:{{'/apim/3.x/event_native_tutorials_apim.html' | relative_url}}[Installing APIM]. To confirm it is running, go to `http://localhost:8084`.
* AKHQ running in Docker, as described in link:{{'/apim/3.x/event_native_tutorials_akhq.html'| relative_url}}[Installing AKHQ]. To confirm it is running, go to `http://localhost:8080`.
* Installed link:https://github.com/vi/websocat#websocat[websocat].

== Creating the API

1. In the Tutorials Postman Collection, open the `Kafka and Websockets` folder.

2.  Open the `Create the API` request and look at the request body. Note that the `definitionVersion` is `4.0.0` and the `type` is `async`. This means we are using the Gravitee 4.0.0 OpenAPI specification to create an asynchronous API. If you look under `listeners` you can see that we are creating two entrypoints, a `websocket` entrypoint, and an `http-post` entrypoint. In this tutorial the `http-post` entrypoint is only used for publishing data to Kafka. For a full tutorial on Kafka and HTTP, see link:{{ '/apim/3.x/event_native_tutorials_kafka_websockets.html' | relative_url }}[Kafka and HTTP].
+
Under `endpointGroups` you can see that we are creating one `kafka` endpoint, which uses a bootstrap server called `kafka` on port `9092`. The `topics` array contains just one topic, `demo`.
+
[TIP]
====
APIM and AKHQ are both running on the Docker bridge network called `storage`. The host `kafka` is a host on that network.
====
+
For full details about the structure of the body, see link:{{'/apim/3.x/management-api/3.20/#tag/V4-APIs' | relative_url}}[V4 - APIs] reference documentation.

3. Send the request. You should receive a response that starts like this.
+
[code,json]
----
{
    "id": "f72cb424-ba8b-4c72-acb4-24ba8bdc723a",
    "name": "Demo of Kafka and Websockets",
    "apiVersion": "1.0.0",
    "definitionVersion": "4.0.0",
    "type": "async",
    "createdAt": 1675674428097,
    "updatedAt": 1675674428097,
----
+
The `id` is the ID of the API we just created. Copy the ID, and paste it into the `CURRENT VALUE` field for the `api` variable in the APIM 3.20 Tutorials Environment. Click Save. 

== Creating a keyless plan

1. Select the `Create an Open (keyless) Plan` request and look at the request body. It looks like this.
+
[code,json]
----
{
    "name": "Open",
    "description": "Keyless",
    "status": "PUBLISHED",
    "characteristics": [],
    "security": {
        "type": "subscription"
    }
}
----
+
For full details about the structure of the body, see link:{{'/apim/3.x/management-api/3.20/#tag/V4-API-Plans/operation/createApiPlan_1' | relative_url}}[Create a plan] reference documentation.

2. Send the request. You should receive a response that starts like this.
+
[code,json]
----
{
    "id": "17bcd33d-c8e7-4a5b-bcd3-3dc8e7ca5b2b",
    "name": "Open",
    "description": "Keyless",
    "createdAt": 1675674494100,
    "updatedAt": 1675674494100,
    "publishedAt": 1675674494102,
----
+
The `id` is the ID of the plan we just created.

3. Copy the ID, and paste it into the `CURRENT VALUE` field for the `plan` variable in the APIM 3.20 Tutorials Environment. Click Save. 

== Starting the API

1. Select the `Start the API` request. You will see that it has no request body.

2. Send the request. You should receive a `204` response with no response body.

The API has been created and is ready to be used.

== Using the API

1. In Postman, select the `Push Data` request and look at the request body. It looks like this.
+
[code,json]
----
{
    "tempF": "75"
}
----

2. Send the request. You should receive a status response of `200 OK`.

3. Go to http://localhost:8080/ui/docker-kafka-server/tail and select `demo` from the topics drop-down menu. Click the search icon. This page will now display a live feed of all messages published on the `demo` topic.

4. Send the request several more times, and observe it appear on http://localhost:8080/ui/docker-kafka-server/tail. 

5. Use `websocat` to connect to the API using the following terminal command.
+
[code,bash]
----
 websocat ws://localhost:8082/demo/ws
----

6. In Postman, send the `Push Data` request again. You should see a message appear in the terminal where `websocat` is running. 
+
[code,bash]
----
websocat ws://localhost:8082/demo/ws
{     "tempF": "75" }
----

7. publish a message on the `demo` topic using `websocat` by typing the message in the terminal window.
+
[code,bash]
----
websocat ws://localhost:8082/demo/ws
{     "tempF": "75" }
{ "message": "from websocat"}
----
+
The message will be echoed back to the terminal. This is because the API was created to publish and subscribe to all messages on the `demo` topic.
+
[code,bash]
----
websocat ws://localhost:8082/demo/ws
{     "tempF": "75" }
{ "message": "from websocat"}
{ "message": "from websocat"}
----
+
The message will also appear on http://localhost:8080/ui/docker-kafka-server/tail.

== Adding a message filter

We are now going to add message filtering.

1. Select the `Add Flow to API` request. If you look at the body of the request you will see the following line.
+
[code,json]
----
                         "filter": "{#jsonPath(#message.content, '$.feature') == 'demo-filter'}"
----
+
This filter, based on link:{{ '/apim/3.x/apim_publisherguide_expression_language.html' | relative_url }}[APIM Expression Language], blocks all messages, except when the `feature` property of the message matches is `demo-filter`.
+
[TIP]
====
Flows can be added at a number of different specificity levels, including the API, plan, or even organization level, but adding it to the API makes it easy for quick updates and redeployments.
====
+
Send the request. You should see a response that begins like this.
+
[code,json]
----
{
    "id": "f72cb424-ba8b-4c72-acb4-24ba8bdc723a",
    "name": "Demo of Kafka and Websockets",
    "apiVersion": "1.0.0",
    "definitionVersion": "4.0.0",
    "type": "async",
    "deployedAt": 1675674539916,
----

2. Once you have modified the API, you have to redeploy it. Select the `Redeploy API` request and send it. The message body in the response should be similar to the message body you received in the previous step, but the value of `deployedAt` should have been updated.

3. Exit the existing `websocat` session using `CTRL C` and restart it.
+
[code,bash]
----
websocat ws://localhost:8082/demo/ws
----

4. Using the `Push Data` request, publish the following message. 
+
[code,json]
----
{
    "message":"hello again"
}
----
+
You will see the message does not appear in the `websocat` terminal, because the filter prevented it from getting through. However, you will be able to see the message in the "Messages" pane of the Websockets client window, confirming that the message was published.

5. Now publish the following message.
+
[code,json]
----
{
    "feature": "demo-filter",
    "message-body": "I got through!"
}
----
+
You will see the message does appear in the `websocat` terminal, because the filter allowed it to get through.

6. In the `websocat` terminal, publish the following message: `new message`. You will see that it is not echoed back to the terminal, but it does appear on http://localhost:8080/ui/docker-kafka-server/tail.

== Close the plan and delete the API

After finishing this tutorial, run the `Stop the API`, `Close plan`, and `Delete API` requests in the `Delete API` folder in Postman. This removes the plan and API.

Alternatively, you can delete all Docker containers and volumes.