[[event-native-tutorials-kafka-webhooks]]
= Kafka and Webhooks
:page-sidebar: apim_3_x_sidebar
:page-permalink: /apim/3.x/event_native_tutorials_kafka_webhooks.html
:page-folder: apim/v4
:page-layout: apim3x

== Prerequisites 

Before running this tutorial, you must have:

* Set up Postman, as described in link:{{'/apim/3.x/event_native_tutorials_postman.html' | relative_url}}[Setting up Postman].
* The Gravitee API Management Gateway running in Docker, as described in link:{{'/apim/3.x/event_native_tutorials_apim.html' | relative_url}}[Installing APIM]. To confirm it is running, go to `http://localhost:8084`.
* AKHQ running in Docker, as described in link:{{'/apim/3.x/event_native_tutorials_akhq.html'| relative_url}}[Installing AKHQ]. To confirm it is running, go to `http://localhost:8080`.

== Creating the API

1. In the Tutorials Postman Collection, open the `Kafka and Webhooks` folder.

2. Open the `Create the API` request and look at the request body. Note that the `definitionVersion` is `4.0.0` and the `type` is `subscription`. This means we are using the Gravitee 4.0.0 OpenAPI specification to create a subscription - that is the gateway accepts a subscription instead of providing a target HTTP path for the request or initial connection. If you look under `listeners` you can see that we are creating two entrypoints, a `webhook` entrypoint, and an `http-post` entrypoint. In this tutorial the `http-post` entrypoint is only used for publishing data to Kafka. For a full tutorial on Kafka and HTTP, see link:/apim/3.x/event_native_tutorials_kafka_websockets.html[Kafka and HTTP].
+
Under `endpointgroups` you can see that we are creating one `kafka` endpoint, which uses a bootstrap server called `kafka` on port `9092`. The `topics` array contains just one topic, `demo`.
+
[TIP]
====
APIM and AKHQ are both running on the Docker bridge network called `storage`. The host `kafka` is a host on that network.
====
+
For full details about the structure of the body, see link:{{'/apim/3.x/management-api/3.20/#tag/V4-APIs' | relative_url}}[V4 - APIs] reference documentation.

3. Send the request. You should receive a response that starts like this.
+
[code,json]
----
{
    "id": "9a56f324-edd7-4a88-96f3-24edd77a884e",
    "name": "Kafka and Webhooks",
    "apiVersion": "1.0.0",
    "definitionVersion": "4.0.0",
    "type": "async",
    "createdAt": 1675347679105,
    "updatedAt": 1675347679105,
----
+
The `id` is the ID of the API we just created. Copy the ID, and paste it into the `CURRENT VALUE` field for the `api` variable in the APIM 3.20 Tutorials Environment. Click Save. 

== Creating plans

We need to create two plans: a keyless plan to allow us to publish to Kafka over HTTP, and a subscription plan for the webhook subscription.

1. Select the "Create an Open (Keyless) Plan" request and look at the request body. It looks like this.
+
[code,json]
----
{
    "name": "Open",
    "description": "Keyless",
    "status": "PUBLISHED",
    "characteristics": [],
    "security": {
        "type": "key-less"
    }
}
----
+
For full details about the structure of the body, see link:{{'/apim/3.x/management-api/3.20/#tag/V4-API-Plans/operation/createApiPlan_1' | relative_url}}[Create a plan] reference documentation.

2. Send the request. You should receive a response that starts like this.
+
[code,json]
----
{
    "id": "00d71104-8973-46a8-9711-04897316a88c",
    "name": "Keyless",
    "description": "Keyless",
    "createdAt": 1675347712230,
    "updatedAt": 1675347712230,
    "publishedAt": 1675347712231,
----
+
The `id` is the ID of the plan we just created.

3. Copy the ID, and paste it into the `CURRENT VALUE` field for the `plan` variable in the APIM 3.20 Tutorials Environment. Click Save. 

4. Select the "Create an Open (Subscription) Plan" request and look at the request body. It looks like this.
+
[code,json]
----
{
    "name": "Open",
    "description": "Keyless",
    "status": "PUBLISHED",
    "characteristics": [],
    "security": {
        "type": "subscription"
    }
}
----

5. Send the request. You should receive a response that starts like this.
+
[code,json]
----
{
    "id": "e9ec6ed8-df41-42eb-ac6e-d8df4182eb1e",
    "name": "Open",
    "description": "Keyless",
    "createdAt": 1675347779695,
    "updatedAt": 1675347779695,
    "publishedAt": 1675347779695,
----
+
The `id` is the ID of the plan we just created.

6. Copy the ID, and paste it into the `CURRENT VALUE` field for the `subplan` variable in the APIM 3.20 Tutorials Environment. Click Save. 

== Starting the API

1. Select the "Start the API" request. You will see that it has no request body.

2. Send the request. You should receive a `204` response with no response body.

The API has been created and is ready to be used.

== Using the API

We are now going to create an application and use that application to subscribe to the API.

1. Select the "Create an Application" request. If you look at the body of this request you will see that it is a simple demo application.

2. Send the request. You should receive a response that begins like this.
+
[code,json]
----
{
    "id": "886966ce-1dab-48b1-a966-ce1dab68b17d",
    "name": "application",
    "description": "application",
    "status": "ACTIVE",
    "type": "SIMPLE",
    "created_at": 1675347893455,
    "updated_at": 1675347893455,
----

3. Copy the ID, and paste it into the `CURRENT VALUE` field for the `application` variable in the APIM 3.20 Tutorials Environment. Click Save. 

4. Go to https://webhook.site/ and follow the instructions there to create a callback URL. Do not close the browser window.

5. Copy the callback URL, and paste it into the `CURRENT VALUE` field for the `callback-url` variable in the APIM 3.20 Tutorials.

6. Select the "Subscribe to API" request. If you look at the body of the request, you will see name-value pairs for custom headers, and a `metadata` object. These will become useful later. Send the request. You should see a response that begins like this.
+
[code,json]
----
{
    "id": "07125f0e-d4db-4efc-925f-0ed4dbcefc55",
    "plan": {
        "id": "e9ec6ed8-df41-42eb-ac6e-d8df4182eb1e",
        "name": "Open"
    },
    "application": {
        "id": "886966ce-1dab-48b1-a966-ce1dab68b17d",
----

7.  Copy the top-level ID, and paste it into the `CURRENT VALUE` field for the `subscription` variable in the APIM 3.20 Tutorials Environment. Click Save.

8. In Postman, select "Push Data" and look at the request body. It looks like this.
+
[code,json]
----
{
    "tempF": "75"
}
----

9. Send the request. You should receive a status response of `200 OK`.

10. Go to http://localhost:8080/ui/docker-kafka-server/tail and select `demo` from the topics drop-down menu. Click the search icon. This page will now display a live feed of all messages published on the `demo` topic.

11. Send the request several more times, and observe it appear on http://localhost:8080/ui/docker-kafka-server/tail. 
+
You will also see the message appear in the `webhook.site` window. Note that the custom headers defined when the subscription was created are sent as headers with the message.
+
You can publish as many messages as you want and observe them appearing in real time in the `webhook.site` window.

== Adding a message filter

We are now going to add message filtering.

When we created the subscription to the API, the request body contained the following lines.

[code,json]
----
    "metadata": {
        "feature": "demo-filter"
    }
----

Our filter is going to use this metadata to filter the messages.

1. Select the "Add Flow to API request". If you look at the body of the request you will see the following line.
+
[code,json]
----
                        "filter": "{#jsonPath(#message.content, '$.feature') == #subscription.metadata.feature}"
----
+
This filter, based on link:/apim/3.x/apim_publisherguide_expression_language.html[APIM Expression Language], blocks all messages, except when the `feature` property of the message matches the value of the subscription's `metadata.feature` property.
+
[TIP]
====
Flows can be added at a number of different specificity levels, including the API, plan, or even organization level, but adding it to the API makes it easy for quick updates and redeployments.
====
+
Send the request. You should see a response that begins like this.
+
[code,json]
----
{
    "id": "9a56f324-edd7-4a88-96f3-24edd77a884e",
    "name": "Demo of Webhook + MQTT - Subscription Filtering",
    "apiVersion": "1.0.0",
    "definitionVersion": "4.0.0",
    "type": "async",
    "deployedAt": 1675347885490,
    "createdAt": 1675347679105,
    "updatedAt": 1675348100203,
----

2. Once you have modified the API, you have to redeploy it. Select "Redeploy API" and send the request. The message body in the response should be similar to the message body you received in the previous step, but the value of `deployedAt` should have been updated.

3. Select "Push data" and add replace the message body with the following.
+
[code,json]
----
{
    "message":"hello again"
}
----
+
Send the request.
+
You will see the message does not appear in the `webhook.site` window, because the filter prevented it from getting through. However, you will be able to see the message in the live tail on AKHQ, confirming that the message was published.

4. Select "Push data" and add replace the message body with the following.
+
[code,json]
----
{
    "feature": "demo-filter",
    "message-body": "I got through!"
}
----
+
You will see the message does appear in the `webhook.site` window, because the filter allowed it to get through.

== Close the plan and delete the API

After finishing this tutorial, run "Stop the API", "Close plan", and "Delete API" in the "Delete API" folder in Postman. This removes the plan and API. You will also have to copy the `CURRENT VALUE` of `subplan` into the `CURRENT VALUE` field for the `plan` variable in the APIM 3.20 Tutorials Environment, click Save, and then re-run "Close plan" to remove the subscription plan.

Alternatively, you can delete all Docker containers and volumes.