[[v4-event-native-apim-asynchronous-apis]]
= Asynchronous APIS
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/event_native_apim_asynchronous_apis.html
:page-folder: apim/v4
:page-layout: apim3x

In this release of Gravitee API Management, you can create asynchronous APIs and connect to event brokers and asynchronous data sources. You can configure asynchronous API connections using the RESTful interface to the management API.

The OpenAPI specification for the management API is available at link:{{ '/apim/3.x/management-api/3.20/swagger.json' | relative_url }}[`swagger.json`] (link:{{ '/apim/3.x/apim_installguide_rest_apis_documentation.html#apim_console_api_reference' | relative_url }}[reference documentation]). Examples of how to use the management API to configure asynchronous APIs can be found in the link:https://www.postman.com/gravitee-io/workspace/gravitee-public-workspace/overview[Gravitee Postman Collections], which are described in link:event_native_apim_example_use_cases.html[example use cases].

[NOTE]
====
The management API may change.
====

