---
redirect_from:
  - /ee/ee_introduction.html
---
= Installation Guide
:page-description: Gravitee Enterprise Edition - Installation - License
:page-keywords: Gravitee, API Platform, Enterprise Edition, documentation, manual, guide, reference, api

Gravitee.io Enterprise API Platform is provided in separate bundles compared to the community version.

To install the Enterprise version, two options are available:

* Starting with a new installation of the Enterprise platform
* Moving from an existing OSS platform

To ensure that you are running the API platform in optimal conditions, we advise you to start with a new installation.
This will ensure that mandatory libraries and plugins are all well deployed.

== Running a new API Platform

=== Docker installation
To use the official Gravitee.io Docker images, we recommend you to use the images with a tag ending in `-ee`.
Please have a look to the link:/ee/installguide_docker.html[dedicated documentation].

== Migration from an existing platform

Before going further please ensure, as per our link:/ee/ee_version.html[versioning], that you're running a LTS version.

=== Manual installation
This option is only available if you're running a plain installation using the zip file distribution.

=== Docker installation
If you're running Docker, we recommend you to update your docker images to use the `-ee` tags.
See the link:/ee/installguide_docker.html[Docker installation documentation].
