= Upgrade to 3.14.0

== Breaking changes

=== Gateway
From with this version, the name of the APIM Gateway component changes.
As a consequence:

1. The APIM Gateway component available on https://download.gravitee.io is now `gravitee-*apim-gateway*-x.y.z.zip` instead of `gravitee-gateway-x.y.z.zip`

2. The name of the APIM Gateway folder within the full distribution zip file (graviteeio-full-x.y.z.zip) is now `graviteeio-*apim-gateway*-x.y.z` instead of `graviteeio-gateway-x.y.z`

== Gateway bridge upgrade

On hybrid architectures where gateway bridge feature is enabled, gateways have to be upgraded in this order :

. The bridge server gateway
. The bridge client gateway

More information on the gateway bridge feature can be found link:https://docs.gravitee.io/apim/3.x/apim_installguide_hybrid_deployment.html#apim_gateway_http_bridge_server[here].

== Elastic Search reporter plugins configuration

Before Gravitee 3.14 :

- For ES>=7, GeoIp and UserAgent plugins are enabled by default in Gravitee, and can't be disabled
- For ES<7, those plugins are disabled by default and can be enabled in Gravitee configuration.

Since Gravitee 3.14, it behave the same way for all ES versions :
GeoIp and UserAgent plugins are be enabled by default, and can be disabled by overriding default `reporters.elasticsearch.pipeline.plugins.ingest` configuration.

If your Gravitee configuration enables a plugin which is not available on your ES instance, you will get this kind of error message on gateway startup :

`Unable to create ES pipeline 'gravitee_pipeline': status[400] response[{"error":{"root_cause":[{"reason":"No processor type exists with name [geoip]","processor_type":"geoip"}]`

And then, you have to override `reporters.elasticsearch.pipeline.plugins.ingest` default configuration, to remove unrelevant plugin.

