= Management UI - Portal
:page-sidebar: apim_sidebar
:page-permalink: apim_installguide_portal.html
:page-folder: apim/installation-guide

== System Requirements

=== Browsers

Management UI Portal has been tested with the latest versions of Google Chrome, Firefox and Internet Explorer >= 10

== Installing from the ZIP archive

The binaries are available from http://gravitee.io/#downloads or via https://dl.bintray.com/gravitee-io/release/GRAVITEEIO-VERSION/graviteeio-full-GRAVITEEIO-VERSION.zip[bintray].

[source,bash]
[subs="attributes"]
$ curl -L https://dl.bintray.com/gravitee-io/release/GRAVITEEIO-VERSION/graviteeio-full-GRAVITEEIO-VERSION -o gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip

Once file has been downloaded, you just have to unpack it in the right place

[source,bash]
[subs="attributes"]
$ unzip gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip

=== Deploy

The Management UI is a client-side only Angular application and can be deployed on any HTTP server like https://httpd.apache.org/[Apache] or http://nginx.org/[Nginx].

=== or Run it

With Python::

[source,bash]
[subs="attributes"]
$ cd graviteeio-management-ui-GRAVITEEIO-VERSION
$ python3 -m http.server
$ Serving HTTP on 0.0.0.0 port 8000 ...

With Node::

[source,bash]
[subs="attributes"]
$ npm install http-server -g
$ cd graviteeio-management-ui-GRAVITEEIO-VERSION
$ http-server

=== Configuration

The Management UI provides a UI to the Gravitee.io Management API to manage the platform globally. The only one thing to configure is the Gravitee.io Management API URL :

[source,bash]
[subs="attributes"]
$ cd graviteeio-management-ui-GRAVITEEIO-VERSION
$ vi constants.js

[source,javascript]
[subs="attributes"]
'use strict';
angular.module('gvConstants', []).constant('Constants', {
  // if the management REST API is on a different domain, put something like: http://[api-rest-domain]/management/
  "baseURL": '/management/',
  "version": "0.8.2"
});
