---
sidebar: apim_sidebar
permalink: apim_installguide_gateway.html
folder: apim/installation-guide/gateway
description: Gravitee.io API Management - Gateway - Installation
keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
---

[[gravitee-installation-gateway]]
= API Gateway

== System Requirements

=== JDK

Gravitee.io Gateway requires at least Java 8. Before you install Gravitee.io Gateway, please check your Java version :

[source,bash]
----
java -version
echo $JAVA_HOME
----

NOTE: You can download the latest JDK from the http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java SE Download Site].

=== Repository

Default Gravitee.io Gateway distribution requires MongoDB 3.x to store management's configuration data and Elasticsearch 2.x for
reporting / analytics.

NOTE: You can download MongoDB 3.x from https://www.mongodb.org/downloads#production[MongoDB Download Site]
and Elasticsearch 2.x or 5.x from https://www.elastic.co/downloads/elasticsearch[Elastic Download Site]

== Download and install the +.zip+ package

Binaries are available from http://gravitee.io/#downloads[Downloads page] or via https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-GRAVITEEIO-VERSION.zip[Download].

[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-GRAVITEEIO-VERSION.zip -o gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip

Once file has been downloaded, you just have to unpack it in the right place.

[source,bash]
[subs="attributes"]
$ unzip gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip

And you can simply start up the gateway as follow:

[source,bash]
[subs="attributes"]
$ cd graviteeio-gateway-GRAVITEEIO-VERSION
$ ./bin/gravitee

If everything goes well, you should see this kind of logs:

[source,bash]
[subs="attributes"]
...
11:01:53.162 [gravitee] [] INFO  i.g.g.standalone.node.GatewayNode - Gravitee.io - Gateway id[2e05c0fa-8e48-4ddc-85c0-fa8e48bddc11] version[1.6.0] pid[24930] build[175] jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.121-b13] started in 15837 ms.
...

By default, the gateway is listening on port *8082* and can be accessed from: _http://localhost:8082_


HTTP port can be <<apim_installguide_gateway_configuration.adoc#api-gateway-http-server, configured>> if necessary.

== Directory structure

After successfully installed Gravitee.io Gateway, the `graviteeio-gateway` directory looks like this:

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Folder    |Description
|bin       |Startup/shutdown scripts
|config    |<<apim_installguide_configuration.adoc#gravitee-gateway-configuration, Configuration>> folder (application, logs and cache configuration)
|lib       |Libraries (gravitee.io libraries and third parties library)
|logs      |Gateway log files
|plugins   |Gateway <<apim_overview_plugins.adoc#, plugins>>
|======================

