= Configuration
:page-sidebar: apim_sidebar
:page-permalink: apim_installguide_configuration.html
:page-folder: apim/installation-guide

Gravitee.io allows you to externalize your configuration via the `gravitee.yml` file that can be found under `GRAVITEE_HOME/config` folder.

* How to configure <<gravitee-gateway-configuration, Gateway>>
* How to configure <<gravitee-management-api-configuration, Management API>>
* How to configure <<gravitee-repositories-configuration, Repositories>>

[[gravitee-gateway-configuration]]
== Gateway

=== HTTP Server

Embedded Gravitee.io Gateway HTTP server configuration.

[source,yaml]
----
http:
  port: 8082
  idleTimeout: 0
  tcpKeepAlive: true
  compressionSupported: false
  pool:
    workers: 100
  secured: false
  ssl:
    clientAuth: false
    keystore:
      path:
      password:
    truststore:
      path:
      password:
----

=== Plugins repository

Gravitee.io Gateway <<gravitee-plugins,plugins>> directory configuration.

[source,yaml]
----
plugins:
  path: ${gravitee.home}/plugins
----

=== Management repository

Management repository is used to store global configuration such as APIs, applications, apikeys, ...
This is the default configuration using MongoDB (single server). For more information about MongoDB configuration, please have a look to:

http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html

[source,yaml]
----
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    username:
#    password:
#    connectionsPerHost: 0
#    connectTimeout: 500
#    maxWaitTime: 120000
#    socketTimeout: 500
#    socketKeepAlive: false
#    maxConnectionLifeTime: 0
#    maxConnectionIdleTime: 0
#    serverSelectionTimeout: 0
#    description: gravitee.io
#    heartbeatFrequency: 10000
#    minHeartbeatFrequency: 500
#    heartbeatConnectTimeout: 1000
#    heartbeatSocketTimeout: 20000
#    localThreshold: 15
#    minConnectionsPerHost: 0
#    sslEnabled: false
#    threadsAllowedToBlockForConnectionMultiplier: 5
#    cursorFinalizerEnabled: true

# Management repository: single MongoDB using URI
# For more information about MongoDB configuration using URI, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
#management:
#  type: mongodb
#  mongodb:
#    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

# Management repository: clustered MongoDB
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
#    dbname: ${ds.mongodb.dbname}
#    connectTimeout: 500
#    socketTimeout: 250
----

=== Rate Limit repository

When defining <<policy-ratelimit, rate-limiting policy>>, the gateway has to store data to share with other gateway instances.

In this example, we are using MongoDB to store counters.

[source,yaml]
----
ratelimit:
  type: mongodb
  mongodb:
    uri: mongodb://${ds.mongodb.host}/${ds.mongodb.dbname}
----

=== Reporters

Reporters configuration (used to store reporting monitoring data, request metrics, healthchecks and others...)
All reporters are enabled by default. To stop one of them, you have to add the property 'enabled: false'

[source,yaml]
----
reporters:
  # Elasticsearch reporter
  elastic:
    host: ${ds.elastic.host}
    port: ${ds.elastic.port}
    # Reporters are async by nature so the gateway is keeping an internal in-memory structure to stack data before
    # pushing them into a final storage (Elasticsearch in this example)
    queue:
      # Number of elements to store in the queue (extra-elements will be loosed)
      size: 10240
      # Reporter thread is looking for data every x milliseconds (each second in this example)
      pollingTimeout: 1000
----

=== Services

Gravitee.io Gateway services configuration. Provided values are default values. All services are enabled by default. To stop one of them, you have to add the property 'enabled: false' (See the 'local' service for an example).

[source,yaml]
----
services:
  # Synchronization daemon used to keep the gateway state in sync with the configuration from the management repository
  # Be aware that, by disabling it, the gateway will not be sync with the configuration done through management API and management UI
  sync:
    # Synchronization is done each 5 seconds
    cron: '*/5 * * * * *'

  # Service used to store and cache api-keys from the management repository to avoid direct repository communication
  # while serving requests.
  apikeyscache:
    delay: 10000
    unit: MILLISECONDS
    threads: 3 # Threads core size used to retrieve api-keys from repository.

  # Local registry service.
  # This registry is used to load API Definition with json format from the file system. By doing so, you do not need
  # to configure your API using the web console or the rest API (but you need to know and understand the json descriptor
  # format to make it work....)
  local:
    enabled: false
    path: ${gravitee.home}/apis # The path to API descriptors

  # Gateway monitoring service.
  # This service retrieves metrics like os / process / jvm metrics and send them to an underlying reporting service.
  monitoring:
    delay: 5000
    unit: MILLISECONDS

  # Endpoint healthcheck service.
  healthcheck:
    threads: 3 # Threads core size used to check endpoint availability
----

=== Sharding tags

You can apply sharding on Gateway's instances either with system properties or with a configuration as below.
System properties overrides the yaml configuration.

In this example, you are asking deployment only for APIs tagged 'product' or 'store' and among it, you exclude the APIs tagged 'international'.

[source,yaml]
----
tags: 'product,store,!international'
----

=== General Gateway properties

Various properties can be specified inside your `GRAVITEE_HOME/config/gravitee.yml` file. This section provides the general configuration of Gravitee.IO Gateway.

[source,yaml]
----
############################################################################################################
#################################### Gravitee.IO Gateway - Configuration ###################################
############################################################################################################

############################################################################################################
# This file is the general configuration of Gravitee.IO Gateway:
# - Properties (and respective default values) in comment are provided for information.
# - You can reference other property by using ${property.name} syntax
# - gravitee.home property is automatically set-up by launcher and refers to the installation path. Do not override it !
#
# Please have a look to http://docs.gravitee.io/ for more options and fine-grained granularity
############################################################################################################

# Gateway HTTP server
#http:
#  port: 8082
#  idleTimeout: 0
#  tcpKeepAlive: true
#  compressionSupported: false
#  instances: 0
#  secured: false
#  ssl:
#    clientAuth: false
#    keystore:
#      path:
#      password:
#    truststore:
#      path:
#      password:

# Plugins repository
#plugins:
#  path: ${gravitee.home}/plugins
# If a plugin is already installed (but with a different version), management node does not start anymore
#  failOnDuplicate: true

# Management repository is used to store global configuration such as APIs, applications, apikeys, ...
# This is the default configuration using MongoDB (single server)
# For more information about MongoDB configuration, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    username:
#    password:
#    connectionsPerHost: 0
#    connectTimeout: 500
#    maxWaitTime: 120000
#    socketTimeout: 500
#    socketKeepAlive: false
#    maxConnectionLifeTime: 0
#    maxConnectionIdleTime: 0
#    serverSelectionTimeout: 0
#    description: gravitee.io
#    heartbeatFrequency: 10000
#    minHeartbeatFrequency: 500
#    heartbeatConnectTimeout: 1000
#    heartbeatSocketTimeout: 20000
#    localThreshold: 15
#    minConnectionsPerHost: 0
#    sslEnabled: false
#    threadsAllowedToBlockForConnectionMultiplier: 5
#    cursorFinalizerEnabled: true

# Management repository: single MongoDB using URI
# For more information about MongoDB configuration using URI, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
#management:
#  type: mongodb
#  mongodb:
#    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

# Management repository: clustered MongoDB
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
#    dbname: ${ds.mongodb.dbname}
#    connectTimeout: 500
#    socketTimeout: 250

# When defining rate-limiting policy, the gateway has to store data to share with other gateway instances.
# In this example, we are using MongoDB to store counters.
ratelimit:
  type: mongodb
  mongodb:
    uri: mongodb://${ds.mongodb.host}/${ds.mongodb.dbname}

cache:
  type: ehcache

# Reporters configuration (used to store reporting monitoring data, request metrics, healthchecks and others...
# All reporters are enabled by default. To stop one of them, you have to add the property 'enabled: false'
reporters:
  # Reporting system configuration
  system:
    buffersize: 4096 # Must be a power of 2

  # Elasticsearch reporter
  elasticsearch:
    enabled: true # Is the reporter enabled or not (default to true)
    hosts:
      - ${ds.elastic.host}:${ds.elastic.port}
#    index: gravitee
#    cluster: elasticsearch
#    bulk:
#      actions: 1000           # Number of requests action before flush
#      flush_interval: 5       # Flush interval in seconds
#      concurrent_requests: 5  # Concurrent requests

# Gateway service configurations. Provided values are default values.
# All services are enabled by default. To stop one of them, you have to add the property 'enabled: false' (See the
# 'local' service for an example).
services:
  # Synchronization daemon used to keep the gateway state in sync with the configuration from the management repository
  # Be aware that, by disabling it, the gateway will not be sync with the configuration done through management API
  # and management UI
  sync:
    # Synchronization is done each 5 seconds
    cron: '*/5 * * * * *'

  # Service used to store and cache api-keys from the management repository to avoid direct repository communication
  # while serving requests.
  apikeyscache:
    delay: 10000
    unit: MILLISECONDS
    threads: 3 # Threads core size used to retrieve api-keys from repository.

  # Local registry service.
  # This registry is used to load API Definition with json format from the file system. By doing so, you do not need
  # to configure your API using the web console or the rest API (but you need to know and understand the json descriptor
  # format to make it work....)
  local:
    enabled: false
    path: ${gravitee.home}/apis # The path to API descriptors

  # Gateway monitoring service.
  # This service retrieves metrics like os / process / jvm metrics and send them to an underlying reporting service.
  monitoring:
    delay: 5000
    unit: MILLISECONDS

  # Endpoint healthcheck service.
  healthcheck:
    threads: 3 # Threads core size used to check endpoint availability

handlers:
  request:
    transaction:
      header: X-Gravitee-Transaction-Id

# Referenced properties
ds:
  mongodb:
    dbname: gravitee
    host: ${GRAVITEEIO_MONGODB_HOST:localhost}
    port: ${GRAVITEEIO_MONGODB_PORT:27017}
  elastic:
    host: ${GRAVITEEIO_ELASTIC_HOST:localhost}
    port: ${GRAVITEEIO_ELASTIC_PORT:9300}

# Sharding tags configuration
# Allows to define inclusion/exclusion sharding tags to only deploy a part of APIs. To exclude just prefix the tag with '!'.
#tags: products,stocks,!international
----

[[gravitee-management-api-configuration]]
== Management API Settings

=== HTTP Server

Management API HTTP server configuration.

[source,yaml]
----
jetty:
  port: 8083
  idleTimeout: 30000
  acceptors: -1
  selectors: -1
  pool:
    minThreads: 10
    maxThreads: 200
    idleTimeout: 60000
    queueSize: 6000
  jmx: false
  statistics: false
  accesslog:
    enabled: true
    path: ${gravitee.home}/logs/gravitee_accesslog_yyyy_mm_dd.log
----

=== Plugins repository

Gravitee.io Management API <<gravitee-plugins,plugins>> directory configuration.

[source,yaml]
----
plugins:
  path: ${gravitee.home}/plugins
----

=== Management repository

Management repository is used to store global configuration such as APIs, applications, apikeys, ...
This is the default configuration using MongoDB (single server). For more information about MongoDB configuration, please have a look to:

http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html

[source,yaml]
----
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    username:
#    password:
#    connectionsPerHost: 0
#    connectTimeout: 500
#    maxWaitTime: 120000
#    socketTimeout: 500
#    socketKeepAlive: false
#    maxConnectionLifeTime: 0
#    maxConnectionIdleTime: 0
#    serverSelectionTimeout: 0
#    description: gravitee.io
#    heartbeatFrequency: 10000
#    minHeartbeatFrequency: 500
#    heartbeatConnectTimeout: 1000
#    heartbeatSocketTimeout: 20000
#    localThreshold: 15
#    minConnectionsPerHost: 0
#    sslEnabled: false
#    threadsAllowedToBlockForConnectionMultiplier: 5
#    cursorFinalizerEnabled: true

# Management repository: single MongoDB using URI
# For more information about MongoDB configuration using URI, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
#management:
#  type: mongodb
#  mongodb:
#    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

# Management repository: clustered MongoDB
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
#    dbname: ${ds.mongodb.dbname}
#    connectTimeout: 500
#    socketTimeout: 250
----

=== Analytics

Analytics repository is used to store all reporting, metrics, healthchecks stored by gateway instances.

This is the default configuration using https://www.elastic.co/products/elasticsearch[Elasticsearch].

[source,yaml]
----
analytics:
  type: elasticsearch
  elasticsearch:
    host: ${ds.elastic.host}
    port: ${ds.elastic.port}
----

[[gravitee-standalone-management-security-configuration]]
=== Security configuration

Security configuration providing Authentication, Identity and access-control mechanism for the Gravitee.io Management API.

==== Authentication Type

Gravitee.IO Management API supports both Basic Authentication and OAuth2 Authentication. The authentication-type can be defined using the following property :

[source,yaml]
----
security:
  type: basic # authentication type (default to 'basic', possible values : 'basic', 'oauth2')
----

===== Basic Authentication configuration

Authentication Provider::

The Gravitee.io management API supports by default some standard ways to retrieve user information for authentication from InMemory to LDAP or Gravitee.io <<gravitee-repositories, repository>>. Let's see how to configure it.

InMemory Provider::

Basic in-memory implementation, a simple and convenient way to declare "technical" users such as the administrator users. An example configuration is shown below:

[source,yaml]
----
# ===================================================================
# IN MEMORY SECURITY PROPERTIES
#
# This sample file declared one in memory authentication source with two users
# ===================================================================
security:
  type: basic                       # authentication type
  providers:                        # required authentication providers
    - type: memory                  # authentication source type (possible values : memory, ldap, gravitee)
      users:
        - user:
          username: user
          password: password
          roles: USER               # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
        - user:
          username: admin
          password: admin
          roles: ADMIN              # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
----

NOTE: We've just declared two users, `user` with `ROLE_USER` role and `admin` with `ROLE_ADMIN`

LDAP Provider::

An AuthenticationProvider implementation that authenticates against an LDAP server. There are many ways in which the LDAP authentication source can be configure. You should be familiar with LDAP before trying to use it.

[source,yaml]
----
# ===================================================================
# LDAP SECURITY PROPERTIES
#
# This sample file declared one ldap authentication source
# ===================================================================
security:
  type: basic                               # authentication type
  providers:                                # required authentication providers
    - type: ldap
      embedded: true                        # embedded mode (true to use the embedded ldap server, usefull for test/demo, possible values : true or false)
      # if embedded is false set the following values
      context-source-username: test
      context-source-password: test
      context-source-url: ldap://localhost:389/dc=gravitee,dc=io
      role-mapping: true                    # role mapping mode for ldap user (possible values : true or false)
      # if role-mapping is true set the following role mapper LDAP values (syntax { "user_ldap_role" : "user_new_added_ldap_role"})
      role-mapper: {
        ROLE_DEVELOPERS: ROLE_USER,
        ROLE_MEMBERS: ROLE_USER,
        ROLE_OWNERS: ROLE_ADMIN
      }
      user-dn-patterns: uid={0},ou=people   # user dn patterns (default 'uid={0},ou=people')
      group-search-base: ou=groups          # groupe search base (default 'ou=groups')
      context-source-base: dc=gravitee,dc=io # the context source base
----

Gravitee.io Repository Provider::

An AuthenticationProvider implementation that authenticates against Gravitee.io data source repository. Users are defined via the Gravitee.io management API.

[source,yaml]
----
# ===================================================================
# GRAVITEE SECURITY PROPERTIES
#
# This sample file declared gravitee authentication source
# ===================================================================
security:
  type: basic                       # authentication type
  providers:                        # required authentication providers
    - type: gravitee                # authentication source type (possible values : memory, ldap, gravitee)
      password-encoding: true       # enable password encoding (possible values : true or false)
----

NOTE: If password encoding system is enable the password encoder uses the BCrypt strong hashing function.

Combine the providers::

You can specify as many providers as you want. They will be checked in same order you declared them inside the providers attribute. Once a successfull authentication is made, the Gravitee.io Management API will stop polling the providers.

[source,yaml]
----
# ===================================================================
# MULTIPLE PROVIDER SECURITY PROPERTIES
#
# This sample file declared gravitee authentication source
# ===================================================================
security:
  type: basic
  providers:

    # First authentication source
    - type: ldap
      embedded: true
      role-mapping: true
      # if role-mapping is true set the following role mapper LDAP values
      role-mapper: {
        ROLE_DEVELOPERS: ROLE_USER,
        ROLE_MEMBERS: ROLE_USER,
        ROLE_OWNERS: ROLE_ADMIN
      }
      user-dn-patterns: uid={0},ou=people
      group-search-base: ou=groups
      context-source-base: dc=gravitee,dc=io
      # if embedded is false set the following values
      # context-source-username: test
      # context-source-password: test
      # context-source-url: ldap://localhost:389/dc=gravitee,dc=io

    # Second authentication source
    - type: memory
      users:
        - user:
          username: user
          password: password
          roles: USER
        - user:
          username: admin
          password: admin
          roles: ADMIN

    # Third authentication source
    - type: gravitee
      password-encoding: true
----

NOTE: The authentication process will loop through the three providers to attempt user authentication

==== OAuth2 Authentication configuration

Before you get started, make sure you have a fully fonctionnal OAuth2 Authorization Server with OAuth2 Token Validation endpoint that allows a resource server to validate an access token. The OAuth2 Authorization Server must expose the following resource :

[source]
----
Request         POST /oauth/check_token
Request Body    token=<access_token>
Request Headers Authorization: Basic 'Base64.encode(client_id:client_secret)'
                Content-Type: application/x-www-form-encoded
Response Codes  200 OK
Response Body   ::
                {
                    "exp": 1426391913,
                    "user_name": "user",
                    "scope": [
                        "read",
                        "write"
                    ],
                    "authorities": [
                        "ROLE_USER"
                    ],
                    "client_id": "test"
                }
Response Codes  400 KO
Respoce Body    ::
                {
                  Token not recognized/Token expired
                }
----

The Gravitee.io Management API supports OAuth2 Authentication via the following configuration :

[source,yaml]
----
# ===================================================================
# OAUTH 2 SECURITY PROPERTIES
#
# This sample file declared oauth2 security configuration
# ===================================================================
security:
  type: oauth2 # authentication type
  oauth.endpoint.check_token: # OAuth2 token validation endpoint url
  oauth.client.id: # OAuth2 resource server client id
  oauth.client.secret: # OAut2 resource server client secret
----

NOTE: With OAuth2 Authentication type, all requests to Gravitee Management API must contain the following header : Authorization Bearer <your-access-token>

=== Sending emails

==== SMTP

SMTP configuration used to send mails.

[source,yaml]
----
email:
  host: smtp.my.domain
  port: 465
  from: noreply@my.domain
  username: user@my.domain
  password: password
----

==== Mail templates

Mail templates configuration. Gravitee.io Management API use https://velocity.apache.org/[Velocity template engine] to parse and create the mail templates.

[source,yaml]
----
templates:
  path: ${gravitee.home}/templates
----

Currently, there are three kind of mail templates :

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Mail Template            |Description
|apiKeyRevoked.html       |API Key revoked notification.
|apiMember.html           |New API member notification.
|applicationMember.html   |New application member notification.
|======================

You can access to your api data on your api's templates by doing so: ${api.name} or ${api.metadata['foo-bar']}


=== Common Gravitee.io Management API properties

Various properties can be specified inside your `GRAVITEE_HOME/config/gravitee.yml` file. This section provides the general configuration of Gravitee.IO Management API.

[source,yaml]
----
#############################################################################################################
 ################################ Gravitee.IO Management API - Configuration ################################
 ############################################################################################################

 ############################################################################################################
 # This file is the general configuration of Gravitee.IO Management API:
 # - Properties (and respective default values) in comment are provided for information.
 # - You can reference other property by using ${property.name} syntax
 # - gravitee.home property is automatically set-up by launcher and refers to the installation path. Do not override it !
 #
 # Please have a look to http://docs.gravitee.io/ for more options and fine-grained granularity
 ############################################################################################################

 # HTTP Server
 #jetty:
 #  port: 8083
 #  idleTimeout: 30000
 #  acceptors: -1
 #  selectors: -1
 #  pool:
 #    minThreads: 10
 #    maxThreads: 200
 #    idleTimeout: 60000
 #    queueSize: 6000
 #  jmx: false
 #  statistics: false
 #  accesslog:
 #    enabled: true
 #    path: ${gravitee.home}/logs/gravitee_accesslog_yyyy_mm_dd.log

 # Path to plugins repository
 #plugins:
 #  path: ${gravitee.home}/plugins
 # If a plugin is already installed (but with a different version), management node does not start anymore
 #  failOnDuplicate: true

 # Management repository is used to store global configuration such as APIs, applications, apikeys, ...
 # This is the default configuration using MongoDB (single server)
 # For more information about MongoDB configuration, please have a look to:
 # - http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html
 management:
   type: mongodb
   mongodb:
     dbname: ${ds.mongodb.dbname}
     host: ${ds.mongodb.host}
     port: ${ds.mongodb.port}
 #    username:
 #    password:
 #    connectionsPerHost: 0
 #    connectTimeout: 500
 #    maxWaitTime: 120000
 #    socketTimeout: 500
 #    socketKeepAlive: false
 #    maxConnectionLifeTime: 0
 #    maxConnectionIdleTime: 0
 #    serverSelectionTimeout: 0
 #    description: gravitee.io
 #    heartbeatFrequency: 10000
 #    minHeartbeatFrequency: 500
 #    heartbeatConnectTimeout: 1000
 #    heartbeatSocketTimeout: 20000
 #    localThreshold: 15
 #    minConnectionsPerHost: 0
 #    sslEnabled: false
 #    threadsAllowedToBlockForConnectionMultiplier: 5
 #    cursorFinalizerEnabled: true

 # Management repository: single MongoDB using URI
 # For more information about MongoDB configuration using URI, please have a look to:
 # - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
 #management:
 #  type: mongodb
 #  mongodb:
 #    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

 # Management repository: clustered MongoDB
 #management:
 #  type: mongodb
 #  mongodb:
 #    servers:
 #      - host: mongo1
 #        port: 27017
 #      - host: mongo2
 #        port: 27017
 #    dbname: ${ds.mongodb.dbname}
 #    connectTimeout: 500
 #    socketTimeout: 250

 # Analytics repository is used to store all reporting, metrics, healthchecks stored by gateway instances
 # This is the default configuration using Elasticearch
 analytics:
   type: elasticsearch
   elasticsearch:
     hosts:
       - ${ds.elastic.host}:${ds.elastic.port}
 #    index: gravitee
 #    cluster: elasticsearch

 # Authentication and identity sources
 # Users can have following roles (authorities):
 #  USER: Can access portal and be a member of an API
 #  API_PUBLISHER: Can create and manage APIs
 #  API_CONSUMER: Can create and manage Applications
 #  ADMIN: Can manage global system
 security:
   type: basic # authentication type (default to 'basic', possible values : 'basic', 'oauth2')
   providers:  # authentication providers
     - type: memory
       users:
         - user:
           username: user
           # Passwords are encoded using BCrypt
           # Password value: password
           password: $2a$10$9kjw/SH9gucCId3Lnt6EmuFreUAcXSZgpvAYuW2ISv7hSOhHRH1AO
           roles: USER
         - user:
           username: admin
           # Password value: admin
           password: $2a$10$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq
           roles: ADMIN
         - user:
           username: api1
           # Password value: api1
           password: $2a$10$iXdXO4wAYdhx2LOwijsp7.PsoAZQ05zEdHxbriIYCbtyo.y32LTji
           # You can declare multiple roles using comma separator
           roles: API_PUBLISHER, API_CONSUMER
         - user:
           username: application1
           # Password value: application1
           password: $2a$10$2gtKPYRB9zaVaPcn5RBx/.3T.7SeZoDGs9GKqbo9G64fKyXFR1He.
           roles: API_CONSUMER
     # Enable authentication using internal repository
     - type: gravitee
 #    - type: ldap
       # This is default LDAP configuration for ApacheDS
 #      context-source-username: "uid=admin,ou=system"
 #      context-source-password: "secret"
 #      context-source-url: "ldap://localhost:10389/c=io,o=gravitee"
 #      context-source-base: "c=io,o=gravitee" # the context source base
       # The 'user-dn-patterns' value is a specific pattern used to build the user's DN, for example "uid={0},ou=people". The key "{0}" must be present and will be substituted with the username.
 #      user-dn-patterns: "uid={0},ou=people"
       # Search base for user searches. Defaults to "". Only used with user-search-filter.
 #      user-search-base: "o=user accounts"
       # The LDAP filter used to search for users (optional). For example "(uid={0})". The substituted parameter is the user's login name.
 #      user-search-filter: "mail={0}"
       # The search base for group membership searches. Defaults to "".
 #      group-search-base: "o=authorization groups"
       # The LDAP filter to search for groups. Defaults to "(uniqueMember={0})". The substituted parameter is the DN of the user.
 #      group-search-filter: "member={0}"
       # Specifies the attribute name which contains the role name. Default is "cn".
 #      group-role-attribute: "cn"
       # If role-mapping is equals to true (default to false)
       #   Use role-mapper to map LDAP role with internal Gravitee role (syntax { "user_ldap_role" : "user_new_added_ldap_role"})
 #      role-mapping: true
 #      role-mapper: {
 #        GRAVITEE-CONSUMERS: API_CONSUMER,
 #        GRAVITEE-PUBLISHERS: API_PUBLISHER,
 #        GRAVITEE-ADMINS: ADMIN,
 #        GRAVITEE-USERS: USER,
 #      }

 # SMTP configuration used to send mails
 email:
   enabled: false
   host: smtp.my.domain
 #  port: 465
   from: noreply@my.domain
   username: user@my.domain
   password: password

 # Mail templates
 #templates:
 #  path: ${gravitee.home}/templates

 # Referenced properties
 ds:
   mongodb:
     dbname: gravitee
     host: ${GRAVITEEIO_MONGODB_HOST:localhost}
     port: ${GRAVITEEIO_MONGODB_PORT:27017}
   elastic:
     host: ${GRAVITEEIO_ELASTIC_HOST:localhost}
     port: ${GRAVITEEIO_ELASTIC_PORT:9300}

 jwt:
   secret: myJWT4Gr4v1t33_S3cr3t
   # Allows to define the end of validity of the token in seconds (default 604800 = a week)
   #expire-after: 604800
   # Allows to define the end of validity of the token in seconds for email registration (default 86400 = a day)
   #email-registration-expire-after: 86400
   # Allows to define issuer (default gravitee-management-auth)
   #issuer: gravitee-management-auth
   # Allows to define cookie context path (default /)
   #cookie-path: /
   # Allows to define cookie domain (default "")
   #cookie-domain: .gravitee.io
   # Allows to define if cookie secure only (default false)
   #cookie-secure: true

 swagger:
   # Default scheme used when creating an API from a Swagger descriptor if there is no scheme specified.
   scheme: https

 user:
    login:
       # Create a default application when user connects to the portal for the very first time (default true)
       #defaultApplication: true
    creation:
       # Allows to register new users from portal (default false)
       #enabled: true
       token:
          #expire-after: 86400

 # The portal URL used in emails
 #portalURL: http://portal-url.net
----

[[gravitee-repositories-configuration]]
== Advanced Repositories Settings

[[gravitee-repositories-types]]
=== Repository types

* Management: All the data to manage the Gravitee.io API Management platform, including API definitions, users,
applications, plans, ...
* Rate Limit: Rate limiting data
* Analytics: Analytics data

**Compatibility Matrix: **
|===
|Scope|MongoDB |Redis |Elasticsearch| Cassandra| AWS DynamoDB

|Management
|X |X |- |X |X

|Rate Limit
|X |X |- |X |-

|Analytics
|- |- |X |- |-

|===

[[gravitee-repository-mongodb-configuration]]
=== MongoDB

Default implementation is based on https://www.mongodb.org/[MongoDB], let's see the configuration options:

[source,yaml]
----
# ===================================================================
# MINIMUM MONGO REPOSITORY PROPERTIES
#
# This is a minimal sample file declared connection to MongoDB
# ===================================================================
management:
  type: mongodb             # repository type
  mongodb:                  # mongodb repository
    dbname:                 # mongodb name (default gravitee)
    host:                   # mongodb host (default localhost)
    port:                   # mongodb port (default 27017)
----

NOTE: This is the minimum sample file to start with a mongo server, number of other properties control the behavior of mongo database, let's jump into it.

[source,yaml]
----
# ===================================================================
# MONGO REPOSITORY PROPERTIES
#
# This is a sample file declared all properties for MongoDB Repository
# ===================================================================
management:
  type: mongodb                 # repository type
  mongodb:                      # mongodb repository
    dbname:                     # mongodb name (default gravitee)
    host:                       # mongodb host (default localhost)
    port:                       # mongodb port (default 27017)
    username:                   # mongodb username (default null)
    password:                   # mongodb password (default null)
    connectionPerHost:          # mongodb connection per host (default 10)
    connectTimeOut:             # mongodb connection time out (default 0 -> never)
    maxWaitTime:                # mongodb max wait time (default 120000)
    socketTimeout:              # mongodb socket time out (default 0 -> never)
    socketKeepAlive:            # mongodb socket keep alive (default false)
    maxConnectionLifeTime:      # mongodb max connection life time (default null)
    maxConnectionIdleTime:      # mongodb max connection idle time (default null)
    minHeartbeatFrequency:      # mongodb min heartbeat frequency (default null)
    description:                # mongodb description (default null)
    heartbeatConnectTimeout:    # mongodb heartbeat connection time out (default null)
    heartbeatFrequency:         # mongodb heartbeat frequency (default null)
    heartbeatsocketTimeout:     # mongodb heartbeat socket time out (default null)
    localThreshold:             # mongodb local threshold (default null)
    minConnectionsPerHost:      # mongodb min connections per host (default null)
    sslEnabled:                 # mongodb ssl mode (default false)
    threadsAllowedToBlockForConnectionMultiplier: # mongodb threads allowed to block for connection multiplier (default null)
    cursorFinalizerEnabled:     # mongodb cursor finalizer enabled (default false)
----

NOTE: All theses properties allow you to fine tuned your MongoDB connection

[[gravitee-repository-redis-configuration]]
=== Redis

[source,yaml]
----
# ===================================================================
# MINIMUM REDIS REPOSITORY PROPERTIES
#
# This is a minimal sample file declared connection to Redis
# ===================================================================
management:
  type: redis               # repository type
  redis:                    # redis repository
    host:                   # redis host (default localhost)
    port:                   # redis port (default 6379)
    password:               # redis password (default null)
    timeout:                # redis timeout (default -1)
----

[[gravitee-repository-dynamodb-configuration]]
=== AWS DynamoDB

[source,yaml]
----
# ===================================================================
#
# AWS DYNAMODB REPOSITORY PROPERTIES
#
# ===================================================================
management:
  type: dynamodb               # repository type
  dynamodb:                    # dynamodb repository
    awsRegion:                 # AWS Region (default: the one configure in your aws config file)
    awsAccessKeyId:            # AWS Access Key Id (default: the one configure in your aws credential file)
    awsSecretKey:              # AWS Secret Access Key (default: the one configure in your aws credential file)
    awsEndpoint:               # your local dynamodb, for test purpose (default: amazon)
----

[[gravitee-reporters-configuration]]
== Reporters

[[gravitee-reporter-elasticsearch-configuration]]
=== Elasticsearch

*TODO*

[[gravitee-reporter-file-configuration]]
=== File (accesslog)

*TODO*
