---
sidebar: apim_sidebar
permalink: apim_installguide_portal.html
folder: apim/installation-guide/portal
description: Gravitee.io API Management - Portal - Installation
keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
layout: apim
---

[[gravitee-installation-portal]]
= Portal

== System Requirements

=== Browsers

Management UI Portal has been tested with the latest versions of Google Chrome, Firefox and Internet Explorer >= 10

== Installing from the ZIP archive

The binaries are available from http://gravitee.io/#downloads[Downloads page] or via https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-GRAVITEEIO-VERSION.zip[Download].

[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-GRAVITEEIO-VERSION -o gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip

Once file has been downloaded, you just have to unpack it in the right place

[source,bash]
[subs="attributes"]
$ unzip gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip

=== Deploy

The Management UI is a client-side only Angular application and can be deployed on any HTTP server like https://httpd.apache.org/[Apache] or http://nginx.org/[Nginx].

=== or Run it

With Python::

[source,bash]
[subs="attributes"]
$ cd graviteeio-management-ui-GRAVITEEIO-VERSION
$ python3 -m http.server
$ Serving HTTP on 0.0.0.0 port 8000 ...

With Node::

[source,bash]
[subs="attributes"]
$ npm install http-server -g
$ cd graviteeio-management-ui-GRAVITEEIO-VERSION
$ http-server