---
sidebar: apim_sidebar
permalink: apim_installguide_gateway.html
folder: apim/installation-guide/gateway
description: Gravitee.io API Management - Gateway - Installation
keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
---

[[gravitee-installation-gateway]]
= API Gateway

== System Requirements

=== JDK

API Gateway requires at least Java 8. Before you install it, please check your Java version :

[source,bash]
----
$ java -version
$ echo $JAVA_HOME
----

NOTE: You can download the latest JDK from the http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java SE Download Site].

=== Repository

Default API Gateway distribution requires MongoDB 3.x to poll environment configuration and Elasticsearch 2.x for
reporting / analytics.

NOTE: You can download MongoDB 3.x from https://www.mongodb.org/downloads#production[MongoDB Download Site]
and Elasticsearch 2.x or 5.x from https://www.elastic.co/downloads/elasticsearch[Elastic Download Site]

== Download and install the +.zip+ package

Binaries are available from http://gravitee.io/#downloads[Downloads page] or via https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-GRAVITEEIO-VERSION.zip[Download].

[source,bash]
----
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-GRAVITEEIO-VERSION.zip -o gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip
----

Once file has been downloaded, you just have to unpack it in the right place.

[source,bash]
----
$ unzip gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip
----

== Running API Gateway from the command line

API Gateway can be started from the command line as follows:

[source,bash]
----
$ cd graviteeio-gateway-GRAVITEEIO-VERSION
$ ./bin/gravitee
----

By default, API Gateway runs in the foreground, prints its logs to the standard output (stdout), and can be stopped
by pressing Ctrl-C.

If everything goes well, you should see this log:

[source,bash]
[subs="attributes"]
...
11:01:53.162 [gravitee] [] INFO  i.g.g.standalone.node.GatewayNode - Gravitee.io - Gateway id[2e05c0fa-8e48-4ddc-85c0-fa8e48bddc11] version[1.6.0] pid[24930] build[175] jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.121-b13] started in 15837 ms.
...

== Checking that API Gateway is running

You can test that your API Gateway node is running by sending an HTTP request to port `8082` on `localhost`:

[source,bash]
----
$ curl -X GET http://localhost:8082/
----

which should give you a response something like this:

[source,bash]
----
No context-path matches the request URI.
----

== Running as a daemon

To run API Gateway as a daemon, specify -d on the command line, and record the process ID in a file using the -p option:

[source,bash]
----
$ ./bin/gravitee -d -p=/var/run/gio.pid
----

Log messages can be found in the `$GRAVITEE_HOME/logs/` directory.

To shut down API Gateway, kill the process ID recorded in the pid file:

[source,bash]
----
$ kill `cat /var/run/gio.pid`
----

== Directory layout of .zip archive

The .zip and .tar.gz packages are entirely self-contained. All files and directories are, by default, contained within
$GRAVITEE_HOME — the directory created when unpacking the archive.

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Location    |Description
|bin       |Binary scripts including `gravitee` to start a node
|config    |Configuration files including `gravitee.yml`
|lib       |Libraries (gravitee.io libraries and third parties library)
|logs      |Log files location.
|plugins   |Plugin files location.
|======================

