---
sidebar: apim_sidebar
permalink: apim_installguide_management_api.html
folder: apim/installation-guide/management-api
description: Gravitee.io API Management - Management API - Overview
keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
---

[[gravitee-installation-management-api]]
= Management API - Overview

== System Requirements

=== JDK

Gravitee.io Management API requires at least Java 8. Before you install Gravitee.io Management API, please check your Java version :

[source,bash]
----
java -version
echo $JAVA_HOME
----

NOTE: You can download the latest JDK from the http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java SE Download Site].

=== Datastore

Default Gravitee.io Management API distribution requires MongoDB to store mandatory data and ElasticSearch to store reporting data.

NOTE: You can download MongoDB from https://www.mongodb.org/downloads#production[MongoDB Download Site]
and download Elasticsearch 2.x or 5.x from https://www.elastic.co/downloads/elasticsearch[Elastic Download Site]

== Installing from the ZIP archive

The binaries are available from http://gravitee.io/#downloads[Downloads page] or via https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-GRAVITEEIO-VERSION.zip[Download].

[source,bash]
[subs="attributes"]
$ curl -L https://download.gravitee.io/graviteeio-apim/distributions/graviteeio-full-GRAVITEEIO-VERSION -o gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip

Once file has been downloaded, you just have to unpack it in the right place

[source,bash]
[subs="attributes"]
$ unzip gravitee-standalone-distribution-GRAVITEEIO-VERSION.zip

And you can simply start up the Management API as follow:

[source,bash]
[subs="attributes"]
$ cd graviteeio-management-api-GRAVITEEIO-VERSION
$ ./bin/gravitee

If everything goes well, you should see this kind of logs:

[source,bash]
[subs="attributes"]
...
11:01:53.162 [gravitee] INFO  i.g.m.standalone.node.ManagementNode - Gravitee.io - Management API id[2e05c0fa-8e48-4ddc-85c0-fa8e48bddc11] version[1.6.0] pid[24930] build[175] jvm[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/25.121-b13] started in 15837 ms.
...

Default Gravitee.io Management API listens on port *8083* and can be accessed using the following URL :

http://SERVER_DOMAIN:8083/management.

This port is <<apim_installguide_configuration.adoc#http_server_2, configurable>> if necessary.

== Directory structure

After successfully installed Gravitee.io Management API, the `graviteeio-management-api` directory looks like this:

[width="100%",cols="20%,80%",frame="topbot",options="header"]
|======================
|Folder    |Description
|bin       |Gravitee.io Management API startup/shutdown scripts.
|config    |Gravitee.io Management API <<apim_installguide_configuration.adoc#gravitee-management-api-configuration, configuration>> folder (application, logs and cache configuration).
|lib       |Gravitee.io Management API libraries (Gravitee.io Management API and third party libraries).
|logs      |Gravitee.io Management API log files.
|plugins   |Gravitee.io Management API pluggable <<apim_installguide_configuration.adoc#plugins_repository_2, plugins>>.
|======================

