---
sidebar: apim_sidebar
permalink: apim_installguide_repositories_elasticsearch.html
folder: apim/installation-guide/repositories
description: Gravitee.io API Management - Repositories - Elasticsearch
keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api, elastic, es, elasticsearch
---

[[gravitee-installation-repositories-elasticsearch]]
= Elasticsearch

WARNING: Elasticsearch > v5 are not currently supported.
The Elasticsearch 2.4 is no longer supported by elastic (https://www.elastic.co/support/eol).

NOTE: Since Gravitee v1.12.x the default connector is the HTTP one, compliant with ES 2.x and 5.x.
Before release v1.12.x, Gravitee.io APIM is bundled by default with the native client for ES 2.X.


== Configuration

=== Management API configuration
[source,yaml]
----
analytics:
  type: elasticsearch
  elasticsearch:
    endpoints:
      - http://localhost:9200
#    index: gravitee
#    security:
#       username:
#       password:
----

=== API Gateway configuration
[source,yaml]
----
reporters:
  elasticsearch:
    endpoints:
      - http://localhost:9200
#    index: gravitee
#    bulk:
#       actions: 500           # Number of requests action before flush
#       flush_interval: 1      # Flush interval in seconds
#    security:
#       username:
#       password:
----

== Moving to native Elasticsearch 5.x

By default, Gravitee.io API Management components are based on Elasticsearch HTTP connector.

Here you may find procedure to move from Elasticsearch HTTP to 5.x native.

=== API Gateway

* Download latest Elasticsearch 5.x reporter from https://download.gravitee.io/graviteeio-apim/plugins/reporters/gravitee-reporter-elasticsearch/[Download]
* Replace current Elasticsearch 2.x reporter with the new reporter

[source,bash]
----
$ curl -L https://download.gravitee.io/graviteeio-apim/plugins/reporters/gravitee-reporter-elasticsearch/gravitee-reporter-elasticsearch-5x-REPORTER_VERSION.zip -o gravitee-reporter-elasticsearch-5x-REPORTER_VERSION.zip
$ mv gravitee-reporter-elasticsearch-5x-REPORTER_VERSION.zip ${GRAVITEE_HOME}/plugins
$ rm -f ${GRAVITEE_HOME}/plugins/gravitee-reporter-elasticsearch-http-REPORTER_VERSION.zip
----

And restart the API Gateway...

=== Management API

* Download latest Elasticsearch 5.x repository from https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-repository-elasticsearch/[Download]
* Replace current Elasticsearch HTTP repository with the new repository

[source,bash]
----
$ curl -L https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-repository-elasticsearch/gravitee-repository-elasticsearch-5x-REPOSITORY_VERSION.zip -o gravitee-repository-elasticsearch-5x-REPOSITORY_VERSION.zip
$ mv gravitee-repository-elasticsearch-5x-REPOSITORY_VERSION.zip ${GRAVITEE_HOME}/plugins
$ rm -f ${GRAVITEE_HOME}/plugins/gravitee-repository-elasticsearch-http-REPOSITORY_VERSION.zip
----

== Index management with ES Curator

Es Curator is a great tool for ES administration.  
For optimizing data footprint and ES performance you can define a retention window and periodically merge shards into only one segment

----
/usr/bin/curator --config /opt/curator/curator.yml /opt/curator/action-curator.yml
----

curator.yml :
[source,yaml]
----
client:
  hosts:
    - node1
    - node2	
  port: 9200

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
----

action-curator.yml :
[source,yaml]
----
actions:
  1:
    action: forcemerge
    description: "Perform a forceMerge on selected indices to 'max_num_segments' per shard. Merge Days - 1 index for optimize disk space footprint on Elasticsearch TS"
    options:
      max_num_segments: 1
      continue_if_exception: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: '^(gravitee-).*$'
      exclude: False
    - filtertype: age
      source: name
      direction: older
      unit: days
      unit_count: 1
      timestring: '%Y.%m.%d'
  2:
    action: delete_indices
    description: "Delete selected indices older than 15d days"
    options:
      continue_if_exception: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: '^(gravitee-).*$'
      exclude: False
    - filtertype: age
      source: name
      direction: older
      unit: days
      unit_count: 15
      timestring: '%Y.%m.%d'
----
