---
sidebar: apim_sidebar
permalink: apim_installguide_management_api_configuration.html
folder: apim/installation-guide/management-api
description: Gravitee.io API Management - Management API - Installation
keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api
---

[[gravitee-installation-management-api-configuration]]
= Management API - Configuration

== HTTP Server

Management API HTTP server configuration.

[source,yaml]
----
jetty:
  port: 8083
  idleTimeout: 30000
  acceptors: -1
  selectors: -1
  pool:
    minThreads: 10
    maxThreads: 200
    idleTimeout: 60000
    queueSize: 6000
  jmx: false
  statistics: false
  accesslog:
    enabled: true
    path: ${gravitee.home}/logs/gravitee_accesslog_yyyy_mm_dd.log
----

=== How to enable HTTPS support
First, you need to provide a keystore. If you don't have one, you can generate it :
----
keytool -genkey \
  -alias test \
  -keyalg RSA \
  -keystore server-keystore.jks \
  -keysize 2048 \
  -validity 360 \
  -dname CN=localhost \
  -keypass secret \
  -storepass secret
----

After that, you have to enable secure mode in your `gravitee.yml` :
----
jetty:
  ...
  secured: true
  ssl:
    keystore:
      path: ${gravitee.home}/security/keystore.jks
      password: secret
    truststore:
      path: ${gravitee.home}/security/truststore.jks
      password: secret
----

== Plugins repository

Gravitee.io Management API <<gravitee-plugins,plugins>> directory configuration.

[source,yaml]
----
plugins:
  path: ${gravitee.home}/plugins
----

== Management repository

Management repository is used to store global configuration such as APIs, applications, apikeys, ...
This is the default configuration using MongoDB (single server). For more information about MongoDB configuration, please have a look to:

http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html

[source,yaml]
----
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    username:
#    password:
#    connectionsPerHost: 0
#    connectTimeout: 500
#    maxWaitTime: 120000
#    socketTimeout: 500
#    socketKeepAlive: false
#    maxConnectionLifeTime: 0
#    maxConnectionIdleTime: 0
#    serverSelectionTimeout: 0
#    description: gravitee.io
#    heartbeatFrequency: 10000
#    minHeartbeatFrequency: 500
#    heartbeatConnectTimeout: 1000
#    heartbeatSocketTimeout: 20000
#    localThreshold: 15
#    minConnectionsPerHost: 0
#    sslEnabled: false
#    threadsAllowedToBlockForConnectionMultiplier: 5
#    cursorFinalizerEnabled: true

# Management repository: single MongoDB using URI
# For more information about MongoDB configuration using URI, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
#management:
#  type: mongodb
#  mongodb:
#    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

# Management repository: clustered MongoDB
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
#    dbname: ${ds.mongodb.dbname}
#    connectTimeout: 500
#    socketTimeout: 250
----

== Analytics

Analytics repository is used to store all reporting, metrics, health-checks stored by gateway instances.

This is the default configuration using https://www.elastic.co/products/elasticsearch[Elasticsearch].

[source,yaml]
----
  type: elasticsearch
  elasticsearch:
    endpoints:
      - http://localhost:9200
#    index: gravitee
#    security:
#       username:
#       password:
----

[[gravitee-standalone-management-security-configuration]]
== Security configuration

Security configuration providing Authentication, Identity and access-control mechanism for the Gravitee.io Management API.

=== Authentication Type

Gravitee.IO Management API supports both Basic Authentication and OAuth2 Authentication. The authentication-type can be defined using the following property :

[source,yaml]
----
security:
  type: basic # authentication type (default to 'basic', possible values : 'basic', 'oauth2')
----

==== Basic Authentication configuration

Authentication Provider::

The Gravitee.io management API supports by default some standard ways to retrieve user information for authentication from InMemory to LDAP or Gravitee.io <<gravitee-repositories, repository>>. Let's see how to configure it.

InMemory Provider::

Basic in-memory implementation, a simple and convenient way to declare "technical" users such as the administrator users. An example configuration is shown below:

[source,yaml]
----
# ===================================================================
# IN MEMORY SECURITY PROPERTIES
#
# This sample file declared one in memory authentication source with two users
# ===================================================================
security:
  type: basic                       # authentication type
  providers:                        # required authentication providers
    - type: memory                  # authentication source type (possible values : memory, ldap, gravitee)
      users:
        - user:
          username: user
          password: password
          roles: USER               # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
        - user:
          username: admin
          password: admin
          roles: ADMIN              # you can declare multiple roles with comma separator (USER, OWNER, ADMIN ...)
----

NOTE: We've just declared two users, `user` with `ROLE_USER` role and `admin` with `ROLE_ADMIN`

LDAP Provider::

An AuthenticationProvider implementation that authenticates against an LDAP server. There are many ways in which the LDAP authentication source can be configure. You should be familiar with LDAP before trying to use it.

[source,yaml]
----
# ===================================================================
# LDAP SECURITY PROPERTIES
#
# This sample file declared one ldap authentication source
# ===================================================================
security:
  type: basic                               # authentication type
  providers:                                # required authentication providers
    - type: ldap
      embedded: true                        # embedded mode (true to use the embedded ldap server, usefull for test/demo, possible values : true or false)
      # if embedded is false set the following values
      context-source-username: test
      context-source-password: test
      context-source-url: ldap://localhost:389/dc=gravitee,dc=io
      role-mapping: true                    # role mapping mode for ldap user (possible values : true or false)
      # if role-mapping is true set the following role mapper LDAP values (syntax { "user_ldap_role" : "user_new_added_ldap_role"})
      role-mapper: {
        ROLE_DEVELOPERS: ROLE_USER,
        ROLE_MEMBERS: ROLE_USER,
        ROLE_OWNERS: ROLE_ADMIN
      }
      user-dn-patterns: uid={0},ou=people   # user dn patterns (default 'uid={0},ou=people')
      group-search-base: ou=groups          # groupe search base (default 'ou=groups')
      context-source-base: dc=gravitee,dc=io # the context source base
----

Gravitee.io Repository Provider::

An AuthenticationProvider implementation that authenticates against Gravitee.io data source repository. Users are defined via the Gravitee.io management API.

[source,yaml]
----
# ===================================================================
# GRAVITEE SECURITY PROPERTIES
#
# This sample file declared gravitee authentication source
# ===================================================================
security:
  type: basic                       # authentication type
  providers:                        # required authentication providers
    - type: gravitee                # authentication source type (possible values : memory, ldap, gravitee)
      password-encoding: true       # enable password encoding (possible values : true or false)
----

NOTE: If password encoding system is enable the password encoder uses the BCrypt strong hashing function.

Combine the providers::

You can specify as many providers as you want. They will be checked in same order you declared them inside the providers attribute. Once a successfull authentication is made, the Gravitee.io Management API will stop polling the providers.

[source,yaml]
----
# ===================================================================
# MULTIPLE PROVIDER SECURITY PROPERTIES
#
# This sample file declared gravitee authentication source
# ===================================================================
security:
  type: basic
  providers:

    # First authentication source
    - type: ldap
      embedded: true
      role-mapping: true
      # if role-mapping is true set the following role mapper LDAP values
      role-mapper: {
        ROLE_DEVELOPERS: ROLE_USER,
        ROLE_MEMBERS: ROLE_USER,
        ROLE_OWNERS: ROLE_ADMIN
      }
      user-dn-patterns: uid={0},ou=people
      group-search-base: ou=groups
      context-source-base: dc=gravitee,dc=io
      # if embedded is false set the following values
      # context-source-username: test
      # context-source-password: test
      # context-source-url: ldap://localhost:389/dc=gravitee,dc=io

    # Second authentication source
    - type: memory
      users:
        - user:
          username: user
          password: password
          roles: USER
        - user:
          username: admin
          password: admin
          roles: ADMIN

    # Third authentication source
    - type: gravitee
      password-encoding: true
----

NOTE: The authentication process will loop through the three providers to attempt user authentication

=== OAuth2 Authentication configuration

Before you get started, make sure you have a fully fonctionnal OAuth2 Authorization Server with OAuth2 Token Validation endpoint that allows a resource server to validate an access token. The OAuth2 Authorization Server must expose the following resource :

[source]
----
Request         POST /oauth/check_token
Request Body    token=<access_token>
Request Headers Authorization: Basic 'Base64.encode(client_id:client_secret)'
                Content-Type: application/x-www-form-encoded
Response Codes  200 OK
Response Body   ::
                {
                    "exp": 1426391913,
                    "user_name": "user",
                    "scope": [
                        "read",
                        "write"
                    ],
                    "authorities": [
                        "ROLE_USER"
                    ],
                    "client_id": "test"
                }
Response Codes  400 KO
Respoce Body    ::
                {
                  Token not recognized/Token expired
                }
----

The Gravitee.io Management API supports OAuth2 Authentication via the following configuration :

[source,yaml]
----
# ===================================================================
# OAUTH 2 SECURITY PROPERTIES
#
# This sample file declared oauth2 security configuration
# ===================================================================
security:
  type: oauth2 # authentication type
  oauth.endpoint.check_token: # OAuth2 token validation endpoint url
  oauth.client.id: # OAuth2 resource server client id
  oauth.client.secret: # OAut2 resource server client secret
----

NOTE: With OAuth2 Authentication type, all requests to Gravitee Management API must contain the following header : Authorization Bearer <your-access-token>

== Sending emails

=== SMTP

SMTP configuration used to send mails.

[source,yaml]
----
email:
  host: smtp.my.domain
  port: 465
  from: noreply@my.domain
  username: user@my.domain
  password: password
----

==== Configure the Gmail SMTP server

Here is the Gmail SMTP configuration.

[source,yaml]
----
email:
  enabled: true
  host: smtp.gmail.com
  port: 587
  from: user@gmail.com
  username: user@gmail.com
  password: xxxxxxxx
  properties:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com
----

If you're using the 2-Factor Authentication (if not, you should), you have to generate an application password : https://security.google.com/settings/security/apppasswords .

=== Email templates

Email templates configuration. Gravitee.io Management API use http://freemarker.org[Freemarker template engine] to parse and create the email templates.

[source,yaml]
----
templates:
  path: ${gravitee.home}/templates
----

Here's the list of email templates :

[width="100%",cols="20%,60%,20%",frame="topbot",options="header"]
|======================
|Email Template                 |Description                                    |Variables
|groupMember.html               |New API group member notification.             |_username_, *group*, *user*
|apiKeyExpired.html             |API Key expired notification.                  |*owner*, *api*, *plan*, *application*, apiKey, expirationDate
|apiKeyRevoked.html             |API Key revoked notification.                  |*owner*, apiKey
|apiMember.html                 |New API member notification.                   |_username_, *api*, *user*
|applicationMember.html         |New application member notification.           |_username_, *application*, *user*
|subscriptionApproved.html      |API subscription approved notification.        |*owner*, *api*, *plan*, *subscription*
|subscriptionReceived.html      |API subscription received notification.        |*owner*, *api*, *plan*, *application*, *subscription*, subscriptionUrl
|subscriptionRejected.html      |API subscription rejected notification.        |*owner*, *api*, *plan*, *subscription*
|userRegistration.html          |User registration notification.                |_username_, registrationUrl, *user*
|supportTicket.html             |Support ticket creation.                       |*api*, *application*, *user*, content
|======================

You can access to your api data on your api's templates by doing so: ${api.name} or ${api.metadata['foo-bar']}

Available attributes:

[width="100%",cols="20%,20%,20%,20%,20%",frame="topbot",options="header"]
|======================
|Api                |Application        |Group              |Plan               |Owner/User    |Subscription
|name               |name               |name               |name               |username      |status
|description        |description        |-                  |description        |firstname     |request
|version            |type               |-                  |order              |lastname      |reason
|role               |status             |-                  |publishedAt (Date) |displayName   |processedAt
|metadata (Map)     |role               |-                  |closedAt (Date)    |email         |startingAt
|deployedAt (Date)  |-                  |-                  |-                  |-             |endingAt
|createdAt (Date)   |createdAt (Date)   |createdAt (Date)   |createdAt (Date)   |-             |closedAt
|updatedAt (Date)   |updatedAt (Date)   |updatedAt (Date)   |updatedAt (Date)   |-             |subscribedAt
|======================

Here's an example of template:
[source,html]
----
<html>
	<body style="text-align: center;">
		<header>
			<#include "header.html" />
		</header>
		<div style="margin-top: 50px; color: #424e5a;">
			<h3>Hi ${owner.username},</h3>
			<p>The API Key <code>${apiKey}</code> has been expired.
		</p>
	</body>
</html>

----

== Default configuration

Various properties can be specified inside your `GRAVITEE_HOME/config/gravitee.yml` file. This section provides the general configuration of Gravitee.IO Management API.

[source,yaml]
----
############################################################################################################
################################ Gravitee.IO Management API - Configuration ################################
############################################################################################################

############################################################################################################
# This file is the general configuration of Gravitee.IO Management API:
# - Properties (and respective default values) in comment are provided for information.
# - You can reference other property by using ${property.name} syntax
# - gravitee.home property is automatically set-up by launcher and refers to the installation path. Do not override it !
#
# Please have a look to http://docs.gravitee.io/ for more options and fine-grained granularity
############################################################################################################

# HTTP Server
#jetty:
#  IP/hostname to bind to. Default is 0.0.0.0
#  host: 0.0.0.0
#  port: 8083
#  idleTimeout: 30000
#  acceptors: -1
#  selectors: -1
#  pool:
#    minThreads: 10
#    maxThreads: 200
#    idleTimeout: 60000
#    queueSize: 6000
#  jmx: false
#  statistics: false
#  accesslog:
#    enabled: true
#    path: ${gravitee.home}/logs/gravitee_accesslog_yyyy_mm_dd.log

# Plugins repository
#plugins:
#  path:
#    - ${gravitee.home}/plugins
#    - ${gravitee.home}/my-custom-plugins
# If a external is already installed (but with a different version), management node does not start anymore
#  failOnDuplicate: true

# Management repository is used to store global configuration such as APIs, applications, apikeys, ...
# This is the default configuration using MongoDB (single server)
# For more information about MongoDB configuration, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientOptions.html
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname}
    host: ${ds.mongodb.host}
    port: ${ds.mongodb.port}
#    username:
#    password:
#    connectionsPerHost: 0
#    connectTimeout: 500
#    maxWaitTime: 120000
#    socketTimeout: 500
#    socketKeepAlive: false
#    maxConnectionLifeTime: 0
#    maxConnectionIdleTime: 0
#    serverSelectionTimeout: 0
#    description: gravitee.io
#    heartbeatFrequency: 10000
#    minHeartbeatFrequency: 500
#    heartbeatConnectTimeout: 1000
#    heartbeatSocketTimeout: 20000
#    localThreshold: 15
#    minConnectionsPerHost: 0
#    sslEnabled: false
#    threadsAllowedToBlockForConnectionMultiplier: 5
#    cursorFinalizerEnabled: true

# Management repository: single MongoDB using URI
# For more information about MongoDB configuration using URI, please have a look to:
# - http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
#management:
#  type: mongodb
#  mongodb:
#    uri: mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]

# Management repository: clustered MongoDB
#management:
#  type: mongodb
#  mongodb:
#    servers:
#      - host: mongo1
#        port: 27017
#      - host: mongo2
#        port: 27017
#    dbname: ${ds.mongodb.dbname}
#    connectTimeout: 500
#    socketTimeout: 250

services:
  core:
    http:
      enabled: true
      port: 18083
      host: localhost
      authentication:
        # authentication type to be used for the core services
        # - none : to disable authentication
        # - basic : to use basic authentication
        # default is "basic"
        type: basic
        users:
          admin: adminadmin

# Analytics repository is used to store all reporting, metrics, healthchecks stored by gateway instances
# This is the default configuration using Elasticearch
analytics:
  type: elasticsearch
  elasticsearch:
    endpoints:
      - http://${ds.elastic.host}:${ds.elastic.port}
#    index: gravitee
#    security:
#       username:
#       password:

# Authentication and identity sources
# Users can have following roles (authorities):
#  USER: Can access portal and be a member of an API
#  API_PUBLISHER: Can create and manage APIs
#  API_CONSUMER: Can create and manage Applications
#  ADMIN: Can manage global system
security:
  providers:  # authentication providers
    - type: memory
      # password encoding/hashing algorithm. One of:
      # - bcrypt : passwords are hashed with bcrypt
      # - none : passwords are not hashed/encrypted
      # default value is bcrypt
      password-encoding-algo: bcrypt
      users:
        - user:
          username: user
          # Passwords are encoded using BCrypt
          # Password value: password
          password: $2a$10$9kjw/SH9gucCId3Lnt6EmuFreUAcXSZgpvAYuW2ISv7hSOhHRH1AO
          roles: MANAGEMENT:USER, PORTAL:USER
        - user:
          username: admin
          # Password value: admin
          password: $2a$10$Ihk05VSds5rUSgMdsMVi9OKMIx2yUvMz7y9VP3rJmQeizZLrhLMyq
          roles: ADMIN
        - user:
          username: api1
          # Password value: api1
          password: $2a$10$iXdXO4wAYdhx2LOwijsp7.PsoAZQ05zEdHxbriIYCbtyo.y32LTji
          # You can declare multiple roles using comma separator
          roles: MANAGEMENT:API_PUBLISHER, PORTAL:API_PUBLISHER
        - user:
          username: application1
          # Password value: application1
          password: $2a$10$2gtKPYRB9zaVaPcn5RBx/.3T.7SeZoDGs9GKqbo9G64fKyXFR1He.
          roles: MANAGEMENT:USER, PORTAL:USER
    # Enable authentication using internal repository
    - type: gravitee
#    - type: ldap
      # This is default LDAP configuration for ApacheDS
#      context-source-username: "uid=admin,ou=system"
#      context-source-password: "secret"
#      context-source-url: "ldap://localhost:10389/c=io,o=gravitee"
#      context-source-base: "c=io,o=gravitee" # the context source base
      # The 'user-dn-patterns' value is a specific pattern used to build the user's DN, for example "uid={0},ou=people". The key "{0}" must be present and will be substituted with the username.
#      user-dn-patterns: "uid={0},ou=people"
      # Search base for user searches. Defaults to "". Only used with user-search-filter.
#      user-search-base: "o=user accounts"
      # The LDAP filter used to search for users (optional). For example "(uid={0})". The substituted parameter is the user's login name.
#      user-search-filter: "mail={0}"
      # The search base for group membership searches. Defaults to "".
#      group-search-base: "o=authorization groups"
      # The LDAP filter to search for groups. Defaults to "(uniqueMember={0})". The substituted parameter is the DN of the user.
#      group-search-filter: "member={0}"
      # Specifies the attribute name which contains the role name. Default is "cn".
#      group-role-attribute: "cn"
      #   Use role-mapper to map LDAP role with internal Gravitee role (syntax { "user_ldap_role" : "user_new_added_ldap_role"})
#      role-mapper: {
#        GRAVITEE-CONSUMERS: API_CONSUMER,
#        GRAVITEE-PUBLISHERS: API_PUBLISHER,
#        GRAVITEE-ADMINS: ADMIN,
#        GRAVITEE-USERS: USER,
#      }
#    - type: google # Allow to authenticate to portal using a Google Plus account
#      clientId: xxxx-xxx-xxx-xxx
#      clientSecret: xxxx-xxx-xxx-xxxx
#    - type: github # Allow to authenticate to portal using a GitHub account
#      clientId: xxxx-xxx-xxx-xxx
#      clientSecret: xxxx-xxx-xxx-xxxx
#    - type: oauth2
#      clientId: xxxx-xxx-xxx-xxx
#      clientSecret: xxxx-xxx-xxx-xxx
#      tokenEndpoint: https://oauth2_authorization_server/token
#      userInfoEndpoint: https://oauth2_authorization_server/userinfo
#      accessTokenProperty: access_token
#      authorizationHeader: "Bearer %s"
#      mapping:
#        id: sub
#        email: email
#        lastname: family_name
#        firstname: given_name
#        picture: profile.picture  //You can use JSON-path to select the corresponding field,see [JsonPath doc](https://github.com/json-path/JsonPath)
      #   by default created user will have default role for MANAGEMENT and PORTAL
      #   you can override this by assigning user to groups, on user creation, if its user info content match expression
#     groups:
#       - mapping:
#           condition: "{#jsonPath(#profile, '$.identity_provider_id') == 'idp_5' && #jsonPath(#profile, '$.job_id') != 'API_BREAKER'}"
#           values: [Example group,soft user]
#       - mapping:
#           condition: "{#jsonPath(#profile, '$.job_id') != 'API_BREAKER'}"
#           values: ["Api consumer"]

# SMTP configuration used to send mails
email:
  enabled: false
  host: smtp.my.domain
  subject: "[Gravitee.io] %s"
#  port: 465
  from: noreply@my.domain
  username: user@my.domain
  password: password
#  properties:
#    auth: true
#    starttls.enable: true
#    ssl.trust: smtp.gmail.com

# Mail templates
#templates:
#  path: ${gravitee.home}/templates

# Referenced properties
ds:
  mongodb:
    dbname: gravitee
    host: ${GRAVITEEIO_MONGODB_HOST:localhost}
    port: ${GRAVITEEIO_MONGODB_PORT:27017}
  elastic:
    host: ${GRAVITEEIO_ELASTIC_HOST:localhost}
    port: ${GRAVITEEIO_ELASTIC_PORT:9300}

jwt:
  secret: myJWT4Gr4v1t33_S3cr3t
  # Allows to define the end of validity of the token in seconds (default 604800 = a week)
  #expire-after: 604800
  # Allows to define the end of validity of the token in seconds for email registration (default 86400 = a day)
  #email-registration-expire-after: 86400
  # Allows to define issuer (default gravitee-management-auth)
  #issuer: gravitee-management-auth
  # Allows to define cookie context path (default /)
  #cookie-path: /
  # Allows to define cookie domain (default "")
  #cookie-domain: .gravitee.io
  # Allows to define if cookie secure only (default false)
  #cookie-secure: true

swagger:
  # Default scheme used when creating an API from a Swagger descriptor if there is no scheme specified.
  scheme: https

user:
   login:
      # Create a default application when user connects to the portal for the very first time (default true)
      #defaultApplication: true
   creation:
      # Allows to register new users from portal (default false)
      #enabled: true
      token:
         #expire-after: 86400

# The portal URL used in emails
#portalURL: http://portal-url.net

# Allows to create support ticket (default value: false)
#support:
  #enabled: true

# Allows to rate an API (default value: false)
#rating :
  #enabled: true
----
