= Install the full AM stack
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_redhat_stack.html
:page-folder: am/installation-guide/redhat
:page-layout: am
:page-description: Gravitee.io Access Management - Installation Guide - Red Hat or CentOS - Access Management
:page-keywords: Gravitee.io, API Platform, Access Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

:gravitee-package-name: graviteeio-am-3x

== Overview

This section describes how-to install the full AM stack, including all the components and, optionally, dependencies.

If you want to install AM components individually, see the following sections:

* link:{{ '/am/current/am_installguide_amazon_gateway.html' | relative_url }}[Install AM Gateway]
* link:{{ '/am/current/am_installguide_amazon_management_api.html' | relative_url }}[Install AM API]
* link:{{ '/am/current/am_installguide_amazon_management_ui.html' | relative_url }}[Install AM Console]

== Prerequisites

Before you install the AM stack, you must complete the following configuration.

=== Install Nginx

To install Nginx, run the following commands:

[source,bash,subs="attributes"]
----
sudo yum install epel-release
sudo yum install nginx
----

=== Configure the package management system

Ensure you have configured your package management system, as described in link:{{ '/am/current/am_installguide_redhat_introduction.html#configure-the-package-management-system-yum' | relative_url }}[Configure the package management system (yum)^].

== Install the AM package (no dependencies)

To install the AM package only, run the following command:

[source,bash,subs="attributes"]
----
sudo yum install {gravitee-package-name}
----

== Install the AM package with dependencies

=== Configure dependency repositories

Before you install the AM package, you may need to add third-party repositories.

==== MongoDB

NOTE: For guidance on installing and configuring MongoDB, see the link:https://www.mongodb.com/docs/v4.4/tutorial/install-mongodb-on-red-hat/[MongoDB installation documentation^].

[source,bash]
----
echo "[mongodb-org-4.4]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.4/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc" | sudo tee /etc/yum.repos.d/mongodb-org-4.4.repo > /dev/null

sudo yum install -y mongodb-org
sudo systemctl start mongod
----

=== Install AM

[source,bash,subs="attributes"]
----
curl -L https://bit.ly/install-am-3x | bash
----

== Run AM with `systemd`

To start up the AM components, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl daemon-reload
sudo systemctl start {gravitee-package-name}-gateway {gravitee-package-name}-management-api
sudo systemctl restart nginx
----

== Check the AM components are running

When all components are started, you can do a quick test to see if everything is ok by checking these URLs:

|===
|Component |URL

|AM Gateway
|http://localhost:8092

|AM API
|http://localhost:8093

|AM Console
|http://localhost:8094
|===
