= Install AM API
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_redhat_management_api.html
:page-folder: am/installation-guide/redhat
:page-layout: am
:page-description: Gravitee.io Access Management - Installation Guide - Red Hat or CentOS - Management API
:page-keywords: Gravitee.io, API Platform, Access Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

:gravitee-component-name: AM API
:gravitee-package-name: graviteeio-am-management-api-3x
:gravitee-service-name: graviteeio-am-management-api

== Overview

AM API is required to run AM Console. You must install AM API first before you can use AM Console.

== Prerequisites

The following steps assume you have configured your package management system, as described in link:{{ '/am/current/am_installguide_redhat_introduction.html#configure-the-package-management-system-yum' | relative_url }}[Configure the package management system (yum)^].

== Install the {gravitee-component-name} package

To install the latest stable version of {gravitee-component-name}, run the following command:

[source,bash,subs="attributes"]
----
sudo yum install -y {gravitee-package-name}
----

== Run {gravitee-component-name}

These steps assume that you are using the default settings.

To configure {gravitee-component-name} to start automatically when the system boots up, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl daemon-reload
sudo systemctl enable {gravitee-service-name}
----

To start and stop {gravitee-component-name}, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl start {gravitee-service-name}
sudo systemctl stop {gravitee-service-name}
----

NOTE: These commands provide no feedback as to whether {gravitee-component-name} started successfully. this information will be written in the log files located in `/opt/graviteeio/am/management-api/logs/`.

== View the logs

When `systemd` logging is enabled, the logging information are available using the `journalctl` commands.

To tail the journal, run the following command:

[source,bash,subs="attributes"]
----
sudo journalctl -f
----

To list journal entries for the {gravitee-component-name} service, run the following command:

[source,bash,subs="attributes"]
----
sudo journalctl --unit {gravitee-service-name}
----

To list journal entries for the {gravitee-component-name} service starting from a given time, run the following command:

[source,bash,subs="attributes"]
----
sudo journalctl --unit {gravitee-service-name} --since  "2020-01-30 12:13:14"
----
