= Introduction
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_redhat_introduction.html
:page-folder: am/installation-guide/redhat
:page-layout: am
:page-description: Gravitee.io Access Management - Installation Guide - Red Hat or CentOS - Introduction
:page-keywords: Gravitee.io, API Platform, Access Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

== Overview

This section explains how to install AM on Red Hat Enterprise Linux, CentOS Linux or Oracle Linux
using the `yum` package manager.

NOTE: RPM installation is not supported on distributions with old versions of RPM, such as SLES 11 and CentOS 5.
If you are running one of these versions, you need to link:{{ '/am/current/am_installguide_zip_introduction.html' | relative_url }}[Install Access Management with .zip^] instead.

== Configure the package management system (`yum`)

. Create a file called `graviteeio.repo` in location `/etc/yum.repos.d/` so that you can install AM directly using `yum`:
+
[source,properties]
----
[graviteeio]
name=graviteeio
baseurl=https://packagecloud.io/graviteeio/rpms/el/7/$basearch
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/graviteeio/rpms/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
----
+
. Enable GPG signature handling, which is required by some of our RPM packages:
+
[source,bash]
----
sudo yum install pygpgme yum-utils
----
+
. Before continuing, you may need to refresh your local cache:
+
[source,bash]
----
sudo yum -q makecache -y --disablerepo='*' --enablerepo='graviteeio'
----

Your repository is now ready to use.

== Install the AM components

You can choose to install the full AM stack or install components one by one:

* link:{{ '/am/current/am_installguide_redhat_stack.html' | relative_url }}[Install the full AM stack] (includes all components below)
* link:{{ '/am/current/am_installguide_redhat_gateway.html' | relative_url }}[Install AM Gateway]
* link:{{ '/am/current/am_installguide_redhat_management_api.html' | relative_url }}[Install AM API]
* link:{{ '/am/current/am_installguide_redhat_management_ui.html' | relative_url }}[Install AM Console]
