= Install Gravitee.io Access Management on Red Hat or CentOS
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_redhat_introduction.html
:page-folder: am/installation-guide/redhat
:page-liquid:
:page-layout: am
:page-description: Gravitee.io Access Management - Installation Guide - Red Hat or CentOS - Introduction
:page-keywords: Gravitee.io, API Platform, Access Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

== Overview

Use this tutorial to install Gravitee.io Access Management on Red Hat Enterprise Linux, CentOS Linux, or Oracle Linux
using the yum package manager.

NOTE: RPM install is not supported on distributions with old versions of RPM, such as SLES 11 and CentOS 5. Please see link:/am/current/am_installguide_gateway_install_zip.html[Install Gravitee.io Access Management with .zip] instead.

=== Gravitee.io Access Management Version

This tutorial installs Gravitee.io Access Management {{ site.products.am._3x.version }}. To install a different version of
Gravitee.io Access Management, just replace the version with the one expected.

== Install Gravitee.io Access Management

=== Configure the package management system (yum)
Create a file called `graviteeio.repo` in the `/etc/yum.repos.d/` so that you can install Gravitee.io Access Management directly using yum:

[source,properties]
----
[graviteeio]
name=graviteeio
baseurl=https://packagecloud.io/graviteeio/rpms/el/7/$basearch
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/graviteeio/rpms/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
----

Then, some packages are required to handle GPG signatures of our RPM packages:

[source,bash]
----
sudo yum install pygpgme yum-utils
----

Before going ahead, you may to refresh your local cache.

[source,bash]
----
sudo yum -q makecache -y --disablerepo='*' --enablerepo='graviteeio'
----

Your repository is ready to use, now it's time to install Gravitee.io Access Management.

=== Install the Gravitee.io components on Red Hat or CentOS

You can choose to install the complete Gravitee.io Access Management stack or install components one by one:

* link:/am/current/am_installguide_redhat_stack.html[Install Access Management] (includes all components below)
* link:/am/current/am_installguide_redhat_gateway.html[Install API Gateway]
* link:/am/current/am_installguide_redhat_management_api.html[Install Management API]
* link:/am/current/am_installguide_redhat_management_ui.html[Install Management UI]