= Install AM Console
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_installguide_redhat_management_ui.html
:page-folder: am/installation-guide/redhat
:page-layout: am
:page-description: Gravitee.io Access Management - Installation Guide - Red Hat or CentOS - Management UI
:page-keywords: Gravitee.io, API Platform, Access Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api

:gravitee-component-name: AM Console
:gravitee-package-name: graviteeio-am-management-ui-3x
:gravitee-service-name: graviteeio-am-management-ui

== Prerequisites

Before you install AM Console, you must complete the following configuration. You must also ensure AM API is installed and running.

=== Install Nginx

To install Nginx, run the following commands:

[source,bash,subs="attributes"]
----
sudo yum install epel-release
sudo yum install nginx
----

=== Configure your package management system

Ensure you have configured your package management system, as described in link:{{ '/am/current/am_installguide_redhat_introduction.html#configure-the-package-management-system-yum' | relative_url }}[Configure the package management system (yum)^].

== Install the {gravitee-component-name} package

To install the latest stable version of {gravitee-component-name}, run the following command:

[source,bash,subs="attributes"]
----
sudo yum install -y {gravitee-package-name}
----

== Run {gravitee-component-name}

NOTE: {gravitee-component-name} is based on Nginx

To configure {gravitee-component-name} to start automatically when the system boots up, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl daemon-reload
sudo systemctl enable nginx
----

To start and stop Nginx, run the following commands:

[source,bash,subs="attributes"]
----
sudo systemctl start nginx
sudo systemctl stop nginx
----

== View the logs

When `systemd` logging is enabled, the logging information are available using the `journalctl` commands:

To tail the journal, run the following command:

[source,shell]
----
sudo journalctl -f
----

To list journal entries for the Nginx service, run the following command:

[source,shell]
----
sudo journalctl --unit nginx
----

To list journal entries for the Nginx service starting from a given time:

[source,shell]
----
sudo journalctl --unit nginx --since  "2020-01-30 12:13:14"
----
