= Concepts
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_overview_concepts.html
:page-folder: am/overview
:page-toc: false
:page-layout: am

== Overview
This page describes the main concepts used in AM.

[[gravitee-am-concepts-organization]]
== Organization

NOTE: New in AM 3.6, the OSS version of AM comes with a single default organization

An organization is internal data space AM provisions for you, to hold all the resources to handle user authentication.

[[gravitee-am-concepts-environment]]
== Environment

NOTE: New in AM 3.6, the OSS version of AM comes with a single default environment

An environment is a logical workspace in which administrative users can manage security domains.

[[gravitee-am-concepts-security-domain]]
== Security domain

A security domain:

* Gives you access to all the AM resources, such as applications, users and identity providers
* Exposes authentication and authorization URLs
* Gathers analytics and reporting

[[gravitee-am-concepts-application]]
== Application

An application:

* Can be any type of application, for example:
** Web Application (PHP, Java, Node.js)
** Single App (JavaScript)
** Native App (iOS, Android)
** Backend App (Job, CLI)

* Applications use AM to sign in and make requests to the Gateway Authorization Server
* Applications can be used by end users (B2C) or autonomous (B2B)

[[gravitee-am-concepts-idp]]
== Identity provider

An identity provider:

* Brokers trust with external user providers such as:
** LDAP / Active Directory
** Database
** Web services
** Social providers
** OpenID Connect providers
** SAML v2 IDP
** Custom providers

* Is used during the login process to verify user credentials and retrieve profile information

[[gravitee-am-concepts-extension-point]]
== Extension point

NOTE: Deprecated in version 3.5.x and replaced by the `flow` concept described below

An extension point:

* Extends the behavior of the AM server by executing policies on selected stages
* Customizes the authentication and authorization flow by:
** Adding extra actions after the login form process
** Adding extra actions before and after the user consent process

[[gravitee-am-concepts-flow]]
== Flow

NOTE: New in AM 3.5.x

A flow:

* Allows you to build your own custom authentication and authorization journey by executing policies during specific phases of the authentication flow
* Can be used to:
** Enrich user profiles
** Notify 3rd party systems
** Add extra authorization rules (such as verify users or enforce MFA)
