= Using Management APIs
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_publisherguide_manage_apis_using_our_apis.html
:page-folder: apim/user-guide/publisher/manage-apis
:page-layout: apim3x

{% assign version = site.products.apim._3x.version | split: "." %}
{% capture current_version %}{{ version[0] }}.{{ version[1] }}{% endcapture %}

== Overview

The following sections describes the process of creating and updating your API through our management API and provide examples of integration into a CI/CD workflow.

== API definition

=== What is an API definition?

An API definition is a JSON representation of your API and its content (e.g., plans, pages, metadata).

=== How to get an API definition?

You can get the API definition by exporting it from the APIM console.
Or, by using the export endpoint `**GET /apis/{api.id}/export**`
(link:{{ '/apim/3.x/management-api/' | relative_url | append: current_version | append: '/index.html#operation/exportApiDefinition' }}[API reference^]).

=== What does it contain ?

In this definition each entity (e.i, API, plan or page) has:

- A **crossId** that identifies the entity (e.i, API, plan or page) across environments:
meaning that the same entity will keep its `crossId` from one environment to another.

TIP: You can find an API by its crossId, using the `getApis` endpoint by providing the `crossId` as a query paramater.
`**GET /apis?crossId=my-cross-id**`
(link:{{ '/apim/3.x/management-api/' | relative_url | append: current_version | append: '/index.html#operation/getApis' }}[API reference^]).

- A technical **id** that uniquely identifies an entity in one environment only:
The same entity will have a different technical id from one environment to another

NOTE: The API import process relies on the **crossId** to match entities with existing ones.
The technical **id** is used during the import only if the **crossId** is not provided. For example in case of an old exported API definition.

== Import and update business rules

The sections below describe the business rules applied during import and update process.

For clarity, the following terminology is used:

* **Imported API**: the API definition you are trying to import.
* **Target API**: an API definition that may already exists in the environment with the same `crossID` as the **Imported API**.

=== Plans

* Plans in Imported API that already exist in the Target API will be _updated_ (plan's status _remains unchanged_).
* Plans in Imported API that do not exist in the Target API will be _created_.
* Plans without subscriptions in Target API that are not present in the Imported API will be _deleted_.

=== Pages

* Pages in Imported API that already exist in the Target API will be _updated_.
* Pages in Imported API that do not exist in the target API will be _created_.
* Pages in Target API that are not present in the Imported API _remains unchanged_.

=== Groups, Members and roles

Depending on your installation setup, group, members and roles will not be imported the same way.

* When using the import feature to update or create an API on the same environment, members, groups and roles can be edited, and group memberships are _preserved_.

* When importing on another environment, groups unknown to the target environment will be _created_, but their memberships will _not be preserved_.

* When importing on another environment that runs on the same APIM instance (same database), direct members will be _preserved_ on the target environment.

* When importing on another environment that runs on a separate APIM instance, direct members _will not be preserved_ and group that are unknown to the target environment will be _created without preserving their memberships_.


== Endpoints for managing your APIs

This section describes the different endpoints your can use to manage your APIs.

They require the target organization and environment in the prefix:
`/organizations/**{organization.id}**/environments/**{environment.id}**/`

=== Creating a new API from an API definition

`**POST /api/import**`
(link:{{ '/apim/3.x/management-api/' | relative_url | append: current_version | append: '/index.html#operation/importApiDefinition' }}[API reference^]).

The HTTP request body can contain :

* the JSON API definition
* **OR** an HTTP link to the JSON API definition

NOTE: An error is raised if an API with same **crossId** already exists on the target environment.

=== Exporting an existing API

Use the following endpoint to export an API definition:

`**GET /apis/{api.id}/export**`
(link:{{ '/apim/3.x/management-api/' | relative_url | append: current_version | append: '/index.html#operation/exportApiDefinition' }}[API reference^])


=== Updating an existing API from an API definition

`**PUT /api/import**`
(link:{{ '/apim/3.x/management-api/' | relative_url | append: current_version | append: '/index.html#operation/updateWithDefinition' }}[API reference^])

This method relies on the **crossId** provided as part of the Imported API definition to eventually match your API to an existing API in the target environment.

NOTE: An error is raised if the **crossId** of the Imported API matches with an existing API on the target environment.

WARNING: Endpoint  `**PUT /apis/{api.id}/import**`
(link:{{ '/apim/3.x/management-api/' | relative_url | append: current_version | append: '/index.html#operation/updateWithDefinitionPUT' }}[API reference^]) based on the technical **id** (passed as a path parameter) can still be used, but is no longer the recommended option.

=== Partially update an API

This endpoint lets you update only a part of an existing API definition and its sub-resources.

`**PATCH /apis/{api.id}/definition**`

Refer to this link:{{ '/apim/3.x/apim_publisherguide_partial_update_apis.html' | relative_url}}[section^] for more details.

== CI/CD use cases examples

=== Create your API on development environment

Create your API in development environment, using the APIM console.

=== Push your API to the production environment

* Get your API definition by exporting it from APIM console, or using the export endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X GET \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/35a1b7d4-b644-43d1-a1b7-d4b64493d134/export
----

* On each environment you want to create your API, call the POST endpoint. For example
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X POST \
     -d '{
            "name": "my-api",
            "crossId": "3e645da6-039c-4cc0-a45d-a6039c1cc0d3",
            "version": "1",
            [....]
        }' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/import
----

=== Update your API on production environment

* Update your API definition. Manually, or by re-exporting the source API from development environment.

* On each environment you want to update your API, call the PUT endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PUT \
     -d '{
            "name": "my-updated-api",
            "crossId": "3e645da6-039c-4cc0-a45d-a6039c1cc0d3",
            "version": "1",
            [....]
        }' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]//management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/import
----


=== Update your API version

* On an API you want to update the version, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.version",
             "value": "3.2.0",
             "operation": "REPLACE"
           }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----

=== Update the weight of specific backend

* On an API you want to update the weight of specific backend, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.proxy.groups[?(@.name == 'my-group')].endpoints[?(@.name == 'my-endpoint')].weight",
             "value": "10",
             "operation": "REPLACE"
           }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----

=== Switch endpoint backup

* On an API you want to switch endpoint backup, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.proxy.groups[?(@.name == 'my-group')].endpoints[?(@.name == 'my-endpoint')].backup",
             "value": true,
             "operation": "REPLACE"
           },
          {
             "jsonPath": "$.proxy.groups[?(@.name == 'my-group')].endpoints[?(@.name == 'my-endpoint-backup')].backup",
             "value": false,
             "operation": "REPLACE"
          }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----

=== Update the target of an endpoint

* On an API you want to update the target of an endpoint, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.proxy.groups[?(@.name == 'default-group')].endpoints[?(@.name == 'my-endpoint')].target",
             "value": "https://api.gravitee.io/echo",
             "operation": "REPLACE"
           }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----


=== Create policy flow

* On an API you want to create a policy flow, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             name: 'ALL',
             methods: ['GET', 'POST', 'PUT'],
             'path-operator': {
               path: '/',
             },
             pre: [],
             post: []
           },
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----

=== Add policy to flow

* On an API you want to add policy to flow, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.flows[?(@.path-operator.path == '/')].post",
             "value": {
               policy: 'mock',
               name: 'A mock',
               configuration: {
                 status: '200',
                 content: '{ "message": "This is a mock" }',
               },
              },
             "operation": "ADD"
           }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----

=== Update a policy configuration

* On an API you want to update a policy configuration, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.flows[?(@.path-operator.path == '/')].pre[?(@.name == 'A mock')].configuration",
             "value": {
               "status": "500",
               "content": "{#request.attributes.application}",
             },
             "operation": "REPLACE"
           }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----

=== Add a resource

* On an API you want to add a resource, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.resources",
             "value": {
               "name": "cache_name",
               "type": "cache",
               "enabled": false,
               "configuration": {
                 "name": "my-cache",
                 "timeToIdleSeconds": 100,
                 "timeToLiveSeconds": 200,
                 "maxEntriesLocalHeap": 1000
               }
             },
             "operation": "ADD"
            }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----

=== Update a resource configuration

* On an API you want to update a resource configuration, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.resources[?(@.name == 'cache_name')].enabled",
             "value": false
           },
           {
             "jsonPath": "$.resources[?(@.name == 'cache_name')].configuration.timeToIdleSeconds",
             "value": 1000
           }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----

=== Set properties if not exist

* On an API you want to set all properties if not exist, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.properties",
             "value": "null",
             "operation": "TEST"
           },
           {
             "jsonPath": "$.properties",
             "value": [
                { key: 'properties_1', value: 'my_property_value_1' },
                { key: 'properties_2', value: 'my_property_value_2' },
             ],
             "operation": "REPLACE"
           }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----

=== Remove a property with key

* On an API you want to remove a property, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.properties[?(@.key == 'properties_1')]",
             "operation": "REMOVE"
           }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition
----


=== Check the update of version

* On an API you want to check the update of version, call the PATCH endpoint. For example :
+
[source,bash]
----
curl -H "Authorization: Bearer MY-ACCESS-TOKEN" \
     -H "Content-Type:application/json;charset=UTF-8" \
     -X PATCH \
     -d '[
           {
             "jsonPath": "$.version",
             "value": "3.2.0",
             "operation": "REPLACE"
           }
         ]' \
     https://[GRAVITEEIO-APIM-MGT-API-HOST]/management/organizations/[ORGANIZATION_ID]/environments/[ENVIRONMENT_ID]/apis/[API_ID]/definition?dryRun=true
----