= Revoke Refresh Tokens
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_userguide_oauth2_refresh_tokens_revoke.html
:page-folder: am/dev-guide/protocols/oauth2
:page-layout: am

A refresh token can be revoked if it has been compromised or it has to be removed by the end of a user session.

NOTE: By default the refresh token is single use only.
See link:{{ '/am/current/am_userguide_oauth2_refresh_tokens_rotation.html' | relative_url }}[Refresh Token Rotation^] for more information.

To revoke a refresh token, the application must call the OAuth 2.0 Revocation Endpoint, the request would look like the following :

----
curl --request POST \
  --url 'https://AM_GW/{domain}/oauth/revoke' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --header 'authorization: Basic (clientId:clientSecret)'
  --data 'token={refreshToken}'
----

NOTE: The application should match the one for which the refresh token was issued.

See also:

* link:{{ '/am/current/am_userguide_oauth2_refresh_tokens_get.html' | relative_url }}[How to get Refresh Tokens^]
* link:{{ '/am/current/am_userguide_oauth2_refresh_tokens_use.html' | relative_url }}[How to use Refresh Tokens^]
* link:{{ '/am/current/am_userguide_oauth2_refresh_tokens_rotation.html' | relative_url }}[Refresh Token Rotation^]

