= Get Refresh Tokens
:page-sidebar: am_3_x_sidebar
:page-permalink: am/current/am_userguide_oauth2_refresh_tokens_get.html
:page-folder: am/dev-guide/protocols/oauth2
:page-layout: am
:page-toc: false

NOTE: To get refresh tokens during OAuth 2.0 flows (authorization_code or password)
the **Refresh Token** Grant Type must be selected in your application settings.

For example, if you are using the OAuth 2.0 Password Flow, the request would look like the following:

----
curl --request POST \
  --url 'https://AM_GW/{domain}/oauth/token' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --header 'authorization: Basic (clientId:clientSecret)'
  --data 'grant_type=password' \
  --data 'username={password}' \
  --data 'password={password}'
----

The response will contain an access token and a refresh token (+ id_token if you have specified the openid scope).

----
{
  "access_token": "eyJraWQiOi...kZWZh",
  "refresh_token": "eyJraWBHSHD...zessdOLS",
  "token_type": "Bearer",
  "scope": "...",
  "expires_in": "..."
}
----

NOTE: Be sure to securely store the refresh token as it will be used to get a new access token without user credentials.

== See also

* link:{{ '/am/current/am_userguide_oauth2_refresh_tokens_use.html' | relative_url }}[How to use Refresh Tokens]
* link:{{ '/am/current/am_userguide_oauth2_refresh_tokens_revoke.html' | relative_url }}[How to revoke Refresh Tokens]
* link:{{ '/am/current/am_userguide_oauth2_refresh_tokens_rotation.html' | relative_url }}[Refresh Token Rotation]